alphagov/government-frontend

- app/controllers/concerns/ab_testable.rb
- test/controllers/content_items_controller_test.rb
- test/controllers/development_controller_test.rb
This commit updates the A/B test variant for related links from `RelatedLinksABTest1` to `RelatedLinksABTest2`. This is to support the second iteration of the A/B test which is using a new set of related link data.
Trello: https://trello.com/c/H6dFvnsH
---
https://government-frontend-pr-1253.surge.sh/gallery.html
https://government-frontend-pr-1253.herokuapp.com/component-guide
> Update related links A/B test variant

- config/initializers/csp.rb
This commit adds a new SHA256 hash for a version of the inline JavaScript detection script that has leading whitespace. It also swaps the hashes for two inline JavaScript scripts that were commented the wrong way around.
> Add new SHA256 hash for inline JS CSP

- config/initializers/csp.rb
Everything inside the script tags, including both leading and trailing spaces, is important for the hash.
> Fix component guide inline JS CSP hash

- app/views/development/index.html.erb
For the migration to search-api we're going to re-target the 'search'
alias to search-api.
---
[Trello card](https://trello.com/c/yrq9hZmU/77-point-the-search-alias-to-search-api-if-rummager-is-disabled)
> Change Plek(rummager) to Plek(search)

- app/controllers/concerns/ab_testable.rb
- test/controllers/content_items_controller_test.rb
- test/controllers/development_controller_test.rb
This PR updates the A/B test variant for related links from `RelatedLinksABTest2` to `RelatedLinksABTest3`. This is to support the third iteration of the A/B test which is using a new set of related link data.
---
https://government-frontend-pr-1269.surge.sh/gallery.html
https://government-frontend-pr-1269.herokuapp.com/component-guide
> Update related links A/B test variant for test #3

- app/controllers/concerns/ab_testable.rb
- app/controllers/content_items_controller.rb
- test/controllers/content_items_controller_test.rb
- test/controllers/development_controller_test.rb
This PR adds an additional `C` variant for the upcoming related links A/B test iteration v3. In the previous test we saw some users who had the control variant cookie, yet navigated via the related links which are only shown on the `B` variant.
In order to check if there are any problems with our A/B testing framework, in addition to making the data collection easier for later analysis, we are introducing the new `C` variant which will become our test variant. How the variants now work are as follows:
- `A` variant: No users should ever end up in this variant, as our CDN will be configured it to assign 0% of users. If users do end up in this variant, we may have issues with our A/B testing framework which will require further investigation.
- `B` variant: Our control variant, where …
> Add additional variant for Related Links A/B test v3

- app/controllers/concerns/ab_testable.rb
- test/controllers/content_items_controller_test.rb
- test/controllers/development_controller_test.rb
This PR updates the A/B test variant for related links from RelatedLinksABTest3 to RelatedLinksABTest4. This is to support the fourth iteration of the A/B test which is using a new set of related link data.
---
https://government-frontend-pr-1282.surge.sh/gallery.html
https://government-frontend-pr-1282.herokuapp.com/component-guide
> Update variant for Related Links A/B test v4

- config/initializers/csp.rb
This commit changes the URL that content security policy violations are reported to to a new AWS Lambda function that filters out most junk reports and forwards the rest to Sentry.
> Change CSP report URL to AWS Lambda function

- config/initializers/csp.rb
This commit changes the content security policy to allow all inline scripts, until we can conclusively document all the inline scripts we use, and there's a better way to filter out junk reports.
> Allow all inline scripts in CSP

- Gemfile
- Gemfile.lock
- test/test_helper.rb
This helps troubleshoot flaky tests by printing the name and duration of each
test as it runs.
> Add minitest reporters

- app/presenters/content_item/withdrawable.rb
- test/presenters/content_item/withdrawable_test.rb
Currently a withdrawn translated edition may display the majority of the
withdrawal notice title in English, but with dates and publication type
in the chosen locale.
Until withdrawal notices are also available via I18n, this PR will ensure
only English is displayed.
---
> Display withdrawal notices on translated editions in English

- Gemfile
- Gemfile.lock
This allows using the Rails DSL for content_security_policy
> Bump govuk_app_config to 1.18.1

- app/views/development/index.html.erb
This was missed from a previous [PR](https://github.com/alphagov/government-frontend/pull/1354) when an AB test had finished.
> Remove related_links_variant from index

- app/controllers/content_items_controller.rb
- app/lib/services.rb
- app/models/feature_toggler.rb
- app/models/http_feature_flags.rb
- config/initializers/feature_flags.rb
- test/controllers/content_items_controller_test.rb
- test/models/feature_toggler_test.rb
- test/models/http_feature_flags_test.rb
This PR adds support for the new recommended related links to be shown based on the existence of a HTTP header set by our CDN. To achieve this we add support in general for feature flags via a `FeatureToggler` class.
Should the header exist, the new recommended related links will only be shown if there are no existing `ordered_related_items` in the content item, to ensure that we do not override manually curated links.
Dependent on https://github.com/alphagov/govuk-content-schemas/pull/908.
---
https://government-frontend-pr-1386.surge.sh/gallery.html
https://government-frontend-pr-1386.herokuapp.com/component-guide
> Display new recommended related links

- app/views/content_items/help_page.html.erb
- test/integration/help_page_test.rb
We don't want to have this page appearing in our search, but instead for
users to see '/help/cookies' as the only result because the details page
is confusing as a landing page. The settings page also links to the
details page.
---
https://government-frontend-pr-1394.surge.sh/gallery.html
https://government-frontend-pr-1394.herokuapp.com/component-guide
> Add noindex for '/help/cookie-details'

- app/controllers/content_items_controller.rb
- app/models/feature_toggler.rb
- app/models/http_feature_flags.rb
- test/controllers/content_items_controller_test.rb
- test/models/feature_toggler_test.rb
- test/models/http_feature_flags_test.rb
This PR adds the `Govuk-Use-Recommended-Links` Vary response header and value header to responses generated by the `ContentItemsController`. This is to enable cache invalidation of previous responses if the incoming `Govuk-Use-Recommended-Links` request header changes state.
---
https://government-frontend-pr-1397.surge.sh/gallery.html
https://government-frontend-pr-1397.herokuapp.com/component-guide
> Add Govuk-Use-Recommended-Links Vary response header and value header

- app/models/http_feature_flags.rb
- config/initializers/feature_flags.rb
- test/controllers/content_items_controller_test.rb
- test/models/http_feature_flags_test.rb
This PR changes the feature flag names used in `FeatureFlagNames` to represent headers as we set them at the CDN. This allows us to output response headers for the feature flags and in the `Vary` header which are consistent with others headers that we set (see below):
**Before (first and last headers)**
**After (first and last headers)**
---
https://government-frontend-pr-1398.surge.sh/gallery.html
https://government-frontend-pr-1398.herokuapp.com/component-guide
> Change feature flag names to represent headers set at the CDN

- app/controllers/content_items_controller.rb
- app/lib/request_helper.rb
- app/models/http_feature_flags.rb
- test/controllers/content_items_controller_test.rb
- test/services/request_helper_test.rb
This PR fixes the related links response header to be determined by the request header. If the request header is not set or does not match the required value as defined by the `feature_flags` initializer, we set the response header to `false`; if the request header is set and matches the required value, it's set to `true`.
This will enable us to change the request header at CDN level if we need to change related links.
---
https://government-frontend-pr-1400.surge.sh/gallery.html
https://government-frontend-pr-1400.herokuapp.com/component-guide
> Use request header for related links to determine response header

- Gemfile
- Gemfile.lock
- test/test_helper.rb
Trello: https://trello.com/c/hwMoAOau/3-%F0%9F%90%B3-get-all-apps-working-on-docker
This replaces the manual for headless chrome with that provided by
govuk_test and allows removing the chromedriver version pinning in
govuk_docker [1]
[1]: https://github.com/alphagov/govuk-docker/blob/1503800b0c5ac5a9385456ff08286a840493a025/government-frontend/chromedriver-version
> Use govuk_test

- app/assets/stylesheets/components/_banner.scss
- app/views/components/_banner.html.erb
https://trello.com/c/lJMjbUEq/22-fix-language-on-history-notice
When pages are translated, the history notice/banner content is not. They should be marked as being in English and left-to-right reading direction should be enforced - this PR addresses this and makes the page work better for screenreaders.
---
https://government-frontend-pr-1415.surge.sh/gallery.html
https://government-frontend-pr-1415.herokuapp.com/component-guide
> Mark banner (history notice) as English language and enforce left-to-right flow.

- Gemfile
- Gemfile.lock
- app/controllers/development_controller.rb
- app/views/development/index.html.erb
- startup.sh
The dashboard will show the URL for the content store and search, which will contain a username/password combo for integration. This hides the info.
> Don't show HTTP Basic auth on dev dashboard

- app/views/components/_figure.html.erb
https://trello.com/c/APajl08R/4-where-alt-text-is-presented-mark-as-english
When pages are translated, there is no translation on the alt
text or the caption attached to an image, so they need to be
semantically labelled as being in English.
> Label figure component as English

- app/assets/stylesheets/components/_published-dates.scss
- app/assets/stylesheets/components/_publisher-metadata.scss
- app/presenters/content_item_presenter.rb
- app/views/components/_published-dates.html.erb
- app/views/components/_publisher-metadata.html.erb
https://trello.com/c/YjWKQe6Z/12-update-metadata-component-for-language
On translated pages we are largely failing to translate the metadata,
leading to messy strings where the only translated content is the month
or the word "and" amongst otherwise English sentences.
This change sets the locale to English for the dates, and reverts attempts
to translate other sections of the page, and it marks the components
as being in English. It removes classnames that aren't used from the CSS
and forces the text direction to be left-to-right for these components.
This marks the page up more semantically, and supports a better experience
for screenreader users as they can now context switch the language
appropriately.
https://www.gov.uk/government/news/death-of-former-prime-minister-lady-thatcher.ar …
> Force English for metadata

- app/models/feature_toggler.rb
- test/controllers/content_items_controller_test.rb
This PR adds an additional check to ensure that `suggested_ordered_related_items` are only assigned if there are both no `ordered_related_items` and no `ordered_related_items_overrides`. This is necessary because publishers can manually add overrides and expect them to be displayed instead of any existing links.
Depends on https://github.com/alphagov/govuk-content-schemas/pull/918.
---
https://government-frontend-pr-1429.surge.sh/gallery.html
https://government-frontend-pr-1429.herokuapp.com/component-guide
> Ensure suggested related links respect overrides

- app/presenters/document_collection_presenter.rb
- test/presenters/document_collection_presenter_test.rb
Trello: https://trello.com/c/VdQtNZeV/1122-spike-making-content-publisher-documents-show-up-in-whitehall-document-collections
[With the update to Whitehall that allows adding any GOV.UK page to a
document collection](https://github.com/alphagov/whitehall/pull/4980) there is the potential users could add documents
with types the Government Frontend knows nothing about. For these cases
this will return a nil value rather than raise a failed translation
message.
At this point in time it seems unlikely users would use a document type
that is not known about as the expected usage is Content Publisher
document types. However there is nothing to prevent wider usage of
document types.
This resolves a situation like this:
--- …
> Don't show failed translation message for missing document types

- app/views/shared/_translations.html.erb
'govuk-grid-column-third' isn't defined and thus had no styles being applied. This was causing an issue for Whitehall content with translations when viewed on a mobile device.
Example: https://www.gov.uk/government/news/new-online-service-for-commercial-drivers-to-pay-dvsa-fines
|--------|------|
|![Screen Shot 2019-08-15 at 14 40 37](https://user-images.githubusercontent.com/5111927/63098621-2d10ea80-bf6b-11e9-9473-018cfc92e836.png)|![Screen Shot 2019-08-15 at 14 42 16](https://user-images.githubusercontent.com/5111927/63098638-38641600-bf6b-11e9-9209-438e5db54b13.png)|
Arises from Zendesk ticket 3771721.
---
https://government-frontend-pr-1445.surge.sh/gallery.html …
> Fix class: 'govuk-grid-column-third' => 'govuk-grid-column-one-third'

- app/presenters/document_collection_presenter.rb
- test/presenters/document_collection_presenter_test.rb
This stops document collections raising errors when a public_updated_at
value is not set on a document. This is often the case with draft GOV.UK
documents, however Whitehall tends to fill in this field which is why
this error hasn't been seen before.
---
> Prevent errors for missing public_updated_at

- app/assets/stylesheets/application-ie6.scss
- app/assets/stylesheets/application-ie7.scss
- app/assets/stylesheets/application-ie8.scss
- app/views/layouts/application.html.erb
- config/initializers/assets.rb
We no longer support IE6 and IE7 to the extent where specific stylesheets are
necessary and the IE8 stylesheet was doing nothing helpful. Removing these
improves the compile time and makes the dev environment more useable.
---
https://government-frontend-pr-1450.surge.sh/gallery.html
https://government-frontend-pr-1450.herokuapp.com/component-guide
> Remove outdated CSS

- app/helpers/application_helper.rb
- app/presenters/content_item/title_and_context.rb
- app/presenters/content_item_presenter.rb
- app/views/content_items/publication.html.erb
- test/helpers/application_helper_test.rb
- test/presenters/corporate_information_page_presenter_test.rb
- test/presenters/specialist_document_presenter_test.rb
https://trello.com/c/iQcgz7lt/25-2-mark-language-on-page-kicker-section-of-page
This adds a helper method which detects whether the string requested
was returned by the current locale's translation file. If not, it returns
the default locale.
This helper is in turn used on the contextual headings, allowing us to
pass the information on to the component that displays the heading, meaning
we will be able to markup the contextual header's actual language, supporting
screenreaders and making the page more semantic.
---
https://government-frontend-pr-1447.surge.sh/gallery.html
https://government-frontend-pr-1447.herokuapp.com/component-guide
> Add detection of contextual title translation

- app/views/development/index.html.erb
- app/views/layouts/application.html.erb
- public/robots.txt
Adds a noindex,nofollow to pages rendered using the application layout in
Heroku review apps.
Also disallows spiders from crawling this app using the robots.txt.  The
robots.txt will only be accessible from apps that are not behind router.
This means that Heroku preview apps will indicate to crawlers that they should
not index the site, but applications in production environments will be unaffected.
---
https://government-frontend-pr-1461surge.sh/gallery.html
https://government-frontend-pr-1461.herokuapp.com/component-guide
> Ban indexing in preview apps

- app/views/content_items/guide.html.erb
- public/robots.txt
- test/integration/guide_test.rb
This potentially gives us more control over the presentation of the result in external search applications.
Related to https://github.com/alphagov/govuk_publishing_components/pull/1087
https://government-frontend-pr-1467.herokuapp.com/component-guide
---
I need to re-allow spidering (reverts part of https://github.com/alphagov/government-frontend/pull/1461) in order to review structured data in checkers such as https://search.google.com/structured-data/testing-tool/u/0/ and https://search.google.com/test/rich-results
This only affects review apps as this robots.txt is not publicly accessible from production-like environments
We noindex, nofollow all the content pages in Heroku review apps, so I think we're safe to allow robots to access these pages.
> Switch guides to emit faq structured data

- app/assets/stylesheets/components/_back-to-top.scss
- app/assets/stylesheets/components/_important-metadata.scss
- app/assets/stylesheets/components/_published-dates.scss
- app/assets/stylesheets/components/_publisher-metadata.scss
- app/assets/stylesheets/helpers/_parts.scss
- app/assets/stylesheets/mixins/_govuk-template-link-focus-override.scss
- app/presenters/content_item/linkable.rb
- app/presenters/content_item/parts.rb
- app/presenters/fatality_notice_presenter.rb
- app/presenters/specialist_document_presenter.rb
- app/views/components/_back-to-top.html.erb
- app/views/components/_print-link.html.erb
- app/views/components/_published-dates.html.erb
- test/presenters/case_study_presenter_test.rb
- test/presenters/content_item/linkable_test.rb
- test/presenters/content_item/parts_test.rb
- test/presenters/publication_presenter_test.rb
- test/presenters/specialist_document_presenter_test.rb
- test/presenters/speech_presenter_test.rb
- test/presenters/statistics_announcement_presenter_test.rb
- test/presenters/travel_advice_presenter_test.rb
https://trello.com/c/0OfIgpul/51-5-update-government-frontend-to-govukpublishingcomponents-v19-with-compatibility-mode-on
This adds the govuk-link class to multiple links throughout the codebase
in order to inherit the correct styles, and updates related tests. Where
the class is overridden by govuk-template the styles have been updated to
use a temporary mixin to enforce the correct colour state and the class is
locally overridden where white links are needed.
Some example urls:
contents list:
https://government-frontend-pr-1466.herokuapp.com/log-in-register-hmrc-online-services
important metadata:
https://government-frontend-pr-1466.herokuapp.com/drug-device-alerts/field-safety-notice-10-april-to-14-april-2017
https://government-frontend-pr-1466.herokuapp.com/government/fatalities/fatali …
> Adjust focus states

- app/assets/stylesheets/helpers/_parts.scss
The focus state for links on the in page navigation took up the entire width of the parent element. Stopping the link from displaying like a block element fixes this with no other side effects.
Before:
After:
---
https://government-frontend-pr-1474.surge.sh/gallery.html
https://government-frontend-pr-1474.herokuapp.com/component-guide
> Stop the focus state on in page navigation links from being full width

- app/presenters/content_item/national_applicability.rb
- test/presenters/detailed_guide_presenter_test.rb
- test/presenters/publication_presenter_test.rb
Fix for https://github.com/alphagov/government-frontend/issues/1475
https://government-frontend-pr-1476.surge.sh/gallery.html
https://government-frontend-pr-1476.herokuapp.com/component-guide
> Add classes to override invisible links

- app/views/content_items/guide.html.erb
- test/helpers/application_helper_test.rb
- test/integration/guide_test.rb
- test/models/http_feature_flags_test.rb
- test/services/request_helper_test.rb
At present we're showing the same FAQ schema on each page of a guide. This is a bit suboptimal.  We have the option of splitting it up and showing one question and answer per part/chapter in the guide, but it seems much better to present it to Google as a joined up publication, because that's how it's been designed.
To resolve this problem, we present the FAQ page on the default page of the guide, but fall back to the Article schema for chapter pages, so we're still presenting some schema.org content everywhere, but not presenting duplicate content.
[Structured data from /universal-credit](https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fgovernment-frontend-pr-1478.herokuapp.com%2Funiversal-credit) should show the FAQ schema
[Structured data from …
> Deduplicate FAQ page schema presentation

- app.json
- app/controllers/application_controller.rb
This has been lifted from [Collections](https://github.com/alphagov/collections/blob/master/app/controllers/application_controller.rb#L11-L16)
The env variables have been added to government-frontend.herokuapp.com already.
This is to prevent users from accidentally landing on a page in the review
app and believing that it's GOV.UK.
---
Example page for this PR:
https://government-frontend-pr-1484.herokuapp.com/universal-credit
> Add basic auth to government frontend review app

- app/presenters/document_collection_presenter.rb
When the contents list component doesn't display (if there's 2 groups or less), then the heading level skips from H1 (page title) to H3 (group headings).
Someone raised this issue in a Zendesk ticket: https://govuk.zendesk.com/agent/tickets/3800830
This commit checks whether a contents list will be displayed, and uses a H2 if not.
- Page with contents list: /government/collections/statistics-exclusions
- Page without contents list: /government/collections/statistics-performance-tables
> Use h2 if there's no contents list

- app/assets/javascripts/application.js
- app/assets/javascripts/set-ga-client-id-on-form.js
- app/controllers/content_items_controller.rb
- app/views/content_items/service_sign_in/_choose_sign_in.html.erb
- spec/javascripts/set-ga-client-id-on-form.spec.js
- test/controllers/service_sign_in_content_item_controller_test.rb
On pages such as https://www.gov.uk/log-in-file-self-assessment-tax-return/sign-in/prove-identity
we redirect users to services such as tax.service.gov.uk to complete their sign in.
This will pass the `_ga` cookie as the `_ga` param as part of cross-domain tracking, so that we can measure user journeys across domains.
This will only pass the _ga param to other .gov.uk services. Currently these are:
- www.tax.service.gov.uk
- www.signin.service.gov.uk
- www.ruralpayments.service.gov.uk
Pages to check: 
- https://government-frontend-pr-1483.herokuapp.com/log-in-file-self-assessment-tax-return/sign-in/prove-identity
- https://government-frontend-pr-1483.herokuapp.com/check-state-pension/sign-in/prove-identity
- https://government-frontend-pr-1483.herokuapp.com/update-company-car-details/sign- …
> Pass _ga client id to external signon services

- app/assets/stylesheets/helpers/_organisation-links.scss
Links on pages that used branding colours (for example, the [DCM and also S About page](https://www.gov.uk/government/organisations/department-for-digital-culture-media-sport/about)) didn't have the correct focus state text colour.
Rough and ready patch for #1487.
This changes the text colour of the focus state of all of the links which use branded colours.
Before:
After:
---
https://government-frontend-pr-1491.surge.sh/gallery.html
https://government-frontend-pr-1491.herokuapp.com/component-guide
> Fix branded links and organisation logo hover state text colour

- Gemfile
- Gemfile.lock
- app/views/content_items/answer.html.erb
- app/views/content_items/guide.html.erb
- test/integration/answer_test.rb
- test/integration/guide_test.rb
- test/test_helper.rb
The FAQ schema now only supports single page bodies rather than being able to traverse an array of guide sections. This means we should now use the `:faq` schema on all guide parts. 
Some guide tests in this repo exercise a path where a guide has no parts which is why the conditional in the guide.html.erb view is required.
The change to the schema allows us to add it to mainstream answers.
Checkout:
Guides:
- https://government-frontend-pr-1492.herokuapp.com/universal-credit
- https://government-frontend-pr-1492.herokuapp.com/student-finance/continuing-fulltime-students
Answers:
- https://government-frontend-pr-1492.herokuapp.com/visit-europe-brexit
- https://government-frontend-pr-1492.herokuapp.com/tax-free-childcare
You can paste the page source into …
> Use the updated FAQ schema

- app/views/content_items/guide.html.erb
- test/integration/answer_test.rb
- test/integration/guide_test.rb
The logic for guides was incorrect so the body of the default guide chapter wasn't being passed to the machine readable component.
> Ensure that FAQs are generated correctly

- config/locales/nl.yml
Our translation for Dutch is incorrect
> Correct spelling of Nederlands

- app/controllers/content_items_controller.rb
- app/presenters/content_item/parts.rb
- app/presenters/content_item_presenter.rb
- app/views/content_items/guide_single.html.erb
- config/routes.rb
We think it might really help our SEO to have guide content on one page.  The how to vote page is particularly interesting because we have some data about searching intents that might bring people to this page.  We also think that amending this format to a single page might benefit voice answers.
There are some existing issues with guides having multiple h1 tags on a page. This PR doesn't attempt to fix it (and in a way makes it worse) because we have more h1s on the page than we used to (because on the multiple sections).  I'm led to believe that this is not relevant to WCAG by this [trello card on the GOV.UK accessibility backlog](https://trello.com/c/LzxvPjUz/117-fix-multiple-h1-heading-structure).
Other than that, this has been mostly stolen from the existing guide layout, only …
> Render a guide as a single page

- app/presenters/content_item_presenter.rb
- app/presenters/machine_readable/yaml_faq_page_schema_presenter.rb
- app/views/content_items/guide_single.html.erb
- config/machine_readable/voting-in-the-uk.yml
- test/integration/guide_test.rb
We think that the voting intents around this page mean that users will benefit from a more curated schema.  This is intended to be a one of a kind for now, and is obviously time sensitive, hence the somewhat blunt approach.
The content for the FAQPage schema is loaded from a local config file, and presented.  It's hard to do this programmatically from the content in the content item because the sections we want don't necessarily map to an h2 and the following paragraphs (for example).  
We'll be looking into how to structure our content/apis to make things like this easier in the near future.
I've added a couple of light touch tests to ensure that they aren't broken inadvertently.
We'll be keeping the content in the yaml file in step with the published content until we find a better …
> Add hardcoded FAQPage schema for voting-in-the-uk

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/helpers/_organisation-logos.scss
- app/assets/stylesheets/views/_html-publication.scss
- app/views/content_items/html_publication.html.erb
- test/integration/html_publication_test.rb
- organisation logos on html publications are stacked, which wastes vertical and horizontal space as they only occupy around 1/4 of the page width on desktop
- this change uses flexbox to arrange the logos in columns across the page, improving the use of space
- for older browsers that don't support flexbox (IE10 and below), the original layout is preserved
This change is in response to [this issue](https://github.com/alphagov/government-frontend/issues/981).
Example page:
- [live](https://www.gov.uk/government/publications/canada-united-kingdom-joint-declaration/canada-united-kingdom-joint-declaration)
- [heroku](https://government-frontend-pr-1530.herokuapp.com//government/publications/canada-united-kingdom-joint-declaration/canada-united-kingdom-joint-declaration)
> Change organisations logo layout on HTML publications

- config/machine_readable/voting-in-the-uk.yml
This is in sync with the live version of https://www.gov.uk/voting-in-the-uk
There's a diff of the content here: https://publisher.publishing.service.gov.uk/editions/5db306a6ed915d0abee89539/diff
Not all sections of the content item are included (which is why we have the schema config in a yaml file right now).
> Update the date of the election on FAQPage schema

- config/machine_readable/voting-in-the-uk.yml
The content was updated on Friday so we need to update this to keep it in step.  There is [a diff of the content changes](https://publisher.publishing.service.gov.uk/editions/5dbc325c40f0b670153e4e18/diff) in Publisher.
The relevant page in the preview app is https://government-frontend-pr-1537.herokuapp.com/voting-in-the-uk
Only certain sections of the page are included in the schema, because there's a limit to the amount of content that can be included in the FAQ schema. (That's also the reason for using a separate yml config file for this rather than generating it dynamically from the content item).
The [initial version of the page](https://docs.google.com/document/d/14g7FK-v_Y5iqWcB9y5WqTUWU6JuY_eaSGAqxXSMb0Ek/edit#heading=h.9w2yx5uysegs) (with the relevant FAQ sections highlighted) …
> Update /voting-in-the-uk schema

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_contents-list-with-body.scss
- app/assets/stylesheets/components/_download-link.scss
- app/assets/stylesheets/components/_error-message.scss
- app/assets/stylesheets/components/_figure.scss
- app/assets/stylesheets/components/_important-metadata.scss
- app/assets/stylesheets/components/_print-link.scss
- app/assets/stylesheets/components/_published-dates.scss
- app/assets/stylesheets/components/helpers/_variables.scss
- app/assets/stylesheets/helpers/_content-bottom-margin.scss
- app/assets/stylesheets/helpers/_organisation-links.scss
- app/assets/stylesheets/helpers/_parts.scss
- app/assets/stylesheets/helpers/_publisher-metadata-with-logo.scss
- app/assets/stylesheets/mixins/_margins.scss
- app/assets/stylesheets/mixins/_white-links.scss
- app/assets/stylesheets/print.scss
- app/assets/stylesheets/views/_coming-soon.scss
- app/assets/stylesheets/views/_consultation.scss
- app/assets/stylesheets/views/_detailed-guide.scss
- app/assets/stylesheets/views/_document-collection.scss
- app/assets/stylesheets/views/_guide.scss
- app/assets/stylesheets/views/_html-publication.scss
- app/assets/stylesheets/views/_unpublishing.scss
Remove toolkit sass dependency. Should be no visual changes.
(some) Pages to check:
- https://government-frontend-pr-1529.herokuapp.com
- https://government-frontend-pr-1529.herokuapp.com/government/organisations/attorney-generals-office/about
- https://government-frontend-pr-1529.herokuapp.com/government/case-studies/get-britain-building-carlisle-park
- https://government-frontend-pr-1529.herokuapp.com/government/publications/car-show-me-tell-me-vehicle-safety-questions/car-show-me-tell-me-vehicle-safety-questions
- https://government-frontend-pr-1529.herokuapp.com/log-in-file-self-assessment-tax-return
---
https://government-frontend-pr-1529.herokuapp.com/component-guide
> Remove govuk_frontend_toolkit sass dependency

- config/machine_readable/voting-in-the-uk.yml
- test/integration/guide_test.rb
We're adding a query param to the links in the FAQSchema to help us measure when traffic is being referred from links parsed from the schema, and when it's coming from more traditional means.
[The query param (`?foo=bar`) should go before the fragment (`#baz`)](https://tools.ietf.org/html/rfc3986#section-4.2) where applicable.
> Add query params to schema.org links

- config/machine_readable/voting-in-the-uk.yml
We're extending the content covered in this schema to include a link to more comprehensive information about who can vote in the general election.
This is already in the [live content](https://www.gov.uk/voting-in-the-uk#elections-you-can-vote-in) but wasn't originally included in the schema for brevity.
> Add eligibility criteria

- config/machine_readable/voting-in-the-uk.yml
The diff of this is [markdown in publisher](https://publisher.publishing.service.gov.uk/editions/5dd7c2dfe5274a0aca896563/diff) which might be easier to use to check the changes.
The content is now live though, and so the html should match that in the [Eligibility to vote section](https://www.gov.uk/voting-in-the-uk?sdfsd#eligibility-to-vote)
I've added the `src=schema` query string to the links to help us monitor traffic driven from the schema.org json.
> Update voting eligibility to match live content

- app/controllers/content_items_controller.rb
- app/services/presenter_builder.rb
This content is new to the Publishing API, and while I believe
Government Frontend is the appropriate place for it to be rendered, I
want to put of that decision, and the decisions around how to render
it until after the intended changes to history mode have been made, as
that's what I'm focusing on.
> Don't attempt to render pages for Governments

- README.md
Replaces two links in the `government-frontend` README which were pointing to pages that no longer exist on GOV.UK / are now being rendered by different frontend applications.
> Replace broken links to live GOV.UK formats

- app/presenters/content_item/political.rb
Currently, Whitehall includes the details of the associated government
for some content in the details. Now Whitehall also links the content
to a content item representing the government.
Using the linking approach is preferable going forward, as that means
the Publishing API can take care of updating the content store when a
government changes (becoming historical), rather than Whitehall having
to publish new editions.
This change to Government Frontend can be deployed once all the
relevant content has been linked to the correct government, something
which is being done in bulk from Whitehall.
> Switch to using the government from links, rather than the details

- app/presenters/contact_presenter.rb
HMRC needs webchat functionality on  5 more contacts pages. 
Added the urls required and their corresponding webchat_ids as per ticket https://govuk.zendesk.com/agent/tickets/3862497
1. Charities and Community Amateur Sports Clubs
https://www.gov.uk/government/organisations/hm-revenue-customs/contact/charities-and-community-amateur-sports-clubs-cascs
Webchat server channel 1087
2. Employers: expatriate employees
https://www.gov.uk/government/organisations/hm-revenue-customs/contact/enquiries-from-employers-with-expatriate-employees Webchat server channel 1089
3. Employment related securities
https://www.gov.uk/government/organisations/hm-revenue-customs/contact/share-schemes-for-employees
Webchat server channel 1088
4. Non-UK resident employees …
> added 5 new webchat_ids that will show webchat links

- app/presenters/content_item/political.rb
- test/presenters/publication_presenter_test.rb
Now that we properly represent governments in the links hash, we can use the title from there instead of the title of the government in the details hash.
[Trello](https://trello.com/c/WnCAxrlz/901-display-changed-government-name-in-history-mode-banner)
> Set history banner title from government in the links hash

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_back-to-top.scss
- app/assets/stylesheets/components/_download-link.scss
- app/assets/stylesheets/components/_important-metadata.scss
- app/assets/stylesheets/components/_published-dates.scss
- app/assets/stylesheets/components/_publisher-metadata.scss
- app/assets/stylesheets/helpers/_parts.scss
- app/assets/stylesheets/mixins/_govuk-template-link-focus-override.scss
- app/assets/stylesheets/mixins/_white-links.scss
- app/views/components/_download-link.html.erb
https://trello.com/c/nhfpb4wh/139-revisit-government-frontend-in-light-of-knowing-about-the-govuk-compatibility-govuktemplate-flag
This switches to using the $govuk-compatibility-govuktemplate and removes other code that was implemented to get the correct focus states.
The only visual change should be an update to the focus state of buttons when they are both hovered/active and focused. 
Button example page: https://www.gov.uk/settled-status-eu-citizens-families/applying-for-settled-status
-----
Examples of pages affected by updates, where no visual change is expected:
- Back to top link: https://www.gov.uk/guidance/pregnancy-advice-on-contact-with-animals-that-are-giving-birth
- Download link: https://www.gov.uk/foreign-travel-advice/afghanistan (PDF link beneath image)
- Published …
> Use compatibility flag for focus state colours and remove manual fixes

- .rubocop.yml
- app/assets/javascripts/modules/show-gov-uk-verify-hint.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/views/_choose_sign_in.scss
- app/views/content_items/service_sign_in/_choose_sign_in.html.erb
- config/initializers/csp.rb
- spec/javascripts/show-gov-uk-verify-hint.spec.js
This is a time-limited live test of showing a Verify hint to the users
who have verified with GOV.UK Verify before.
This test should be teared down before 20th December 2019.
The way this works, is on page load, an Ajax call is made to Verify domain to check whether
the user has successfully verified with an IDP before, if they haven't nothing happens. If they
have a new box is displayed at the top of the page showing their IDP and an option to continue.
A few points to consider when reviewing:
- the hint will only show on personal tax account sign-in page
- CSP rules have been adjusted by adding a new domain to our S3 where we store
IDP and Verify logos. It's an identical copy of the gov_uk_app_config gem (had to add and exclusion to robocop as it's failing the linter)
- added tests to …
> HUH-74: Verify sign-in hint on interstitial page - live test

- app/assets/stylesheets/views/_choose_sign_in.scss
There's some inconsistency in the browsers (talking about you Safari!). Firefox and Chrome works fine.
By setting to a zero value instead of negative it makes it better.
---
https://government-frontend-pr-1588.surge.sh/gallery.html
https://government-frontend-pr-1588.herokuapp.com/component-guide
> HUH-74: Fix margin for on the Verify hint

- app/assets/stylesheets/components/_contents-list-with-body.scss
Update colour contrast for back-to-top bar as it currently doesn't meet WCAG AA
---
Example page:
https://government-frontend-pr-1589.herokuapp.com/guidance/track-a-dbs-application
https://government-frontend-pr-1589.surge.sh/gallery.html
> Update back to top colour contrast

- app/views/content_items/statistical_data_set.html.erb
Use the Dataset schema.org schema for statistical dataset pages.
Related to https://github.com/alphagov/govuk_publishing_components/pull/1247
https://trello.com/c/0W3LfcGl/1232-implement-schemaorg-dataset-schema-on-published-statistics-document-types
---
https://government-frontend-pr-1609.surge.sh/gallery.html
https://government-frontend-pr-1609.herokuapp.com/component-guide
> Add Dataset structured data

- app/assets/stylesheets/components/_published-dates.scss
- app/views/components/_published-dates.html.erb
- test/components/published_dates_test.rb
Change notes are currently rendered all on one line, which can be hard to read.
This preserves line breaks in the change notes, ensuring any leading or trainlig blank lines are removed.
Before
After
[Trello](https://trello.com/c/rdNti5Hh/1670-5-investigate-allowing-line-breaks-in-change-notes)
> Allow new lines to show in change notes

- app/assets/javascripts/webchat/library.js
- app/models/webchat.rb
- app/views/shared/_webchat.html.erb
- lib/webchat.yaml
- spec/javascripts/webchat.spec.js
- test/presenters/contact_presenter_test.rb
updated the webchat yaml to point to the new nuance urls - pul lrequest to facilitate testing
---
https://government-frontend-pr-1622.surge.sh/gallery.html
https://government-frontend-pr-1622.herokuapp.com/component-guide
> New hmrc provdier yaml

- app/assets/javascripts/webchat/library.js
- lib/webchat.yaml
- test/presenters/contact_presenter_test.rb
Updated display logic for messages in accordance with availability responses shown below.
Inside hours of operation, no agents logged in 
{"inHOP":"true","status":"offline","availability":"false"}  = UNAVAILABLE                 = Webchat is closed at the moment.
Outside hours of operation
{"inHOP":"false","status":"offline","availability":"false"} = UNAVAILABLE                 = Webchat is closed at the moment.
Inside hours of operation, agents logged in and chat ready immediately
{"inHOP":"true","status":"online","availability":"true"}   = AVAILABLE                      = Advisers are available to chat.
Inside hours of operation, agents logged in and there is a space in the queue
{"inHOP":"true","status":"busy","availability":"true"}      = AVAILABLE                      = Advisers are …
> Hmrc webchat availability scenario update

- app/assets/stylesheets/components/_header-notice.scss
- app/presenters/content_item/no_deal_notice.rb
- app/presenters/content_item_presenter.rb
- app/views/components/_header-notice.html.erb
- app/views/components/docs/header-notice.yml
- app/views/content_items/case_study.html.erb
- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/document_collection.html.erb
- app/views/content_items/html_publication.html.erb
- app/views/content_items/publication.html.erb
- test/components/header_notice_test.rb
Trello: https://trello.com/c/FLS2G6uj/370-frontend-display-no-deal-content-notice-banner-on-relevant-pages
- Adds a header-notice component. This could eventually be rolled into our existing [notice component](https://components.publishing.service.gov.uk/component-guide/notice), but at the moment the use case is only within government-frontend and could be iterated multiple times as it's still being tested, so it's easier keeping it within one app.
- Adds the concept of a No Deal Notice to specific content items to match the [Whitehall flag](https://github.com/alphagov/whitehall/pull/5249).
We want to flag no-deal content to users as it may potentially not be relevant to them at the moment.
> No deal notice

- app/presenters/publication_presenter.rb
- app/views/content_items/publication.html.erb
- test/contracts/govuk_content_schemas_test.rb
- test/controllers/content_items_controller_test.rb
- test/controllers/service_sign_in_content_item_controller_test.rb
- test/controllers/step_navigation_controller_test.rb
- test/integration/corporate_information_page_test.rb
- test/integration/document_collection_test.rb
- test/integration/guide_print_test.rb
- test/integration/guide_test.rb
- test/integration/help_page_test.rb
- test/integration/html_publication_test.rb
- test/integration/meta_tags_test.rb
- test/integration/phase_label_test.rb
- test/integration/publication_test.rb
- test/integration/service_sign_in/choose_sign_in_test.rb
- test/integration/service_sign_in/create_new_account_test.rb
- test/integration/statistical_data_set_test.rb
- test/integration/topical_event_about_page_test.rb
- test/integration/travel_advice_atom_feed_test.rb
- test/integration/travel_advice_print_test.rb
- test/integration/travel_advice_test.rb
- test/integration/working_group_test.rb
- test/support/govuk_content_schema_examples.rb
- test/test_helper.rb
We want to use the correct schema.org type as much as possible.  National statistics, Official statistics and Transparency types contain things of interest to people searching for open data.
I've fixed a bunch of gds-api-adapter deprecation warnings as part of this PR, so reviewing by commit might be advised.
I also discovered a `===` comparison which I'm not sure is intended, so I've flipped it back to `==`.
Example pages: 
- https://government-f-stats-2-675loifr4.herokuapp.com/government/statistics/residues-of-veterinary-medicines-in-food-2019 (official stats)
- https://government-f-stats-2-675loifr4.herokuapp.com/government/statistics/local-authority-capital-expenditure-and-receipts-in-england-2018-to-2019-individual-local-authority-data (national stats)
- …
> Roll out Dataset schema to more types

- app/assets/stylesheets/components/_header-notice.scss
- app/presenters/content_item/no_deal_notice.rb
- app/presenters/content_item_presenter.rb
- app/views/components/_header-notice.html.erb
- app/views/components/docs/header-notice.yml
- app/views/content_items/case_study.html.erb
- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/document_collection.html.erb
- app/views/content_items/html_publication.html.erb
- app/views/content_items/publication.html.erb
- test/components/header_notice_test.rb
Reverts alphagov/government-frontend#1636
We originally reverted this as it turns out we didn't want to deploy it before Thursday 30th Jan 2020. This PR reverts the revert... preparing it for Thursday.
See https://github.com/alphagov/government-frontend/pull/1629 for all the original commits and explanation
> Add no deal notice 

- app/assets/stylesheets/components/_header-notice.scss
- app/presenters/content_item/no_deal_notice.rb
- app/views/components/_header-notice.html.erb
- app/views/components/docs/header-notice.yml
- test/components/header_notice_test.rb
Trello: https://trello.com/c/fBavxD33/426-no-deal-notice-should-display-if-no-links-provided
When the publisher in Whitehall ticks the checkbox for the notice to be displayed with no links, the `brexit_no_deal_notice` is present, with a value of `[]`.
We were expecting to see the notice in this case. However, the code was assuming we should only show the notice if links were present.
> Show no deal notice with no links

- app/views/layouts/application.html.erb
- app/views/shared/_webchat.html.erb
Change to remove SRI on the JavaScript / CSS and remove the `crossorigin` attribute.
This change is part of [RFC-115](https://github.com/alphagov/govuk-rfcs/pull/115).
Changes have been tested on integration, [seen here](https://github.com/alphagov/static/pull/1993#issuecomment-580287175)
> Remove crossorigin and SRI from our static assets (CSS/JS)

- docs/PULL_REQUEST_TEMPLATE
Remove the heroku link in PR templates
We are using the new heroku review apps, which don't have fixed URLs based on PR number.
> Remove heroku link from PR template

- app/assets/javascripts/webchat/library.js
- app/models/webchat.rb
- app/views/shared/_webchat.html.erb
- spec/javascripts/webchat.spec.js
Updated the default availability request to be in JSON as opposed to JSONP. 
Need to check on integration as this environment has been "whitelisted" to allow requests to the Nuance server.
Note: Local Dev environments using port numbers have not been included 
---
https://government-frontend-pr-1642.surge.sh/gallery.html
https://government-frontend-pr-1642.herokuapp.com/component-guide
> Hmrc webchat update to JSON availability reqest

- test/models/webchat_test.rb
See failure in https://ci.integration.publishing.service.gov.uk/job/government-frontend/job/deployed-to-production/506/console
> Fix "uninitialized constant ActiveModel::ValidationError" in test

- app/presenters/html_publication_presenter.rb
- app/views/content_items/html_publication/_print_meta_data.html.erb
- test/integration/html_publication_test.rb
- test/presenters/html_publication_presenter_test.rb
Trello - https://trello.com/c/w5dsqKuc/1381-remove-redundant-fields-for-whitehall-attachments-org-contact-and-web-isbn
These file types are redundant and should be removed. They are no longer being sent to the publishing api by whitehall
These fields are also being removed from govuk content schemas and whitehall
whitehall - https://github.com/alphagov/whitehall/pull/5333
content schemas - https://github.com/alphagov/govuk-content-schemas/pull/958
---
> Remove web_isbn and print_meta_data_contact_address

- app/views/content_items/html_publication/_print_meta_data.html.erb
- test/integration/html_publication_test.rb
Following https://github.com/alphagov/government-frontend/pull/1649 Web ISBN has been removed. This left us with "Print ISBN" which sounds a bit odd if there are no other ISBN's. This renames "Print ISBN" to make things a bit clearer.
---
> Rename "Print ISBN" to "ISBN"

- app/presenters/consultation_presenter.rb
- app/presenters/content_item/featured_attachments_migration.rb
- app/presenters/publication_presenter.rb
- test/presenters/content_item/featured_attachments_migration.rb
If both are set and the attachments field is the same size as the
documents field.  If they're not the same size an error is logged.  We
can use this to be confident that, after republishing everything,
we've not somehow lost any data.
When we're happy to remove the old field, we can revert this commit
and just use the new field directly.
---
[Trello card](https://trello.com/c/iOfOQesh/1389-make-frontend-apps-render-featuredattachments)
https://government-f-msw-rfc-11-dk2x9g.surge.sh/gallery.html
> Override old "documents" fields with new "attachments" fields

- app/presenters/content_item/news_image.rb
- test/presenters/content_item/news_image_test.rb
In the past this linked to an image served by Whitehall, but because of the way Rails generates hashes for assets, we can't guarantee that this URL will always exist. This hasn't been a problem in the past because we've been able to put an unhashed version of the image on the Whitehall machines, but since moving to AWS the machines can be recreated at any moment and won't have the file.
To solve this problem I've uploaded the file to Asset Manager and we can link to that instead. Ideally, we wouldn't depend on a file in a different application, but this solves the problem for now.
This is similar to https://github.com/alphagov/collections/pull/1522.
[Trello Card](https://trello.com/c/2hsW6TBA/1766-5-investigateplaceholderjpg-being-missing-from-whitehallbackend-machines-now-its-in-aws)
> Use a placeholder image from asset-manager

- app/controllers/asset_manager_redirect_controller.rb
- config/routes.rb
- test/controllers/asset_manager_redirect_controller_test.rb
This is [currently handled by Whitehall](https://github.com/alphagov/whitehall/blob/master/test/functional/asset_manager_redirect_controller_test.rb) but we're trying to move away from Whitehall being a frontend application. The next best place for this bit of code seems to be Government Frontend.
The code itself is used to handle assets which are still being requested on their own URL before we migrated all assets over to Asset Manager.
Once this is merged and deployed, I will set up a route in Special Route Publisher which sends requests prefixed with `/government/uploads` to Government Frontend.
[Trello Card](https://trello.com/c/Ubk3IEYg/1450-investigate-redirecting-whitehall-assets-higher-in-the-stack)
> Handle old-style /goverment/uploads routes

- config/routes.rb
- test/controllers/asset_manager_redirect_controller_test.rb
Currently the route for assets assumes that it ends with a file extension (for example `.pdf`). In the case of the preview URLs (which end with `/preview`) it thinks the format of the page is `.pdf/preview`. This gets URL encoded into `.pdf%2Fpreview` by Rails and so the redirect doesn't work.
Rather than handling the file extension special, this PR changes it to accept any path containing any number of file extensions or slashes in no particular format.
> Support redirecting to asset preview URLs

- app/assets/stylesheets/components/_header-notice.scss
- Adjust padding on black header to take border into account
- Remove bottom margin on last paragraph inside the notice
> Header notice spacing tweaks

- app/assets/stylesheets/application.scss
- app/views/content_items/travel_advice.html.erb
Add a warning about travel to travel advice pages. Awaiting final copy.
Bespoke component used - see also https://github.com/alphagov/frontend/pull/2282 for sibling pull request.
Design has been signed off by @stephenjoe1
Example URL: https://www.gov.uk/foreign-travel-advice/france
<table>
<tr>
<th>Mobile before</th>
<th>Mobile after</th>
</tr>
<tr><td valign="top">
</td><td valign="top">
</td></tr></table>
> Emergency travel warning

- app/views/development/index.html.erb
The dev landing page was looking a bit broken. It's always looked a little unstyled, but with the recent change to the components gem it was looking worse (the search box was unstyled, footer layout was broken). This fixes that.
Before:
After:
> Fix the appearance of the dev landing page

- app/views/content_items/contact.html.erb
HMRC are experiencing high numbers of calls at the moment and we want to make sure that people are using the webchat were possible, so move this up to the top of the page so it becomes more visible.
[Trello Card](https://trello.com/c/L5LSGY8T/1879-move-webchat-section-on-hmrc-contact-pages)
> Move webchat to the top of the page

- app/views/content_items/contact.html.erb
There was some confusion in the last change (5b00d3e40ec26778a918be73aeb58f99f82c585f) and it looks like they would prefer the webchat section to appear above the email section (rather than above the phone section).
[Trello Card](https://trello.com/c/L5LSGY8T/1879-move-webchat-section-on-hmrc-contact-pages)
> [DO NOT MERGE] Move webchat section to be above the email section

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/print.scss
- app/views/content_items/travel_advice.html.erb
Update government-frontend to import the sass for only the components it is using, instead of all components, as [documented here](https://github.com/alphagov/govuk_publishing_components/blob/master/docs/install-and-use.md#import-sass-for-individual-components).
Before:
Total **851 KB**
After:
Total **628 KB**
Also update all travel pages (such as [foreign travel advice to the USA](http://localhost:3090/foreign-travel-advice/usa/entry-requirements)) to use the warning text component. This was previously not possible because the component did not allow for a heading but has been updated to allow this.
This is being done as part of this PR because this page used styles from the component but not the component itself - so I noticed it had broken when I made the Sass change (because the …
> Use individual component sass

- app/presenters/content_item/news_image.rb
- test/presenters/content_item/news_image_test.rb
Adds a new placeholder image for world news stories.
https://govuk.zendesk.com/agent/tickets/3992513
> Add different placeholder image for world news

- .rspec
This project dropped rspec for minitest all the way back in 2014 (798ee918)
so no longer needs this file.
---
> Remove .rspec

- Dockerfile
- config/application.rb
- config/environments/development.rb
- config/environments/production.rb
Trello: https://trello.com/c/oNEtjIVp/99-serve-static-assets-from-www-hostname
This is marked as a draft until the following PR's are merged (and in puppets case, deployed):
This removes the configuration in this app that specifies that this app should use the `assets.publishing.service.gov.uk` hostname for serving assets with the expectation that these assets will instead be served off the `www` hostname. This is to implement [RFC 115](https://github.com/alphagov/govuk-rfcs/blob/master/rfc-115-enabling-http2-on-govuk.md). Because of this the path to assets will be changed to be prefixed with `/assets` so all GOV.UK assets are hosted in the same path.
The asset host can still be configured in this app by a `ASSET_HOST` environment variable, this will be used in govuk-docker and …
> Switch asset hostname

- .rubocop.yml
- app/helpers/machine_readable_metadata_helper.rb
- app/helpers/webchat_availability_helper.rb
https://github.com/alphagov/rubocop-govuk/issues/73
We should avoid disable Cops for the entire repo on the basis of a
couple of issues, which can be fixed or ignored in-place.
---
> Remove redundant RuboCop config

- app/assets/stylesheets/helpers/_organisation-logos.scss
- this prevents the contextual breadcrumb component, when showing the step nav header component, from colliding with it
- the step nav component has no margin bottom, but the other components that can be displayed in the contextual breadcrumb do, so this change should not impact variations on this layout as the newly added top margin will overlap any bottom margin from the breadcrumb
Happens on pages like: https://www.gov.uk/government/publications/coronavirus-covid-19-guidance-on-phased-return-of-sport-and-recreation/elite-sport-return-to-domestic-competition-guidance
Before:
After:
> Add margin top to organisation logos

- test/models/webchat_test.rb
Before:
```
bundle exec rails test test/models/webchat_test.rb:20
Started with run options --seed 46747
WebchatTest
test_should_return_error_if_config_is_invalid                  ERROR (0.00s)
Minitest::UnexpectedError:         NameError: uninitialized constant ActiveModel::ValidationError
test/models/webchat_test.rb:25:in `block in <class:WebchatTest>'
Finished in 0.00445s
1 tests, 0 assertions, 0 failures, 1 errors, 0 skips
```
After:
```
bundle exec rails test test/models/webchat_test.rb:20
Started with run options --seed 32937
WebchatTest
test_should_return_error_if_config_is_invalid                   PASS (1.28s)
Finished in 1.28149s
1 tests, 1 assertions, 0 failures, 0 errors, 0 skips
```
[The previous fix](https://github.com/alphagov/government-frontend/commit/277f49385154c028785fca …
> Fix active_model require in webchat test

- app/views/content_items/html_publication.html.erb
Updates html publication content items to use the new _html_publication_ schema [recently added to govuk_publishing_components](https://github.com/alphagov/govuk_publishing_components/pull/1543)
> 304 Fix FAQ Schemas for html publications

- app/controllers/asset_manager_redirect_controller.rb
- test/controllers/asset_manager_redirect_controller_test.rb
Trello: https://trello.com/c/oNEtjIVp/99-serve-static-assets-from-www-hostname
I'm removing this as part of a plan to remove Plek#public_asset_host and
the associated GOVUK_ASSET_HOST env var. The reason to remove these is
because they are the same #asset_root and GOVUK_ASSET_ROOT, which pushes
developers to consider which one to use when they both have the same
effect.
Government frontend appears to be the only app other than Whitehall that
has used this method, which I assume is because the code it is used in
was ported from Whitehall.
---
> Use Plek#asset_root over Plek#public_asset_host

- app/views/content_items/guide.html.erb
Continuing on from alphagov/govuk_publishing_components#1617 and https://github.com/alphagov/collections/pull/1840/commits/99718ffce5e9753be9eba16f63faf9cb9ab98d88
Human readable structured data is much easier to debug and reason about.
> Format machine readable output

- app/presenters/content_item/no_deal_notice.rb
Content designers have come up with some text that we hope people will understand
better.
https://trello.com/c/ijTzb33b/347-change-the-brexit-banner-on-whitehall-pages
> Update the Brexit "banner" text

- app/presenters/content_item/no_deal_notice.rb
- app/views/components/_header-notice.html.erb
- test/components/header_notice_test.rb
We wanted to be able to display multiple lines of text.
[Content update](https://docs.google.com/document/d/1jfwDr-G4NP0HKDfNKA5FG2POGjeH1JVK7qGrA4Fj7FE/edit#)
[Trello card](https://trello.com/c/ijTzb33b/347-tweak-the-brexit-banner-on-whitehall-pages)
Example page: https://www.gov.uk/government/publications/eu-lawyers-in-the-uk-from-1-january-2021
> Update Brexit notice

- app/assets/stylesheets/components/_important-metadata.scss
Fixes the focus state for links in the important metadata component, on pages like https://www.gov.uk/guidance/coronavirus-covid-19-travel-corridors
Before:
After:
This occurred on visited links when focussed.
> Fix focus states for 'applies to' links

- app/views/content_items/detailed_guide.html.erb
- test/integration/detailed_guide_test.rb
They are the same shape as answers, so we should be OK to reuse that template.
https://government-f-detailed-g-zfkvcd.herokuapp.com/guidance/get-a-discount-with-the-eat-out-to-help-out-scheme
https://government-f-detailed-g-zfkvcd.herokuapp.com/guidance/coronavirus-covid-19-travel-corridors …
> Add FAQ Page schema to detailed guides

- lib/webchat.yaml
Trello: https://trello.com/c/mXx8NF3R
#WHAT
Update the YAML file for HMPO
https://github.com/alphagov/government-frontend/blob/master/lib/webchat.yaml
Change availability URL:
https://hmpowebchat.klick2contact.com/v03/providers/HMPO2/api/availability.php
to
https://hmpowebchat.klick2contact.com/v03/providers/HMPO/api/availability.php
#WHY
The above change should ensure the webchat page (which is live but not currently linked from anywhere) works correctly
www.gov.uk/government/organisations/hm-passport-office/contact/passport-advice-and-complaints
- Make sure you follow [the guidance for deployments](https://docs.publishing.service.gov.uk/manual/development- …
> Update HMPO Webchat URL

- lib/publish_static_pages.rb
Replaced 'FCO' with 'FCDO' in Lancaster House and King Charles Street page titles.
> Update 'FCO' in history page titles

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/helpers/application_helper.rb
These are the changes required to upgrade to ruby 2.7
There's a script that can be run to change the ruby version across all apps, so I've made the necessary changes for 2.7.1 but left the version as 2.6.6. However, the tests don't pass under ruby 2.6.6.
---
https://government-frontend-pr-1828.surge.sh/gallery.html
- Check your branch is being deployed in the [Release app](https://release.publishing.service.gov.uk/applications/government-frontend), after …
> Upgrade to ruby 2.7.1

- app/assets/stylesheets/application.scss
- app/views/content_items/guide.html.erb
Adds an additional skip link above the guide contents that goes to the actual content of the guide.
This was identified as a WCAG fail (specifically WCAG SC 2.4.1) as for keyboard only users, it meant that they had the option to skip navigation in the govuk header but still have to tab through the navigation of the guide contents to get to the "actual" content of the guide. This solution of using an additional skip link is used on govuk search pages to skip past filters.
**Card:** https://trello.com/c/x3QKWP0z/340-cannot-bypass-repeated-navigation
- Make sure you follow [the guidance for deployments](https://docs.publishing.service.gov.uk/manual/development- …
> Add additional skip link on guide views

- app/views/components/_header-notice.html.erb
This section is not currently translated, though it can and does appear on
[some non-English pages](https://www.gov.uk/government/publications/trade-with-the-uk-from-january-2021-prepare-your-eu-business/handel-mit-dem-vereinigten-konigreich-ab-1-januar-2021-fur-unternehmen-mit-sitz-in-der-eu).  Because of this, we should add the English language attribute to the section.
https://trello.com/c/uaDK0l8U/445-add-language-attribute-to-autogenerated-eu-transition-banner
- Check your …
> Add 'en' language attribute to the Brexit callout

- app/presenters/content_item/withdrawable.rb
https://trello.com/c/k5JCHIoZ/382-add-language-attribute-to-withdrawn-banner
Withdrawal notices are always presented in English but sometimes
appear on a translated page. This passes en as a language value to
the notice component when that happens.
Example page: https://www.gov.uk/government/news/changes-to-uk-visa-application-process-in-germany.de
There are no visual changes. **The effects of this won't be seen until the notice component supports the lang attribute which will happen in a forthcoming release (see https://github.com/alphagov/govuk_publishing_components/pull/1686) but there are no ill effects from passing the extra parameter.**
- Make sure …
> Add lang attribute to withdrawal notice

- lib/webchat.yaml
Trello: https://trello.com/c/VmJdgRXL
Add this page as a base_path:
https://www.gov.uk/government/organisations/hm-passport-office/contact/webchat
With the same values for open_url, availability_url and open_url_redirect as the existing page.
> Add new webchat base_path for HMPO

- app/assets/stylesheets/helpers/_organisation-logos.scss
- app/views/content_items/html_publication.html.erb
- test/integration/html_publication_test.rb
Move logos at the top of organisation pages out of the ordered list element.
These logos should not be in an ordered list as there's nothing to denote them as ordered. This could've been changed into an unordered list but this itself isn't ideal as they aren't really intended as a list. [Example of a page with multiple …
> Remove ordered list markup for organisation logos

- app/presenters/specialist_document_presenter.rb
Certain Specialist Documents can have internal notes that
should not be presented on the frontend.
[Trello](https://trello.com/c/Wec6wH3s/2146-3-add-protected-food-names-specialist-document)
> Remove internal notes from specialist document presenter

- app/controllers/content_items_controller.rb
- test/integration/guide_test.rb
We want to test whether changing the text on the banner navigation improves click through rate. We want to keep the test simple, so we've just chosen a [single, high traffic page](https://www.gov.uk/visit-europe-1-january-2021) as
victim.
The displayed navigation is determined in [govuk_publishing_components](https://github.com/alphagov/govuk_publishing_components/blob/b4c917fb07db5d6c9ed24b1d27dc8a09387832b1/lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority.rb#L11), however we know how it works. If a certain taxonomy content_id is found in the taxon links of a content item, then a step by step banner (colloquially a "super breadcrumb") will be displayed using the title of the taxon.
If we intercept the content item before it is passed to the component, then …
> Test alternative text for Transition navigation

- config/routes.rb
https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review
Previously this repo had a very basic healthcheck. This extends it
with a more thorough check of the infrastructure it needs to run:
Memcached [1] [2]. Since the caching can fail silently, there is
even more motivation for us to know about it.
[1]: https://github.com/alphagov/slimmer/blob/64482b28572a7d038827de214832317e75f0c1ae/lib/slimmer.rb#L13
[2]: https://github.com/alphagov/government-frontend/blob/0bd1bbad134b2ddb521e2372b45df0d08bc7b142/Gemfile#L5
- Make sure you follow [the guidance for deployments](https://docs.publishing.service.gov.uk/manual/development-pipel …
> Add healthcheck for memcached

- app/assets/stylesheets/helpers/_parts.scss
- app/views/content_items/travel_advice.html.erb
- test/integration/travel_advice_test.rb
This removes the bespoke 2 column layout for parts navigation and replaces it with the contents-list component. This brings in a header of "Contents" and makes the navigation more consistent with the rest of the site which is good for accessibility. 
https://trello.com/c/LbVmpaK6/441-inconsistent-naming-of-table-of-contents
Sample page: https://www.gov.uk/foreign-travel-advice/switzerland
> Replace bespoke nav with contents list component

- app/controllers/content_items_controller.rb
- test/integration/guide_test.rb
This reverts commit b58beb46b355595fc67a8b168c3444ab9f56566a.
We're going to update the transition taxonomy topic to have a new name, based on what we did here. We no longer need this custom code.
https://trello.com/c/kRqJ1G0X/539-update-transition-taxon-name
> Revert "Test alternative text for Transition navigation"

- app/assets/stylesheets/views/_html-publication.scss
- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/html_publication.html.erb
Adds print link to detailed guides
User research found that users were not clear on how to print pages.
https://trello.com/c/zSFv4dxR/497-add-the-print-button-to-c19-pages-that-dont-have-it
- Detailed guide: https://government-f-add-print--e2mbxk.herokuapp.com/guidance/coronavirus-covid-19-information-for-the-public
- HTML publications: https://government-f-add-print--e2mbxk.herokuapp.com/government/publications/wuhan-novel-coronavirus-infection-prevention-and-control/updates-to-the-infection-prevention-and-control-guidance-for-covid-19
--- 
- Make sure you follow [the guidance for deployments](https://docs.publishing.service.gov.uk/manual/development-pipeli …
> Add print link to detailed guides

- app/views/content_items/_attachments.html.erb
- app/views/content_items/_body_with_related_links.html.erb
- app/views/content_items/_document_collection_body.html.erb
- app/views/content_items/case_study.html.erb
- app/views/content_items/consultation.html.erb
- app/views/content_items/corporate_information_page.html.erb
- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/fatality_notice.html.erb
- app/views/content_items/gone.html.erb
- app/views/content_items/guide.html.erb
- app/views/content_items/html_publication.html.erb
- app/views/content_items/news_article.html.erb
- app/views/content_items/publication.html.erb
- app/views/content_items/service_sign_in/_choose_sign_in.html.erb
- app/views/content_items/service_sign_in/_create_new_account.html.erb
- app/views/content_items/specialist_document.html.erb
- app/views/content_items/speech.html.erb
- app/views/content_items/statistical_data_set.html.erb
- app/views/content_items/take_part.html.erb
- app/views/content_items/topical_event_about_page.html.erb
- app/views/content_items/travel_advice.html.erb
- app/views/content_items/unpublishing.html.erb
- app/views/content_items/working_group.html.erb
- app/views/content_items/world_location_news_article.html.erb
- app/views/shared/_travel_advice_summary.html.erb
This updates the way Govspeak wraps content.
Templates updated:
* world location news article - [live](https://gov.uk/government/news/changes-to-secure-english-language-test-providers-for-uk-visas) - [dev](http://government-frontend.dev.gov.uk/government/news/changes-to-secure-english-language-test-providers-for-uk-visas)
* working group - [live](https://gov.uk/government/groups/abstraction-reform) - [dev](http://government-frontend.dev.gov.uk/government/groups/abstraction-reform)
* unpublishing - [live](https://www.gov.uk/government/publications/foi-03274-cost-of-advertising-on-social-media) - [dev](http://government-frontend.dev.gov.uk/publications/foi-03274-cost-of-advertising-on-social-media)
* gone - seems to be the same as unpublishing?
* travel advice - …
> Update Govspeak usage

- app/views/content_items/_body_with_related_links.html.erb
- app/views/content_items/detailed_guide.html.erb
Replaces `sanitise` with `raw` in detailed guide template.
The `sanitize` method was stripping out tables for reasons. But using `sanitize`s allow list meant listing most of the HTML elements, and introducing a risk of further breakages if a element is accidently left out of the allow list - so using `raw` was the least worst compromise between fixing this now, fixing this in the future, and security.
Before:
After:
---
- Check your branch is being deployed in the [Release …
> Swap sanitize for raw when used in Govspeak component

- lib/webchat.yaml
Trello: https://trello.com/c/qawZD9QE
Update the YAML file for HMPO - add webchat to a new page
https://github.com/alphagov/government-frontend/blob/master/lib/webchat.yaml
Adds this page as a base_path:
https://www.gov.uk/government/organisations/hm-passport-office/contact/hm-passport-office-webchat
With the same values for open_url, availability_url and
open_url_redirect
The above change will add a webchat page which will be linked to from
https://www.gov.uk/passport-advice-line.
This retitles and will replace the existing page as they were getting a
number of people thinking it was an HMRC page.
- Make sure you follow [the guidance for …
> Add Webchat to `hm-passport-office-webchat page`

- app/views/content_items/travel_advice.html.erb
Trello: https://trello.com/c/iS4WvL1j
Updates the link to Wales restrictions on pages like https://www.gov.uk/foreign-travel-advice/cuba
We changed the link for wales information to:
https://gov.wales/coronavirus-firebreak-frequently-asked-questions
We should change it back to https://gov.wales/local-lockdown
> Update the Wales link on travel advice call out

- app/views/content_items/_attachments.html.erb
Allows tracking attributes to be rendered when sanitized
This will allow us to track detail summary component
https://trello.com/c/3U1QEEK1/584-add-event-tracking-to-track-how-many-times-request-accessible-format-is-clicked
> allow tracking attributes to be rendered when sanitized

- app/views/content_items/_attachments.html.erb
Attachments are currently hard coded to use `h2` which isn't very flexible. The attachment component is often used as a child of a section of a page, in which case the heading level of the component should be adjusted to reflect the hierarchy of the content.
There is already a `h2`  in `app/views/content_items/_attachments.html.erb` –  it does not make sense that the attachments have the same heading level as their parent. This specifies that they use `h3` instead.
Related PRs:
- [adds the ability to override default heading level in attachment component](https://github.com/alphagov/govuk_publishing_components/pull/1781) 
- [changes the heading level of pre-rendered legacy attachments from Whitehall](https://github.com/alphagov/whitehall/pull/5885) …
> Use heading level 3 for attachments

- app/views/content_items/html_publication/_print_meta_data.html.erb
The `gsi` part has been removed from government email address. This now matches the address given at https://www.nationalarchives.gov.uk/information-management/keeping-touch/contacts/.
Zendesk ticket: https://govuk.zendesk.com/agent/tickets/4322124
> Update email address for National Archives in print metadata

- app/presenters/content_item/shareable.rb
- test/integration/consultation_test.rb
The [share links component](https://components.publishing.service.gov.uk/component-guide/share_links) has  "Share on" as visually hidden text by default.
This helps AT users make sense of the links (ie "Share on Facebook" makes more sense than just "Facebook").
It looks like `government-frontend` is also adding a hidden "Share on" as part of the share links text. This is causing an issue where hidden content is being repeated e.g. "Share on Share on Facebook". 
https://trello.com/c/shAQ6AQu/460-social-media-links-repeat-hidden-content-bug
----------
- Make sure you follow [the guidance for deployments](https://docs.publishing.service.gov.uk/manual/developmen …
> Remove hidden "Share on" from share links text

- app/presenters/content_item/corporate_information_groups.rb
Some [corporate information pages](https://www.gov.uk/government/organisations/migration-advisory-committee/about) are erroring because the list of IDs in corporate information groups in the  details hash doesn't match the list of linked corporate information pages in the links hash.
Even if they do eventually resolve, these two lists will occasionally be out of sync when they're updated because of the way our publishing system works. We should defend against this so it doesn't error.
Resolves this [sentry error](https://sentry.io/organizations/govuk/issues/1813208304/?environment=production&project=202226&query=is%3Aunresolved&statsPeriod=14d)
Compare:
- [before](http://government-frontend.herokuapp.com/government/organisations/migration-advisory-committee/about)
- …
> Fix corporate information pages error

- app/views/content_items/_attachments.html.erb
A user on basecamp recently reported confusing navigation around attachments where they were hearing numbers as part of the link. This turned out to be due to Jaws reading out the filename of the attachments as the aria-hidden attribute is being sanitized out of the duplicate thumbnail link. This adds aria-hidden to the allow list to prevent that.
- Check your branch is being deployed in the [Release app](https://release.publishing.service.gov.uk/applications/government-frontend), …
> Allow aria-hidden attribute so icons are hidden from screenreaders

- app/views/content_items/travel_advice.html.erb
- due to the change from national to local coronavirus restrictions on 02/12/2020
[Trello](https://trello.com/c/xFCKku6i/948-update-the-travel-advice-callout-box-on-travel-pages)
> Update travel advice callout box content

- app/presenters/specialist_document_presenter.rb
- test/presenters/specialist_document_presenter_test.rb
This behaviour is slightly confusing because it re-orders the facets that are already in a defined order in Specialist Publisher. This means that content designers might be expecting the order in a certain way and then when it gets to the frontend the ordering is different.
A very clear example of this is if you had three facets, one `date`, one `text` and one `time`. In the finder the facets might be ordered such that you have the date, the time and then the text field.
However this code will re-order that so you end up with the date and time field separated by the text field in between them.
This change was added in 4f0f5a63b9127717bc738ac1375ef80f853979f5 but I would argue that a better solution is to avoid having this sort of logic in the frontend app and instead make it such that the …
> Don't sort facets by type

- app/views/content_items/travel_advice.html.erb
This is due to the new tier 4 guidance.
> Update travel advice callout box for country pages.

- app/views/components/_figure.html.erb
- test/components/figure_test.rb
Previously if the image source was missing the tag would still render.
This was fine in many browsers but caused a big empty space in IE.
This pull request should fix that issue.
Zendesk: https://govuk.zendesk.com/agent/tickets/4391436
> Add filter to prevent empty image tags from rendering in figures

- app/controllers/content_items_controller.rb
- app/views/content_items/briefing.html.erb
- test/controllers/content_items_controller_test.rb
Add support for briefing
Creates a new schema type style for briefings
https://trello.com/c/MGERWyD9/682-add-page-template-for-video-briefing-to-government-frontend
> Add support for briefing

- config/locales/dr.yml
- config/locales/pa-ur.yml
- config/locales/ps.yml
Corresponding ticket: https://govuk.zendesk.com/agent/tickets/4398151.
These languages are right-to-left (RTL) in Whitehall, but not in this frontend app:
https://github.com/alphagov/whitehall/blob/bcda05ec43d87b3bec1541e644c1373bafa2a3e8/config/locales/ps.yml#L315-L316
This will ensure pages such as this one are rendered correctly:
https://www.gov.uk/guidance/coronavirus-covid-19-taxis-and-phvs.ps
How the page should look (with different language with correct cofig):
https://www.gov.uk/guidance/coronavirus-covid-19-taxis-and-phvs.ar
> Set i18n.direction to rtl for languages DR, PA-UR, PS

- app/presenters/content_item/no_deal_notice.rb
https://trello.com/c/kUqdYsCD/746-update-the-wording-of-the-whitehall-brexit-callout-box
This is a short-term change to encourage users to act on what they
see, in advance of the planned content update on the 31st.
> Update brexit callout box content

- app/presenters/content_item/brexit_notice.rb
- app/views/components/_brexit-notice.html.erb
https://trello.com/c/93GauglA/755-update-whitehall-guidance-call-out-box-8
> Update content / design of Brexit notice

- app/assets/javascripts/modules/track-links.js
- app/views/content_items/briefing.html.erb
- spec/javascripts/modules/track-links.js
Adds new module to track all links rendered within the briefings page
This will allow us to add tracking where it is required for reporting purposes.
https://trello.com/c/BHqdvxKg/688-set-up-analytics-for-briefing-video-page
> Add tracking for briefings

- app/views/content_items/travel_advice.html.erb
The last line should not be `<strong>`, so this has been amended.
> No longer render text as <strong> importance

- app/presenters/travel_advice_presenter.rb
- app/views/content_items/_ireland_covid_travel_guidance.html.erb
- app/views/content_items/travel_advice.html.erb
- test/presenters/travel_advice_presenter_test.rb
[Trello](https://trello.com/c/J01vLuo9/1042-display-different-travel-advice-content-based-on-country?menu=filter&filter=label:Tech)
This updates the copy for the individual country pages. It also adds different copy for the Irish page in line with advice from FCDO.
> Update callout box

- app/assets/stylesheets/components/_contents-list-with-body.scss
- fixes issue https://github.com/alphagov/government-frontend/issues/1921
- 'contents' sticky element z-index was lower than z-index for some of the elements of the step by step navigation in the right hand column
Before: 
After:
> Fix step nav appearing over contents

- app/controllers/asset_manager_redirect_controller.rb
- test/controllers/asset_manager_redirect_controller_test.rb
At the moment these redirects aren't cached which means that they won't be cached by Fastly and will always hit our origin. This PR should prevent this from happening and instead they'll be cached by Fastly for 1 day.
We should think about moving this code out of government-frontend and into Nginx, but that's a bigger change so this PR should help for now.
[Trello Card](https://trello.com/c/CN2bhhZi/1998-make-asset-redirections-cacheable)
> Ensure asset-manager redirects are cached

- app/assets/javascripts/modules/cookieless-tracker.js
- app/assets/javascripts/modules/track-variant.js
- app/controllers/application_controller.rb
- app/controllers/concerns/cookieless_testable.rb
- app/views/layouts/application.html.erb
- spec/javascripts/track-variant-spec.js
- test/controllers/content_items_controller_test.rb
This PR adds a new Cookieless A/A test, which sends hit-only data to analytics up until cookies have been accepted by the user. This is necessary to understand whether we can rely on the approach offered by our CDN to reliably assign users to a variant of an A/B test and maintain that variant, such that we'd expect to see an even distribution of users across all active variants of a test (or according to any prescribed percentages of variants).
**This PR should not be merged until we're ready to turn on the A/A test.**
> Add cookieless A/A test

- app/assets/stylesheets/print.scss
- app/views/content_items/travel_advice.html.erb
- app/views/shared/_translations.html.erb
Update component references following this change to correct component file names: https://github.com/alphagov/govuk_publishing_components/pull/1848
Also taking the opportunity to add missing print styles for the `skip link` component.
> Fix component references

- app/presenters/specialist_document_presenter.rb
- test/presenters/specialist_document_presenter_test.rb
Fixes https://sentry.io/organizations/govuk/issues/1870942805/events/latest/?project=202226
This code was initially added in 9f39d8856f8d8a998e8b2c26f61c334eb9a3af69,
around 4 years ago, seemingly just being cautious. There's no
evidence it has highlighted any useful problems for us, and
recently the check has become problematic as departments often
publish documents first before making the finder live.
The link would be there in Publishing API, but Publishing API
wouldn't know how to expand it yet as the finder itself isn't
live, so nothing matches its `content_id`.
> Don't notify Sentry when specialist document is missing finder

- app/views/content_items/travel_advice.html.erb
- test/integration/travel_advice_test.rb
https://www.pivotaltracker.com/story/show/176908254
This has been requested by FCDO [1], and agreed with GOV.UK Notify,
who originally asked for the word "alert" to be removed so that it
did not conflict with the upcoming emergency alert pages on GOV.UK.
Note the original change was applied via the default text changing
in GOV.UK Publishing Components [2].
[1]: https://govuk.zendesk.com/agent/tickets/4417745
[2]: https://github.com/alphagov/govuk_publishing_components/commit/36953fd979db6c144ba0fd0245ed414066fc88b0
> Restore original wording for travel advice emails

- app/assets/javascripts/modules/sticky-element-container.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_contents-list-with-body.scss
- app/assets/stylesheets/helpers/_sticky-element-container.scss
- app/assets/stylesheets/views/_html-publication.scss
- app/presenters/content_item/brexit_notice.rb
- app/views/components/_important-metadata.html.erb
- app/views/components/_published-dates.html.erb
- app/views/components/_publisher-metadata.html.erb
- app/views/content_items/_document_collection_body.html.erb
- app/views/content_items/html_publication.html.erb
- app/views/content_items/travel_advice.html.erb
- spec/javascripts/modules/sticky-element-container.spec.js
- test/components/important_metadata_test.rb
- test/components/published_dates_test.rb
- test/components/publisher_metadata_test.rb
- test/integration/document_collection_test.rb
- Switch from using `trackClick` script to `gemTrackClick` script. They are virtually the same, the latter being [copied over from `static` to `govuk_publishing_components`](https://github.com/alphagov/govuk_publishing_components/pull/1751)
- Switch from using `toggle` script to `gemToggle` script
- Port `sticky-element-container` from `static` as this app is the only one using it ([PR prepared to remove it from `static`](https://github.com/alphagov/static/pull/2405) after this gets merged)
Part of [a bigger piece of work](https://github.com/alphagov/static/pull/2405) to reduce the size of assets served to users and keep our codebase to a minimum.
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.ht …
> Switch from static to govuk_publishing_components scripts

- app/assets/stylesheets/helpers/_publisher-metadata-with-logo.scss
- app/presenters/content_item/metadata.rb
- app/views/shared/_publisher_metadata_with_logo.html.erb
- test/controllers/content_items_controller_test.rb
- test/integration/consultation_test.rb
- test/integration/detailed_guide_test.rb
- test/integration/document_collection_test.rb
- test/integration/fatality_notice_test.rb
- test/integration/news_article_test.rb
- test/integration/publication_test.rb
- test/integration/specialist_document_test.rb
- test/integration/speech_test.rb
- test/integration/statistical_data_set_test.rb
- test/test_helper.rb
Update local app Meta block to [gem component](https://components.publishing.service.gov.uk/component-guide/metadata)
As part of on-going accessibility team work to align to gem based architecture to ensure future a11y improvements to components are cascaded to all apps
(Before > After)
[Ticket](https://trello.com/c/VSxcJHxI)
Testing Links:
https://www.gov.uk/government/news/statement-from-greg-clark-secretary-of-state-for-business-energy-and-industrial-strategy
https://www.gov.uk/government/publications/dwp-welsh-language-leaflets
https://www.gov.uk/government/news/christmas-2016-prime-ministers-message
Translations are out of scope of this particular card and have been [raised here](https://trello.com/c/mEGHKNGt/2371-5-investigate-and-fix-dates-not-being-translated):
> Switch to meta block

- app/views/content_items/_attachments.html.erb
Replace `sanitize` with `raw` for the legacy pre-rendered documents list.
`sanitize` was stripping out the `tabindex` attribute from the legacy document list markup provided by Whitehall. `sanitize` requires an allowlist of attributes, but a more future-proof option is to use `raw` since this is markup from a trusted source.
The document icon was focusable with an invisible focus state - so a user could tab there but there was no visual indication that the document icon was focused. This removes that link from the tab index, so it's no longer reachable by tabbing through the page. This means that the tab focus jumps from the document title to the next document title without detouring. …
> Replace sanitize with raw for legacy document list

- config/locales/en.yml
We have support for two variations of Punjabi. This PR updates the language names for these two locales for clearer differentiation.
[trello](https://trello.com/c/devOCero/2369-3-change-punjabi-pakistan-language-tag)
> Add script names to Punjabi locale variations

- app/views/content_items/travel_advice.html.erb
This removes `from 8 March` from the copy in the callout boxes.
[Trello](https://trello.com/c/SGZS4z43/224-travel-advice-call-out-box-update-8-march)
> Update travel advice callout boxes

- app/presenters/content_item/attachments.rb
- app/views/content_items/_attachments.html.erb
- test/test_helper.rb
I was able to find three causes to a problem where unique schemas weren't being generated for the [random publication test](https://github.com/alphagov/government-frontend/blob/15c9c09d64767f73c145d9610494e675e246247d/test/integration/publication_test.rb#L4-L6).
1. Generating for an unexpected document type (fix in first commit)
2. Assumptions of attachment presence in code that don't match schema rules (fix in 2nd commit)
3. Invalid schemas being generated due to an array expecting unique items (fix in https://github.com/alphagov/govuk_schemas/pull/63) 
More info in the commits.
> Fix flaky random publication tests

- config/locales/bn.yml
- config/locales/pa-pk.yml
- config/locales/pa.yml
Adds the provided translated strings for the following languages:
* Bangla (`bn`)
* Punjabi Gurmukhi (`pa`)
* Punjabi Shahmukhi (`pa-PK`)
Follows on from https://github.com/alphagov/whitehall/pull/6023.
This was done with the `locales_export_import` gem to avoid large amounts of copy and pasting.
Trello card: https://trello.com/c/bJZCbzaI
> Add translations for Bangla, Punjabi Gurmukhi and Punjabi Shahmukhi

- config/machine_readable/how-to-vote.yml
This work is in preparation for the local elections on 6 May.
We can't use Top Actions because we don't render them visibly on the page. We've been advised to use "Related content" instead.
Related to: https://github.com/alphagov/frontend/pull/2665
> Rename Top Actions in How To Vote schema

- app/views/components/_back-to-top.html.erb
It was recommended on GOVUK Accounts team's DAC report that `focusable="false"` and `aria-hidden="true"` are added to the "up arrow" SVG on our [Privacy notice and Accessibility statement page](https://www.gov.uk/government/publications/govuk-accounts-trial-full-privacy-notice-and-accessibility-statement/govuk-accounts-trial-full-privacy-notice#content):
SVGs are in tab sequence in IE, which means that focus disappears as it sequences over them. Adding `focusable="false"` ensures the SVG is not in tab sequence, while `aria-hidden="true"` ensures that it is hidden from screen readers.
https://trello.com/c/lNkwruEi/647-fix-accessibility-issues-raised-by-dac 
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pi …
> Update back-to-top SVG arrow attributes

- config/locales/az.yml
- config/locales/fa.yml
- config/locales/he.yml
- config/locales/id.yml
- config/locales/ja.yml
- config/locales/ka.yml
- config/locales/ko.yml
- config/locales/ms.yml
- config/locales/th.yml
- config/locales/vi.yml
- config/locales/zh.yml
In https://github.com/alphagov/government-frontend/pull/2045, we updated the plural rules for each language that we support that is not included [in the ruby-i18n gem](https://github.com/ruby-i18n/i18n/blob/master/test/test_data/locales/plurals.rb).
This removes the keys that are no longer required in each language from their locale files.
Trello card: https://trello.com/c/lkVB57ri
I have not made any changes to `zh-hk` and `zh-tw` as there are problems with the translations, which will be addressed in https://trello.com/c/mbFPEn9h.  Also not made any changes to `tr` as I believe the i18n rules for this could be wrong, so will write a card to look into this.
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development- …
> Remove unused pluralisation keys from locale files

- Gemfile.lock
- config/machine_readable/how-to-vote.yml
We know the actual deadline dates now, so we can add them to the schema.
Should match the content in https://www.gov.uk/how-to-vote#postal-vote-deadlines-for-6-may-elections (and the proxy section)
> Add deadlines for how-to-vote

- config/locales/ar.yml
- config/locales/ru.yml
- config/locales/si.yml
- config/locales/so.yml
- config/locales/sr.yml
- config/locales/ta.yml
- config/locales/tk.yml
- config/locales/uk.yml
- config/locales/uz.yml
- config/locales/zh-hk.yml
- config/locales/zh.yml
Most of these are blank keys anyway. The exception is the `taxonomy_navigation` key which only exists in Arabic and Russian.
https://trello.com/c/qlDQFq2I/2428-3-remove-locale-keys-with-no-english-translation
> Remove translation keys that do not exist in the English version

- app/views/content_items/travel_advice.html.erb
'England' currently links to the old https://www.gov.uk/guidance/national-lockdown-stay-at-home URL which has been redirected to the new guidance.
This PR updates it to points directly at: https://www.gov.uk/guidance/covid-19-coronavirus-restrictions-what-you-can-and-cannot-do
> Update link for England travel advice

- config/environments/development.rb
Relates to: https://github.com/alphagov/govuk-docker/pull/478
This is required for testing authenticating-proxy(.dev.gov.uk).
> Support other domains in development

- app/assets/stylesheets/views/_contact.scss
Adds a `word-wrap` css class to `.contact`
bandaid fix for issues with the contacts block on [this page](http://government-frontend.dev.gov.uk/government/publications/attendance-allowance-claim-form).
| --- | --- |
| ![Screenshot 2021-04-21 at 16 18 06](https://user-images.githubusercontent.com/64783893/115578462-36fcfc00-a2bd-11eb-9d6c-7deb087b3657.png) | ![Screenshot 2021-04-21 at 16 18 12](https://user-images.githubusercontent.com/64783893/115578478-3cf2dd00-a2bd-11eb-9d64-ea018485bcc6.png) |
This is a very quick fix and does not solve the root problem that whitehall is using a single partial to render similar information for 2 different use cases ([the other use case](https://www.gov.uk/world/organisations/british-embassy-kabul)). Notably, the instance seen here is …
> Add break word to contact class

- app/views/histories/11_downing_street.html.erb
Changes the first `h3` on the [history of 11 Downing Street page](https://www.gov.uk/government/history/11-downing-street) ("Roots of the Treasury") to a `h2`.
Currently this pages is semantically incorrect. Headings should follow a logical pattern stepping down one at a time based on sections in the content eg: h1, h2, h2, h2, h3, h2 etc. For screen reader users who explicitly rely on heading structure it could be confusing and create the idea that they've missed a section of text.
[Card](https://trello.com/c/bGJM4TXa/703-11-downing-street-page-has-confusing-heading-structure)
| --- | --- |
| ![Screenshot 2021-04-29 at 17 30 12](https://user-images.githubusercontent.com/64783893/116587561-7c9b7380-a912-11eb-958b-ada516f5c14a.png) | ![Screenshot 2021-04-29 at 17 30 …
> Change h3 to an h2 on 11 downing street

- app/views/content_items/travel_advice.html.erb
Trello: https://trello.com/c/nPAGEeOq
Update travel advice callout box on `/foreign-travel-advice/<country-name>` to show the rule changes from Monday 17th May
|Before|After|
|-------|-----|
|<img width="1648" alt="Screenshot 2021-05-14 at 16 25 00" src="https://user-images.githubusercontent.com/5793815/118293469-996aa600-b4d1-11eb-8e55-11d8a1fc95ad.png">|<img width="1648" alt="Screenshot 2021-05-14 at 16 25 45" src="https://user-images.githubusercontent.com/5793815/118293626-bdc68280-b4d1-11eb-8074-a0030bcc54ac.png">|
The new advice should start to be displayed from 00:00 on Monday 17th May.
> Add travel advice updates for 17th May 2021

- app/views/content_items/travel_advice.html.erb
https://github.com/alphagov/government-frontend/pull/2106 introduced some logic so that we wouldn't have to deploy at midnight. This just cleans that up now the time has passed.
> Remove time based logic from travel advice.

- test/test_helper.rb
The require statement for the printer doesn't replace the general one for
the module. It's actually unclear how this worked without it, but I don't
think that's worth investigating.
Error, for reference:
```
/govuk/government-frontend/test/test_helper.rb:10:in `<top (required)>':
undefined method `config' for I18n::Coverage:Module (NoMethodError)
```
> Fix error when running a single test

- app/assets/stylesheets/components/_save-this-page.scss
- app/helpers/save_this_page_helper.rb
- app/views/components/_save_this_page.html.erb
- app/views/components/docs/save_this_page.yml
- config/locales/en.yml
- test/components/save_this_page_test.rb
- test/helpers/save_this_page_helper_test.rb
Add `save-this-page` component to `government-frontend`.
The work for this was originally done on the [components gem](https://github.com/alphagov/govuk_publishing_components/pull/2069). 
However, in the meanwhile it was decided that in the early stages of our experiment, we would only be trialling the component on select pages on the `government-frontend` app. Adding this as an app-level component at first will ensure that we can iterate on it rapidly in the initial stages (if needed). This code is mostly copied over from the [original PR](https://github.com/alphagov/govuk_publishing_components/pull/2069) with some fairly significant differences in the tests, as a result of the testing libraries being different. 
Nothing renders without a `page_path` parameter. The component also takes …
> Add new Save page box

- app/controllers/content_items_controller.rb
- app/presenters/content_item/brexit_hub_page.rb
- app/presenters/content_item_presenter.rb
- app/views/content_items/detailed_guide.html.erb
- app/views/layouts/application.html.erb
- config/locales/en.yml
- test/integration/detailed_guide_test.rb
- test/test_helper.rb
We are using the detailed guide doc type to publish the brexit child taxon pages, but we need to customise a few things. 
See [commit](https://github.com/alphagov/government-frontend/pull/2097/commits/fa11d218fd8a1e152be8b2dc219a8d72191adeec) message for more details.
The review apps for this pr are pointed at integration where the detailed guides have been published.
- [Business page](https://government-f-brexit-hub-pxjxwy.herokuapp.com/guidance/brexit-guidance-for-businesses)
- [Citizens page](https://government-f-brexit-hub-pxjxwy.herokuapp.com/guidance/brexit-guidance-for-individuals-and-families) …
> Customise detailed guide pages for Brexit hubs

- app/assets/stylesheets/helpers/_organisation-links.scss
##What
Update the brand colour link override seen on [about us pages](https://www.gov.uk/government/organisations/attorney-generals-office/about) so that the organisation logo is always the default black colour.
##Why
To ensure that our patterns are consistent across govuk. This pattern's default state is black and there is no value added to the user by changing the link colour to the brand colour of a given department.
[Card](https://trello.com/c/djz1Sxy3/740-update-organisation-component-to-be-consistent-throughout-govuk-and-remove-any-style-overrides)
##Visual changes
| --- | --- |
| ![Screenshot 2021-06-03 at 17 32 50](https://user-images.githubusercontent.com/64783893/120682767-be30b880-c494-11eb-888a-7e57a84f4d8e.png) | ![Screenshot 2021-06-03 at 17 33 …
> Remove brand colour for organisation logos on department about pages

- app/views/content_items/consultation.html.erb
The text content from this page comes from a translation file. This means that any coding gets exposed unless we deliberately render it as raw. Since we control the translations we can be confident that doing this is safe. The error that was exposed was noted by a user in https://govuk.zendesk.com/agent/tickets/4582865
Sample URL: https://www.gov.uk/government/consultations/tobacco-and-related-products-legislation-introduced-between-2015-to-2016-reviewing-effectiveness
> Fix exposed html from translation

- app/lib/body_parser.rb
- app/presenters/content_item/body.rb
- app/presenters/content_item/brexit_hub_page.rb
- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/detailed_guide/_brexit_links.html.erb
- test/integration/detailed_guide_test.rb
- test/test_helper.rb
- test/unit/body_parser_test.rb
We need to add some tracking to the links on the new brexit child taxon pages. Because the content of detailed guides is sent to government-frontend as a string of html in the details hash of the content item, we need to parse it before we can add the data attributes. See commit [message](https://github.com/alphagov/government-frontend/commit/f61f705186099ab477e3f2af2258491ca5c39c49) for more information.
- Once this #2097 is merged, the review apps for this pr will render the brexit pages correctly. 
- The review apps will need to be pointed at integration.
- The detailed guides will need to be published in integration:
- https://whitehall-admin.integration.publishing.service.gov.uk/government/admin/detailed-guides/1204514
- https://whitehall-admin.integration.publishing.service.gov.uk/go …
> Add some analytics to the brexit child taxon pages

- app/views/content_items/detailed_guide/_brexit_links.html.erb
This partial is already rendered in a `govuk-grid-row` so adding an extra one here is causing a container misalignment.
[Recommend reviewing without whitespace changes](https://github.com/alphagov/government-frontend/pull/2140/files?diff=split&w=1).
> Fix brexit links partial alignment

- config/locales/ne.yml
Nepali has two types of plural, [according to the Unicode rules](https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html#ne), but the translations we received didn't specify pluralization, so I'm making these changes based on other languages.
> Fixes Nepali translation

- app/lib/body_parser.rb
- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/detailed_guide/_brexit_links.html.erb
- test/integration/detailed_guide_test.rb
- test/unit/body_parser_test.rb
- As requested [here](https://docs.google.com/presentation/d/19bQ2ojvtlqGg9QmjMlNE6R55cxPRAnewh7MljV00KWU/edit?pli=1&disco=AAAAMgHfaLU) we would like to record a different value when a user clicks on this bit:
- The content list is generated based on the ID of the H2's, but due to the way we pull out those H2's on the child taxon pages the ID's were missing. See [commit](https://github.com/alphagov/government-frontend/pull/2143/commits/029ea0cdeed3c73981421a235edfb27ab604071a) for more info.
---
> Amend tracking and anchor links on brexit child taxon pages

- Gemfile.lock
Manually bumping govuk-publishing-components to v.[24.16.0](https://github.com/alphagov/govuk_publishing_components/pull/2166) as we need the scroll tracking in this release of the gem to be live asap. 
( I wasn't able to kick off a dependabot as there's an edited [PR](https://github.com/alphagov/government-frontend/network/updates/165807409) needing a poke. )
Trello: https://trello.com/c/OD132cuZ/1610-add-scroll-depth-tracking-to-new-rules-of-origin-triage-page
> Bump publishing components gem version

- app/assets/stylesheets/helpers/_organisation-links.scss
Fix to resolve buttons text colours on buttons
https://www.gov.uk/government/organisations/department-for-work-pensions/about/accessible-documents-policy
Button text colours are being overwritten due to the styles applying department branding, this is an WCAG fails as the colour contrast makes this text unreadable therefore impact low vision and blind users.
As part of an on-going Epic corporate information templates will be updated entirely so this will act as a temporally fix until this work is complete
> Fix button colour

- app/presenters/travel_advice_presenter.rb
- config/locales/en.yml
FCO (Foreign and Commonwealth Office) changed to FCDO (Foreign, Commonwealth and Development Office) - this updates mentions of it
> Update mentions of FCO

- app/presenters/content_item/brexit_taxons.rb
- config/locales/cy.yml
- config/locales/en.yml
The majority of the content of the brexit child taxon pages is stored in the body of the content item. As such the translations are handled by whitehall and rendered by gov-frontend as a detailed guide. However the guidance nav link is hardcoded, so must be amended here.
https://draft-origin.publishing.service.gov.uk/guidance/brexit-guidance-for-businesses.cy
https://government-f-translate--splmdt.herokuapp.com/guidance/brexit-guidance-for-businesses.cy
Trello https://trello.com/c/0chnMRTQ/1642-create-welsh-versions-of-the-brexit-child-taxon-pages
> Add welsh translation to brexit child taxon pages

- app/views/content_items/detailed_guide/_brexit_sections.html.erb
- test/integration/detailed_guide_test.rb
When a user clicks on a link in a section on one of the Brexit child taxon pages, send the name of the section rather than the name of the page, as that's already recorded. Request from PA.
trello https://trello.com/c/RcOTINct/1653-change-event-category-value-on-child-taxon-pages
> Amend tracking category on Brexit child taxon pages

- README.md
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_important-metadata.scss
- app/presenters/content_item/national_applicability.rb
- app/presenters/fatality_notice_presenter.rb
- app/presenters/specialist_document_presenter.rb
- config/locales/en.yml
- test/presenters/detailed_guide_presenter_test.rb
- test/presenters/publication_presenter_test.rb
- test/presenters/specialist_document_presenter_test.rb
Apply the feature flag for new link styles, from the latest release of GOV.UK Frontend, on this app.
Additionally updates the readme to include an example of a guide document and replaces instances of the `.app-link` class with `.govuk-link--inverse`.
Part of an ongoing effort by the GOV.UK frontend community and GOV.UK Accessibility team to ensure that we are using the new design system link styles across our apps, ensuring that users reap the benefit of better link visibility.
- The government navigation menu at the top of some government frontend pages isn't using the new link styles properly. This is because this component is reliant on styles from the old "core" layout in static. I won't be pursuing getting these to work perfectly at the moment as the layout is due to be updated to …
> Trigger new link styles for government-frontend

- app/views/histories/10_downing_street.html.erb
- app/views/histories/11_downing_street.html.erb
- app/views/histories/1_horse_guards_road.html.erb
- app/views/histories/king_charles_street.html.erb
- app/views/histories/lancaster_house.html.erb
https://trello.com/c/3ENWcE93/729-confusing-contextual-link-on-some-pages
Remove the link from the context text on the main heading, add breadcrumb to replace it.
The styling of the contextual text in the component doesn't indicate in any way that it is a link without user interaction. We plan to remove the ability to add links from the components gem.  We decided to preserve the linking back to the History page by adding a breadcrumb. The wording there more explicitly describes where the link goes.
> Replace context link with breadcrumb

- app/presenters/content_item/brexit_taxons.rb
- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/detailed_guide/_brexit_sections.html.erb
- test/integration/detailed_guide_test.rb
Send a more specific event tracking label to GA for clicks on section links.
[Review app](https://government-f-amend-even-honozw.herokuapp.com/guidance/brexit-guidance-for-businesses)
[Trello](https://trello.com/c/vrMCwyUy/1667-trello-template-copy-me)
> Amend the tracking category on Brexit child taxon pages

- app/controllers/ab_tests/explore_menu_ab_testable.rb
- app/controllers/content_items_controller.rb
- app/views/layouts/application.html.erb
- test/controllers/content_items_controller_test.rb
Shows users in B variant of AB test the new Explore Super Menu header.
Static has a new header that the GOV.UK Explore team want to AB test as part of their beta.
https://github.com/alphagov/static/pull/2515
Trello https://trello.com/c/LUhrajXF/323-prepare-the-new-menu-a-b-test-for-sections-of-govuk
We are slowly rolling out to users a redesigned header.
https://user-images.githubusercontent.com/424772/123002723-23980b00-d3aa-11eb-8f6b-cf76b6cb0812.mov
https://user-images.githubusercontent.com/424772/123840676-889db480-d906-11eb-9991-1a3f12f91f60.mov
> Add AB Test for Explore Super Menu Navigation

- app/controllers/content_items_controller.rb
- test/controllers/save_a_page_test.rb
I spotted that the account-api was getting a *lot* of saved-page
queries in staging, which I tracked down to this: we're checking if
the page is saved even if the user has no session (which will always
fail).  We can skip the API call in that case.
We had a similar issue once in the Transition Checker, where we were
trying to fetch saved results regardless of whether the user had a
session or not.  Since this has come up twice now we should think
about how this problem can be solved generically.  Maybe we could put
more logic in gds-api-adapters, for example?
> Do not check if a page is saved if a user has no session header

- app/views/histories/history.html.erb
Fix the jump links at the top of https://www.gov.uk/government/history, specifically:
- link to `notable people` was mistyped and wasn't working
- link to `online records` wasn't working because linked heading didn't have an ID
None.
> Fix jump links on history of government

- app/assets/stylesheets/print.scss
There was some refactoring to remove `display: none` rules from component stylesheets in favour of using the `govuk-!-display-none-print` class instead: https://github.com/alphagov/govuk_publishing_components/pull/1561
As a consequence of this, some of the component print stylesheets which previously used to contain CSS are now empty files. This removes references to these files from the application print stylesheet.
Relevant issue: https://github.com/alphagov/govuk_publishing_components/issues/2065
------
> Remove @import of empty print stylesheets

- app/views/content_items/travel_advice.html.erb
There is a bug where these navigation links are sending two GA events
per click. This is occurring because the contents-list component has an
undocumented [1] feature of tracking links which was presumably not
known about when this code was changed to use this component [2].
The resolution for this is to remove the usage of track links on the nav
element and just use the components one.
[1]: https://github.com/alphagov/govuk_publishing_components/blob/147a825fc7608eb3dfdaab0d418c5b2fdaaf08aa/app/views/govuk_publishing_components/components/docs/contents_list.yml
[2]: https://github.com/alphagov/government-frontend/pull/1877
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-r …
> Fix tracking Travel Advice links twice

- app/views/layouts/application.html.erb
Remove the conditional from the explore variant meta tag.
https://trello.com/c/8Y8tYYzk
This was only being output on the page when on the "B" side of the test; the meta tag should be added to the page for all sides of the test so it can be picked up by analytics and the browser extension.
None
> Remove conditional from A/B test meta tag

- app/controllers/ab_tests/explore_menu_ab_testable.rb
- app/controllers/content_items_controller.rb
- app/views/layouts/application.html.erb
- test/controllers/explore_ab_test.rb
At present we're only returning Vary response headers when we get a B variant. We want to do this all the time or it's confusing for Fastly to know how to cache.
I've added a test that ensures (using the `with_variant` helper) that the header is being set correctly, and also checks for analytics set up.
It's trickier to assert things about the template because slimmer's testing is harder to figure out right now, but it'd be useful to add these at some point too. :-)
> Return response headers for Explore AB test

- app/views/content_items/travel_advice.html.erb
**DO NOT MERGE** This change depends upon a new version of the components gem that includes this change: https://github.com/alphagov/govuk_publishing_components/pull/2263
- adds tracking of links only to the foreign advice travel box on /foreign-travel-advice
- should track link clicks using the options on the box and use the link text for the event label
We want to know how effective this box is.
None.
Trello card: https://trello.com/c/Q6kr2nFK/551-add-ga-tracking-codes-to-fcdo-call-out-box-of-covid-info
> Add tracking to the foreign travel advice call out box

- app/views/histories/10_downing_street.html.erb
- app/views/histories/11_downing_street.html.erb
- app/views/histories/1_horse_guards_road.html.erb
- app/views/histories/king_charles_street.html.erb
- app/views/histories/lancaster_house.html.erb
This is a bug fix for the exposed context hash on some history pages. We removed the ability to link context text in the gem and I removed the href from the context hash, but mistakenly left the hash in situ leading to the following visual bug:
Sample broken page: https://www.gov.uk/government/history/lancaster-house
> Fix syntax on context param

- app/views/content_items/travel_advice.html.erb
- uses the new feature of the track click script to track link clicks only inside the grey callout box (the second callout box on the page)
- this is inside govspeak content so we can't directly apply tracking to it, hence the new feature of the track click script to limit tracking to a specific element
Trello card: https://trello.com/c/JREgQ2iv/579-spike-into-tracking-enhancements
> Add tracking to the travel advice pages

- app/assets/stylesheets/application.scss
- app/presenters/content_item/national_applicability.rb
- app/views/content_items/consultation.html.erb
- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/publication.html.erb
- test/integration/consultation_test.rb
- test/integration/detailed_guide_test.rb
- test/integration/publication_test.rb
- test/presenters/consultation_presenter_test.rb
- test/presenters/detailed_guide_presenter_test.rb
- test/presenters/publication_presenter_test.rb
- test/test_helper.rb
https://trello.com/c/WVrZ35zt/793-dev-implementation-of-devolved-nations-task
Replace uses of 'Metadata block component' for new 'Devolved Nations component' for linking to guidance for other nations.
This change takes effect on the following page types -
- Publications e.g. https://www.gov.uk/government/publications/theory-and-practical-driving-tests-taken-at-wigan-and-atherton-with-a-voiceover-or-interpreter
- Statistics e.g. https://www.gov.uk/government/statistics/affordable-housing-supply-in-england-2011-to-2012
- Consultations e.g. https://www.gov.uk/government/consultations/setting-the-grade-standards-of-new-gcses-in-england-2017-2018
- Guidance e.g. https://www.gov.uk/guidance/report-lost-or-stolen-cattle
When no advice is available the component is not rendered e.g. …
> Use devolved nations component in place of important metadata component on publication page

- app/views/content_items/travel_advice.html.erb
Adds scroll tracking to the pages listed on https://www.gov.uk/foreign-travel-advice (but not that page itself). Should add tracking for all pages for all countries, for example on:
- https://www.gov.uk/foreign-travel-advice/afghanistan
- https://www.gov.uk/foreign-travel-advice/afghanistan/coronavirus
- https://www.gov.uk/foreign-travel-advice/afghanistan/safety-and-security
(etc.)
Uses the new AutoScrollTracker module, initialised as a meta tag, configured to track headings. This is included in the latest version of the gem, which has already been added to government-frontend (this PR rebased to match).
We want …
> Add scroll tracking to foreign travel advice pages

- app/views/layouts/application.html.erb
- test/integration/fatality_notice_test.rb
- test/integration/news_article_test.rb
- test/test_helper.rb
Remove use of the [government navigation component][gnc].
The [navigation header][nh] is being rolled out, so this is no longer needed.
---
The component is no longer needed as the navigation header is being rolled out.
[gnc]: https://components.publishing.service.gov.uk/component-guide/government_navigation
[nh]: https://components.publishing.service.gov.uk/component-guide/layout_super_navigation_header
> Remove `government_navigation` component

- config/locales/en.yml
[Trello](https://trello.com/c/fzN6TU9L/660-fcdo-top-grey-box-update-to-reflect-new-travel-roles-october-4th)
- Update red list country link
- Update 'return to England' link
> Update COVID travel links

- app/assets/stylesheets/views/_get-involved.scss
- app/views/content_items/get_involved.html.erb
<table>
<tr><th>Before</th><th>After</th></tr>
<tr><td valign="top">
</td><td valign="top">
</td></tr>
</table>
> Fix get involved styles

- app/assets/javascripts/modules/sticky-element-container.js
- spec/javascripts/modules/sticky-element-container.spec.js
This change removes jQuery from the `sticky-element-container.js` module and replaces it with vanilla JS.
We're removing jQuery from GOV.UK.
[Trello](https://trello.com/c/10eQvjT8/275-from-jquery-from-government-frontend-sticky-element-containerjs-reasonable-js-knowledge-required)
> Remove jQuery from javascripts/modules/sticky-element-container.js

- app/assets/javascripts/application.js
- app/assets/javascripts/set-ga-client-id-on-form.js
- spec/javascripts/set-ga-client-id-on-form.spec.js
Remove jQuery from the set ga client id file.
We're using an old and unsupported version of jQuery for browser support reasons. Rather than upgrade, it's far better to remove our dependence.
jQuery makes writing JavaScript easier, but it doesn't do anything that you can't do with vanilla JavaScript, because it's all written in JavaScript.
Once it's removed, we no longer have to worry about upgrading it, and users don't have to download the jQuery library when they visit GOV.UK.
https://trello.com/c/bqdisKbm/277-from-jquery-from-government-frontend-set-ga-client-id-on-formjs-and-applicationjs-moderate-js-knowledge-required
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-req …
> Remove jq from set ga client

- app/views/content_items/_context_and_title.html.erb
- app/views/content_items/consultation.html.erb
- app/views/content_items/publication.html.erb
- config/locales/en.yml
- test/views/content_items/attachments.html.erb_test.rb
We currently have live pages that have attachments that share the exact same title for a number of publications and consultations. This can make for confusing user journeys and in the case of HTML attachments can make it confusing for users of assistive technology navigating between the pages and can disorientate those with cognitive problems. Our solution to the issue to to adjust the parent page title in cases where this happens and add the word "overview". This will affect both the HTML page title (as seen in the browser tab), and the H1 for affected pages. In unaffected pages the H1 contains the name of the document with supporting document type context above it. Where a page is affected that contextual text has "overview:" appended and it is moved inside the H1 tag. …
> Add "overview:" to titles where an attachment has the same name

- app/assets/javascripts/modules/track-radio-group.js
- spec/javascripts/track-radio-group.spec.js
This change removes jQuery from the `track-radio-group.js` module and replaces it with vanilla JS
We're removing jQuery from GOV.UK
[Trello](https://trello.com/c/IoQlSiAk/276-remove-jquery-from-government-frontend-track-radio-groupjs-reasonable-js-knowledge-required)
> Remove jQuery from track-radio-group.js

- app/assets/stylesheets/components/_published-dates.scss
It should be #0b0c0c as per our designs.
Fixes https://github.com/alphagov/government-frontend/issues/2278
> Fix font colour being black

- app/assets/javascripts/modules/set-ga-client-id-on-form.js
Restores a check for the `window.ga` object to this script. This problem is currently causing a smokey test to fail.
This script is used on pages like https://www.gov.uk/check-income-tax-current-year/sign-in/prove-identity to add the ga client ID to the form action attribute.
This was unintentionally removed in a recent change: https://github.com/alphagov/government-frontend/pull/2276
None.
> Restore check for window.ga

- app/views/content_items/_context_and_title.html.erb
- test/views/content_items/attachments.html.erb_test.rb
In https://github.com/alphagov/government-frontend/pull/2238 we added the word overview to format titles where an attachment shared the name of the page. The intent was for this to appear inside the H1, using the context_inside parameter. Unfortunately a refactor after review meant that the variable was scoped too tightly and never available to the component call. This resolves that by initially setting the variable outside of the each loop, and adds extra testing to ensure it is there when necessary.
Sample affected url: https://www.gov.uk/government/consultations/call-for-evidence-to-inform-orbital-liability-and-insurance-policy
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own …
> Fix variable scope of context boolean

- app/assets/javascripts/modules/sticky-element-container.js
- spec/javascripts/modules/sticky-element-container.spec.js
Currently, the sticky-element in Government Frontend does not follow the JavaScript module pattern, for example...
```
window.GOVUK = window.GOVUK || {}
window.GOVUK.Modules = window.GOVUK.Modules || {};
(function (Modules) {
function StickyElementContainer ($module) {
this.module = $module
}
StickyElementContainer.prototype.init = function () {
// etc.
}
Modules.StickyElementContainer = StickyElementContainer
})(window.GOVUK.Modules)
```
Convert the existing code to be consistent with this pattern.
The module pattern is the standard approach and this JavaScript component does not follow the convention.
[Trello](https://trello.com/c/XwULsSw8/316-convert-sticky-element-in-government-frontend-to-follow-the-module-pattern) …
> Convert sticky-element.js to use Module pattern

- app/views/content_items/get_involved.html.erb
There appears to be a `<div>..</div>` that isn't necessary in the get involved page's "next closing" inset text component.
This was causing Smokey to fail on [this following selector](https://github.com/alphagov/smokey/blob/09fb94026e55061d4f1b4d870bde54db22b1cf3b/features/step_definitions/get_involved_page_steps.rb#L8).
> Remove unused div from get involved inset text

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/controllers/content_items_controller.rb
- app/views/components/_published-dates.html.erb
- app/views/components/docs/published-dates.yml
- app/views/content_items/publication.html.erb
- app/views/shared/_publisher_metadata_with_logo.html.erb
- test/components/published_dates_test.rb
This adds the [Single page notification button](https://components.publishing.service.gov.uk/component-guide/single_page_notification_button) to the `publication` template, after the metadata blocks at the top and bottom of the page.
We only want to launch with a couple of pages in the initial stages, therefore the button will initially show up only on the pages listed on `in_single_page_notifications_trial?` under `content_items_controller.rb`
| Top  | Bottom |
| ------------- | ------------- |
|<img width="386" alt="Screenshot 2021-11-18 at 12 19 40" src="https://user-images.githubusercontent.com/7116819/142414509-00553860-7261-4cf3-8f16-3e2197eac738.png"> | <img width="391" alt="Screenshot 2021-11-18 at 12 19 51" src="https://user-images.githubusercontent.com/7116819/142414530-847106e4- …
> Add the single page notification button to publication template

- app/assets/javascripts/modules/sticky-element-container.js
Fixes https://github.com/alphagov/government-frontend/issues/2297
The sticky element was 'flashing' when positioned at the bottom of the area. This was due to the element being constantly switched between the sticky and non-sticky states.
This was an interesting bug. There is a function called on scroll that sets `this.hasScrolled` and a second function `checkScroll` called on an interval that checks to see if `this.hasScrolled` is true, updates the sticky element as appropriate, then sets it back to false, ready for the next scroll. 
The function `checkResize` checks and then sets the equivalent …
> Fixes sticky element glitch

- app/views/shared/_email_subscribe_unsubscribe_flash.html.erb
The space between the "You've signed up to emails about this page" flash message and the title below is too large.
This amends the `margin-bottom` on the success message and the margin-top of its container ,so that the spacing between the breadcrumb and success message and title below appears more balanced.
| Before  | After |
| ------------- | ------------- |
| <img width="1108" alt="Screenshot 2021-12-02 at 11 08 56" src="https://user-images.githubusercontent.com/7116819/144411245-5010f343-303d-4141-8726-83aa4435d482.png"> | <img width="1478" alt="Screenshot 2021-12-02 at 10 41 11" src="https://user-images.githubusercontent.com/7116819/144411292-2cbfb877-43bf-4e20-8ac9-7c953de4b779.png"> |
| Before  | After |
| ------------- | ------------- |
| <img width="495" alt="Screenshot …
> Amend success message spacing

- app/controllers/content_items_controller.rb
- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/publication.html.erb
- app/views/shared/_publisher_metadata_with_logo.html.erb
Based on feedback we received following our original rollout of the single page notification button to a couple of pages, the GOVUK Accounts team are moving forward with adding the single page notification button to a few additional pages. 
Some of these pages are `detailed_guide` pages rather than `publication`s. 
This adds the button to the `detailed_guide` template, and adds the paths of the new pages to the list in `content_items_controller.rb`.
https://trello.com/c/GHkbMziw/1172-enable-single-page-notifications-on-more-pages
https://trello.com/c/fGfa64jD
> Add notification button to detailed guide template

- Gemfile.lock
Dependabot hasn't spotted this yet and we need the change to the contextual sidebar rolled out.
what I did:
pulled main on government-frontend
ran bundle update govuk_publishing_components
pushed the changes
> Bump the components gem

- app/views/shared/_email_subscribe_unsubscribe_flash.html.erb
- config/locales/en.yml
- test/controllers/content_items_controller_test.rb
Handle the new flash message variation added in https://github.com/alphagov/email-alert-frontend/pull/1223
which should be shown when a user clicks the button to subscribe to
email alerts about a page, but is already subscribed.
[Trello](https://trello.com/c/PkNG9Ecl/1190-journey-when-clicking-on-get-email-updates-when-i-have-a-subscription-already-but-am-not-signed-in)
New banner:
---
> Add 'already subscribed' email flash banner

- app/views/shared/_email_subscribe_unsubscribe_flash.html.erb
- test/controllers/content_items_controller_test.rb
In email-alert-frontend we set this flash message in the
AccountSubscriptionsController[1][2], but the name of the key used in
this app was inconsistent with what was being set - so the banner was
never being shown.
[1] https://github.com/alphagov/email-alert-frontend/blob/22a0a2048dc09243a386a214bb507c52f51bc8f1/app/controllers/account_subscriptions_controller.rb#L86
[2] https://github.com/alphagov/email-alert-frontend/blob/22a0a2048dc09243a386a214bb507c52f51bc8f1/app/services/create_account_subscription_service.rb#L5
---
[Trello card](https://trello.com/c/PkNG9Ecl/1190-journey-when-clicking-on-get-email-updates-when-i-have-a-subscription-already-but-am-not-signed-in)
> Fix `email-subscription-already-subscribed` flash inconsistency

- app/views/content_items/answer.html.erb
- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/guide.html.erb
- app/views/content_items/html_publication.html.erb
Turn on scroll tracking for various pages.
**NOTE** this change depends on [this change](https://github.com/alphagov/govuk_publishing_components/pull/2548) in the components gem being deployed to `static` at the same time, otherwise duplicate or no scroll tracking events may occur.
We're retiring the old scroll tracker and migrating all pages that use it to the new one.
None.
Trello card: https://trello.com/c/sdugtMbX/37-migrate-to-new-scroll-tracker
> Turn scroll tracking on for various pages

- app/views/content_items/guide.html+print.erb
- app/views/content_items/guide.html.erb
- app/views/content_items/travel_advice.html+print.erb
- app/views/content_items/travel_advice.html.erb
- config/locales/en.yml
- test/integration/guide_test.rb
- test/integration/travel_advice_test.rb
https://trello.com/c/OlsybM1y/914-update-print-entire-guide-functionality
- Remove **Print entire guide** button and replace with link **View a printable version of the whole guide** and
- Replace **print link component** with a hyperlink to the printable version page (`/print`)
- Disable the print dialogue from automatically appearing on the printable version page (`/print`)
- Add additional copy below page `h1`, **Printable version** using the **lead paragraph component**
- Add two **Print this page** buttons on the printable version page (`/print`)
- Add analytics / click-rate tracking on both print buttons (top and bottom)
- The current implementation of printing an entire piece of guidance on GOV.UK is very jarring experience e.g. when a user selects the button they are taken to a …
> Update "print entire guide" functionality

- app/views/content_items/detailed_guide.html.erb
Applies to https://www.gov.uk/guidance/travel-abroad-from-england-during-coronavirus-covid-19 and https://www.gov.uk/guidance/travel-to-england-from-another-country-during-coronavirus-covid-19
- for the given URLs, only scroll track some of the headings, not all of the headings
- this will need to be updated in future if the headings change
We only want to scroll track these headings. Anything else is just adding unneeded data.
None.
Trello card: https://trello.com/c/sdugtMbX/37-migrate-to-new-scroll-tracker
> Track only specific headings

- app/views/components/_published-dates.html.erb
This is to prevent the change in this PR being a breaking one:
https://github.com/alphagov/govuk_publishing_components/pull/2558
Once the change above has been rolled out to `government-frontend`, the
additional container can be removed, and the id of the component wrapper updated
from "history" to "full-publication-update-history"
> Add temporary container to published-dates

- app/assets/javascripts/application.js
`require` the script which was introduced in https://github.com/alphagov/govuk_publishing_components/pull/2552 
https://trello.com/c/XwSjaTET
> Require metadata script for skiplink fix

- config/locales/ur.yml
Sets the `i18n.direction` key in the Urdu language file to right-to-left.
This key used by application to determine whether the direction that text should be displayed:
ttps://github.com/alphagov/government-frontend/blob/4fab76c1cc871f3da91592a88a1b06f94922d58d/app/helpers/application_helper.rb#L3
Urdu was missing this key, so was defaulting to displaying it left-to-right.
Before:
After:
From https://www.gov.uk/government/news/innovative-afghan-businesses-receive-uk-aid-grants.ur
---
> Set Urdu text direction to right-to-left

- config/locales/en.yml
Add custom pluralisation for the new Product Safety Alerts, Reports and Recalls
specialist finder.
Trello: https://trello.com/c/ojsFViiX/2746-create-new-specialist-document-and-finder-product-safety-alerts-unsafe-products-and-recalls-3-5
> Add custom pluralisation for the new Product Safety Alerts, Reports and Recalls

- app/views/components/_published-dates.html.erb
- test/components/published_dates_test.rb
PR #2330 added an additional div around `published-dates` to prevent this
change in `govuk_publishing_components` being a breaking one:
https://github.com/alphagov/govuk_publishing_components/pull/2558
This additional div is now safe to remove and the id of the wrapper for
`published-dates` can be updated to the new one.
Fixes https://github.com/alphagov/govuk_publishing_components/issues/600
> Undo temporary workaround in pull request #2330

- app/views/content_items/consultation.html.erb
- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/publication.html.erb
- app/views/shared/_published_dates_with_notification_button.html.erb
Add support for the single page notification button to the `consultation`
template. The button will not appear until the feature is enabled on
pages with this content type.
Seeing as the button is always grouped together with the published dates
component I created a new  `published_dates_with_notification_button`
partial to be shared between `publication`, `detailed_guide` and
`consultation`.
https://trello.com/c/iqhyMnMP
> Add single page notification button to `consultation` template

- app/views/content_items/get_involved.html.erb
Add comment
Add a contextual comment / docs - indicating to future developers that changes [to this page](https://www.gov.uk/government/get-involved) might impact smokey tests
> Add comment

- config/locales/dr.yml
- config/locales/fr.yml
- Correct the language name for Dari from بعدی to دری
- Capitalize "français" to match the convention in the other languages
In Dari "بعدی" means "the next one" or "future" rather than the language name, so needed to be corrected. 
And "français" was the only language name not to be capitalised, so looked out of place in the list of languages on a page.
From https://www.gov.uk/government/publications/what-is-a-forced-marriage:
Before:
After:
From https://www.gov.uk/guidance/passenger-locator-form-how-to-guide.fr:
Before:
After:
---
> Correct language names for French and Dari

- app/controllers/content_items_controller.rb
- app/presenters/content_item/single_page_notification_button.rb
- app/presenters/content_item_presenter.rb
- app/views/content_items/consultation.html.erb
- test/controllers/content_items_controller_test.rb
- test/integration/answer_test.rb
- test/integration/case_study_test.rb
- test/integration/consultation_test.rb
- test/integration/contact_test.rb
- test/integration/corporate_information_page_test.rb
- test/integration/detailed_guide_test.rb
- test/integration/document_collection_test.rb
- test/integration/fatality_notice_test.rb
- test/integration/guide_test.rb
- test/integration/help_page_test.rb
- test/integration/html_publication_test.rb
- test/integration/news_article_test.rb
- test/integration/publication_test.rb
- test/integration/specialist_document_test.rb
- test/integration/speech_test.rb
- test/integration/statistical_data_set_test.rb
- test/integration/statistics_announcement_test.rb
- test/integration/take_part_test.rb
- test/integration/topical_event_about_page_test.rb
- test/integration/travel_advice_test.rb
- test/integration/working_group_test.rb
- test/integration/world_location_news_article_test.rb
- test/test_helper.rb
The next stage for the single page notification rollout is to put the button on all pages with a `publication`, `detailed_guide` or `consultation` type. 
The exemption mechanism will be a denylist. Publishers can request that the button not be included on certain individual pages. The way the exemption is applied is by adding the `content_id` of the page to the single page notification button exclusion list.
Change single page notification button allow list to an exemption list.
Switch from using `base_path`s to `content_id`s for long term stability (content ids persist, base paths can change)
Add some basic tests to verify that pages whose content item is on the exemption list do not display with the single page notification button.
This was missed in the previous PR which added the …
> Change single page notification button allow list to an exemption list

- app/assets/stylesheets/print.scss
- app/assets/stylesheets/print/_language_support.scss
Allow right-to-left (rtl) languages to be printed correctly 
Some languages read rtl, when these languages are active the print stylesheets do not adjust to cater for this.
Testing links
- https://www.gov.uk/government/news/statement-by-saudi-arabia-the-uae-the-uk-and-the-us-about-the-situation-in-yemen-and-the-region.ar
- https://www.gov.uk/government/news/foreign-secretary-statement-on-kurdish-referendum.ar
- https://www.gov.uk/government/news/welcome-to-our-new-website-gov-uk.ur
[A different approach](https://github.com/alphagov/govuk_publishing_components/pull/2629) was taken at the start which involved adding a blanket solution to `govuk_publishing_components` to support all `rtl` while desirable, after review multiple relevant issues were noted. As a result a more incremental …
> Add rtl langauge support

- app/assets/stylesheets/components/_important-metadata.scss
- app/views/components/_important-metadata.html.erb
Reset `<dl>` styles in important-metadata component
This component was most probably relying on a reset stylesheet that has been removed and now it has the browser default margins on the `<dl>` and `<dd>` elements. We now reset those values in the component stylesheet.
[Live example](https://www.gov.uk/government/speeches/pm-message-to-the-people-of-ukraine-and-russia-25-february-2022) → [Update preview](https://government-f-reset-dl-s-rvrq7s.herokuapp.com/government/speeches/pm-message-to-the-people-of-ukraine-and-russia-25-february-2022)
<table>
<tr><td>Before</td><td>After</td>
<tr><td valign="top">
</td><td valign="top">
</td>
</tr>
</table>
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html …
> Reset list styles on `important-metadata` component

- app/assets/javascripts/application.js
- app/assets/stylesheets/components/_banner.scss
- app/presenters/content_item_presenter.rb
- app/views/layouts/application.html.erb
- test/integration/guide_test.rb
- test/test_helper.rb
Adds the intervention banner to specific pages that links to a tree test that User Research want to conduct.
[Trello card](https://trello.com/c/i6PqMLdp/842-add-banner-to-guidance-pages)
> Display intervention banner on specific pages for User Research

- lib/webchat.yaml
As requested by HMPO, this commit changes the old provider URL to
the new provider, as well as the associated availability URL.
We need to decide how this can be tested correctly by HMPO.
https://trello.com/c/wg6cckR1/770-set-up-a-test-page-for-hmpo-to-check-new-webchat-update
> Update HMPO live chat form to new URL

- app/presenters/content_item/attachments.rb
- test/presenters/content_item/attachments_test.rb
- test/views/content_items/attachments.html.erb_test.rb
These are needed to render the new accessible form link from GOVUK
Publishing Components. This is dependant on the component being updated
first [1].
This change will apply to publications and consultations, which use the
attachments partial. Initially, the new flow of requesting accessible
formats will be a pilot and only available for documents, owned by a few
organisations. This code will not need to be changed when the change is
released to all orgs.
> App tests will not pass until [1] has been merged
[1]: https://github.com/alphagov/govuk_publishing_components/pull/2636
Trello: https://trello.com/c/FdQvPVhD/1094-accessible-format-request-government-frontend-add-parent-document-contentid-to-the-attachment-model …
> Add accessible form link

- app/assets/javascripts/webchat.js
- app/assets/javascripts/webchat/library.js
- spec/javascripts/support/jasmine.yml
- spec/javascripts/vendor/jasmine-ajax-3.4.0.js
- spec/javascripts/webchat.spec.js
Trello: https://trello.com/c/jymNmjHN
Remove jQuery from [webchat/library.js](https://github.com/alphagov/government-frontend/blob/main/app/assets/javascripts/webchat/library.js) and [webchat.js](https://github.com/alphagov/government-frontend/blob/main/app/assets/javascripts/webchat.js).
This change is very large, so the initialisation of the code has not been changed, neither has Webchat been converted into a GOVUK module. The focus of this change is just to remove the reliance on jQuery in the Webchat scripts which is a large change by itself.
An anomaly was discovered during the testing of this change.
There is only one webchat page that this script runs on:
[/government/organisations/hm-passport-office/contact/hm-passport-office-webchat](https://www.gov.uk/government/organisations/hm- …
> Remove jQuery from Webchat

- app/presenters/content_item/single_page_notification_button.rb
Add exception to single page notification button
Signing up for updates on '[Local Sponsorship Scheme for Ukraine](https://www.gov.uk/guidance/local-sponsorship-scheme-for-ukraine)' is currently only possible by setting up an Account, which requires a UK phone number to set up. This is currently causing issues to users, so we drop this in favour of adding [a sign-up link to the related topical event](https://www.gov.uk/email-signup?link=/government/topical-events/russian-invasion-of-ukraine-uk-government-response) as part of the content.
> Add exception to single page notification button

- app/presenters/content_item/single_page_notification_button.rb
Add exceptions to single page notifications button
Signing up for updates on certain pages is currently only possible by setting up an Account, which requires a UK phone number to set up. This is currently causing issues to users, so we drop this in favour of adding a sign-up link to the related topical event as part of the content on the following pages:
- https://www.gov.uk/guidance/taking-humanitarian-aid-out-of-great-britain-to-support-ukraine
- https://www.gov.uk/government/publications/immigration-information-for-ukrainians-in-the-uk-british-nationals-and-their-family-members
- https://www.gov.uk/guidance/ukrainian-nationals-in-the-uk-visa-support
- https://www.gov.uk/guidance/support-for-family-members-of-british-nationals-in-ukraine-and-ukrainian-nationals-in-ukraine-and-the-uk
- …
> Add exceptions to single page notifications button

- app/lib/recruitment_helper.rb
- app/presenters/content_item/recruitment_banner.rb
- app/presenters/content_item_presenter.rb
- app/views/layouts/application.html.erb
- test/integration/guide_test.rb
- test/integration/recruitment_banner_test.rb
Add banner to pages requested by UR colleagues as per [sheet](https://docs.google.com/spreadsheets/d/104ird2xevvcA77Lrhtrelkz4DpkoLJ30jdnDaq6bhpg/edit#gid=0)
Trello: https://trello.com/c/qPhlRiUx/779-launch-and-monitor-the-recruitment-banner-for-money-tax
> Add recruitment banner to tax and business browse pages

- app/presenters/content_item/single_page_notification_button.rb
Remove the content id for 'Local Sponsorship Scheme for Ukraine' from
the single page notification exemption list.
The exemption was added here: https://github.com/alphagov/government-frontend/pull/2391
However, the original page has now been unpublished with a redirect.
So the original page was:
https://www.gov.uk/guidance/local-sponsorship-scheme-for-ukraine
But it is now redirecting to:
https://homesforukraine.campaign.gov.uk
----
> Remove 'Local Sponsorship Scheme for Ukraine' from exemptions

- app/presenters/guide_presenter.rb
- test/presenters/guide_presenter_test.rb
https://trello.com/c/vG0AdGbb/40-incomplete-page-title-for-first-page-of-mainstream-guide-11
Update the first page of a guide to include both the page title and sub section title. So, for https://www.gov.uk/change-address-driving-licence, the page title should be change to
```
<title lang="en">
Change the address on your driving licence: Apply online - GOV.UK
</title>
```
From
```
<title lang="en">
Change the address on your driving licence - GOV.UK
</title>
```
WCAG failure
- WCAG SC: 2.4.2
- severity: 1
- complexity: 1
> Fix incomplete page title for first page of mainstream guide

- app/presenters/content_item/single_page_notification_button.rb
**DO NOT MERGE: merge this in tomorrow 15 March at ~9-9:15am**
------
Remove guidance related to the Ukraine crisis from the single page notifications exemption list.
The pages:
- https://www.gov.uk/guidance/taking-humanitarian-aid-out-of-great-britain-to-support-ukraine
- https://www.gov.uk/government/publications/immigration-information-for-ukrainians-in-the-uk-british-nationals-and-their-family-members
- https://www.gov.uk/guidance/ukrainian-nationals-in-the-uk-visa-support
- https://www.gov.uk/guidance/support-for-family-members-of-british-nationals-in-ukraine-and-ukrainian-nationals-in-ukraine-and-the-uk
- https://www.gov.uk/guidance/apply-for-a-ukraine-family-scheme-visa
---- 
https://trello.com/c/KF9ee09L …
> [DO NOT MERGE] Remove Ukraine pages from the exemptions list

- app/presenters/content_item/recruitment_banner.rb
- test/integration/recruitment_banner_test.rb
Update the survey URL in the recruitment banner.
[Trello](https://trello.com/c/qPhlRiUx/779-launch-and-monitor-the-recruitment-banner-for-money-tax)
[Tracking sheet](https://docs.google.com/spreadsheets/d/104ird2xevvcA77Lrhtrelkz4DpkoLJ30jdnDaq6bhpg/edit#gid=0)
> Update survey URL in recruitment banner

- app/views/content_items/consultation.html.erb
https://trello.com/c/sxOV4t11/1190-add-id-reference-to-ways-to-respond-section-of-consultation-template
There's a section called _Ways to respond_. An id reference `#ways-to-respond` has been added to this section.
So that departments can link directly to the section when needing to mention it in external places.
https://user-images.githubusercontent.com/87758239/165786888-f7b083aa-3daf-4c6c-a32f-be0a52d5e06b.mov
> Add id reference to 'ways to respond' section of consultation template

- app/presenters/content_item/manual.rb
- app/presenters/content_item/manual_section.rb
- test/integration/hmrc_manual_section_test.rb
- test/integration/manual_section_test.rb
Currently (in Government Frontend) , a manual section's timestamps for
published at and last updated at originate from the manual section.
However, the live version (Manuals Frontend) uses the parents manual
timestamps. This commit applies parent manuals timestamps 
as we should keep the behaviour the same.
Trello:
https://trello.com/c/qCSHqqN7/1287-use-parent-manual-timestamps-for-manual-sections
> Use manual timestamps for manual section header

- test/presenters/content_item/manual_section_test.rb
This test failed on CI as the gds-api-adapters version had been bumped,
meaning the hardcoded user-agent version was no longer the same and the
stub failed to match the request.
> Fix failing test

- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/guide.html.erb
The Moving to the UK for Work team would like to implement scroll tracking on some of the work visa pages to get some insights into how far down the page users tend to scroll.
The pages we would like to do this on are:
- Applying for a visa to come to the UK: (https://www.gov.uk/apply-to-come-to-the-uk)
- Skilled Worker visa (Overview) (https://www.gov.uk/skilled-worker-visa)
- Skilled Worker visa (Documents) (https://www.gov.uk/skilled-worker-visa/documents-you-must-provide)
- Financial evidence for sponsored or endorsed work routes: (https://www.gov.uk/guidance/financial-evidence-for-sponsored-or-endorsed-work-routes)
Scroll tracking will help us to analyse user behaviour and gain better insights, so that we can implement useful content changes.
Co-authored-by: Alex Newton …
> Moving to the UK for Work: Scroll tracking on visa content pages

- app/presenters/html_publication_presenter.rb
- app/views/content_items/html_publication.html.erb
- app/views/shared/_history_notice.html.erb
- test/integration/detailed_guide_test.rb
- test/integration/document_collection_test.rb
- test/integration/html_publication_test.rb
- test/integration/news_article_test.rb
- test/integration/publication_test.rb
- test/integration/statistical_data_set_test.rb
- test/integration/world_location_news_article_test.rb
- test/presenters/html_publication_presenter_test.rb
We're doing some work to expose a history banner on html attachments to let the user know that a publication was published under a previous government. This means that we need to expose whether a html publication is political and which government it was published under on the object passed to the frontend.
This PR exposes the history banner on the Frontend when a html publication is historically political 
https://github.com/alphagov/whitehall/pull/6585
https://github.com/alphagov/govuk-content-schemas/pull/1096
https://trello.com/c/xWMcmTqb/409-implement-history-mode-banner-on-html-attachments
> Use govuk design system information banner for historical editions and html attachments

- app/presenters/html_publication_presenter.rb
- app/views/content_items/html_publication.html.erb
- test/integration/html_publication_test.rb
- test/presenters/html_publication_presenter_test.rb
We're doing some work to expose national applicability data for html attachments. If a consultation or Publication only relates to some of the devolved nations, then it also renders for html attachments that belong to it.
This commit does the work to render the component on the page when national applicability information is contained in the details hash of a piece of content
Whitehall - https://github.com/alphagov/whitehall/pull/6606
GOVUK Content Schema - https://github.com/alphagov/govuk-content-schemas/pull/1100
https://trello.com/c/pLnsviDN/402-implement-devolved-nations-national-applicability-banner-on-html-attachments
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull- …
> Expose national applicability information for HMTL Attachments

- app/views/content_items/html_publication.html.erb
The devolved nations component was added to html publications in this PR https://github.com/alphagov/government-frontend/pull/2460
At the moment this renders at 2/3 width and looks a bit clunky. After speaking to Nikin we're going to make it full width pending feedback from Find & View designers.
> Make the national applicability banner full width

- Gemfile
- Gemfile.lock
- app/controllers/asset_manager_redirect_controller.rb
- test/controllers/asset_manager_redirect_controller_test.rb
Trello: https://trello.com/c/nvG4055w/510-asset-redirects-are-broken-in-draft-draft-draft-assets
The previous code had a bug where a redirect to the draft assets host
was incorrect. It was redirecting to a double prefixed asset host as the
"draft-" was implicit. Illustrated by:
```
➜  ~ govuk-connect app-console -e production draft_frontend/government-frontend
irb(main):001:0> Plek.new.external_url_for("draft-assets")
=> "https://draft-draft-assets.publishing.service.gov.uk"
irb(main):002:0> Plek.new.external_url_for("assets")
=> "https://draft-assets.publishing.service.gov.uk"
```
This resolves the problem by using the external_url_for method for both
scenarios. As when we are on the draft stack there will be an env var
that prefixes hostnames accordingly.
I added climate_control to test …
> Fix redirecting to incorrect assets domain

- app/views/content_items/get_involved.html.erb
- test/controllers/get_involved_controller_test.rb
The /government/get-involved page was previously tested in a rather unusual way where there weren't any real tests for the endpoint in this application but there was an unusually thorough set of tests in Smokey. This isn't ideal because the Smokey tests are expensive and unnecessary since the logic is in this app. 
This rewrites the tests to allow for the majority of the Smokey tests to be removed.
> Add get involved tests to replace Smokey tests

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/print.scss
* Remove `component_support`
* Remove included component stylesheets that are now being served by Static
* Add accordion and organisation logo print stylesheets
Reduces `applications.css` from 287.91 kB to 218.13 kB uncompressed.
Reduces `application.js` from 116.95 kB to 109.60 kB uncompressed.
Component support includes a set of base styles needed by the components; and component styles used by multiple rendering applications are also included in `static`'s stylesheet. Because both of this they don't need to be duplicated in `government-frontend`.
The missing print stylesheets needed to be included to ensure a consistent print experience across GOV.UK - missing them out of one application would mean that these components would print differently depending on which page was being printed. …
> Tidy up stylesheets and JavaScript

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_banner.scss
- app/presenters/content_item/recruitment_banner.rb
- app/presenters/content_item_presenter.rb
- app/views/layouts/application.html.erb
- test/integration/recruitment_banner_test.rb
The number of responses hasn't been as much as we hoped, so I'd like to put the
banner out more widely. This adds the banner to all pages tagged to 'Working,
jobs and pensions' mainstream browse. Excluding the mainstream browse page itself,
as that's been looked at in the A/B test.
[Trello](https://trello.com/c/1Mo3VmGB/1106-launch-and-monitor-the-tree-test-using-the-intervention-banner-baseline)
<kbd>
</kbd>
> Add UR recruitment banner to pages tagged to Working browse

- app/presenters/content_item/manual_section.rb
- app/presenters/hmrc_manual_section_presenter.rb
- test/presenters/hmrc_manual_section_presenter_test.rb
https://trello.com/c/NToovfjr/1349-add-parent-manuals-title-to-the-hmrc-section-content-item
> Simplify HRMC rendering with new schema data

- app/presenters/content_item/manual_section.rb
- app/presenters/content_item_presenter.rb
- app/presenters/hmrc_manual_section_presenter.rb
- app/views/layouts/application.html.erb
- test/presenters/hmrc_manual_section_presenter_test.rb
This PR does the following:
* Fetch title from manuals content item for a HMRC section, rather than pulling it from it's own content item, as this functionality is going to be removed soon 
* Removes TODOs that no longer apply
* Improves how we fetch the manual content item for breadcrumbs by reducing coupling    
Trello:
https://trello.com/c/ItYKGMqF/1464-revert-add-parent-manuals-title-to-the-hmrc-section-content-item
> Fetch title from manuals content item

- app/assets/stylesheets/views/_html-publication.scss
- app/views/content_items/html_publication.html.erb
- test/integration/html_publication_test.rb
Stop using `sticky-element-container.js` on [HTML publication pages](https://www.gov.uk/government/publications/heatwave-plan-for-england/beat-the-heat-staying-safe-in-hot-weather) and instead use native CSS sticky.
The page layout has a contents list in the left hand column and the main content in the right. The script was used to keep a jump link to the contents (and a print this page button) visible at all times when scrolling, so users can jump back to the top at any time.
This change switches from using the script to the native CSS position: sticky attribute. It has been applied to the contents list, so now …
> Use CSS sticky on HTML publications instead of custom script

- app/presenters/content_item/recruitment_banner.rb
- test/integration/recruitment_banner_test.rb
Add recruitment banner to pages related to the UK visa service.
See [trello](https://trello.com/c/4oYXIjMN/1173-add-a-research-recruitment-banner-for-the-visa-journeys-team-s) card for list of pages.
> Visa service recruitment banner

- app/helpers/manuals_helper.rb
- app/presenters/content_item/manual_updates.rb
- app/views/content_items/manual_section.html.erb
- app/views/content_items/manuals/_updates.html.erb
- test/helpers/manuals_helper_test.rb
- test/presenters/content_item/manual_updates_test.rb
We are currently working to complete the implementation of GA4 tracking on all accordions, across all frontend apps.
This PR adds tracking to the accordions on the following pages:
Example URL(s):
- https://www.gov.uk/hmrc-internal-manuals/employment-income-manual/updates
- https://www.gov.uk/guidance/understanding-your-driving-test-result/car-driving-test
There are more [example pages](https://docs.publishing.service.gov.uk/repos/manuals-publisher.html) listed in the manuals publisher docs.
Also, in this PR is a bug fix. Currently, the I18N `manuals.updates_amendments` string is visible on the rendered page. This is because the `visuallyhidden` class has been replaced by the `govuk-visually-hidden` class. The `visuallyhidden` class has been replaced and appropriate tests added. …
> Add GA4 accordion tracking to manuals

- app/views/content_items/manual_section.html.erb
- app/views/content_items/manuals/_updates.html.erb
Rename the GA4 tracking module to `ga4-event-tracker`.
The GA4 tracking module [has been renamed to `ga4-event-tracker`](https://github.com/alphagov/govuk_publishing_components/pull/2906).
[Trello](https://trello.com/c/0gjuZZxe/344-complete-the-implementation-of-ga4-accordions-on-all-frontend-apps)
> Rename GA4 tracking module

- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/guide.html+print.erb
- app/views/content_items/hmrc_manual.html.erb
- app/views/content_items/hmrc_manual_section.html.erb
- app/views/content_items/html_publication.html.erb
- app/views/content_items/manual.html.erb
- app/views/content_items/manual_section.html.erb
- app/views/content_items/manuals/_updates.html.erb
- app/views/content_items/travel_advice.html+print.erb
Add GA4 tracking to 'print this page' links on GOV.UK.
Note that these changes are only active on integration, not live.
Pages affected:
- detailed guides ([example detailed guide](https://www.gov.uk/guidance/register-a-trust-as-a-trustee))
- guides ([example guide](https://www.gov.uk/change-address-driving-licence/print))
- HMRC manuals ([example manual](https://www.gov.uk/hmrc-internal-manuals/employment-income-manual) and [example manual section](https://www.gov.uk/hmrc-internal-manuals/employment-income-manual/eim00100) and [example updates page](https://www.gov.uk/hmrc-internal-manuals/trust-registration-serv …
> Add GA4 analytics tracking to print links

- app/views/content_items/manual_section.html.erb
Use only the `text` attribute of the object that is used to render the accordion headings on manual sections.
Currently, when the value arrives in Google Analytics (GA) the `ga4['text']` value is showing as `[object Object]` and not a simple string. Looking at the values within the HTML for the accordion, a sub-object is clearly visible (see before screenshot).
|---|---|
| <img width="1125" alt="Screenshot 2022-09-07 at 10 07 07" src="https://user-images.githubusercontent.com/44037625/188839990-5f79620b-d9d4-44e4-9591-f1a030394e87.png"> | <img width="1125" alt="Screenshot 2022-09-07 at 10 07 35" src="https://user-images.githubusercontent.com/44037625/188840026-389462ed-f78b-4b5e-a37c-2ae1eb08f485.png"> |
[Trello](https://trello.com/c/4WHhMr96/373-object-object-text-value …
> [object Object] 'text' values for accordions on manual_section pages

- app/views/content_items/manual_section.html.erb
- app/views/content_items/manuals/_updates.html.erb
Add the `module` to the `data_attributes` hash within the accordion component.
The `Show/hide all sections` part of the accordion on the manuals pages is not being tracked and the `dataLayer` push is not firing.
[Trello](https://trello.com/c/PiCNfSZq/374-datalayer-push-not-functioning-on-some-show-hide-all-sections-accordion-interactions)
> Accordion `show/hide all sections` not working on manual pages

- docs/webchat.md
After talking to HMPO and their new service provider, it became clear that they were looking at an old version of the code for the Webchat implementation and quoting incorrect polling times etc.
Removing the link to a specific commit means that we are always linking to the current version of the code.
There is a risk that the file could move and the link could break, but if that seems a more acceptable risk than having to also update these docs if any of the hardcoded values change.
Also removes the jQuery example code and replaces it with vanilla Javascript as jQuery has been removed from all of the frontend GOV.UK applications and we don't want to encourage its return. …
> Update links in Webchat README

- Dockerfile
`WORKDIR` creates its directory anyway, and the mkdir fails now that we're creating `/app` in govuk-ruby-base. Thought I'd fixed all these before merging the change to govuk-ruby-base, but turns out I forgot to actually raise a bunch of the PRs that I'd prepared.
> Remove unnecessary `mkdir /app` from Dockerfile.

- Gemfile.lock
- app/lib/services.rb
- app/views/development/index.html.erb
- test/controllers/get_involved_controller_test.rb
See alphagov/gds-api-adapters#1170 for context.
> Use canonical name when connecting to search-api.

- app.json
- app/views/development/index.html.erb
We are retiring the dummy content store as part of replatforming work, making it easier for us to deploy content schemas in the new world. Switching to using gov.uk/api for PLEK_SERVICE_CONTENT_STORE_URI brings us this application in line with most other applications.
This brings this application in line with most other frontend applications, e.g. [collections](https://github.com/alphagov/collections/blob/e983dc77e4239bff031b33088b54c9f34f387216/app.json#L15)
This PR also removes the dummy content store examples from the PR index page. Instead, the examples from the live site which are found on the same page can be used.
[Trello](https://trello.com/c/z08hU3Ov/360-retire-the-dummy-content-store) …
> switch from using dummy content store to using gov api

- app/controllers/content_items_controller.rb
- app/presenters/consultation_presenter.rb
- app/presenters/content_item/single_page_notification_button.rb
- app/presenters/content_item_presenter.rb
- app/presenters/detailed_guide_presenter.rb
- app/presenters/publication_presenter.rb
- app/views/content_items/consultation.html.erb
- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/publication.html.erb
- app/views/shared/_published_dates_with_notification_button.html.erb
- app/views/shared/_publisher_metadata_with_logo.html.erb
- app/views/shared/_single_page_notification_button.html.erb
- test/presenters/consultation_presenter_test.rb
- test/presenters/detailed_guide_presenter_test.rb
- test/presenters/publication_presenter_test.rb
There are no user facing changes here, it's just a reorganisation of the existing code. 
We will soon be wanting to add the button to a new document type (document collections) with custom button text, so doing a bit of a tidy up first to make the code easier to extend.
See commit messages for more detail.
https://trello.com/c/gpch42Uc/1456-enable-custom-text-for-the-single-page-notification-button-component-l
> Refactor single page notification button logic prior to adding new functionality

- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/guide.html+print.erb
- app/views/content_items/hmrc_manual.html.erb
- app/views/content_items/hmrc_manual_section.html.erb
- app/views/content_items/html_publication.html.erb
- app/views/content_items/manual.html.erb
- app/views/content_items/manual_section.html.erb
- app/views/content_items/manuals/_updates.html.erb
- app/views/content_items/travel_advice.html+print.erb
**NOT TO BE MERGED unless also including the [new version of the components gem](https://github.com/alphagov/govuk_publishing_components/pull/3091) that includes the changes detailed below**
Update references to GA4 event tracker to cope with breaking changes introduced in https://github.com/alphagov/govuk_publishing_components/pull/3057
- GA4 event tracker has been rewritten to use a `data-ga-event` attribute in place of `data-ga4`
- updating for tracking on various pages for print link
Pages affected:
- detailed guides ([example detailed guide](https://www.gov.uk/guidance/register-a-trust-as-a-trustee))
- …
> Update for event tracker changes

- Gemfile
- Gemfile.lock
- config/locales/plurals.rb
- config/locales/zh-hk.yml
- config/locales/zh-tw.yml
We're now using the extra plural rules defined by RTM as a prod
dependency [1]. This will replace the list defined in govuk_app_config
and so the reference has also been removed. RTM's version loads
automatically [2] and so we don't have to explicitly include the file in
the app.
Testing locally on a production rails server:
Fetching from plural file [1]:
```
[6] pry(#<ContentItemsController>)> plural_form = I18n.with_locale("cy") { I18n.t!("i18n.plural.keys") }.sort
=> [:few, :many, :one, :other, :two, :zero]
[7] pry(#<ContentItemsController>)> plural_form = I18n.with_locale("zh") { I18n.t!("i18n.plural.keys") }.sort
=> [:other]
[8] pry(#<ContentItemsController>)> plural_form = I18n.with_locale("dr") { I18n.t!("i18n.plural.keys") }.sort
=> [:one, :other]
```
Fetching from the default …
> Bump Rails Translation Manager and use new plural file

- .dockerignore
- Dockerfile
- Gemfile
- Gemfile.lock
- config/boot.rb
We seem to be using [bootsnap](https://github.com/Shopify/bootsnap) on most of the publisher apps but not on the frontends.
We don't care much about startup time per se, but reducing the CPU spike on pod startup is helpful for capacity planning and helps to keep the overall performance of the cluster more predictable.
Tested: works on the integration k8s cluster. Benchmarking locally with `docker run` showed [\>40% improvement](https://docs.google.com/spreadsheets/d/13-acYdjnMcqV_JzrHR-fWFK8vYsM2aCXJuw6X_cRoAY/edit#gid=0) in startup time and savings of roughly 2 core-seconds per pod startup. Regression tested on EC2 by deploying to the integration environment, checking that smoke tests still pass there and checking there were no errors/warnings in app logs.
> Use bootsnap to improve startup time.

- app/assets/stylesheets/components/_banner.scss
- app/presenters/content_item/recruitment_banner.rb
- app/presenters/content_item_presenter.rb
- app/views/layouts/application.html.erb
- test/integration/recruitment_banner_test.rb
Trello https://trello.com/c/woeqmUsz/1521-banner-request-for-cost-of-living-tree-test-m
Page served by this app with banner
https://government-frontend-pr-2630.herokuapp.com/guidance/cost-of-living-payment
> Add recruitment banner for cost of living tree test

- config/locales/zh-hk.yml
We removed `one` in [1], which complied with Chinese plural rules, however the value of `one` was actually the correct value for the `other` key. This PR swaps the the values for each plural.
[1]: https://github.com/alphagov/government-frontend/pull/2621/commits/a181f038a63a25aa929410297ee0f55d63ea6afd
> Update Chinese (Hong Kong) plurals

- app/controllers/content_items_controller.rb
- app/models/webchat.rb
- app/presenters/contact_presenter.rb
- docs/webchat.md
- lib/webchat.yaml
- test/integration/contact_test.rb
- test/models/webchat_test.rb
- test/presenters/contact_presenter_test.rb
Trello: https://trello.com/c/lxxx5XLZ/178-govuk-has-a-half-implemented-content-security-policy-csp
Webchat integrations on GOV.UK require modifications to the Content
Security Policy (CSP), these previously have been handled in
govup_app_config [1]. Overtime we have ended up with these falling out
of date, with more CSP entries than used cases. It is also a pain to
deploy these as you need to update the gem first.
This PR moves the CSP configuration into this application, which
resolves these pain points and follows the convention in our CSP
documentation [2] to not apply config that is just for a single
application.
This applies an approach where the CSP modification is only applied on
the webchat page, so it won't be broadcast across all other GOV.UK
pages. I set this up to meet the …
> Handle webchat CSP modifications in application 

- app/views/histories/10_downing_street.html.erb
- app/views/histories/11_downing_street.html.erb
- app/views/histories/1_horse_guards_road.html.erb
- app/views/histories/history.html.erb
- app/views/histories/king_charles_street.html.erb
- app/views/histories/lancaster_house.html.erb
Trello: https://trello.com/c/lxxx5XLZ/178-govuk-has-a-half-implemented-content-security-policy-csp
The changes here have been made in order for this application to be compatible with the changes coming in https://github.com/alphagov/govuk_app_config/pull/279, where inline styles will no longer be permitted. The scope grew a little to do a bit of a clean-up in the history pages where inline styles were present.
This change:
- removes classes that have no effect
- fixes a layout bug
- replaces inline styles with a class
The layout bug is demonstrated below
Before:
After:
---
Follow [these …
> Fix layout of /government/history and remove use of inline styles

- app/assets/stylesheets/components/_back-to-top.scss
- app/assets/stylesheets/views/_detailed-guide.scss
- app/views/content_items/detailed_guide.html.erb
- app/views/shared/_published_dates_with_notification_button.html.erb
At the bottom of content item pages, the email subscription button and print button have been moved to be on the same row.
This was a request from the designers of the Navigation and Presentation team.
[Relevant Trello Card](https://trello.com/c/Jlix7XV6/1489-move-placement-of-email-subscription-and-print-this-page-buttons-on-guidance-pages-s)
> Subscribe and Print Buttons on Same Row

- test/contracts/govuk_content_schemas_test.rb
- test/support/govuk_content_schema_examples.rb
The test file test/contracts/govuk_content_schemas_test.rb was not actually testing anything because there was a typo in the support file, such that GovukSchemas::Example.find_all(supported_schemas) was returning [] 
- This is because the `find_all` method expects a single string param. See [here](https://github.com/alphagov/govuk_schemas/blob/4fef0aa95be24c3534a00b622a59ea7f1e8175fa/lib/govuk_schemas/example.rb#L5)
- Also removes redirect, as there is no frontend rendering. https://github.com/alphagov/publishing-api/tree/main/content_schemas/examples/redirect
- Minitest won't run tests of the same name, and multiple schema examples have the same basepath. Hence adding in the index to the iterator. …
> Fix content schema tests

- app/views/content_items/statistics_announcement.html.erb
- app/views/shared/_footer_navigation.html.erb
- app/views/shared/_sidebar_navigation.html.erb
Turn on GA4 tracking in the related navigation, contextual sidebar and contextual footer components. Note that this will enable tracking for the related navigation and the step by step navigation components, where they are present inside the contextual sidebar component.
Example pages:
- [contextual sidebar containing a step by step navigation](https://www.gov.uk/national-minimum-wage-rates)
- [contextual sidebar and contextual footer both containing related navigation](https://www.gov.uk/government/statistics/uk-armed-forces-recovery-capability-wounded-injured-and-sick-in-the-recovery-pathway-financial-year-20151 …
> Turn on GA4 tracking in sidebar and footer

- app/views/content_items/publication.html.erb
Enables GA scroll tracking on:
* https://www.gov.uk/government/publications/form-pa14-medical-certificate-probate
* https://www.gov.uk/government/publications/find-a-will-or-probate-document-form-pa1s
* https://www.gov.uk/government/publications/report-a-will-is-lost-to-support-a-probate-application
See https://govuk.zendesk.com/agent/tickets/5176602
> Add scroll tracking to requested MoJ pages

- app/presenters/corporate_information_page_presenter.rb
Missing from https://github.com/alphagov/government-frontend/pull/2687
> Update page for reshuffle banner

- app/views/content_items/corporate_information_page.html.erb
> Move 'the' to prefix the link text

- Gemfile.lock
Applies [1] which will fix the issue spotted in [2].
[1]: https://github.com/alphagov/govuk_publishing_components/pull/3243
[2]: https://govuk.zendesk.com/agent/tickets/5207548.
> Bump publishing components version

- app/controllers/content_items_controller.rb
- app/presenters/content_item_presenter.rb
- app/presenters/service_manual_presenter.rb
- app/views/layouts/application.html.erb
A few minor tweaks to service manual pages, following on from https://github.com/alphagov/government-frontend/pull/2583
1. Remove unwanted breadcrumb from /service-toolkit
2. Add "service manual" to the page title
> Small amends to service manual pages

- Gemfile.lock
Dependabot scan is taking ages
> Bump govuk_publishing_components to version 34.12.0

- app/assets/stylesheets/components/_banner.scss
- app/presenters/content_item/cost_of_living_banner.rb
- app/presenters/content_item_presenter.rb
- app/views/layouts/application.html.erb
- test/integration/cost_of_living_banner_test.rb
Add an intervention banner that links to the Cost of living survey banner.
Paths affected:
/guidance/cost-of-living-payment
/cost-living-help-local-council
/benefits-calculators
/the-warm-home-discount-scheme
/universal-credit
/universal-credit/eligibility
/universal-credit/what-youll-get
/universal-credit/how-to-claim
/universal-credit/other-financial-support
/universal-credit/contact-universal-credit
/new-state-pension/what-youll-get
/get-help-energy-bills
/get-help-energy-bills/getting-discount-energy-bill
/pension-credit
[Trello](https://trello.com/c/XozIyJgB/1670-cost-of-living-col-1-of-2-surveys-user-researc …
> Add Cost of living survey banner

- app/views/layouts/application.html.erb
Enables tracking on the super breadcrumb.
N/A
Trello card: https://trello.com/c/AM5JCKEd/430-add-tracking-to-super-breadcrumbs
> Enable GA4 tracking on super breadcrumb

- app/presenters/get_involved_presenter.rb
This was incorrectly added in
https://github.com/alphagov/government-frontend/pull/2712, so fixing to display the year instead of the timezone.
> Fix date format on Get Involved page

- app.json
app.json is used to configure the env vars for Heroku.  
> Update environment variable name to make search work for review apps

- app/views/content_items/guide.html.erb
- app/views/content_items/guide_single.html.erb
- app/views/content_items/manual_section.html.erb
- app/views/content_items/travel_advice.html.erb
Updates how the contents list component is called. Specifically the `aria_label` option for the contents list component has been replaced with the `aria` option (passing a hash of aria options).
Updates to the component in the gem mean that this option would no longer work, needed updating. Note that this PR should not be merged until the change below is merged into a new version of the gem and updated in this application as part of this PR.
Related PR: https://github.com/alphagov/govuk_publishing_components/pull/3254
None.
> Update how contents list is called

- app/assets/stylesheets/modules/_related-content.scss
- app/views/shared/_email_signup.html.erb
Replace email subscription link on service manual pages with subscription link component.
Adjustment to the design of the email subscription link on service manual pages.
> Replace subscription email link with component

- app/presenters/corporate_information_page_presenter.rb
Content request: DCMS [1] has now been closed and we can remove the org is changing banner. department-for-business-energy-and-industrial-strategy and department-for-international-trade will be closing soon, at which point we can remove this bespoke banner code entirely.
We also need to remove the banner code for the actual org page which lives in collections. Once an org is closed in Whitehall the bespoke banner gets replaced automatically as a different view is rendered [2] vs [3]. This means we don't have to remove each orgs custom banner as it gets replaced anyway. We will still need to remove the banner code in Collections when all three orgs are closed.
[1]: https://www.gov.uk/government/organisations/department-for-digital-culture-media-sport/
[2]: …
> Remove banner from DCMS about page

- app/views/content_items/corporate_information_page.html.erb
Content request: the banner text should reflect the org pages [1].
[1]: https://www.gov.uk/government/organisations/department-for-international-trade
> Update banner text for about pages

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/views/_detailed-guide.scss
- app/assets/stylesheets/views/_published-dates-button-group.scss
- app/views/shared/_published_dates_with_notification_button.html.erb
https://trello.com/c/fc41oyEK/1923-enable-individual-loading-of-stylesheets-in-government-frontend
Extract published dates button group shared styles
These styles are currently included in `_detailed-guide.scss` but are used by 3 document types:
- Consultation
- Detailed guide
- Publication
This will cause a problem when the AssetHelper is implemented since the complete `_detailed-guide.scss` styles would need to be loaded for the above document types.
None
- https://github.com/alphagov/govuk_publishing_components/pull/3014
- https://github.com/alphagov/frontend/pull/3342
- https://github.com/alphagov/smart-answers/pull/6213
- [RFC #149](https://github.com/alphagov/govuk-rfcs/pull/152)
> Extract published dates button group shared styles

- app/views/content_items/hmrc_manual.html.erb
- app/views/content_items/hmrc_manual_section.html.erb
- app/views/content_items/hmrc_manual_updates.html.erb
- app/views/content_items/manual.html.erb
- app/views/content_items/manual_section.html.erb
- app/views/content_items/manual_updates.html.erb
- app/views/content_items/manuals/_manual_layout.html.erb
- app/views/content_items/manuals/_manual_section_layout.html.erb
- app/views/content_items/manuals/_manual_updates_layout.html.erb
Refactor the manual and HMRC manual partials so that they have common layout partials with the mark-up that is common to both of them.
The partials _hrmc_manual.html.erb/_manual.html.erb, _manual_section.html.erb/_hmrc_manual_section.html.erb and _hmrc_manual_updates.html.erb/_manual_updates.html.erb in content_items/manuals/ shared much of the same mark-up. Reducing duplicated mark-up makes things more maintainable.
[Relevant Trello Card](https://trello.com/c/CuRc02VB/1697-refactor-manual-pages-in-g …
> Refactor the Manual Pages

- app/views/content_items/field_of_operation.html.erb
https://trello.com/c/fc41oyEK/1923-enable-individual-loading-of-stylesheets-in-government-frontend
- Add [Govspeak component](https://components.publishing.service.gov.uk/component-guide/govspeak) for description content as a pre-requisite to implementing the AssetHelper to load component and view style sheets only required on the page being viewed
- Some minor style improvements (see visual changes below).
So Govspeak component styles will be automatically loaded on **field of operation** document types and no need to explicitly add the styles with the `add_gem_component_stylesheet` helper and to make it easier when implementing the helper.
- https://github.com/alphagov/govuk_publishing_components/pull/3014
- https://github.com/alphagov/frontend/pull/3342
- …
> Add Govspeak component

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/views/_corporate-information-page.scss
https://trello.com/c/fc41oyEK/1923-enable-individual-loading-of-stylesheets-in-government-frontend
Move `organisation-links` helper alongside corporate information page… as a pre-requisite to implementing the AssetHelper to load component and view style sheets only required on the page being viewed.
So there will be less CSS to be reviewed and updated when implementing the helper.
None.
- https://github.com/alphagov/govuk_publishing_components/pull/3014
- https://github.com/alphagov/frontend/pull/3342
- https://github.com/alphagov/smart-answers/pull/6213
- [RFC #149](https://github.com/alphagov/govuk-rfcs/pull/152)
> Move organisation-links helper alongside corporate information page view styles

- app/presenters/specialist_document_presenter.rb
Add missing `govuk-link` link formatting.
See https://www.gov.uk/eu-withdrawal-act-2018-statutory-instruments/the-drivers-hours-and-tachographs-amendment-regulations-2021
Consistent link appearance.
> Add missing `govuk-link` link formatting

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_banner.scss
- app/presenters/content_item/research_banner.rb
- app/presenters/content_item_presenter.rb
- app/views/layouts/application.html.erb
- test/integration/research_banner_test.rb
Add a GOV.UK user research banner for Cost of Living
Paths affected:
/cost-living-help-local-council
/benefits-calculators
/the-warm-home-discount-scheme
/universal-credit
/universal-credit/eligibility
/universal-credit/what-youll-get
/universal-credit/how-to-claim
/universal-credit/other-financial-support
/universal-credit/contact-universal-credit
/new-state-pension/what-youll-get
/get-help-energy-bills
/get-help-energy-bills/getting-discount-energy-bill
/pension-credit
[Trello card](https://trello.com/c/1O3pEivw/1777-govuk-user-research-banner-requests-for-col-tree-testing-study-1m)
Before:
After:
> Add cost of living user research banner

- config/environments/test.rb
https://trello.com/c/fc41oyEK/1923-enable-individual-loading-of-stylesheets-in-government-frontend.
Turn digests back on (remove `config.assets.digest = false`) in test environment as a pre-requisite to implementing the AssetHelper to load component and view style sheets only required on the page being viewed.
The default `config.assets.digest` was changed here: https://github.com/alphagov/government-frontend/commit/a806be8eb76bab3ec592671c43f623af7b05dee1 due to an issue loading Axe core in integration tests (with a comment to re-enable the option).
I've discovered an issue running some tests when individual style sheets are loaded with the GOV.UK Publishing Components [AssetHelper module](https://github.com/alphagov/govuk_publishing_components/blob/main/docs/set-up-individual-component-c …
> Turn digests back on in test environment

- app/presenters/corporate_information_page_presenter.rb
- app/views/content_items/corporate_information_page.html.erb
- test/presenters/corporate_information_page_presenter_test.rb
This was asked by content.
DIT and BEIS have now closed which means we can remove the transitory banners on the org about pages and the accompanying code. We've already removed DCMS's banner prior to this [1].
Trello:
https://trello.com/c/ZATeFciM/5-remove-temporary-banner-for-certain-org-about-pages
[1]: https://github.com/alphagov/government-frontend/pull/2726
> Remove org changing banner for DIT and BEIS

- Procfile
As we're now using Puma it's unlikely that the Procfile is needed for Heroku.
Our apps are crashing https://government-frontend-pr-2775.herokuapp.com/
as it's using the Procfile to call `bundle exec unicorn -c ./config/unicorn.rb -p ${PORT:-3090}` but we've dropped Unicorn https://github.com/alphagov/govuk_app_config/commit/71f4f2fa3871721e5c8140bcf73d683e09d8d7b2 
> Remove Procfile

- app/presenters/content_item/research_banner.rb
- test/integration/research_banner_test.rb
Piggy backing off of work to add the Cost of living survey banner. The two pages are different content types so need specific tests.
* https://government-frontend-pr-2775.herokuapp.com/benefits-end-of-life
* https://government-frontend-pr-2775.herokuapp.com/pip/claiming-if-you-might-have-12-months-or-less-to-live
[Trello](https://trello.com/c/vhN2QSQf/1806-add-end-of-life-survey-banner-s)
> Add End Of Life research banner

- app/views/content_items/case_study.html.erb
- app/views/content_items/consultation.html.erb
- app/views/content_items/corporate_information_page.html.erb
- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/document_collection.html.erb
- app/views/content_items/fatality_notice.html.erb
- app/views/content_items/html_publication.html.erb
- app/views/content_items/news_article.html.erb
- app/views/content_items/publication.html.erb
- app/views/content_items/speech.html.erb
- app/views/content_items/statistical_data_set.html.erb
https://trello.com/c/fc41oyEK/1923-enable-individual-loading-of-stylesheets-in-government-frontend
- Conditionally load [Devolved Nations](https://components.publishing.service.gov.uk/component-guide/devolved_nations) component 
- Conditionally load [Notice](https://components.publishing.service.gov.uk/component-guide/notice) component on Detailed Guide
Pre-requisites to implementing the AssetHelper to load component and view style sheets only required on the page being viewed.
**Review URL(s):**
- [Waste exemption: NWFD 2 temporary storage at the place of production](https://government-frontend-pr-2782.herokuapp.com/guidance/waste-exemption-nwfd-2-temporary-storage-at-the-place-of-production--2) (no devolved nations component)
- [Living safely with respiratory infections, including …
> Conditionally load components

- Gemfile
- Gemfile.lock
This swaps `pry` for `pry-byebug` so that we can use step-by-step debugging actions.
It also moves the debugging Gem into the `development` and `test` group so that we can debug when running the tests.
---
> Use `pry-byebug` for debugging

- test/integration/travel_advice_print_test.rb
The summary section of travel advice can now be optional so this test no longer passes given the summary field is not expected.
Trello card: https://trello.com/c/EnEbVdZs/1268-travel-advice-cleanup
> Remove travel advice summary from tests

- app/assets/stylesheets/views/_manual.scss
Fix style issues (incorrect background colour and spacing) on manuals when `inverse` [metadata component](https://components.publishing.service.gov.uk/component-guide/metadata#on_a_dark_background) is included within the header.
To fix style issues introduced following an update to the `inverse` [metadata component](https://components.publishing.service.gov.uk/component-guide/metadata#on_a_dark_background) https://github.com/alphagov/govuk_publishing_components/pull/3365
No.
> Fix manuals with inverse metadata component style issue

- app/presenters/content_item/research_banner.rb
- test/integration/research_banner_test.rb
Trello card: https://trello.com/c/0OnIdenV/1799-take-down-user-research-banner-for-col-m
Before
After
> [DO NOT MERGE BEFORE 23 MAY] Remove cost of living user research banner

- app/assets/stylesheets/views/_worldwide-organisation.scss
- Remove the margin from the `dd` elements in the header metadata section. In Whitehall (which previously rendered these pages), this was applied globally.
- Add top padding to the header section. As breadcrumbs are now shown where they weren't in Whitehall, this section looks a little squashed.
|Before|After|
|-|-|
|![image](https://github.com/alphagov/government-frontend/assets/47089130/8aa681a5-2594-4aa0-8aee-edcc8470304d)|<img width="1175" alt="image" src="https://github.com/alphagov/government-frontend/assets/47089130/9af51c78-06a5-4441-9026-3edccccf06cf">|
Follow [these …
> Improve spacing on the Worldwide Office pages

- README.md
Now that we have migrated Worldwide Offices across from Whitehall, we can mark them as "migrated" and provide an example.
---
> Mark Worldwide Offices as migrated in the README

- app/assets/stylesheets/views/_worldwide-organisation.scss
The narrow column design of the Worldwide Office page means that there is an
issue where long links (that don't contain wrapping characters like `-`) will
overflow.
This is a pre-existing issue from the Whitehall app.
As a quick fix, we can allow wrapping within words. Whilst the break points are
arbitrary, this is preferable to the overlapping we currently see. Both the
`word-wrap` and `overflow-wrap` declarations are needed to support all browsers.
|Before|After|
|-|-|
|<img width="1194" alt="image" src="https://github.com/alphagov/government-frontend/assets/47089130/05a733e2-f0f5-43ef-8226-d1bc4001ef25">|<img width="1070" alt="image" src="https://github.com/alphagov/government-frontend/assets/47089130/d373c713-bb75-4fdd-8f91-c665b8835be0">|
---
⚠️ This repo is Continuously Deployed: …
> Fix overlapping links on contact section of Worldwide Offices

- app/presenters/worldwide_office_presenter.rb
- test/presenters/worldwide_office_presenter_test.rb
https://trello.com/c/sLMFQp5N
As part of moving the rendering of the Worldwide Office pages to
government-frontend, we republished all of the Worldwide Organisations.
However, there was an issue where some Organisations were not republished. This
meant that we saw errors in production where we were trying to access the
details of a sponsoring organisation which was nil.
This makes sure that we are correctly handling the case where there are no
sponsoring organisations linked to the office's organisation.
`worldwide_organisation` is made private as it's not referred to outside of
this class.
---
Follow [these …
> Ensure `nil` sponsoring organisations are handled appropriately

- app/assets/stylesheets/views/_worldwide-organisation.scss
- app/controllers/content_items_controller.rb
- app/presenters/content_item_presenter.rb
- app/presenters/history_presenter.rb
- app/presenters/service_manual_homepage_presenter.rb
- app/presenters/service_manual_presenter.rb
- app/presenters/service_manual_service_standard_presenter.rb
- app/presenters/service_manual_service_toolkit_presenter.rb
- app/presenters/service_manual_topic_presenter.rb
- app/presenters/worldwide_office_presenter.rb
- app/presenters/worldwide_organisation_presenter.rb
- app/views/content_items/worldwide_organisation/_header.html.erb
- app/views/layouts/application.html.erb
- config/govuk_examples.yml
- test/integration/worldwide_office_test.rb
- test/integration/worldwide_organisation_test.rb
https://trello.com/c/MIgcASTq
Currently, we are maintaining multiple lists of which content items should not
show breadcrumbs in the `ContentItemsController`.
This moves the logic that determines whether a page shows
breadcrumbs into the derived classes of `ContentItemPresenter`.
We don't want to show breadcrumbs on the worldwide organisation and office
pages.
We updated the class names for the styling of this page, but missed the logo
class.
|This PR|Prod|
|-|-|
|https://government-frontend-pr-2812.herokuapp.com/world/organisations/british-embassy-paris/office/british-embassy|https://www.gov.uk/world/organisations/british-embassy-paris/office/british-embassy|
|This PR|Prod|
|-|-|
|https://government-frontend-pr-2812.herokuapp.com/government/history/10-downing-street|https://www.gov.uk/gov …
> Do not show breadcrumbs for worldwide organisation and office pages

- app/presenters/travel_advice_presenter.rb
- app/views/content_items/travel_advice.html.erb
- test/integration/travel_advice_test.rb
- test/test_helper.rb
We had a flakey test which was failing since it was randomly selecting a travel advice example (from content schemas) to test against, and one of these example schemas actually isn't able to be rendered at the moment. This was actually highlighting a bug whereby travel advice content items with no parts errored upon rendering, since the rendering code always assumes there are parts. 
While it looks like we have no live travel advice content items with no parts, it's permitted by the schema where a parts field is [required](https://github.com/alphagov/publishing-api/blob/main/content_schemas/formats/travel_advice.jsonnet) but there's nothing stopping it from being an empty array. It's also permitted by the publishing application - I tested in integration and nothing stopped me from …
> Fix bug in rendering travel advice with no parts

- app/views/content_items/travel_advice.html.erb
- app/views/shared/_email_signup.html.erb
This PR adds GA4 tracking to the `Get email alerts`/`Get emails` link (screenshots below).
`Get email alerts` link at the top of a page:
`Get emails` link in a sidebar:
As per the Implementation Guide, it is believed that these links only appear once on each page and therefore the `index_link` and `index_total` properties have been hardcoded to 1.
[Trello card](https://trello.com/c/Df3jj1HF/567-subscribe-get-email-alerts-link)
> Add ga4 tracking for email alerts

- app/views/content_items/guide.html.erb
This is a temporary hack to allow a single content item (https://www.gov.uk/child-benefit/how-to-claim) to expand a Youtube link into a Youtube embed. 
This was requested by Anna Hepburn (Head of Content) and was agreed with HMRC at senior level.
This hack is logged as tech debt to ensure it is removed when appropriate and if necessary can be replaced with a solution that allows embeds at a publisher controlled level: https://trello.com/c/3rIkaWkA/253-government-frontend-hacked-to-support-youtube-embed
Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if you are doing a Rails …
> Enable youtube embeds

- app/assets/stylesheets/application.scss
We've had a zendesk ticket come in https://govuk.zendesk.com/agent/tickets/5368540 which has reported an issue with table headings in RTL languages. While the body of the table renders RTL the headers don't.
I've updated the stylesheets to ensure that TH elements use `text-align: start;` which resolves the issue.
> Text algin right table headers for RTL content items

- app/assets/stylesheets/helpers/_parts.scss
- app/assets/stylesheets/views/_guide.scss
- app/views/content_items/guide.html.erb
Change the font size of the heading on guide pages by using a heading component with the font size `govuk-heading-l`.
This type of page features a title (rendered by the application) and a body of HTML that is saved to the content item in Whitehall and then rendered using Govspeak. This was leading to an accessibility issue where the page had two differently styled H1s. If we wanted to ensure that the page had one H1 then all the content that is rendered in the guides would need to be re-edited to update the heading levels. In addition we would need to ensure that future guides used this offset of headings. The solution that has the least amount of overhead (and would also ensure this issue does not crop up again for new pages) was to change the stying of the second H1 to resemble the …
> Change font size of second H1 on guide pages

- README.md
- app/presenters/worldwide_corporate_information_page_presenter.rb
- app/views/content_items/worldwide_corporate_information_page.html.erb
- config/govuk_examples.yml
- test/integration/worldwide_corporate_information_page_test.rb
- test/presenters/worldwide_corporate_information_page_presenter_test.rb
> **Warning**
> **Depends on ~~https://github.com/alphagov/publishing-api/pull/2409~~ and ~~https://github.com/alphagov/government-frontend/pull/2804~~**
https://trello.com/c/ATDZQXqq
- [As noted in the worldwide office rendering PR](https://github.com/alphagov/government-frontend/pull/2793) and [worldwide organisation PR](https://github.com/alphagov/government-frontend/pull/2804), the location name in the header will now link to the world location news, instead of the world location taxonomy.  
- We lose some additional padding at the bottom of the page, do we want to preserve this?
|This PR|Prod|
|-|-|
|![image](https://github.com/alphagov/government-frontend/assets/47089130/24d8d7bd-f0c6-4b27-9590-d99128f21588)|![image](https://github.com/alphagov/government-frontend/assets/47089130/e34 …
> Render Worldwide Corporate Information Pages

- app/assets/stylesheets/views/_travel-advice.scss
- app/views/content_items/travel_advice.html.erb
Change the font size of the heading on travel advice pages by using a heading component with the font size `govuk-heading-l`.
This type of page features a title (rendered by the application) and a body of HTML that is saved to the content item in Whitehall and then rendered using Govspeak. This was leading to an accessibility issue where the page had two differently styled H1s. If we wanted to ensure that the page had one H1 then all the content that is rendered in the guides would need to be re-edited to update the heading levels. In addition we would need to ensure that future guides used this offset of headings. The solution that has the least amount of overhead (and would also ensure this issue does not crop up again for new pages) was to change the stying of the second H1 to resemble …
> Use heading component with size l on travel advice pages

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/views/_worldwide-organisation.scss
- test/integration/worldwide_corporate_information_page_test.rb
- test/integration/worldwide_organisation_test.rb
https://trello.com/c/ImE91AWP
The worldwide organisation pages need the `direction-rtl` class in order to
correctly render languages with RTL writing systems like Arabic.
The groundwork is already in place for this, we simply need to include the page
type in `application.css`.
Visually, the page is now the same as it was in Whitehall (before the rendering
was moved over), except for the social media logos, which are now on the right.
This change is enabled by the components library and is desirable.
The `padding-inline-start` change ensures that the list of corporate
information pages does not have additional padding when rendered RTL.
This padding is present in Whitehall.
The worldwide corporate informaiton pages need the `direction-rtl` class in
order to correctly render languages with …
> Render RTL text for worldwide organisation pages

- app/views/content_items/worldwide_organisation/_header.html.erb
- test/integration/worldwide_corporate_information_page_test.rb
- test/integration/worldwide_office_test.rb
- test/integration/worldwide_organisation_test.rb
Currently, when sponsoring organisations are absent for a worldwide organisation (this isn't true for any currently, but can be), we still show the "Part of:" description in the header.
This makes it conditional on the presence of the sponsoring organisations, and adds some additional testing around this.
|Before|After|
|-|-|
|<img width="1007" alt="image" src="https://github.com/alphagov/government-frontend/assets/47089130/6344afa8-c25c-4420-af00-4024bd6c8a0c">|<img width="1031" alt="image" src="https://github.com/alphagov/government-frontend/assets/47089130/c9d09169-2f11-422b-bd4a-00d6b5a6b41c">|
Follow [these …
> Don't show "Part of:" tag when sponsoring organisations are absent

- app/views/content_items/consultation.html.erb
- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/publication.html.erb
- app/views/shared/_published_dates_with_notification_button.html.erb
- app/views/shared/_single_page_notification_button.html.erb
This PR adds GA4 tracking to the `Get emails about this page` button (see screenshot below).
This code is dependant on [PR #3443](https://github.com/alphagov/govuk_publishing_components/pull/3443).
[Trello card](https://trello.com/c/iP21pmuk/565-subscribe-get-emails-about-this-page-stop-getting-emails-about-this-page-button)
> Add ga4 tracking to single page notification button

- README.md
These are now rendered by Government Frontend (instead of Whitehall), so we can add examples to the README and update their migrated status.
Additonally, we can remove the "migration status" column from the README, as all schemas that can be rendered by this application are now rendered by it.
[Trello card](https://trello.com/c/TEa7G3Jp)
> Update README to reflect migration of rendering Worldwide Organisations out of Whitehall

- app/presenters/consultation_presenter.rb
- test/presenters/consultation_presenter_test.rb
This PR originates from feedback provided on https://github.com/alphagov/government-frontend/pull/2828, which duplicated behaviour from the consultation presenter. I intend to rebase that PR on top of these changes
This PR addresses several issues with the consultation presenter:
- Use of `to_a` to handle possible nil values, rather than handling them explicitly
- Readability improvements to `held_on_another_website?`
- Ensure that we are testing the interface rather than the implementation of document pre-rendering methods
> Consultation presenter improvements

- config/locales/ps.yml
- incorrectly had the pashto word for German instead of Pashto
https://govuk.zendesk.com/agent/tickets/5410354
> Update Pashto language name

- app/views/components/_contents_list_with_body.html.erb
- app/views/components/_published_dates.html.erb
- app/views/content_items/field_of_operation.html.erb
- app/views/content_items/guide.html.erb
- app/views/content_items/guide_single.html.erb
- app/views/content_items/hmrc_manual_section.html.erb
- app/views/content_items/how_government_works.html.erb
- app/views/content_items/html_publication.html.erb
- app/views/content_items/manuals/_header.html.erb
- app/views/content_items/manuals/_manual_section_layout.html.erb
- app/views/content_items/service_manual_guide.html.erb
- app/views/content_items/travel_advice.html.erb
- app/views/content_items/worldwide_office.html.erb
- app/views/histories/10_downing_street.html.erb
- app/views/histories/11_downing_street.html.erb
- app/views/histories/1_horse_guards_road.html.erb
- app/views/histories/king_charles_street.html.erb
- app/views/histories/lancaster_house.html.erb
- app/views/shared/_publisher_metadata_with_logo.html.erb
- test/components/published_dates_test.rb
- test/integration/guide_test.rb
- test/integration/travel_advice_test.rb
https://trello.com/c/C9M2EJQu/553-content-navigation-chapter-headings-next-previous-view-a-printable-version-navigation-and-show-hide-updates-interaction
- Adds tracking to our content pages as part of the content navigation card. It enables `ga4_tracking: true` on certain components, or adds a GA4 object to the HTML if the HTML is not rendered via `govuk_publishing_components`. 
This is part of our content navigation GA4 tracking. The elements which are tracked are:
- Contents list links at the top of the page.
- A "See all updates" jump link at the top of the page.
- Previous/Next page links at the bottom of the page.
- "View a printable version of this page" links at the bottom of the page.
- A "+ show updates" / " - hide updates" accordion at the bottom of the page.
I haven't written …
> Add GA4 tracking to content navigation components

- app/views/content_items/consultation.html.erb
- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/publication.html.erb
- app/views/shared/_single_page_notification_button.html.erb
- test/integration/consultation_test.rb
- test/integration/detailed_guide_test.rb
- test/integration/publication_test.rb
- test/test_helper.rb
Small refactor of the code added https://github.com/alphagov/government-frontend/pull/2818 with additional test coverage.
> Move single page notification button tracking code

- app/views/content_items/guide.html.erb
Adds heading scroll tracking to the following guide pages:
- https://www.gov.uk/skilled-worker-visa/your-partner-and-children
- https://www.gov.uk/penalty-points-endorsements/endorsement-codes-and-penalty-points
- https://www.gov.uk/universal-credit/other-financial-support
None.
Trello card: https://trello.com/c/Revzr3iF/611-scroll-tracking-heading-type-guidance
> Add scroll tracking to guide pages

- app/views/content_items/service_manual_guide.html.erb
- Adds the GA4 event tracker to this page's "+ Show all page updates (3)" element: http://127.0.0.1:3090/service-manual/design/introduction-designing-government-services
- It was missed while adding GA4 tracking to content navigation
- Trello card: https://trello.com/c/C9M2EJQu/553-content-navigation-chapter-headings-next-previous-view-a-printable-version-navigation-and-show-hide-updates-interaction#comment-64c3b662087abc05326982a8
- This is an example of a page with this tracking already on it https://www.gov.uk/guidance/cost-of-living-payment
Follow [these …
> Add GA4 event tracker to service manual guide

- app/presenters/document_collection_presenter.rb
- app/views/content_items/document_collection.html.erb
- app/views/shared/_published_dates_with_notification_button.html.erb
- app/views/shared/_single_page_notification_button.html.erb
- test/integration/document_collection_test.rb
Add the single page notification button to document collections. Pass in the `skip_account` flag to the component so that users sign up via the non GOV.UK account route. 
Review app: https://government-frontend-pr-2535.herokuapp.com/government/collections/technology-case-studies
| --------| ---------- |
| <img width="777" alt="Screenshot 2023-02-03 at 16 32 08" src="https://user-images.githubusercontent.com/17908089/216656408-06fb4d2d-240b-4920-a043-d45a1d8a9102.png"> | <img width="879" alt="Screenshot 2023-06-30 at 09 36 31" src="https://github.com/alphagov/government-frontend/assets/17908089/718bd762-84c6-4d86-97fd-58c7dd1d454f">|
Related work:
- https://github.com/alphagov/email-alert-frontend/pull/1489
- https://github.com/alphagov/govuk_publishing_components/pull/32 …
> Add single page notification button to document collections

- app/views/content_items/travel_advice.html.erb
Missing a closing div tag for some reason.
There is also an issue with header spacing which we'll address in another PR as that's a wider issue.
> Fix Related content section

- app/presenters/worldwide_organisation_presenter.rb
- test/presenters/worldwide_organisation_presenter_test.rb
Adds ", " to a join on the roles of a person in the WorldWideOrganisationPresenter. Adds test cases for spaces being present between roles in the description.
Fixes an issue where the description of people that was being generated by the WorldWideOrganisationPresenter was not adding spacing between multiple roles. Issue raised in a ticket on Zendesk.
> Add spacing to WorldWideOrganisation descriptions

- app/assets/stylesheets/helpers/_parts.scss
- app/assets/stylesheets/views/_travel-advice.scss
- app/views/content_items/guide.html.erb
- app/views/content_items/travel_advice.html.erb
Adjustments in previous commits #2837 and #2840 did not account for simultaneously aligning the grey border with the blue border of the related content, and providing space above the secondary heading. This small fix ensures that both columns line up correctly and that the secondary heading can breathe.
Note that this is a quick fix and further work should be done on these pages to consolidate the template.
See Trello for more info:
https://trello.com/c/H9MfuTul/1916-consolidate-traveladvice-and-guide-pages-in-governmentfrontend-l
Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) …
> Fix misaligned heading and related contents

- app/helpers/content_items_helper.rb
- app/views/content_items/call_for_evidence.html.erb
- app/views/content_items/consultation.html.erb
- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/publication.html.erb
- app/views/shared/_email_subscribe_unsubscribe_flash.html.erb
Adds GA4 tracking for notifications about subscribing/unsubscribing to emails about some pages, specifically:
- [detailed guides](https://www.gov.uk/guidance/cost-of-living-payment)
- call for evidence
- consultation
- [publications](https://www.gov.uk/government/publications/form-pa14-medical-certificate-probate)
These events are generated using the auto tracker, with attributes in the notification, so it should only fire when the notification is visible.
Detailed guide with the notification looks like this:
None.
Trello card: …
> Add tracking for email subscriptions completion

- app/views/content_items/html_publication.html.erb
[Github issue](https://github.com/alphagov/govuk_publishing_components/issues/3085)
This PR addresses a problem where the inverse header displays with uneven vertical spacing. This is caused by the way the component is rendered on the page rather than the component itself and requires that some extra padding is added to the top of the component so that it displays in a satisfactorily balanced way. 
|Current|Updated|
|-|-|
|![heading_before](https://user-images.githubusercontent.com/6080548/222208455-c7cfcdcf-68e5-421b-9469-a9d7b70eee4a.png)|![heading_after](https://user-images.githubusercontent.com/6080548/222208495-af6f4f8a-e4b2-4181-bf76-806bd3e57ac8.png)|
> Adds top margin to title component inside inverse-header

- app/presenters/worldwide_organisation_presenter.rb
- test/presenters/worldwide_organisation_presenter_test.rb
> [!WARNING]  
> 🚨 Do not merge! 🚨 
> Depends on https://github.com/alphagov/whitehall/pull/8162 being merged and all worldwide organisations being republished
https://trello.com/c/54I3mDxr
People linked to a worldwide organisation may have multiple roles, some of which are related to other organsaitions. Currently, we are incorrectly displaying these roles on the world wide organisation pages.
This copies the approach taken in alphagov/collections#1719. We link to all roles from the worldwide organisation, then filter out the incorrect ones in the rendering app.
See also https://github.com/alphagov/publishing-api/pull/2478 and https://github.com/alphagov/whitehall/pull/8162.
--- …
> Filter people roles by organisation

- app/presenters/document_collection_presenter.rb
- app/views/content_items/document_collection.html.erb
- app/views/shared/_taxon_signup_link.html.erb
- test/integration/document_collection_test.rb
- test/test_helper.rb
Allow users to sign up to a mapped taxonomy topic email subscription from some document collection pages if `taxonomy_topic_email_override` is present.
Trello card: https://trello.com/c/uvbb9UYR/1893-document-collection-template-uses-different-email-signup-component-if-taxonomytopicemailoverride-is-present-l
Without `taxonomy_topic_email_override` 
With `taxonomy_topic_email_override`
> Enable taxonomy email signup for document collection

- app/helpers/service_manual_phase_label_helper.rb
- app/views/content_items/call_for_evidence.html.erb
- app/views/content_items/consultation.html.erb
- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/html_publication.html.erb
- app/views/content_items/publication.html.erb
- app/views/layouts/application.html.erb
> Enable GA4 tracking on the phase & devolved nations banners

- lib/webchat.yaml
**To be deployed: 06/09/2023**
The urls provided are for the production environment. We used test URLs in [1].
Zendesk ticket: https://govuk.zendesk.com/agent/tickets/5053254
Trello Card: https://trello.com/c/qkzOuOJc/2155-help-hmpo-set-up-new-webchat-provider
[1]: https://github.com/alphagov/government-frontend/pull/2579
> [PRODUCTION CONFIG] Update Webchat urls for HMPO contact page 

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_intervention.scss
- app/presenters/content_item/recruitment_banner.rb
- app/presenters/content_item_presenter.rb
- app/views/layouts/application.html.erb
- test/integration/recruitment_banner_test.rb
The banner will be applied on the following pages:
- [/repaying-your-student-loan](https://www.gov.uk/repaying-your-student-loan)
- [/student-finance](https://www.gov.uk/student-finance)
- [/jobseekers-allowance](https://www.gov.uk/jobseekers-allowance)
Trello card: https://trello.com/c/EVjvHjqE/2090-brand-team-govuk-user-research-banner-request-to-set-up-m
> Add Brand recruitment banner

- app/presenters/content_item/recruitment_banner.rb
- app/presenters/content_item_presenter.rb
- app/views/layouts/application.html.erb
- test/integration/recruitment_banner_test.rb
The banner will be applied on the following pages:
- [/log-in-register-hmrc-online-services](https://www.gov.uk/log-in-register-hmrc-online-services)
- [/log-in-file-self-assessment-tax-return](https://www.gov.uk/log-in-file-self-assessment-tax-return)
- [/self-assessment-tax-returns](https://www.gov.uk/self-assessment-tax-returns)
- [pay-self-assessment-tax-bill](https://www.gov.uk/pay-self-assessment-tax-bill)
- [/contact-hmrc](https://www.gov.uk/contact-hmrc)
- [/log-in-register-hmrc-online-services/register](https://www.gov.uk/log-in-register-hmrc-online-services/register)
- [/dbs-update-service](https://www.gov.uk/dbs-update-service)
- [/government/organisations/hm-revenue-customs/contact/self-assessment](https://www.gov.uk/government/organisations/hm-revenue-customs/contact/self-asse …
> Add recruitment banner

- app/views/shared/_publisher_metadata_with_logo.html.erb
Most of the 'See all updates' links trigger a `select_content` event when clicked, as they open an accordion and jump to the accordion heading on the page instead of navigating to a new link. Therefore with the `ga4_tracking: true` flag, they were sending a link click (`navigation`) event and a `select_content` event on click. I've removed `ga4_tracking: true`, so that it will only send a `select_content` event on click.
https://trello.com/c/6Yq0OIER/667-see-all-updates-click-coming-through-as-navigation-as-well-as-selectcontent-event-on-some-pages
Follow [these …
> Remove GA4 link tracking from certain 'See all updates' links

- app/presenters/travel_advice_presenter.rb
- app/views/content_items/travel_advice.html.erb
- app/views/shared/_travel_advice_first_part.html.erb
- config/i18n-tasks.yml
- config/locales/en.yml
- test/presenters/travel_advice_presenter_test.rb
Publishers can now set an alert status for a country programmatically instead of including it in the copy content (see screenshot below for the editor options). 
This PR:
- Removes legacy code to render travel alerts as part of the govspeak content. To our knowledge this code has never been used as it wasn't possible to set `alert_status` in the editor until recently. Removes formatting from the presenter which was customised for rendering the alerts in govspeak: it used to flatten the array of alert statuses and wrap them each in a paragraph tag. These changes are in readiness for rendering the alerts with warning text.
- Renders alert statuses with warning text component
- Wraps the alert status in govspeak because the alert copy uses the abbreviation markup as recommended by the GOV.UK …
> Reflect travel advice alert status from travel advice publisher on the advice page

- app/views/components/_published_dates.html.erb
- app/views/content_items/service_manual_guide.html.erb
- test/components/published_dates_test.rb
Changes the GA4 `type` from `content` to `content history` on `show/hide updates` accordions
https://trello.com/c/KdNfD2FM/682-change-see-updates-show-hide-all-updates-selectcontent-event-types-to-content-history
> Change GA4 type for show/hide updates accordions

- app/views/content_items/manuals/_header.html.erb
- adds GA4 tracking to search forms on manual pages
- including manuals e.g. https://www.gov.uk/guidance/understanding-your-driving-test-result/car-driving-test
- and manual section e.g. https://www.gov.uk/guidance/understanding-your-driving-test-result/car-driving-test
- and hmrc manual e.g. https://www.gov.uk/hmrc-internal-manuals/capital-gains-manual
None.
Trello card: https://trello.com/c/zZGLn0tw/694-search-enhancement-add-search-form-tracking-to-manual-manualsection-and-hmrcmanualsection-pages
> Search tracking for manual pages

- app/views/content_items/manuals/_header.html.erb
- include a parameter on the form so that responses are also collected by the form tracker
- PII is automatically redacted by the form tracker in this situation
See [related PR](https://github.com/alphagov/government-frontend/pull/2942) for example URLs.
We want to capture form queries.
None.
Trello card: https://trello.com/c/zZGLn0tw/694-search-enhancement-add-search-form-tracking-to-manual-manualsection-and-hmrcmanualsection-pages
> Adjust manuals search tracking

- app/views/content_items/service_manual_guide.html.erb
Change the GA4 type on the contents list on pages like https://www.gov.uk/service-manual/helping-people-to-use-your-service/making-your-service-accessible-an-introduction#make-non-digital-parts-of-your-service-accessible to 'select content'.
These are in-page navigation events.
None.
Trello card: https://trello.com/c/kPQBqdSw/675-change-contents-navigation-selectcontent-event-types-to-contents-list
> Change GA4 type on service manual contents list

- app/controllers/asset_manager_redirect_controller.rb
- config/routes.rb
- test/controllers/asset_manager_redirect_controller_test.rb
- test/integration/asset_manager_redirect_test.rb
This is to allow request from `gov.uk` domain for `/media` path to be routed to 'asset' domain.
This is a proposed fix to work for modern url for assets for csv previews. Currently only legacy url paths work correctly for csv previews.
Currently csv previews only work for assets with legacy url path which contains `/government/uploads.` This is because when a request comes from 'www.gov.uk' domain for legacy asset path( /government/uploads ), it gets routed to government-frontend app which then redirects it to asset-path and the request works.
We want csv previews to work with modern asset url path `/media/:id/:filename`. Hence this PR adds the '/media/*path' route which will allow to request to get routed correctly to asset-domain as like legacy url path.
examples:
When we `View Online` …
> Adding '/media/*path' route

- app/presenters/content_item/manual_updates.rb
- test/presenters/content_item/manual_updates_test.rb
At the moment, it uses Date.parse which doesn't account for the difference in timing between the timestamp (UTC) and local time (BST).
This causes issues with some updates being a day off if they were published between 00.00 & 00.59.
Time.zone.parse parses the date correctly into the "London" timezone. We still need to convert it back into a date though as it groups on year, then by identical dates, so all updates for a day are grouped.
https://trello.com/c/idVD4RQT/1794-update-history-shows-the-wrong-date
Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if you are doing a Rails …
> Use Time.zone.parse instead of Date.parse in ManualUpdatesPresenter

- app/controllers/content_items_controller.rb
- test/controllers/content_items_controller_test.rb
nginx no likey underscores in headers - https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#missing-disappearing-http-headers
This was resulting in the HTTP header that Fastly sets for the AB test being dropped by one of the nginxs which sit in front of rails.
> Remove underscores from AB test name

- app/views/content_items/answer.html.erb
If our AB test is active (see ContentItemsController#temporary_ab_test_find_utr_page) then @requested_variant will be set, and we should use it to add the required <meta> tag to the page.
Technically this code will work for any Answer that sets a @requested_variant field, but I think that's probably okay / what people would want in that situation anyway.
> Add AB test meta tag to /find-utr-number page

- Dockerfile
As per the documentation for `yarn set version`:
The version specifier can be:
- a tag:
- `latest` / `berry` / `stable` -> the most recent stable berry (`>=2.0.0`) release
So `yarn set version berry` is equivalent to `yarn set version latest`, which will install newly released versions of yarn.
There was a release of yarn v4.0.0 yesterday - https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F4.0.0 which is now breaking the build, because it produces a slightly different lockfile.
The docker build should use whichever yarn version package.json uses, not install the latest version on the fly.
> Do not install yarn latest in docker build

- app/presenters/content_item/recruitment_banner.rb
- app/views/layouts/application.html.erb
- test/integration/recruitment_banner_test.rb
Remove the research banner. Reverts https://github.com/alphagov/government-frontend/pull/2931 from
- [/log-in-register-hmrc-online-services](https://www.gov.uk/log-in-register-hmrc-online-services)
- [/log-in-file-self-assessment-tax-return](https://www.gov.uk/log-in-file-self-assessment-tax-return)
- [/self-assessment-tax-returns](https://www.gov.uk/self-assessment-tax-returns)
- [pay-self-assessment-tax-bill](https://www.gov.uk/pay-self-assessment-tax-bill)
- [/contact-hmrc](https://www.gov.uk/contact-hmrc)
- [/log-in-register-hmrc-online-services/register](https://www.gov.uk/log-in-register-hmrc-online-services/register)
- [/dbs-update-service](https://www.gov.uk/dbs-update-service)
- [/government/organisations/hm-revenue-customs/contact/self-assessment](https://www.gov.uk/government/or …
> Remove the research banner

- app/views/content_items/manuals/_header.html.erb
Add data-ga4-form-no-answer-undefined to search form
Requested by PAs: https://trello.com/c/WtvEWiS3/592-placeholder-replace-no-answer-given-with-undefined-on-homepage-search-event
> Add data-ga4-form-no-answer-undefined to search form

- app/views/content_items/guide.html.erb
Removes scroll tracking for GA4 from several guides.
Scroll tracking is no longer required.
None.
Trello card: https://trello.com/c/R6z5Hd3d/714-remove-scroll-tracking
> Remove scroll tracking

- app/views/layouts/application.html.erb
Enable tracking on the intervention component.
Part of the GA4 migration. This should be turned on when this component is used, but we're exploring alternatives (like enabling tracking by default) so developers don't have to remember to do this.
None.
Trello card: https://trello.com/c/X9VRm9yV/721-add-tracking-to-intervention-component
> Enable GA4 tracking on intervention component

- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/guide.html+print.erb
- app/views/content_items/html_publication.html.erb
- app/views/content_items/manuals/_manual_layout.html.erb
- app/views/content_items/manuals/_manual_section_layout.html.erb
- app/views/content_items/manuals/_updates.html.erb
- app/views/content_items/travel_advice.html+print.erb
- app/views/content_items/travel_advice.html.erb
- app/views/shared/_document_collections_email_signup.html.erb
- app/views/shared/_email_signup.html.erb
- app/views/shared/_published_dates_with_notification_button.html.erb
- app/views/shared/_single_page_notification_button.html.erb
- test/test_helper.rb
- we no longer need to nest GA4 attributes attached to elements, notably the index attributes
- these attributes when collected by trackers are automatically nested based on the structure of the GA4 schema, held in the gem
- flattening them here saves code and complexity
None.
Trello card: https://trello.com/c/IseA05Fd/644-remove-nesting-of-ga4-attributes
> Flatten GA4 attributes

- app/views/content_items/service_manual_homepage.html.erb
- test/integration/service_manual_homepage_test.rb
Adds the GA4 form tracker to /service-manual search form
https://trello.com/c/mpoui5h3/726-add-search-tracking-to-https-wwwgovuk-service-manual
> Add the GA4 form tracker to /service-manual search

- app/assets/javascripts/application.js
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/views/_manual.scss
- app/presenters/content_item/manual.rb
- test/presenters/content_item/manual_test.rb
Addresses some issues to do with component use and practices in this application. See individual commits for details.
Issues raised by our component auditing tools.
None.
> Auditing fixes

- lib/publish_static_pages.rb
I noticed that a meta tag description wasn't appearing for the History of 1 Horse Guards Road page in internal search. I think it could be because of a typo in the word 'description' in this file, so I've updated it.
> Fixed typo in 1 Horse Guards Road description

- app/presenters/service_manual_topic_presenter.rb
- test/presenters/service_manual_topic_presenter_test.rb
This is no longer needed, as the GA4 data attributes are handled within the component (and `data-ga4` was the old name for the attribute)
Example page: https://www.gov.uk/service-manual/helping-people-to-use-your-service
> Remove old GA4 code

- app/helpers/service_manual_phase_label_helper.rb
- app/views/components/_contents_list_with_body.html.erb
- app/views/content_items/call_for_evidence.html.erb
- app/views/content_items/consultation.html.erb
- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/field_of_operation.html.erb
- app/views/content_items/guide.html.erb
- app/views/content_items/guide_single.html.erb
- app/views/content_items/hmrc_manual_section.html.erb
- app/views/content_items/how_government_works.html.erb
- app/views/content_items/html_publication.html.erb
- app/views/content_items/manual_section.html.erb
- app/views/content_items/manuals/_header.html.erb
- app/views/content_items/manuals/_manual_section_layout.html.erb
- app/views/content_items/manuals/_updates.html.erb
- app/views/content_items/publication.html.erb
- app/views/content_items/service_manual_topic.html.erb
- app/views/content_items/statistics_announcement.html.erb
- app/views/content_items/travel_advice.html.erb
- app/views/content_items/worldwide_office.html.erb
- app/views/histories/10_downing_street.html.erb
- app/views/histories/11_downing_street.html.erb
- app/views/histories/1_horse_guards_road.html.erb
- app/views/histories/king_charles_street.html.erb
- app/views/histories/lancaster_house.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_footer_navigation.html.erb
- app/views/shared/_sidebar_navigation.html.erb
Removes all instances of `ga4_tracking: true` in calls to components.
- all components that previously accepted this option now have GA4 tracking enabled by default, so these options are no longer needed
- no tracking should change as a result of this change
- this change was made in components gem v `35.22.0`
We're moving to an 'opt out' model of component inclusion, to future proof tracking as the site changes and components are added and removed.
None.
Trello card: https://trello.com/c/Xwp7dgJN/294-tracking-auditing-tracking-by-default
> Remove ga4_tracking: true component options

- app/views/layouts/application.html.erb
Fixes a problem with unneeded left/right padding around the phase banner.
- below the tablet breakpoint (around 1020px) the phase banner at the top of some pages was being padded left and right, which indented it from the rest of the page
- caused by the govuk-frontend grid wrapping classes, which were unnecessary
- some wrapping divs moved instead to support the phase label, which is similar but does require additional wrapping elements
- also remove some unnecessary logic
Example pages:
- https://www.gov.uk/hmrc-internal-manuals/air-passenger-duty/updates (phase banner with problem)
- …
> Fix phase banner left/right spacing on some pages

- app/presenters/content_item_presenter.rb
- app/views/layouts/application.html.erb
- test/integration/recruitment_banner_test.rb 
Will appear on following pages:
- [/cold-weather-payment](https://www.gov.uk/cold-weather-payment)
- [/cold-weather-payment/eligibility](https://www.gov.uk/cold-weather-payment/eligibility)
- [/cold-weather-payment/what-you-need-to-do](https://www.gov.uk/cold-weather-payment/what-you-need-to-do)
- [/cold-weather-payment/when-youll-get-paid](https://www.gov.uk/cold-weather-payment/when-youll-get-paid)
- [/cold-weather-payment/further-information](https://www.gov.uk/cold-weather-payment/further-information)
Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if you are doing a Rails …
> Add User Research Banner To Cold Weather Payment Pages

- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/guide.html+print.erb
- app/views/content_items/html_publication.html.erb
- app/views/content_items/manuals/_manual_layout.html.erb
- app/views/content_items/manuals/_manual_section_layout.html.erb
- app/views/content_items/manuals/_updates.html.erb
- app/views/content_items/travel_advice.html+print.erb
- app/views/shared/_published_dates_with_notification_button.html.erb
Removes GA4 tracking on 'print page' buttons
- We now have a tracker that tracks the browser's print dialog, so we remove this tracking to prevent duplicate print events.
- https://trello.com/c/8tv1YU8b/718-print-page-button-click-triggers-a-browser-print-event-duplicate-printpage-tracking
(Taken from #2513 )
- detailed guides ([example detailed guide](http://127.0.0.1:3090/guidance/register-a-trust-as-a-trustee))
- guides ([example guide](http://127.0.0.1:3090/change-address-driving-licence/print))
- HMRC manuals ([example manual](http://127.0.0.1:3090/hmrc-internal-manuals/employment-income-manual) and [example manual section](http://127.0.0.1:3090/hmrc-internal-manuals/employment-income-manual/eim00100) and [example updates page](http://127.0.0.1:3090/hmrc-internal-manuals/trust-registr …
> Remove GA4 tracking on 'print this page' buttons

- app/views/content_items/answer.html.erb
- app/views/content_items/guide.html.erb
Add percentage scroll tracking to some of the most visited guide and answer pages.
None.
Trello card: https://trello.com/c/JfkV5NSI/750-add-scroll-tracking-top-100-pages
> Add scroll tracking to guides and answers

- app/presenters/content_item/recruitment_banner.rb
- app/presenters/content_item_presenter.rb
- app/views/layouts/application.html.erb
- test/integration/recruitment_banner_test.rb
Add User Research banner to 10 guidances pages.
Please note, each page has a different survey link URL.
**Review apps:**
- https://government-frontend-pr-3023.herokuapp.com/guidance/check-employment-status-for-tax
- https://government-frontend-pr-3023.herokuapp.com/guidance/corporation-tax-trading-and-non-trading
- https://government-frontend-pr-3023.herokuapp.com/guidance/how-to-fill-in-and-submit-your-vat-return-vat-notice-70012
- https://government-frontend-pr-3023.herokuapp.com/guidance/sign-in-to-your-hmrc-business-tax-account
- https://government-frontend-pr-3023.herokuapp.com/guidance/rates-of-vat-on-different-goods-and-services
- https://government-frontend-pr-3023.herokuapp.com/guidance/claim-a-refund-of-construction-industry-scheme-deductions-if-youre-a-limited-company
- …
> Add user research banner

- test/integration/call_for_evidence_test.rb
This test was printing the page's HTML as output, which cluttered the test results.
Therefore removing.
> Remove `puts` from test

- app/presenters/worldwide_corporate_information_page_presenter.rb
- app/presenters/worldwide_office_presenter.rb
- app/presenters/worldwide_organisation/branding.rb
- app/presenters/worldwide_organisation_presenter.rb
- test/integration/worldwide_corporate_information_page_test.rb
- test/integration/worldwide_office_test.rb
- test/integration/worldwide_organisation_test.rb
- test/presenters/worldwide_corporate_information_page_presenter_test.rb
- test/presenters/worldwide_office_presenter_test.rb
We are currently presenting the Worldwide Organisation's title in the logo. This means there are no line breaks in the places specified by the user.
Updating to use the formatted title, which the publisher would have expected since they entered this in Whitehall.
| Page| Current Rendering | Changed Rendering |
| -- | -- | -- |
| Worldwide Organisation | ![Screenshot showing the logo on a worldwide organisation page with no line break](https://github.com/alphagov/government-frontend/assets/6329861/e5e6ea9d-81e7-4e68-9ef2-9b5fc182979c) | ![Screenshot showing the logo on a worldwide organisation page with the line break in the correct place](https://github.com/alphagov/government-frontend/assets/6329861/8643aa84-9650-45b7-a485-e66735deaa70)  |
| Worldwide Office | ![Screenshot showing the …
> Use formatted name for worldwide organisations

- app/views/shared/_travel_advice_first_part.html.erb
- test/integration/travel_advice_test.rb
FCDO would like the copy of this link updated to be more specific. Zendesk ticket: https://govuk.zendesk.com/agent/tickets/5495177
https://trello.com/c/acKHf0Md/2281-change-link-title-to-download-a-more-detailed-map
> Update copy for download link for travel advice map

- app/presenters/worldwide_organisation_presenter.rb
- test/presenters/worldwide_organisation_presenter_test.rb
In https://github.com/alphagov/whitehall/pull/8734 and https://github.com/alphagov/publishing-api/pull/2601, we have switched worldwide organisations to use edition links to fix a bug in editionable worldwide organisations.
This applies the changes needed to the frontend to reflect the lack of multi-level link expansion in edition links.
Whilst this change adds support for edition links, it also retains compatibility with non-edition links. This will allow us to deploy the frontend changes in advance of republishing the content items, preventing any downtime of these pages. The code for backward compatibility will be removed once the content items have all been republished with edition links (all the code to be removed has been marked with a comment so it is easy to identify).
[Trello …
> Use edition links for Worldwide Organisations

- app/presenters/worldwide_organisation_presenter.rb
- test/presenters/worldwide_organisation_presenter_test.rb
In https://github.com/alphagov/government-frontend/pull/3055, we added support for edition links associated with worldwide organisations. This change included backward compatibility for worldwide organisations without edition links.
Once the worldwide organisations have all been republished without non-edition links, we no longer need the backward compatibility here.
This also simplifies the code slightly, as the content item now only contains roles that are relevant to the worldwide organisation, rather than needing to filter them on the frontend.
[Trello card](https://trello.com/c/yNJwHw4K)
Follow [these …
> Remove code for rendering non-edition links for worldwide organisations

- test/integration/worldwide_organisation_test.rb
https://trello.com/c/npYpoK31
Currently, the worldwide organisation example JSON is incorrect; it contains:
- The link to "Personal information charter" as a corporate information page with a full URL
- A secondary corporate information page with a relative URL.
The former shouldn't be present, and this test relies on it's existence.
This updates the test so that the corporate information page link can be removed in alphagov/publishing-api#2637
The current example JSON produces this:
---
> Fix incorrect test

- app/views/shared/_webchat.html.erb
- test/integration/contact_test.rb
- Adds GA4 tracking to the webchat 'available' link
- It's on this page: http://127.0.0.1:3090/government/organisations/hm-passport-office/contact/hm-passport-office-webchat (if it says webchat is unavailable, inspect element as the relevant GA4 HTML will still be there, it's just hidden via CSS)
https://trello.com/c/Yha4qZD2/790-add-tracking-webchat-link
> Add GA4 tracking to webchat available link

- app/presenters/worldwide_organisation_presenter.rb
- test/presenters/worldwide_organisation_presenter_test.rb
We are currently linking the wrong place for worldwide offices on translated worldwide organisation pages.
E.g. for the content item in the test, we are currrenlty linking to `/world/uk-embassy-in-country.fr/office/british-embassy`, which results in a 404 response.
[Trello card](https://trello.com/c/9ivR4TGQ)
> Fix link to worldwide office for translated worldwide organisations

- app/views/content_items/manuals/_manual_section_layout.html.erb
- test/integration/manual_section_test.rb
[Trello](https://trello.com/c/FhkENn3P/2372-h1-in-manuals-smaller-than-h2)
This PR addresses the styling of H1 headers in manual pages, so there is a visual distinction between H1s and H2s. 
The fix involves adjusting the font size in the `_manual_section_layout.html.erb` partial, increasing it from `m` to `l`.This ensures that H1s now render with a font size of `l` and apply the `govuk-heading-l` class for improved visual differentiation.
Additionally, modified the Manual Section Test to resolve an error that occurred due to an ambiguous match in the rendered document heading.
**Before:**
**After:**
**Before**:
**After**:
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-re …
> Amend h1 font-size in manuals to l

- app/views/components/_banner.html.erb
- test/components/banner_test.rb
- Adds GA4 tracking to this application's banner component
Examples:
- `consultation`: http://127.0.0.1:3090/government/consultations/police-dogs-and-mounted-police-authorised-professional-practice
- `call for evidence`: http://127.0.0.1:3090/government/calls-for-evidence/generative-artificial-intelligence-in-education-call-for-evidence
## Why
https://trello.com/c/2EZokz4r/792-add-tracking-banner-callout-links
None.
> Add GA4 tracking to the banner component

- app/views/content_items/manuals/_updates.html.erb
[Trello](https://trello.com/c/PqXBvn5k/2377-implement-fallback-for-empty-links-in-hmrc-manuals-m)
This deals with an accessibility fail whereby a link to the amended document is not being displayed, see [this page](https://www.gov.uk/hmrc-internal-manuals/employment-status-manual/updates), under the entry for 5 October 2023. 
This happens because there is no value entered in the data for `title`, which is used as the text content for the link. There is a outstanding suggestion to force this to be a required value so that this does not occur but as a more immediate fix to deal with existing instances of the problem it was decided to not render the link at all in these cases. This retains the current visual appearance of the page (see below) but removes the cause of the accessibility fail …
> Implement fallback for empty links in HMRC Manuals

- app/views/shared/_webchat.html.erb
- test/integration/contact_test.rb
- Change `lang: :en` to `locale: :en` and add a test to ensure the GA4 webchat link text is always English
- I accidentally used the wrong word (`lang`) to enforce the English string. So I've fixed it and written a test to ensure it's working.
> Fix locale enforcement on GA4 webchat available link

- config/locales/cy.yml
We had a request to add a Welsh translation for the consultation concluded messaging.
https://govuk.zendesk.com/agent/tickets/5658237
> Add Welsh translation for consultation concluded

- app/controllers/content_items_controller.rb
- app/views/layouts/application.html.erb
- lib/data/recruitment_banners.yml
- test/integration/recruitment_banner_test.rb
The banner will be added on the following pages:    
- [/maternity-allowance](https://www.gov.uk/maternity-allowance)
- [/funeral-payments](https://www.gov.uk/funeral-payments)
- [/disability-living-allowance-children](https://www.gov.uk/disability-living-allowance-children)
- [/pension-credit](https://www.gov.uk/pension-credit)
Trello card: https://trello.com/c/zfgadIUN
> Set up DWP user research banner

- app/views/histories/lancaster_house.html.erb
- Update emails address
- accessibility: remove link element from phone number
Zendesk ticket: https://govuk.zendesk.com/agent/tickets/5668287
> Update Lancaster House contact details

- app/presenters/publication_presenter.rb
- app/views/content_items/_attachments_list.html.erb
- app/views/content_items/publication.html.erb
- test/integration/publication_test.rb
- test/presenters/publication_presenter_test.rb
Rework [form (publication) pages](https://docs.publishing.service.gov.uk/document-types/form.html) to render attachments locally in the application, rather than using the pre-rendered chunk of markup from the content item.
Specifically, rework the list of documents on the forms pages to use the content item data in `details->attachments` to render the required content, in place of the data in `details->documents`, which is pre-rendered. This has involved the creation of a new partial for publication pages, as the existing partial is used by other page types.
Example form pages:
- …
> Convert publications to local rendering

- app/presenters/publication_presenter.rb
- app/views/content_items/_attachments_list.html.erb
- app/views/content_items/publication.html.erb
- test/integration/publication_test.rb
- simplify and fix the code to display attachments on publication/form pages
- move most of the code into the presenter, to reduce ambiguity
- pass only one thing to the attachments_list component
- update tests
Follows on from the work done in https://github.com/alphagov/government-frontend/pull/3058
Recent changes to rendering of publication attachments were not fully correct, as reported in zendesk ticket https://govuk.zendesk.com/agent/tickets/5807151 and elsewhere.
Specifically:
- attachments on https://www.gov.uk/government/publications/further-education-workforce-data-collection should not be marked as …
> Fix publication attachments

- app/presenters/publication_presenter.rb
- test/integration/publication_test.rb
- some attachments are simply links to another website
- for these we need to identify the type as 'external' and pass the right option to the attachment component
- added test for this
Pages like this were showing external links as HTML attachments: https://www.gov.uk/government/publications/national-risk-register-2023
External links should now look like this:
Trello card: https://trello.com/c/tcTN1jbu/28-update-rendering-of-govspeak-attachments
> Fix publication external links

- app/presenters/publication_presenter.rb
- app/views/content_items/_attachments_list.html.erb
- test/integration/publication_test.rb
Add GA4 tracking attributes to details components within attachment components on publication pages.
The tracking for the details components is mostly handled automatically, but the component can't determine the value for `index_section_count` (the total number of related things being tracked) so this must be passed to the component. In this case it is the number of attachments that have a details component showing, which is not necessarily the same as the total number of attachments.
Some example pages to test:
- https://www.gov.uk/government/publications/make-a-lasting-power-of-attorney
- …
> Add GA4 tracking to details in attachments

- app/assets/stylesheets/views/_worldwide-organisation.scss
- app/presenters/worldwide_organisation_presenter.rb
- app/views/content_items/worldwide_organisation.html.erb
Use the `list` from `govuk-publishing-component` to render the list of corporate information pages for worldwide organisations.
The  list component means we can remove the hyphens that were rendered previously. These were read out as either “dash“ or “hyphen“ before each item/link in the Corporate information list.  Screen reader users found that frustrating to read through, so this should improve the experience.
|--------|--------|
| <img width="1030" alt="image" src="https://github.com/alphagov/government-frontend/assets/17481621/3a8d0612-61fd-4c83-812c-d8b2e2da24be"> | <img width="991" alt="image" src="https://github.com/alphagov/government-frontend/assets/17481621/be49b8a0-84a5-456d-a457-4dc07530f9d4"> | 
Trello card: https://trello.com/c/pVeGF0WE
> Prevent hyphens being read out by screen readers

- Gemfile.lock
Upgrade some gems which cannot be upgraded automatically by dependabot because of native extensions no longer compiling.
In order to keep our software up to date as a part of regular maintenance.
> Upgrade better_html, i18n-tasks and parser gems

- Gemfile
- Gemfile.lock
- config/environments/production.rb
Use Terser instead of Uglifier to compile JavaScript.
This change is preparation for upgrading to V5 of govuk-frontend in the govuk-publishing-components gem.
govuk-frontend v5 now targets browsers that support ES6. This means that the UMD modules used in govuk_publsihing_components from govuk-frontend use features of ES6 and so it means that Uglifier can't be used anymore because it only supports ES5.
[Trello card](https://trello.com/c/lnPFryyC/2562-prep-for-51-move-fe-applications-from-uglifier-to-terser-l)
| minifier | file | minified JS | minified JS (gzip) |
| --- | --- | --- | --- |
| uglifer |  government-frontend/application.js | 122KB | 22.7KB |
| terser | government-frontend/application.js | 122KB | 22.8KB |
I've tested the changes on Integration using the browsers below, …
> Use Terser instead of Uglifier

- app/presenters/worldwide_organisation_presenter.rb
- test/integration/worldwide_organisation_test.rb
Links from the Worldwide Organisation pages currently use the `web_url`, which is absolute, and never includes the draft part of the URL.
This means that a user viewing a draft Worldwide Organisation will be taken to the live version of the page.
Updating to make the URL relative, meaning users are always taken to the correct version of the page.
This was never previously an issue, since worldwide organisations have not previously been editionable.
[Trello card](https://trello.com/c/NFYppyyg)
> Use relative URL for worldwide organisation links

- app/presenters/consultation_presenter.rb
- app/views/content_items/consultation.html.erb
- test/integration/consultation_test.rb
- test/presenters/consultation_presenter_test.rb
Output attachments in consultation pages using the data from the content item, rather than the pre-rendered markup from the content item, and apply GA4 tracking to those attachments that contain Details elements.
This follows on from the work to convert publications in the same manner: https://github.com/alphagov/government-frontend/pull/3058
Attachments on consultation pages can occur in three places, so this is a bit more complex than publications, although some of the code and tests have been copied from that previous work.
Example pages to test with:
- [concluded …
> Use components for consultation attachments

- test/presenters/document_collection_presenter_test.rb
Addressing the deprecation warning:
```
DEPRECATED: Use assert_nil if expecting nil. This will fail in Minitest 6.
```
Using assert_equal nil will be deprecated in minitest 6. We should address this deprecation so upgrading will be easier when the time comes, as well as to keep our test outputs nice and clear.
> Address deprecation warning from minitest

- app/assets/javascripts/modules/hide-other-links.js
- app/assets/stylesheets/views/_worldwide-organisation.scss
From [Trello](https://trello.com/c/jrwE1oz3/2588-using-link-loses-focus-with-jaws-s-m):
_When using the ‘+ 12 others’ link with JAWS, the focus is lost. Using the tab key gets you to the first inserted link. But when navigating ‘in context’, using arrow keys to read through the page, the focus for JAWS users gets moved back to the start of the page which causes them to lose their place._ 
This was reported as an issue in JAWS. After testing, I also observed this as a problem in other screen-readers. However, this issue was potentially a problem for _all_ users as it did not focus a relevant element after activation. It would be confusing for non-screen-reader users who use the keyboard to navigate.
The behaviour has now changed:
* Anchor element is replaced with a button for improved …
> Fix the '+(xx) others' link losing focus after activation

- app/presenters/consultation_presenter.rb
- config/locales/en.yml
- test/integration/call_for_evidence_test.rb
- test/integration/consultation_test.rb
Changes the heading on consultations and calls for evidence pages from 'Download the full outcome' to 'Read the full outcome'.
Example pages:
- https://www.gov.uk/government/consultations/pre-employment-checks-for-health-and-care-volunteers
Text doesn't always make sense, specifically because some of the things being linked to are web pages, and some are PDFs (which for the most part just open in the browser rather than being downloaded).
Note that this change has been made only in the English translation for these pages. This is partly because getting all the translations is hard and not having them in one …
> Change publishing outcome pages text

- .govuk_dependabot_merger.yml
Enable automerging of external dependencies
To enable automerging of external dependencies in order to lessen the maintenance burden of developers.
[Trello ticket](https://trello.com/c/IKHEtABq/p)
The criteria mentioned in the [following document](https://github.com/alphagov/govuk-rfcs/blob/main/rfc-167-auto-patch-dependencies.md#conditions-required-for-automatic-patching) have been evaluated. They are repeated below. The linked document provides further explanations of them.
1. MUST ensure it has …
> Enable automerging of external dependencies

- app/views/components/_contents_list_with_body.html.erb
- app/views/components/_important_metadata.html.erb
- app/views/components/docs/contents_list_with_body.yml
- app/views/components/docs/important_metadata.yml
- test/components/all_components_test.rb
Fix the all components test in `government-frontend`. See commit for detail. Also updates some components to allow this test to pass (it should have been failing, but the components test was broken).
Thanks to @KludgeKML for noticing this and writing the fix.
None.
Trello card: https://trello.com/c/N3eQJZlU/168-fix-application-component-tests
> Fix components test

- app/views/content_items/manuals/_header.html.erb
- Adds a `url` value to the manuals search GA4 tracking on pages like https://www.gov.uk/guidance/understanding-your-driving-test-result/car-driving-test
- This value was accidentally missed out when tracking was added
- https://trello.com/c/wQrfhyj3/829-add-url-to-search-on-manual-pages
> Add URL to manuals search GA4 tracking

- app/presenters/call_for_evidence_presenter.rb
- app/presenters/consultation_presenter.rb
- app/presenters/content_item/attachments.rb
- app/presenters/publication_presenter.rb
- Attachment code in Publications, Consultations, and calls for evidence was recently updated to render locally rather than using the pre-rendered HTML from whitehall
- We move some of the duplicated code into the Content Item::Attachment concern, and delete the existing code there (which wasn't being used), and provide a utility method to simplify some of the unavoidably repeated code.
- Coverage slightly improved (presumable due to the deleted unused method).
https://trello.com/c/tcTN1jbu/28-update-rendering-of-govspeak-attachments
Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) …
> DRY up new attachment code

- app/views/content_items/manuals/_updates.html.erb
- Previously manual updates to the same path on the same day were grouped together and only the last was shown, despite all being present in the content item. The grouping code was correct, but in the view only the last item was displayed.
Fixes: https://govuk.zendesk.com/agent/tickets/5624376
Before and after from: https://www.gov.uk/guidance/style-guide/updates
> Handle manual updates on same day correctly

- app/assets/stylesheets/components/_important-metadata.scss
- improve the print styles for the important metadata component
- was defaulting to a light grey text that was quite hard to read
- setting colour and link colour to govuk-text-color (black, basically)
- also adding some padding between the items to improve readability, as includes the full links in the text when printed, so the box can look quite overwhelming
Can be seen on pages such as: https://www.gov.uk/find-funding-for-land-or-farms/wbd2-manage-ditches
Responding to a request from another department.
Before | After
------ | ------
Trello card: https://trello.com/c/UPuK4WOc/74-improve-print-styles-across-govu …
> Improve important metadata print styles

- app/views/histories/1_horse_guards_road.html.erb
- this page https://www.gov.uk/government/history/1-horse-guards-road calls the contents_list component and passes a series of links including one that includes an abbr (abbreviation) tag to explain the acronym 'GOGGS'
- this acroynm is explained several times already in the text of the page, as well as in the contents list link that immediately precedes this one
- there is no need for this tag inside this link, and this also causes significant complexity for the contents list component, which should not have anything other than text passed to it for the value of the text of a link
Before | After
----- | -----
> Remove abbr tag from contents list link

- app/assets/stylesheets/application.scss
- app/views/content_items/how_government_works.html.erb
- fix oversized images on the 'how government works' page https://www.gov.uk/government/how-government-works
- remove hard coded image dimensions and add a class that sets `max-width: 100%`
- was causing the images to overlap the width of the screen at small screen sizes, causing a horizontal scroll bar and a broken layout
- only adding the class or only removing the width/height don't fix the problem, because width/height as inline attributes override CSS
- was hoping to be able to leave the width/height to reduce cumulative layout shift when loading, but this is a small loss compared to fixing the general …
> Fix oversized images

- app/views/content_items/html_publication.html.erb
- passes the `page_text_direction` into the govspeak html publication component to ensure that lists display properly in right to left content
- govspeak html publication is used as a wrapper for the govspeak component, with some additional styles included
- it still accepts and passes through to govspeak a `direction` parameter
- in this case, pages had the the correct `direction` class applied to the top of the page, which seems to work for most of the styles on the page, but the govspeak CSS for RTL is written specifically assuming that the `direction` class is applied to the govspeak component (wrapping …
> Fix display of lists in RTL HTML publications

- app/assets/stylesheets/components/_figure.scss
- app/views/components/_figure.html.erb
- app/views/components/docs/figure.yml
- test/components/figure_test.rb
This fixes the spacing around the `government-frontend` figure component, specifically on mobile.
- on mobile, if a figure had a caption there was no space between it and the following content
- however if there was no caption, there was a space, because the empty figcaption element was still being rendered, which included spacing at the top (to prevent it from being too close to the image)
- this change fixes this problem and refactors the styling of the component in the following ways
- document the undocumented feature of an image credit beneath the caption
- only show the figcaption element if there is a …
> Fix spacing around figure component

- test/controllers/development_controller_test.rb
- test/test_helper.rb
Set up automated checking of ruby test coverage by simplecov as a requirement before a PR can be merged. This can be done in two ways. Either a test can be added, which checks simplecov coverage or an additional step can be added to GitHub CI. Investigate which of those two approaches is easier to implement and implement it.
We need to keep ruby code test coverage at 95% as indicated by simplecov in order to maintain the requirement of dependabot automerger.
[Trello …
> Check ruby test coverage before merging PRs

- app/views/components/_back_to_top.html.erb
- app/views/content_items/call_for_evidence.html.erb
- app/views/content_items/consultation.html.erb
- app/views/content_items/news_article.html.erb
Use `govuk-!-display-none-print` print style instead of `dont-print` class
https://trello.com/c/PnEVIZtq/192-review-and-fix-application-component-print-styles
- Consultations: http://127.0.0.1:3090/government/calls-for-evidence/generative-artificial-intelligence-in-education-call-for-evidence - the share links component does not show on print, as expected
- Calls for evidence: https://www.gov.uk/government/consultations/ices-area-7d-and-lyme-bay-king-scallop-dredge-fishery-closure-proposals-summer-2024 - the share links component does not show on print, as expected
- News articles e.g.: http://127.0.0.1:3090/government/news/secretary-of-state-meets-first-and-deputy-first-ministers - the share links component does not show on print, as expected
- "back top to link": …
> Use govuk-frontend no print style instead of dont-print class

- app/views/content_items/hmrc_manual.html.erb
- test/integration/hmrc_manual_test.rb
In the [content item](https://www.gov.uk/api/content/hmrc-internal-manuals/capital-gains-manual "‌")  for this page:[https://www.gov.uk/hmrc-internal-manuals/capital-gains-manual](https://www.gov.uk/hmrc-internal-manuals/capital-gains-manual "smartCard-inline") the second `child_section_group` contains a title field, but an empty `child_section_group` array. Which renders a random looking “Updates” heading underneath the list of sections.
It’s confusing, and probably an accessibility fail.
[Trello …
> HMRC Manuals: Do not show the title of a section group if the group is empty 

- app/presenters/hmrc_manual_section_presenter.rb
- test/presenters/hmrc_manual_section_presenter_test.rb
When a parent manual has been withdrawn and redirected, we don't get the value for `child_section_groups` as the redirect content item doesn't contain this value.
Therefore not showing any siblings items at all when this is the case, as we can't be sure what the correct parent actually is for this manual section.
This also resolves an issue where there are no breadcrumbs given for an item.
[Trello card](https://trello.com/c/LXBvfN2L)
> Do not attempt to show siblings if there aren't any

- app/presenters/html_publication_presenter.rb
We're currently sorting organisations by their title for the header, but this erases information from the content item, namely the ordering of organisations. Until now that hasn't been useful information (because it was the database natural ordering of the organisations involved). But now it's the lead organisations followed by the supporting organisations, so we shouldn't resort. This will bring the order of organisations in HTML attachments into line with the order presented in the item they're attached to.
Before Merging:
https://trello.com/c/7d3ERApJ/23-lead-organisation-logos-in-html-publications
> Remove org sort by title from html publications

- app/views/content_items/manuals/_manual_layout.html.erb
- app/views/content_items/manuals/_manual_section_layout.html.erb
- test/integration/hmrc_manual_section_test.rb
- test/integration/hmrc_manual_test.rb
https://trello.com/c/DwMxfbuf/1145-breadcrumb-issues-in-hmrc-internal-manuals
Eg on https://www.gov.uk/hmrc-internal-manuals/capital-gains-manual 
|Before|After|
|-|-|
|<img width="889" alt="Screenshot 2024-07-29 at 22 58 32" src="https://github.com/user-attachments/assets/cc455ac9-ae07-479d-93ca-853af0a82f8f">|<img width="1021" alt="Screenshot 2024-07-29 at 22 57 53" src="https://github.com/user-attachments/assets/6ff2281b-6d55-45ce-abfd-b81dfc814e20">|
Here's a page that has a populated description [on live](https://www.gov.uk/hmrc-internal-manuals/debt-management-and-banking) and [on the review app](https://government-frontend-pr-3284.herokuapp.com//hmrc-internal-manuals/debt-management-and-banking) to show that there's no visible change.
Eg debt management and banking manual
- …
> Minor bug fixes to HMRC manual layout and breadcrumbs 

- config/locales/ja.yml
- config/locales/pa-pk.yml
There are rendering anomalies in history mode notification banners for some foreign language pages. Placeholder text is not replaced and some strings are rendered out of the expected order. Examples:
https://www.gov.uk/government/news/uk-and-us-sanction-key-houthi-figures-to-protect-maritime-security-in-the-red-sea.ar
https://www.gov.uk/government/news/his-majesty-the-king-honours-mr-makoto-uchida-president-and-chief-executive-officer-nissan-motor-corporation.ja
This PR fixes the second issue and a …
> Fix bugs in historical mode banner translations

- app/views/content_items/service_manual_topic.html.erb
- app/views/layouts/application.html.erb
- test/integration/service_manual_phase_label_test.rb
[Trello card](https://trello.com/c/SHt2Y8Uu/2767-service-manual-pages-not-aligned-correctly-on-mobile-and-tablet)
This PR addresses alignment issues in the service manual pages across mobile and tablet views which was identified in this GitHub issue: https://github.com/alphagov/government-frontend/issues/3250 
- Removed `govuk-width-container` div from `service_manual_topic.html.erb`: This change fixes the alignment issue of the content of the page.
- Removed `govuk-width-container` div from `application.html.erb`: this adjustment ensures proper alignment of the phase banner with the content in various views.
- Improved `service_manual_phase_label` test: enhanced the test to handle case sensitivity for the "Alpha" phase label, ensuring Capybara correctly identifies the label regardless of …
> Fix: service manual mobile/tablet alignment

- app/presenters/content_item_presenter.rb
- app/presenters/service_manual_presenter.rb
- app/views/layouts/application.html.erb
- Align phase banner on service manual homepage
- Add new `service_manual_homepage?` presenter method
When on the service_manual_homepage, the phase banner will be wrapped in a div element with the `govuk-width-container` class to align it with the rest of the content on the page.
The service manual homepage layout is different from the rest of the service manual as it contains an app-hero banner that needs to span the full width of the page with a blue background, but we still want the phase banner to be contained.
| --- | --- |
| <img width="801" alt="Screenshot 2024-08-09 at 13 56 22" src="https://github.com/user-attachments/assets/1c851b16-049a-4d3e-ba90-4aa6a30c0e0f"> | <img width="720" alt="Screenshot 2024-08-09 at 13 56 58" …
> Align phase banner on service manual homepage

- Gemfile.lock
- app/assets/stylesheets/components/_published-dates.scss
- app/assets/stylesheets/helpers/_sticky-element-container.scss
- app/assets/stylesheets/views/_service_manual_guide.scss
- app/assets/stylesheets/views/_worldwide-organisation.scss
- app/views/development/index.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_webchat.html.erb
- Use type=module for this application's JS file
- To coincide with https://github.com/alphagov/govuk_publishing_components/pull/4111
- Has [DO NOT MERGE] as we want the above PR live on `static` first before this is merged.
- We will combine `es6-components.js` again as a separate task unless you disagree with this
- To accurately test this you will need to use local static that is using a local version the `govuk_publishing_components` branch linked above. If you test without this, this app's `application.js` seems to crash.
- Trello card: https://trello.com/c/Hoa45SMD/141-turn-off-javascript-in-legacy-browsers
> Use type=module for application.js

- app/views/content_items/get_involved.html.erb
Remove link to International Citizen Service, as the link is broken and the service is no longer running.
> Remove ICS link

- app/assets/stylesheets/helpers/_organisation-logos.scss
- On HTML publications such as https://www.gov.uk/government/publications/dvsa-sustainability-strategy/dvsa-sustainability-strategy, if you resize down to mobile, the organisation logo's name will wrap the text when it does not need to
- This is because of `flex-basis: 25%`, which restricts the width of the logo
- It seems like this `flex-basis` exists because some publications have more than one organisation logo on the page. For example: https://www.gov.uk/government/publications/10-downing-street-correspondence-communications-gifts-and-hospitality-privacy-notice/10-downing-street-correspondence-communications-gifts-and-hospitality-privacy-notice
- It seems like `flex-basis` is only needed on desktop, since the logos will stack on tablet / mobile. Therefore I have wrapped the …
> Style organisation logos with flex-basis on desktop only

- app/helpers/govuk_chat_promo_helper.rb
- app/views/shared/_sidebar_navigation.html.erb
- test/helpers/govuk_chat_promo_helper_test.rb
- test/integration/govuk_chat_promo_test.rb
**Note: this is a draft and an incomplete implementation. I'm just looking for feedback for the approach taken.**
We want to show a promo to the new GOV.UK Chat application on certain pages on GOV.UK. It's a CTA pointing users to the chat app.
The list of URLs we want the promo to appear on is quite short and cover only `answer` and `guide` content types from this codebase.
The CTA is to be shown in the sidebar on the right of the relevant pages.
> Display GOV.UK Chat promo on certain pages

- app/views/shared/_intervention_banner.html.erb
Remove unnecessary css class which is causing the intervention banner to indent on tablet.
|Before|After|
|-|-|
|<img width="939" alt="Screenshot 2024-08-30 at 10 41 39" src="https://github.com/user-attachments/assets/1c192180-d91b-42c7-a565-64d3d83a4417">|<img width="936" alt="Screenshot 2024-08-30 at 10 42 28" src="https://github.com/user-attachments/assets/5a424c72-ad3f-4630-8983-223a7dd23204">|
> Improve styling of the intervention banner on tablet

- app/assets/stylesheets/components/_published-dates.scss
This small PR adds extra spacing above the `app-c-published-dates` component when it's printed. [Trello](https://trello.com/c/tcXZsXup/193-review-and-fix-page-level-print-styles)
This component butts up  against the preceding content when printed and needs some breathing space.
> Improve spacing above the published dates footer

- app/helpers/govuk_chat_promo_helper.rb
The original URL is actually a redirect, so the promo wouldn't render
after the browser followed the redirect. This updates the helper to
specify the actual URL.
> Update URL in GOV.UK Chat promo helper

- app/views/content_items/answer.html.erb
- app/views/content_items/document_collection.html.erb
- app/views/content_items/guide.html.erb
- lib/data/recruitment_banners.yml
- test/integration/recruitment_banner_test.rb
As requested by HMRC via our normal processes
https://trello.com/c/1Pln7K5R/2809-govuk-user-research-banner-requests-hmrc-m
Review apps
- https://government-frontend-pr-3314.herokuapp.com/government/collections/tax-compliance-detailed-information
- https://government-frontend-pr-3314.herokuapp.com/government/collections/hm-revenue-and-customs-compliance-checks-factsheets
- https://government-frontend-pr-3314.herokuapp.com/difficulties-paying-hmrc
- https://government-frontend-pr-3314.herokuapp.com/tax-help
- https://government-frontend-pr-3314.herokuapp.com/get-help-hmrc-extra-support
- https://government-frontend-pr-3314.herokuapp.com/guidance/voluntary-and-community-sector-organisations-who-can-give-you-extra-support
- https://government-frontend-pr-3314.herokuapp.com/tax-appeals
- …
> Add HMRC's UR banner to required pages

- app/presenters/publication_presenter.rb
- app/views/content_items/publication.html.erb
- public/robots.txt
- test/integration/publication_test.rb
- test/presenters/publication_presenter_test.rb
As requested by DWP and senior leadership
This is a temporary fix and should be removed within 3 months
This is an existing pattern see [other examples in this application](https://github.com/search?q=repo%3Aalphagov%2Fgovernment-frontend+%3Cmeta+name%3D%22robots%22+content%3D%22noindex%2C+nofollow%22%3E&type=code)
[Trello](https://trello.com/c/fTPduo3e/2830-insert-a-noindex-meta-tag-to-pension-credit-claim-form-government-publications-pension-credit-claim-form-2)
> Add a noindex metatag to specific publication

- app/assets/stylesheets/views/_html-publication.scss
- app/views/content_items/html_publication.html.erb
Fix the HTML Publication layout so that it uses the grid layout classes supplied by govuk-frontend. [Trello](https://trello.com/c/lCNIkgGw/338-html-publication-layout-should-use-govuk-frontend-grid-classes)
This commit removes some of the rules that were previously set for the `.main-content-container` and instead uses the column rules from `govuk-frontend`.
The `.main-content-container` has now been renamed as `contents-container` to be consistent with the `contents-list-container`. I had hoped to remove this class entirely, but it's required to apply different float rules when in RTL reading mode.
This also adds the new class for collapsing columns to full width when printing.
HTML Publication uses some custom classes for managing its layout, but these more-or-less replicate what’s …
> Fix HTML Publication layout to work with design system columns

- config/locales/es-419.yml
This is pretty clearly a typo when the key/values were first put in: https://github.com/alphagov/government-frontend/commit/34c297265c005b8cdf5348b874b524297b4bd072#diff-7110365887255a0b6cf4bd5f866f9cdcfa187ee3844e45aa8b7033d30c135189R45-R51
Correct value is the first half, as confirmed in the card/zendesk ticket:
https://trello.com/c/DWS19aem/30-issue-with-access-and-opening-times-latin-american-spanish-translation-text
> Fix translation typo in Latin American locale

- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/guide.html+print.erb
- app/views/content_items/guide.html.erb
Add the new `gem-print-columns-none` print class to the layouts in Guides and Detailed Guides, to collapse columns on print. [Trello](https://trello.com/c/J1FtkA7Q/344-add-generic-print-styles-to-guide-and-detailed-guide)
When printing various page types, the 2/3rds + 1/3rds column layout causes issues with cropped content and a generally poor printing experience because the full page isn't used. By selectively collapsing floated columns, we can avoid most of these issues and improve the printing experience by using the full width of the page.
| Before    | After |
| -------- | ------- |
|![image](https://github.com/user-attachments/assets/fdd49449-0c43-4cff-a33f-46627c366317)|![image](https://github.com/user-attachments/assets/bc236d30-eca6-4f5c-aa3c-d886a5001d9e)|
| Before    | After | …
> Apply 'no columns' print style to Guide/Detailed Guide

- app/views/shared/_history_notice.html.erb
- test/integration/news_article_test.rb
Depends on https://github.com/alphagov/publishing-api/pull/2901.
Right-to-left languages were displaying the government name in an unusual way, treating the government name as translated text even though it is still English. This commit fixes the text direction, as well as setting the correct language for the text snippet.
Before:
After:
Trello: https://trello.com/c/dyyPjZxD/2870-history-mode-banners-in-foreign-languages-govt-agency-general-issue
> Fix markup (and therefore styling) of RTL history mode banner

- test/integration/specialist_document_test.rb
- test/test_helper.rb
so we can clean up example schemas.
There is already a test that tests random generated examples of specialist document schemas render without error, so it feels a little redundant to test using the other examples too. Removing the test allows us to prune the example schemas from Publishing API
https://trello.com/c/7fzxocSX/2813-remove-specialist-document-examples-from-publishing-api
> Remove specialist example references

- app/views/content_items/answer.html.erb
- app/views/content_items/document_collection.html.erb
- app/views/content_items/guide.html.erb
- lib/data/recruitment_banners.yml
- test/integration/recruitment_banner_test.rb
Reverts alphagov/government-frontend#3351
Trello card: https://trello.com/c/U5Inv6PQ/2912-reinstate-govuk-user-research-banner-requests-hmrc-s
> Revert "Take down HMRC's UR banner"

- app/presenters/content_item/contents_list.rb
- app/presenters/manual_section_presenter.rb
- test/presenters/content_item/contents_list_test.rb
- test/presenters/manual_section_presenter_test.rb
Pair programming effort with @CodeSonia 
This PR contains a minor reorganisation of the existing code with no user facing changes
The show_contents_list? method is hard to understand, and bugs have surfaced here.
The special logic around showing contents lists on MOJ manual sections only should only be called by the manual section presenter class.
> Minor refactor of contents list logic

- app/presenters/content_item/contents_list.rb
- test/presenters/content_item/contents_list_test.rb
The original implementation could result in the `show_contents_list?` method returning nil
rather than true or false. Which is unexpected, and has been a barrier
to changing when and where we display contents lists ([trello](https://trello.com/c/lT8fhx5Q/2806-display-content-lists-on-publications-even-when-there-are-fewer-than-3-h2s-m-l)) because of confusing
test failures (https://github.com/alphagov/government-frontend/pull/3361).
> Refactor contents list logic

- lib/data/recruitment_banners.yml
- test/integration/recruitment_banner_test.rb
Needs to be live on 21/10/2024.
Trello card: https://trello.com/c/jNRnH1Xr/2930-put-live-govuk-user-research-banner-requests-hmrc
Preview pages:
https://government-frontend-pr-3357.herokuapp.com/guidance/keeping-your-hmrc-login-details-safe
https://government-frontend-pr-3357.herokuapp.com/government/collections/hmrc-phishing-and-scams-detailed-information
> Add HMRC UR banner to required pages

- config/environments/test.rb
Set Rails config option action_dispatch.show_exceptions to :none.
Setting this option to false is [deprecated](https://guides.rubyonrails.org/7_1_release_notes.html).
In order to make our Rails configuration up to date.
> Set Rails config option action_dispatch.show_exceptions to :none

- app.json
Our review apps were failing at the line `Installing yarn-v1.22.22`. The error message from Heroku suggested specifically adding a buildpack for node.js before the ruby buildpack is fetched. See logs [here](https://dashboard.heroku.com/pipelines/9af8998d-0da3-4a5f-bd82-ac366adac06f/app-setup/abdac96e-7334-42b5-887f-452e81172b98).
> Update app.json used by heroku

- lib/data/recruitment_banners.yml
- test/integration/recruitment_banner_test.rb
Trello card: https://trello.com/c/KGa5vDZ0/3024-take-down-govuk-user-research-banner-hmrc
Preview pages: 
https://government-frontend-pr-3423.herokuapp.com/guidance/keeping-your-hmrc-login-details-safe
https://government-frontend-pr-3423.herokuapp.com/government/collections/hmrc-phishing-and-scams-detailed-information
> Remove HMRC UR banner

- app/views/content_items/document_collection.html.erb
- app/views/shared/_document_collections_email_signup.html.erb
- test/controllers/content_items_controller_test.rb
- test/integration/document_collection/email_notifications_test.rb
- test/integration/document_collection_test.rb
Fix two issues with the email subscription signup process on Document Collection pages.
This should have been added in https://github.com/alphagov/government-frontend/pull/2535
|Before|After|
|-|-|
|<img width="876" alt="Screenshot 2024-11-12 at 22 28 09" src="https://github.com/user-attachments/assets/a7265f7d-96a4-4ea0-bd5b-b8203aba8ba9">|<img width="816" alt="Screenshot 2024-11-12 at 22 26 38" src="https://github.com/user-attachments/assets/eaee1c16-1230-46ce-a15f-eae93b81e733">|
Allow users with a gov.uk account to unsubscribe from a document collection via the single page notification button. See commit message for full explanation and links to documentation. 
[Trello](https://trello.com/c/qCUfi1lj/2917-bug-single-page-notification-button-unsubscribe-button-broken-on-document-collecti …
> Unsubscribe button on document collection pages

- app/views/shared/_sidebar_navigation.html.erb
This PR removes the blue border top from the chat entry component and adds a margin top on smaller screen sizes as per the design requirements.
Relies on [PR #4417](https://github.com/alphagov/govuk_publishing_components/pull/4417) in the components gem.
Design requirements - [trello card](https://trello.com/c/iOuUw0vs/2157-entry-banner-tweaks)
> Adjust chat entry component

- app/helpers/govuk_chat_promo_helper.rb
- app/views/shared/_sidebar_navigation.html.erb
- test/helpers/govuk_chat_promo_helper_test.rb
- test/integration/govuk_chat_promo_test.rb
We have an allow list of URLs on which we want to render the GOV.UK Chat
promo, which we compare the content item's `base_path` against to
determine whether to show the promo or not.
This results in a bug in some guide pages where we only want to show the
promo on certain steps of the guide.
Let's consider the "/contracted-out" URL. This guide has 3 steps, and so
3 URLs
1. /contracted-out
2. /contracted-out/how-contracting-out-affects-your-amount
3. /contracted-out/check-if-you-were-contracted-out
We only want to show the promo on URL 1 and 3 in the list above, but not
the second one.
With the current logic, we're showing the promo on all of these URLs.
That's because we're looking at the `content_item.base_path` property,
which is "/contracted-out" for all of those URLs.
Instead we …
> Fix GOV.UK Chat promo on pages with multiple path segments

- app/presenters/content_item_presenter.rb
- test/integration/publication_test.rb
All months in the published date component need to be translated.
Trello card: https://trello.com/c/12ai7KMg/3072-allow-months-to-be-translated-in-the-published-dates-field-in-government-frontend-s
> Translate correctly Welsh published date

- app/helpers/govuk_chat_promo_helper.rb
In https://github.com/alphagov/government-frontend/pull/3440 we changed the mechanism for rendering the GOV.UK Chat banner to utilise request path rather than content item base_path. A side effect of this was that for any existing guides that we were embedding the banner on lost the banner on any of their nested sections.
This commit adds each individual path of guides that previously had the banner.
> Restore GOV.UK Chat banner to nested guide page

- app/presenters/content_item/single_page_notification_button.rb
- app/presenters/content_item_presenter.rb
- app/presenters/document_collection/signup_link.rb
- app/presenters/document_collection_presenter.rb
- app/views/shared/_document_collections_email_signup.html.erb
- app/views/shared/_published_dates_with_notification_button.html.erb
- app/views/shared/_single_page_notification_button.html.erb
- test/integration/call_for_evidence_test.rb
- test/integration/consultation_test.rb
- test/integration/detailed_guide_test.rb
- test/integration/document_collection/email_notifications_test.rb
- test/integration/publication_test.rb
- test/presenters/call_for_evidence_presenter_test.rb
- test/presenters/consultation_presenter_test.rb
- test/presenters/detailed_guide_presenter_test.rb
- test/presenters/document_collection/signup_link_test.rb
- test/presenters/document_collection_presenter_test.rb
- test/presenters/publication_presenter_test.rb
- test/test_helper.rb
Hide the single page notification button from pages that are not published in English. 
GOV.UK does not support email subscriptions to foreign language content. The single page notification button was added to all pages (English and foreign language). The consequence has been users signing up to an email subscription that will [never match a content change](https://github.com/alphagov/email-alert-service/blob/main/email_alert_service/models/major_change_message_processor.rb#L23-L26).
We _could_ make the button work so that clicking the button on eg a welsh page results
in the user signing up to the equivalent content in English. But we decided against this for the following reasons:
1. There is no indication that there is a user need for that behaviour
2. The code to fetch the english …
> Hide email signup button from pages that do not have an :en locale

- app/assets/stylesheets/helpers/_parts.scss
- app/views/components/_published_dates.html.erb
- app/views/components/docs/published_dates.yml
- test/components/published_dates_test.rb
- modify the published dates component to use the component wrapper helper
- move the visibly hidden heading inside the component and adjust a test accordingly
This component was using the shared helper for margin bottom but this functionality is being moved to the component wrapper helper.
None.
Trello card: https://trello.com/c/qH4NyWJw/364-add-component-wrapper-to-more-components
Related PR: https://github.com/alphagov/frontend/pull/4543
> Use component wrapper in published dates component

- app/controllers/content_items_controller.rb
- app/lib/features.rb
- app/queries/graphql/news_article_query.rb
- test/controllers/content_items_controller_test.rb
- test/fixtures/graphql/news_article.json
- test/presenter_test_helper.rb
- test/presenters/news_article_graphql_presenter_test.rb
- test/test_helper.rb
This switches the rendering of news articles to use Publishing API's GraphQL endpoint, only when the feature flag is enabled.
The code here (and in the associated Publishing API PR: https://github.com/alphagov/publishing-api/pull/3008) has been written in such a way that the least number of changes have been needed in this app, as this is only a proof of concept for now.  If we decide to use GraphQL for everything going forward, we should revisit the structure of content returned by GraphQL.
Also note that GraphQL powered queries rely on an initial request to Content Store, since we need to know the content type before deciding whether to use GraphQL.
Furthermore it only renders one level of parent taxon.  We will have follow-up work to change how the taxonomy is presented by GraphQL, as …
> Render news articles using GraphQL

- README.md
Update schema examples in README.md:
- Add the "Call for evidence" schema and example page
- Removed the "Help page" and "Take part" schema examples as these are now rendered by `frontend`
Help ensure the schema examples are complete and accurate
> Update schema examples in README.md

- app/assets/stylesheets/components/_banner.scss
- app/views/components/_banner.html.erb
- app/views/components/docs/banner.yml
- app/views/content_items/_attachments_list.html.erb
- app/views/content_items/call_for_evidence.html.erb
- app/views/content_items/consultation.html.erb
- app/views/content_items/publication.html.erb
Change how we use the heading component margin options in consultations pages.
We're removing this option from the heading component because there's some very specific behaviour on these pages and we should move away from corner cases like this to a spacing model that works across pages.
Relates to https://github.com/alphagov/govuk_publishing_components/pull/4510
Some minor spacing changes.
[Consultations pages](https://www.gov.uk/government/consultations/copyright-and-artificial-intelligence) headings have slightly smaller spacing below on desktop and above on mobile.
Before (desktop) | After (desktop)
------ | …
> Stop using mobile_top_margin with heading component

- app/presenters/document_collection_presenter.rb
- test/integration/document_collection_test.rb
- test/presenters/document_collection_presenter_test.rb
Investigate whether we can enable headings in the body text to be included in the contents section, and if possible make it happen.
The 'Contents' section of a document collection page is created automatically from the 'groups' of documents on the page. That works fine the majority of the time.
However, sometimes departments need to also link to documents or webpages that are relevant, but hosted off [GOV.UK](http://GOV.UK "‌").
Because Whitehall doesn't let them add such links off the …
> Enable headings in body text on document collections to appear in contents section 

- app/controllers/content_items_controller.rb
- app/queries/graphql/edition_query.rb
- test/controllers/content_items_controller_test.rb
Publishing API was updated in https://github.com/alphagov/publishing-api/pull/3063 to have a single edition type for most content, instead of a specific type for news articles.
Updating the query used by this application in making such requests to Publishing API.
[Trello card](https://trello.com/c/MSjuzc9M)
> Update GraphQL query to use generic edition type

- Gemfile.lock
- app/views/content_items/call_for_evidence.html.erb
- app/views/content_items/consultation.html.erb
- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/html_publication.html.erb
- app/views/content_items/publication.html.erb
Update instances of the [devolved nations component](https://components.publishing.service.gov.uk/component-guide/devolved_nations) to use a different option name. The option has changed from 'type' to 'content_type'.
Note that this PR will probably fail tests until the change to the component is included in this PR.
The option is changing in https://github.com/alphagov/govuk_publishing_components/pull/4535
None.
Trello card: https://trello.com/c/hUDC8lzz/418-add-component-wrapper-helper-to-button-component
> Change option on devolved nations component

- app/presenters/manual_section_presenter.rb
We're currently calling the main method, and then looping over the result. In each loop, we call the method again so that we can get the length. See manual_section.html.erb, which does roughly:
@content_item.main.each.with_index do |item, index|
{
data_attributes: {
ga4_event: {
index: index,
index_total: @content_item.main.length,
... the effect of this is that we run the main method n times, where n is the number of `<h2>` elements in the body. This results in us spending a lot of time parsing the same document and running the same CSS / XPath selectors on it, which adds up to a lot of time.
Memoizing the result of the main method shaves several seconds off the time to render www.gov.uk/guidance/complete-the-school-census/data-items-2024-to-2025 on my machine.
The flamegraph before …
> Memoize manual section presenter

- app/views/content_items/hmrc_manual.html.erb
- app/views/content_items/hmrc_manual_section.html.erb
- app/views/content_items/manuals/_hmrc_sections.html.erb
- test/integration/hmrc_manual_test.rb
**Example of HMRC manual section pages:** 
- https://government-frontend-pr-3464.herokuapp.com/hmrc-internal-manuals/inheritance-tax-manual/ihtm35000
Before:
After:
**Example of HMRC manual pages:**
- https://government-frontend-pr-3464.herokuapp.com/hmrc-internal-manuals/paye-manual
- https://government-frontend-pr-3464.herokuapp.com/hmrc-internal-manuals/cotax-manual
Before:
After:
Trello card: https://trello.com/c/siEO6N64/3097-hmrc-manuals-api-section-headings-issue-l#
> Fix hmrc manuals heading

- config/locales/ar.yml
The translations for "Policy paper" and "Publish" are incorrect in Arabic.
Page example: https://www.gov.uk/government/publications/uk-candidate-for-the-international-court-of-justice-election-2026-professor-dapo-akande-election-brochure.ar
Before:
After:
Trello card: https://trello.com/c/NkLPasOt/3166-fix-arabic-translation-in-government-frontend
> Fix Arabic translation for 'Published' and 'Policy paper'

- app/assets/stylesheets/components/_figure.scss
- app/assets/stylesheets/components/_published-dates.scss
- app/views/content_items/news_article.html.erb
- app/views/content_items/publication.html.erb
- app/views/content_items/speech.html.erb
- app/views/shared/_publisher_metadata_with_logo.html.erb
Improvements to components and layouts so that right-to-left (RTL) content renders correctly when printing*. This is part of the work to improve print styles more generally. [Trello](https://trello.com/c/6E5UoTiK/335-rtl-print-styles-have-been-considered-and-implemented-where-required)
_Note:_ This PR depends on https://github.com/alphagov/govuk_publishing_components/pull/4365 and https://github.com/alphagov/collections/pull/3835 and the _After_ screenshots below include those dependecies.
_* Although this PR is specifically about print styles, some fixes also apply to the screen rendering due to problems originating in the screen styles._
Some pages are broken for foreign languages that read right to left, with styles not set correctly for the changed direction.
| Before    | After |
| …
> Improve print styles for right-to-left (RTL) content.

- .github/pull_request_template.md
Update the pull request template to include a warning about route migration.
The Patterns and Pages team are currently migrating routes out of this application and into `frontend`. Any devs unaware of this could be making necessary changes to code that has already been copied across, but not yet in use.
None.
> Add warning about migrating routes to PR template

- app/views/content_items/detailed_guide.html.erb
- app/views/content_items/html_publication.html.erb
- app/views/content_items/service_manual_homepage.html.erb
- app/views/content_items/service_manual_service_toolkit.html.erb
- app/views/histories/10_downing_street.html.erb
- app/views/histories/11_downing_street.html.erb
- app/views/histories/1_horse_guards_road.html.erb
- app/views/histories/king_charles_street.html.erb
- app/views/histories/lancaster_house.html.erb
- app/views/shared/_published_dates_with_notification_button.html.erb
Firstly, remove the options to pass a `margin_top` attribute to the print link component, as this option was [removed in a previous PR](https://github.com/alphagov/govuk_publishing_components/pull/4577).
Secondly, replace instances of the title component with the heading component. These are instances where the `margin_top` option is used, and we're removing that from the component (and ultimately working towards retiring the title component). Note that this does not include the HTML publication pages as this is handled in a separate PR: https://github.com/alphagov/government-frontend/pull/3534
Pages where we're …
> Remove margin tops and replace titles with headings

- app/views/content_items/worldwide_corporate_information_page.html.erb
- app/views/content_items/worldwide_office.html.erb
- app/views/content_items/worldwide_organisation.html.erb
- app/views/content_items/worldwide_organisation/_header.html.erb
- test/integration/worldwide_organisation_test.rb
Add the page title as an H1 on worldwide organisation pages
|Before|After|
|-|-|
|<img width="995" alt="Screenshot 2025-01-17 at 14 59 20" src="https://github.com/user-attachments/assets/fada8b04-2d31-453e-a802-9cc860b50ffa" />|<img width="1100" alt="Screenshot 2025-01-17 at 14 58 02" src="https://github.com/user-attachments/assets/1580a802-2399-4669-81e8-605241fd60bc" />|
Old behaviour: The logo is wrapped in an H1
New behaviour: Logo is not wrapped in an H1, new H1 is added beneath containing page title
Review apps:
- [British Embassy Madrid](https://government-frontend-pr-3510.herokuapp.com/world/organisations/british-embassy-madrid)
- [British Embassy Abu Dhabi](https://government-frontend-pr-3510.herokuapp.com/world/organisations/british-embassy-abu-dhabi)
- [Department for Business …
> Display an H1 of the page title of all worldwide org pages

- app/views/content_items/worldwide_organisation.html.erb
Routes in this application are being migrated to another application, please check with #govuk-patterns-and-pages when making changes.
This PR fixes a [Sentry error](https://govuk.sentry.io/issues/5249728298/?environment=integration&environment=integration-blue-aws&environment=integration-eks&environment=staging&environment=staging-eks&project=202226&project=202213&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=0&utc=true)
[In …
> Fix Sentry error "undefined method `any?' for nil"

- app/controllers/content_items_controller.rb
- app/helpers/contents_list_ab_testable.rb
- app/views/content_items/guide.html.erb
- test/controllers/content_items_controller_test.rb
For users allocated a variant B cookie on some Step-by-Step guides:
- Add a contents list, plus the following associated features which are always present when a contents list is shown:
- Show the page title above contents list
- Add chapter title below contents list
- Add pagination component and bottom of the page
|**Variant A or Z** (control no contents list) | **Variant B** (with contents list)|
|--|--|
|<img width="1112" alt="Screenshot 2025-02-10 at 12 32 24" src="https://github.com/user-attachments/assets/dc1cae52-981a-4602-a8f2-095f6bf3d2a7" />|<img width="1065" alt="Screenshot 2025-02-10 at 12 32 10" src="https://github.com/user-attachments/assets/25e0e3fa-599d-4a17-a73e-2c53b29e59fd" />|
[Help paying for childcare](https://government-frontend-pr-3551.herokuapp.com/help-with-child …
> Add AB test for Contents list

- app/assets/stylesheets/components/_banner.scss
- app/views/components/_banner.html.erb
- app/views/components/docs/banner.yml
- app/views/content_items/call_for_evidence.html.erb
- app/views/content_items/consultation.html.erb
- test/components/banner_test.rb
Fix some of the tech debt in the banner component and update the docs to reflect how it is now used on gov.uk. 
We decided to remove the large text variant where when only text is provided, the font size gets increased. This is because the variant isn't being used anywhere at the moment. (We're generally trying to reduce complexity in apps, instead of adding further unnecessary options; there's also been some discussion about how the gem inverse header component could in the future be made more flexible and replace this banner component so we want to make that easier where possible instead of bloating the app component.)
The changes are probably easiest to review commit by commit.
There is a minor change to the design regarding the padding (see …
> Update banner component to reflect current usage

- app/helpers/date_time_helper.rb
- app/presenters/call_for_evidence_presenter.rb
- app/presenters/consultation_presenter.rb
- app/presenters/content_item/last_updated.rb
- app/presenters/content_item/manual.rb
- app/presenters/content_item/manual_section.rb
- app/presenters/content_item/updatable.rb
- app/presenters/content_item/withdrawable.rb
- app/presenters/content_item_presenter.rb
- app/presenters/html_publication_presenter.rb
- app/presenters/specialist_document_presenter.rb
- app/presenters/speech_presenter.rb
- test/presenters/content_item/manual_test.rb
- test/presenters/content_item/metadata_test.rb
- test/presenters/content_item/updatable_test.rb
- test/presenters/content_item/withdrawable_test.rb
There are duplicate code where display date is used (e.g. consultation and call for evidence). We also currently have a hard set reliance on the content item presenter to use date displays. Extracting this to a helper module will allow us to remove that coupling. 
Additionally, there are stubs of the method all over tests which means tests are not testing actual values. Have removed some of this stubbing. 
Routes in this application are being migrated to another application, please check with …
> Extract display date and time methods to a helper

- app/presenters/specialist_document_presenter.rb
- test/presenters/specialist_document_presenter_test.rb
Any facet that is a sub facet needs to be rendered with a label in the format "[main facet] - [sub facet]". The link also needs to include the main facet as part of query params in addition to the sub facet. The linked main facet label and value is passed through in the finder schema via allowed values as illustrated in the test.
https://trello.com/c/4RJusHld/3374-nested-facets-add-new-document
Routes in this application are being migrated to another application, please check with …
> Add rendering for Sub Facet value and sub facet link

- app/views/content_items/html_publication.html.erb
- we recently swapped out the title component (which displays a H1) with the heading component (which defaults to a H2)
- but forgot to explicitly tell the heading component to render a H1
- this fixes that, restoring the title of HTML publications to a H1
Example HTML publication: https://www.gov.uk/government/publications/govuk-proposition/govuk-proposition
None.
> Restore HTML publication H1s

- .github/pull_request_template.md
It's easy to miss this line, and we want avoid clashes with teams making changes in government-frontend and routes being migrated to frontend.
Routes in this application are being migrated to another application, please check with #govuk-patterns-and-pages when making changes.
> Make contacting patterns and pages team bold

- Gemfile.lock
Update to the latest version of `govuk_publishing_components`.
Dependabot doesn't seem to be picking this up for some reason.
> Bump to latest govuk_publishing_components

- Gemfile.lock
Reverts alphagov/government-frontend#3582
https://trello.com/c/Eh88hfrm/80-list-numbers-appearing-in-legislative-lists
Preview link to example page: https://government-frontend-pr-3587.herokuapp.com/guidance/immigration-rules/immigration-rules-introduction
Reverting the change gets the required govspeak styles back: https://github.com/alphagov/govuk_publishing_components/pull/4623/files#diff-0350534e53a36a1c1df873d5e970890c05adc557c38c023285f608dcc6a34792L22-L25
> Revert "Bump to latest govuk_publishing_components"

- app/presenters/publication_presenter.rb
- test/integration/publication_test.rb
- test/presenters/publication_presenter_test.rb
The publications will be linked to from mobile. We don't want them being indexed by search engines as they should be solely consumed by users of the GOV.UK mobile app.
https://govukverify.atlassian.net/jira/software/c/projects/GOVUKAPP/boards/616?selectedIssue=GOVUKAPP-1300
____
> [GOVUKAPP-1300] Add noindex metatag to mobile specific pages

- test/test_helper.rb
- the verbose output of the test suite makes it very hard to find small numbers of failures. Adding this config option shows the failures again at the end, a la RSpec
____
> Add failure summary to test reporter

- app/presenters/publication_presenter.rb
- test/integration/publication_test.rb
- test/presenters/publication_presenter_test.rb
> Correct GOV.UK app noindex url

- app/presenters/specialist_document_presenter.rb
- test/integration/specialist_document_test.rb
- test/presenters/specialist_document_presenter_test.rb
The backend has been remodelled so that it sends a single facet with a nested structure through (and of type "nested"), as opposed to two distinct type "text" facets marked as "nested". That nested facet logic was originally introduced in commit 3e9785c3 / PR https://github.com/alphagov/government-frontend/pull/3574.
These changes adjust the extraction logic, but preserve the behaviour:
- the labels read "Main Facet - Sub Facet"
- the sub-facet links include the Main Facet value.
The `sub_facet_key` and `sub_facet_name` are still sent along, as well as the `main_facet_label` and `main_facet_label` references in the sub-facet, so the only required change is to duplicate the call to the `friendly_facet_value` for the sub-facet key. …
> Change nested facet lookup logic

- app/presenters/specialist_document_presenter.rb
- app/views/content_items/specialist_document.html.erb
- test/integration/specialist_document_test.rb
This change will make rendering the blue metadata box at the top of specialist documents dependent on a value defined in the schema of each finder. 
Specialist publisher frontend rendering may be eventually moved to alphagov/frontend, at the moment that only applies to [license specialist documents](https://www.gov.uk/find-licences/licence-to-abstract-and-or-impound-water-northern-ireland). The approach to this feature should be broadly the same, so eventually migrating over there shouldn't be too arduous. 
The tests in this PR are dependent on example schemas in the publishing API repo and so may brake CI until that is merged. 
**Associated PRs**
1.[ Publishing-API](https://github.com/alphagov/publishing-api/pull/3241)
2. [Specialist-Publisher …
> Make blue metadata box optional

- app/presenters/consultation_presenter.rb
- app/views/content_items/consultation.html.erb
Restore the spacing between the summary banner and notice components on consultation pages as discussed with a designer.
To align with design feedback and to visually separate the components.
We've got some cards in our backlog to review the layout of these pages as it's possible that some of the components used (notice/summary banner/metada) should be consolidated to improve the information hierarchy on consultations. 
[Trello](https://trello.com/c/piJlXt43/3356-fix-issue-on-consultations-and-statistics-announcements-where-notice-and-metadata-components-dont-have-spacing-between-them-m)
____
Follow [these …
> Use default spacing between notice and banner components on consultations

- app/views/shared/_email_subscribe_unsubscribe_flash.html.erb
Update success_alert component spacing
- `margin_bottom: 0` was causing the component to sit in top of the heading component without any white space to between them, by removing this we can rely on the default margin-bottom set by the design system
- `govuk-!-margin-top-3` was adding extra space between the component and breadcrumbs component
Previous PR showing expected spacing: https://github.com/alphagov/government-frontend/pull/2306
| --- | --- |
| <img width="370" alt="Screenshot 2025-04-11 at 11 23 28" src="https://github.com/user-attachments/assets/afd5807b-b805-41a7-ab86-cb74b8fb3091" /> | <img width="368" alt="Screenshot 2025-04-11 at 11 24 48" src="https://github.com/user-attachments/assets/eb2047c1-3d02-4e18-b5f2-eb0313334070" /> |
| --- | …
> Update success_alert component spacing

- app/presenters/content_item/metadata.rb
- app/presenters/content_item/updatable.rb
- test/presenters/content_item/metadata_test.rb
____
This removes the see all updates link in two scenarios:
1. On stats announcement pages where the announcement has been cancelled
2. On standard content items where there are no previous updates.
We are removing the links since it is strange to have the link if there is no section the page can link to. It could be confusing for the user that the link does nothing and seem like a bug.
[Trello card](https://trello.com/c/2RemO0mt/3403-hide-see-all-updates-unless-there-is-a-change-history)
> Hide updates link

- app/presenters/content_item/attachments.rb
- test/presenters/content_item/attachments_test.rb
- test/presenters/publication_presenter_test.rb
After the new /csv-preview url is available, we need to update government-frontend to use this new link on the document page.
Trello card: https://trello.com/c/6w8WHMeX/3482-update-government-frontend-to-use-the-new-csv-preview-url
This is a recreation of [the PR originally created by @richardTowers](https://github.com/alphagov/government-frontend/pull/3434), as there were some issues with actionlint in the previous PR.
>  Use new-style csv preview links for attachments

- app/presenters/content_item/attachments.rb
- test/presenters/content_item/attachments_test.rb
- test/presenters/publication_presenter_test.rb
We want to make the code that sets the preview url for csv attachments consistent with the routes that render that preview. https://github.com/alphagov/frontend/blob/main/config/routes.rb#L81 This is for improving readability of the code and making this logic easier to understand.
Trello card: https://trello.com/c/ldz6xMOx/2042-refactor-government-fronted-logic-https-githubcom-alphagov-government-frontend-pull-3702
____
Follow …
> Improve the code on setting csv attachments preview url

- test/presenters/call_for_evidence_presenter_test.rb
Related PR - https://github.com/alphagov/publishing-api/pull/3405
Trello card: https://trello.com/c/GzNmv0Ag/647-move-callforevidence-from-government-frontend-to-frontend
____
> Fix base paths in call for evidence tests

- app/views/content_items/call_for_evidence.html.erb
- app/views/content_items/consultation.html.erb
- gem classes were being applied to p tags and then inserted into the summary banner component
- arguably okay, but it triggered a warning in the component auditing
- turns out that not applying these classes makes no visual difference, so removing them
- can be seen on pages like https://www.gov.uk/government/calls-for-evidence/the-tax-treatment-of-carried-interest-call-for-evidence (except not on that one, it only shows up where the `held_on_another_website` logic is triggered to include the extra paragraph, can't find a wild example of that but easy enough to fake locally)
None. Well, almost none. If you …
> Remove unnecessary classes

- config/locales/zh-tw.yml
> fix: chinese closing bracket rather than latin at the end of the zh-tw language name

- app/presenters/worldwide_organisation_presenter.rb
Use the [dig method](https://apidock.com/ruby/Hash/dig) in the `WorldwideOrganisationPresenter` to return `nil` if any intermediate step is `nil`.
To fix `undefined method [] for nil (ActionView::Template::Error)`, this happens because we are trying to access `url` and `alt_text` from a nil value (`image`)
Example page: https://www.gov.uk/world/organisations/british-high-commission-barbados
| --- | --- |
| <img width="1081" height="1264" alt="desktop-before" src="https://github.com/user-attachments/assets/f9a770ea-c18d-4ea9-9b55-884d5d5a1fd1" /> | <img width="1034" height="1034" alt="desktop-after" src="https://github.com/user-attachments/assets/7e6f1320-9460-48cc-9bd4-2499da62460b" /> |
> Fix `undefined method [] for nil (ActionView::Template::Error)`

- Gemfile.lock
> Bump govuk_web_banner to 0.13.1
