alphagov/government-frontend

app/views/content_items/unpublishing.html.erb

https://www.agileplannerapp.com/boards/105200/cards/5814
Addresses line 23 of the spreadsheet of copy changes for that ticket.
Part of a group of two pull requests for same issue:
- https://github.com/alphagov/whitehall/pull/1932
- https://github.com/alphagov/government-frontend/pull/16

Copy change unpublished page

---

app/presenters/content_item_presenter.rb
app/views/content_items/case_study.html.erb
test/models/content_item_presenter_test.rb

I based this upon the code which currently does it in Whitehall:
https://github.com/alphagov/whitehall/blob/b1f827a2daa1df50cf69785af6827a621857e815/app/helpers/document_helper.rb#L205-L247
~~Note that the code in Whitehall has many more fields in it, but these aren't
currently sent to content-store. I think this may be based upon an assumption
that Case Studies only have the fields currently being sent to content-store.~~
~~Are there any other "part of" fields which do in fact appear for Case Studies?~~ 
Note: the tests are currently failing on an unrelated pre-existing failure that @danielroseman is working on.

Display the "part of" metadata

---

app/presenters/content_item_presenter.rb
test/models/content_item_presenter_test.rb

Case Studies can have Worldwide Organisations, so we should display them.
The test failure is an unrelated pre-existing one already happening on master.

Add Worldwide Organisations to "From" metadata

---

test/support/govuk_content_schema_examples.rb

The government-frontend does not (yet) support the 'coming_soon' format.
Only attempt to run contract tests for formats which we currently
support.
As we evolve the contract testing approach, we may want to develop a
convention for frontends to declare which formats they support. For now
it seems reasonable to hard code it.

Only run contract tests for specific formats

---

Gemfile
Gemfile.lock
config/application.rb

Use the [`rails_translation_manager`](https://github.com/alphagov/rails_translation_manager) gem to support workflow around translating page furniture (export translations to CSV, import from CSV).
https://trello.com/c/PLRk2VJL/27-add-support-for-loading-translations-to-government-frontend

Use translation manager gem

---

jenkins-schema.sh

Whenever a change is made to govuk-content-schemas we run the examples
against government-frontend to ensure that it still supports all of the
examples.
This will occur for branch builds as well.
This jenkins script provides a way to build the examples. It's
parameterised using the GIT_COMMIT of the schemas, so that it can be
tested against a particular branch or sha ref of the schemas.
https://trello.com/c/nmSJPc9Z/4-setup-ci-job-for-govuk-content-schemas

Support contract testing in jenkins

---

app/views/layouts/application.html.erb

This was triggering an unnecessary HTTP request which would return a 404.
I believe application.js was never in the project as it was generated without
it. See: 8bab8603055e2341a01c91c1df127d2a26520241

Remove unnecessary application.js tag

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/views/_coming-soon.scss
app/controllers/content_items_controller.rb
app/presenters/coming_soon_presenter.rb
app/views/content_items/coming_soon.html.erb
test/controllers/content_items_controller_test.rb
test/presenters/coming_soon_presenter_test.rb
test/support/govuk_content_schema_examples.rb

Coming Soon content items are used for scheduled publishing. It is important in
scheduled publishing that all users see the new version as quickly as possible.
For content that is replacing existing content, this is easy: we simply wind in
the cache headers leading up to the publish time. For new content, this is
harder, because our stack doesn't respect the cache time for HTTP responses
with the 404 status. So instead, we return a 200 status and display a "Coming
Soon" page with the same cache header winding.
Whitehall:
government-frontend:

Support Coming Soon content items

---

app/presenters/content_item_presenter.rb
test/presenters/content_item_presenter_test.rb

https://trello.com/c/pfvFRgg5
Currently, document collection membership is not shown next to 'Part of:' in the metadata section in the header or footer as shown here: https://www.gov.uk/government/case-studies/clever-engineering-macrete-bridges-the-technology-gap

Show document collections edition belongs to

---

app/views/content_items/case_study.html.erb

Fix issue with title size, noted in alphagov/whitehall#2032 (cc @dsingleton)

Use 'long' title format.

---

app/views/content_items/case_study.html.erb

A large number of case studies contain the boolean value "false" as the image caption, and this was displaying underneath the picture. This change just hides that value; a separate change to Whitehall will be needed to ensure no value is sent to content-store if there is an empty caption.

Don't show caption if it is false.

---

app/views/shared/_available_languages.html.erb

This gives a relative path which will work on all environments, and is consistent with what we use for all other links.

Use base_path not web_url in translation links.

---

jenkins-schema.sh

After rake was updated from 10.3.2 to 10.4.2, the schema build, which runs the
jenkins-schema.sh script started to fail:
```
+ time bundle exec rake test:contracts --trace
** Invoke test:contracts (first_time)
** Invoke test:prepare (first_time)
** Execute test:prepare
** Execute test:contracts
invalid option: --trace
```
minitest is complaining that it doesn't know about --trace, but that argument
is meant for rake.
This seems to be related to changes in Rake regarding the editing of ARGV in
Rake: https://github.com/ruby/rake/blob/master/History.rdoc
Rather than downgrade Rake, this change removes the option that is triggering
the bug.
/cc @danielroseman @tommyp

Fix schema build

---

app/presenters/content_item_presenter.rb
test/presenters/content_item_presenter_test.rb

Draft ContentItems that have never been published will not have a
first_public_at date in their details; previously the presenter was
choking in this case.

Prevent exception if item has no first_public_at.

---

app/assets/stylesheets/views/_case-studies.scss
app/presenters/content_item_presenter.rb
app/views/content_items/case_study.html.erb

This updates the display of previously "archived" content to be labelled as
"withdrawn", to be consistent with the retention policy guidance:
https://www.gov.uk/guidance/content-design/gov-uk-content-retention-and-withdrawal-archiving-policy.
It also updates the presenter code accordingly. Separate work will have to
happen to update the schema and migrate the existing content to use the term
"withdrawal" instead or "archive" in the content items themselves.
BEFORE:
AFTER:
The corresponding changes in whitehall are here: https://github.com/alphagov/whitehall/pull/2197
Part of: https://trello.com/c/nhvXmcY9/127-changing-archiving-to-withdrawing-in-whitehall-and-on-frontend

"Archived" content is now "Withdrawn"

---

app/presenters/content_item_presenter.rb

Whitehall has been updated to refer to withdrawing documents rather than
archiving them. This enables content to be sent to the content store
with either withdrawn or archived state. Once all the content in the
content store has been updated this can be changed to only handle
withdrawn documents.
This is the matching change for this schema pull request: https://github.com/alphagov/govuk-content-schemas/pull/79

Handle withdrawn or archived content items

---

app/presenters/content_item_presenter.rb

The migration to withdrawn has been complete so we no longer need to
support archived case studies.

Case studies are withdrawn rather than archived

---

Gemfile
Gemfile.lock

This changes the user agent to include the app
name in API requests.
https://trello.com/c/qkHdtob4/247-bump-gds-api-adapters-everywhere-it-s-used-to-include-user-agent-information

Bump gds api adapters

---

bin/bundle

I was suprised that `bin/bundle` uses Ruby 1.9.1 whereas `.ruby-version`
specifies Ruby 2.1.4. I noticed this because I don't have a `ruby1.91`
executable in my path on my Mac.
Looking at alphagov/contacts-frontend and alphagov/manuals-frontend,
both of those applications specify `/usr/bin/env ruby` in their
`bin/bundle` stubs. This makes more sense to me, since `/usr/bin/env
ruby` will invoke the Ruby version set in `.ruby-version` via rbenv:
matt➜~/govuk/government-frontend(bundle_ruby_version✗)» /usr/bin/env ruby --version
ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-darwin13.0]
matt➜~/govuk/government-frontend(bundle_ruby_version✗)» cat .ruby-version
2.1.4
matt➜~/govuk/government-frontend(bundle_ruby_version✗)»

Don't specify Ruby 1.9.1 in Bundler bin stub

---

app/views/layouts/application.html.erb

The component name has been changed to make it slightly more generic.
This needs reflecting here.

Update name of component

---

config/locales/en.yml

Changes to bring label in line with the style guide, following feedback from the Content team.
https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#statistics
/cc @boffbowsh

Capitalising Official and National [S]tatistics

---

jenkins.sh

This is to make sure that the assets can be built before the application
goes out to production.

Run asset precompile as part of CI tests

---

app/presenters/service_manual_guide_presenter.rb
app/views/content_items/service_manual_guide.html.erb
test/presenters/service_manual_guide_presenter_test.rb

We had a couple of placeholders on the guides page. Real data is being published now, so we can display it on the page.

Use real data when rendering service manual frontend guides

---

app/controllers/content_items_controller.rb
app/presenters/case_study_presenter.rb
app/presenters/coming_soon_presenter.rb
app/presenters/content_item_presenter.rb
app/presenters/service_manual_guide_presenter.rb
app/presenters/unpublishing_presenter.rb
test/presenters/case_study_presenter_test.rb
test/presenters/content_item_presenter_test.rb

Content item presenter was used to render `CaseStudy` format and had a lot of logic that's specific to this format. In order to make `ContentItemPresenter` useful for rendering other content types, I've extracted generic functionality to `ContentItemPresenter` and moved all case-study-specific functionality to a new `CaseStudyPresenter` class. Then I've made other presenters inherit from `ContentItemPresenter` to remove logic duplication.
__Note: this affects case studies, "unpublishing" pages, coming soon pages and service manual guides.__ It would be nice to thoroughly review the changes in case I've broken anything (I'm not familiar with formats other than Service Manual Guide).
This refactoring has been triggered by a discussion in #66. Once this is merged I'll reintroduce the change …

Base presenter

---

Gemfile
Gemfile.lock
app/helpers/phase_label_helper.rb
app/presenters/content_item_presenter.rb
app/views/layouts/application.html.erb
test/integration/phase_label_test.rb
test/test_helper.rb

If a content item responds to `#phase` and it has a value of either 'alpha' or 'beta' render a component with the corresponding label. ~~Currently only Service Manual Guide presenter responds to `#phase` so only this format will be affected. I chose to not expose `phase` in ContentItemPresenter (used by Case Studies atm), because I don't know if the team that owns this format expects the `phase` field value to trigger this feature.~~
~~I'm not particularly happy with the helper test: Rails helpers fail when `render` is invoked on them in test environment. The default Rails test does not have tools for stubbed expectations, so I ended up overwriting `render` method in the test class to serve my purpose.~~
~~Alternatives I can think of: do not use a helper, just have a conditional in the …

Render phase labels

---

app/controllers/content_items_controller.rb
test/controllers/content_items_controller_test.rb
test/integration/phase_label_test.rb

We're deploying service manual publisher to production and it no longer makes
sense to have this feature-flagged.
We're not planning to publish any content yet, but we will need preview
functionality on the draft stack.

Enable service manual guide rendering, remove feature flag

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/helpers/_description.scss
app/assets/stylesheets/helpers/_responsive-bottom-margin.scss
app/assets/stylesheets/helpers/_sidebar-with-body.scss
app/assets/stylesheets/views/_case-studies.scss
app/assets/stylesheets/views/_take-part.scss
app/controllers/content_items_controller.rb
app/presenters/case_study_presenter.rb
app/presenters/take_part_presenter.rb
app/views/content_items/case_study.html.erb
app/views/content_items/take_part.html.erb
app/views/shared/_description.html.erb
app/views/shared/_sidebar_image.html.erb
app/views/shared/_sidebar_with_body.html.erb
config/locales/en.yml
test/presenters/case_study_presenter_test.rb
test/presenters/take_part_presenter_test.rb
test/support/govuk_content_schema_examples.rb

https://trello.com/c/P1IYhe0C/242-take-part-migrate-front-end-work-large
* Add Take Part template, styles and presenter
* Use `format` rather than `format_display_type` for gathering title context
* Copy markup patterns from case study where similar/the same
* Don’t port the strange “underline” take part headings, the take part contents are purposefully left out, and the description has been moved above the image to match other formats.
* Extract styles and markup common to Case Studies and Take Part into partials and mixins
* When an image is omitted it will show a generic government placeholder image
cc @dsingleton @boffbowsh @benlovell @gpeng

Render "Take part" format

---

test/controllers/content_items_controller_test.rb
test/integration/phase_label_test.rb
test/presenters/case_study_presenter_test.rb
test/presenters/coming_soon_presenter_test.rb
test/presenters/service_manual_guide_presenter_test.rb
test/presenters/take_part_presenter_test.rb
test/presenters/unpublishing_presenter_test.rb

As per @benlovell's [comment](https://github.com/alphagov/government-frontend/pull/75#discussion-diff-50845288R109) on PR #75, they're not worth using in tests.

Remove access modifier in tests

---

config/environments/production.rb

To bring this more in line with 12-facgtor principals, this changes the
logging to go to STDOUT(json), and STDERR(everything else).
Precedent: https://github.com/alphagov/publishing-api/pull/109
Needed Puppet change: https://github.com/alphagov/govuk-puppet/pull/3998

Log to STDOUT and STDERR in production mode.

---

app/assets/stylesheets/views/_service-manual-guide.scss
app/views/content_items/service_manual_guide.html.erb

Use the component because it has support for automatic youtube video link
embedding. It modifies the styling of text slightly, which is not ideal, but we
decided it's better than overwriting the components styles.
The long term plan is to list the discrepancies and update the component with
improvements that have been discovered through Service Manual user research.
[Compare. Left: Before. Right: After.](https://cloud.githubusercontent.com/assets/218239/12582503/7b16c5d6-c435-11e5-99d0-fd774309a372.png)

Use GOV.UK Govspeak component for rendering SM guide body

---

test/integration/case_study_test.rb
test/integration/statistics_announcement_test.rb
test/integration/take_part_test.rb
test/test_helper.rb

Government Frontend already has _some_ [integration tests](https://github.com/alphagov/government-frontend/blob/master/test/contracts/govuk_content_schemas_test.rb), that ensure none of the content examples for supported formats return a non-200. This gives some coverage, but when working on Statistics Announcement @binaryberry and I felt that we were missing proper integration coverage, and that it was hard to approach adding a format by TDD.
This PR adds integration tests that be run per format/example, specifically asserting the behaviour of the different examples. The commits show a slight evolution of how I approached this, so read them if you want to know the decisions leading to the overall diff.
I've added some quite basic tests for Take Part and Case Study to illustrate usage, …

Add per example integration testing

---

app/assets/stylesheets/views/_statistics_announcement.scss
app/presenters/statistics_announcement_presenter.rb
app/views/content_items/statistics_announcement.html.erb
test/integration/statistics_announcement_test.rb
test/presenters/statistics_announcement_presenter_test.rb

This applies when a 'confirmed' announcement has it's release date
edited, which should not normally happen. When it does it must be
disclosed, and the reason explained.
In WH this disclosure is done as a separate headed section, with
a second 'metadata'-style block to format the date and reason.
Long term this may not be the right pattern for the page, and may
be consolidated into the main metadata block, or otherwise be
made more consistent with other document formats.
To get the feature migrated in the short term i've included a second
call to the metadata component, which causes some complexity in the
integration test, where there is now two metadata components when
asserting. In order to avoid the conflict, i've scoped the metadata
asserts for the `release_date_changed` example only, …

Support Statistics announcements with changed date

---

test/presenters/statistics_announcement_presenter_test.rb

Flagged in https://github.com/alphagov/government-frontend/pull/85
Searching Github @alphagov uses `refute` exclusively, the only result for
`assert_not` is the instance being removed here.
[1] https://github.com/search?q=refute+%40alphagov&ref=searchresults&type=Code&utf8=%E2%9C%93
[2] https://github.com/search?utf8=%E2%9C%93&q=assert_not+%40alphagov&type=Code&ref=searchresults

Use 'refute' instead of 'assert_not' in tests

---

app/helpers/typography_helper.rb
app/views/shared/_description.html.erb
test/helpers/typography_helper_test.rb

Stop widows by putting a `&nbsp;` between the last two words in a description

Prevent widows in descriptions

---

app/assets/stylesheets/helpers/_notice.scss
app/views/content_items/case_study.html.erb

👀   &nbsp;   **[Before, after and diff of affected pages](https://dl.dropboxusercontent.com/u/262911/government-frontend-notice-spacing/index.html)** &nbsp;  👀
The mixin that powers both of these had poor padding of elements
inside the blue box, and between the title and p/govspeak.
Use standard gutters, tweaked for smaller screens to match spacing
on smaller devices. Use the responsive margin mixin to ensure the
space following the notice looks even compared to other parts of
the page.
Tweak the HTML for case studies, as the notice appeared between
grid columns, but not marked up as a column, so in single-column
(mobile) mode it clung to the edge of the page. Instead, break it
out in to it's own grid row, as it is for statistics announcement
and it will flow to the edge of the grid …

Improve whitespace on withdrawn/cancelled notices

---

app/helpers/typography_helper.rb
test/helpers/typography_helper_test.rb

To add a `nbsp` we need to return an html_safe string, but we shouldn’t assume there’s no unsafe HTML in the text passed through.
* Strip whitespace, escape the HTML then add the non-breaking space and mark as html_safe.
This addresses @dsingleton's feedback from the already merged #88 
cc @jamiecobbett

Escape HTML before preventing widows

---

app/presenters/service_manual_guide_presenter.rb
test/presenters/service_manual_guide_presenter_test.rb

As a part of an effort to reference everything using content_ids allow
Service manual guides to use information about the service manual guide content
owner from the links hash (see [1]) but fall back to the old way when the links
hash is not present.
This will allow us to migrate to the new format without breaking anything.
The fallback code should be removed once the migration process is complete.
[1] - https://github.com/alphagov/govuk-content-schemas/pull/219

Fetch content owner info from the links hash

---

Gemfile.lock

1.6.0 was yanked from ruby gems, see:
https://github.com/alphagov/whitehall/pull/2464

Downgrade rack-cache

---

app/helpers/phase_label_helper.rb
app/views/content_items/service_manual_guide.html.erb
app/views/layouts/application.html.erb
test/integration/phase_label_test.rb

Using the phase label helper, set the message for service manual guide pages. 
http://govuk-component-guide.herokuapp.com/components/beta_label
cc. @dsingleton.

Customise the phase banner message for service manual guides

---

Procfile
app.json

With this change we can enable [Review Apps](https://devcenter.heroku.com/articles/github-integration-review-apps). This allows new Heroku apps to be automatically created for each PR, allowing us to preview the changes against data from the live content store.
I'll enable Review App creation by default, which will result in all PRs gaining something like this comment:
> boffbowsh deployed to government-frontend-pr-97 25 minutes ago

Enable Review Apps for Heroku

---

Gemfile.lock

1.6.0 has been yanked:
https://rubygems.org/gems/rack-cache/versions/1.6.0

Upgrade rack-cache to 1.6.1

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/helpers/_metadata.scss
app/assets/stylesheets/views/_case-studies.scss
app/assets/stylesheets/views/_statistics_announcement.scss

Depends on https://github.com/alphagov/static/pull/730 being deployed.
* Metadata bottom margin is provided by component
* Document footer bottom margin is provided by component

Remove margin styles now in components

---

app/assets/stylesheets/application.scss

The `@imports` were ordered alphabetically but, while it didn't error due to the lazy evalulation of `@mixin`, we lost some meaning because "helpers/responsive-bottom-margin" was a dependency of some of the other helpers.
/cc @fofr

Revert the reordering of the SASS helper imports

---

app/views/content_items/service_manual_guide.html.erb

It doesn't actually link anywhere.

Remove empty #last_updated link in service manual guide

---

app/assets/stylesheets/views/_service-manual-topic.scss
app/assets/stylesheets/views/_service-manual.scss

- Use the $gutter variables from the front end toolkit
- Add a margin at the bottom of the main content area
- Reduce the bottom margin for lede text at smaller screen widths
- Increase the spacing between list items for page contents
cc. @AndrewVos, @thehenster.

Service manual frontend improvements

---

app/assets/stylesheets/views/_service-manual-topic.scss

This is causing the lead paragraph to sit too far below the title. Removing
this additional margin fixes this.
Before:
After:
cc. @fofr.

Remove extra spacing above lede text

---

app/assets/stylesheets/views/_service-manual-topic.scss

The text on Service Manual topic pages is too small.
Increase the size of titles to 24px, ensure all body text is 19px.
Increase the bottom margin between subsections.
Before:
After:
cc. @AndrewVos @thehenster.

Increase font sizes for Service Manual topic pages

---

jenkins.sh
lib/tasks/lint.rake

This should help us stop committing code that will fail the linter under CI.

Run the ruby and sass linters when the default rake task is run

---

app/presenters/service_manual_guide_presenter.rb
app/views/content_items/service_manual_guide.html.erb
test/integration/service_manual_guide_test.rb
test/presenters/service_manual_guide_presenter_test.rb

A bit of to-ing and fro-ing here but this basically the same functionality reimplemented. Content owners can exist in the details or the links but with a preference for the links.
Once all guides have been republished we can remove the code that is trying to find the content owners in the details.

Reimplement content owners for service manual guides

---

app/helpers/typography_helper.rb
test/helpers/typography_helper_test.rb

Descriptions can be null, so we need to handle that. Here's where that's
defined in the schema:
https://github.com/alphagov/govuk-content-schemas/blob/master/formats/metadata.json#L20-L29

Handle nil descriptions

---

config/locales/plurals.rb

This fixes broken rake tasks relating to translations (e.g. rake translation:regenerate)
and should ensure proper rendering of plurals for languages not included in rails-i18n.
There is a non ISO 639-1 code 'dr' which has been used for the
Dari (Afghan Persian) language. This matches the locale used in Whitehall but
should probably be 'prs' as per the ISO 639-3 standard.
All of the additional rules have been set to one/other to match the
available translations in the respective locale files.
[Trello](https://trello.com/c/QKxvrTLP/309-fix-translation-workflow-on-government-frontend)

Add missing pluralization rules

---

app/presenters/service_manual_guide_presenter.rb
app/views/content_items/service_manual_guide.html.erb
test/presenters/service_manual_guide_presenter_test.rb

public_updated_at only shows the last time an item had a "major" change.
For "minor" changes this timestamp is not touched. Instead, use the
"updated_at" field, which is a field that comes out of mongo directly.

Show correct publish time on guide pages

---

app/assets/stylesheets/views/_html-publication.scss
app/presenters/html_publication_presenter.rb
app/views/content_items/html_publication.html.erb
test/integration/html_publication_test.rb
test/presenters/html_publication_presenter_test.rb

This is part of migrating `html_publications` from `whitehall` to `government-frontend`.
Worth mentioning: in the presenter, organisations are sorted because the `content_item["links"]` are not guaranteed to come in a meaningful order.
Relevant Trello ticket: https://trello.com/c/cJGrtnc1/286-5-html-publications-migration-front-end-work-large
Looks like this:

Display the organisation logos in HTML publications.

---

test/controllers/content_items_controller_test.rb
test/integration/government_navigation_test.rb
test/test_helper.rb

The controller assertion assert_select doesn't have a `match:` argument and always passes no matter what the expected value. Replaced with an integration test to take advantage of #within.

Replace active government navigation test

---

app/presenters/html_publication_presenter.rb
app/views/content_items/html_publication.html.erb
test/integration/html_publication_test.rb
test/presenters/html_publication_presenter_test.rb

This will pass through the correct brand that the `organisation_logo` component in `static` expects in order to display the `executive-office` organisation correctly in HTML publications. More precisely, it will
trigger this class and its effects: https://github.com/alphagov/static/blob/500d2fafc7280ba5cc295b28b03c1e85fdf3e95a/app/assets/stylesheets/govuk-component/_organisation-logo.scss#L45.
This is a hack that should be removed once organisations are migrated to the content store.
Part of fixing this visual regression:
Relevant Trello ticket: https://trello.com/c/cJGrtnc1/286-5-html-publications-migration-front-end-work-large

Fix brand for executive office orgs in html pubs.

---

config/application.rb

Part of the addressing the final unintended changes introduced with migrating HTML publications in https://trello.com/c/cJGrtnc1/286-5-html-publications-migration-front-end-work-large.
This brings government-frontend in line with Whitehall with regards to how it handles missing translation keys.
Rails falls back to capitalising the key.
Rails uses the English translation, as on live Whitehall.

Turn on config.i18n.fallbacks.

---

app/assets/stylesheets/views/_html-publication.scss

Part of making HTML publications visually consistent with the previous Whitehall ones.
Relevant Trello ticket: https://trello.com/c/cJGrtnc1/286-5-html-publications-migration-front-end-work-large

Remove margin-bottom on .publication-header.

---

app/assets/stylesheets/views/_html-publication.scss
app/views/content_items/html_publication.html.erb
test/integration/html_publication_test.rb

Part of the addressing the final unintended changes introduced with migrating HTML publications in https://trello.com/c/cJGrtnc1/286-5-html-publications-migration-front-end-work-large.
This fixes the rendering for the header and the see more about link. Changes are grouped in this PR because they are very similar.

Improve HTML publications RTL rendering.

---

app/assets/stylesheets/mixins/_service-manual-related.scss
app/assets/stylesheets/views/_service-manual-topic.scss
app/assets/stylesheets/views/_service-manual.scss
app/helpers/service_manual_topic_helper.rb
app/views/content_items/service_manual_topic.html.erb
test/helpers/service_manual_topic_helper_test.rb
test/integration/service_manual_topic_test.rb

List the communities related to the guides included in a topic in the sidebar and invite visitors to join the community.
https://trello.com/c/rZlsL4Am/152-add-communities-sidebar-to-the-topic-pages
Related content schemas PR: https://github.com/alphagov/govuk-content-schemas/pull/277

Communities in service manual topic sidebar

---

app/assets/stylesheets/views/_topical-event-about-page.scss
app/assets/stylesheets/views/_working-group.scss
app/presenters/working_group_presenter.rb
app/views/content_items/working_group.html.erb
test/integration/working_group_test.rb

When an email is excluded it’s sent as an empty string in the content item, rather than being omitted. The template checks for `email.present?` but the contents logic doesn’t, which creates a discrepancy.
--
When using separate components the vertical rhythm of content could break. We apply special rules to the first element in govspeak, eg removing headings from the first H2.
The second govspeak component would remove the margin from the “Contact details” heading, so its content would appear closer to the body than it should.
Rather than wrap that content and give it some margin, concatenate the two bodies and pass to a single component.

Fix display of contact details on policy groups

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/helpers/_notice.scss
app/assets/stylesheets/helpers/_withdrawal-notice.scss
app/assets/stylesheets/views/_case-studies.scss
app/assets/stylesheets/views/_detailed-guide.scss
app/presenters/case_study_presenter.rb
app/presenters/detailed_guide_presenter.rb
app/presenters/withdrawable.rb
app/views/content_items/case_study.html.erb
app/views/content_items/detailed_guide.html.erb
app/views/shared/_withdrawal_notice.html.erb
lib/generators/format/format_generator.rb
lib/generators/format/templates/format_presenter_test.rb.erb
test/integration/case_study_test.rb
test/integration/detailed_guide_test.rb
test/presenter_test_helper.rb
test/presenters/case_study_presenter_test.rb
test/presenters/coming_soon_presenter_test.rb
test/presenters/detailed_guide_presenter_test.rb
test/presenters/html_publication_presenter_test.rb
test/presenters/statistics_announcement_presenter_test.rb
test/presenters/take_part_presenter_test.rb
test/presenters/topical_event_about_page_presenter_test.rb

See also https://github.com/alphagov/govuk-content-schemas/pull/288
* Extract withdraw presenter logic into module, use in case studies and detailed guides
* Add withdrawn presenter and integration tests for both formats
* Extract withdrawn template into re-usable partial
* Extract withdrawn styles into re-usable helper mixin
Includes some minor bug fixes:
* Fix margins on withdrawal notices
* Avoid an empty "Part of" from showing in metadata component (example has no links)
* Avoid an empty breadcrumb from showing (example has no parent)
* Update titles to use average length, so they appear smaller and match what's currently live
Includes some refactoring:
* Updates presenter tests to all extend PresenterTest – DRY up loading the content item example and presenting the example item, and …

Add withdrawn notice to detailed guides

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/helpers/_history-notice.scss
app/assets/stylesheets/views/_detailed-guide.scss
app/presenters/detailed_guide_presenter.rb
app/presenters/political.rb
app/views/content_items/detailed_guide.html.erb
app/views/shared/_history_notice.html.erb
test/integration/detailed_guide_test.rb
test/presenters/detailed_guide_presenter_test.rb

Depends on https://github.com/alphagov/govuk-content-schemas/pull/290 for passing tests.
* Create a mixin for history notice styles
* Create a partial for history notices
* Create a `Political` module for formats that can be political
* Add mixin, partial and module to detailed guides so that a blue “history mode” banner displays for political content published under a previous government.
Part of:
https://trello.com/c/74ymVfIw/384-6-detailed-guides-migration-front-end-work-for-history-mode-political-status-and-government-small

Add history notices to detailed guides

---

config/locales/fr.yml

- I can't think of any reason why « mise à jour » needs an extra space in it.

Remove an erroneous double space in a French translation string

---

app/presenters/detailed_guide_presenter.rb
app/views/content_items/detailed_guide.html.erb
test/integration/detailed_guide_test.rb
test/presenters/detailed_guide_presenter_test.rb

This implements a missing feature for the detailed guides migration.
Depends on https://github.com/alphagov/govuk-content-schemas/pull/300 for the tests to pass, I think.
cc @fofr

Display applicable nations for detailed guides.

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/helpers/_national_statistics_logo.scss
app/assets/stylesheets/views/_publication.scss
app/assets/stylesheets/views/_statistics_announcement.scss
app/presenters/case_study_presenter.rb
app/presenters/content_item_presenter.rb
app/presenters/linkable.rb
app/presenters/publication_presenter.rb
app/views/content_items/case_study.html.erb
app/views/content_items/detailed_guide.html.erb
app/views/content_items/publication.html.erb
app/views/content_items/statistics_announcement.html.erb
app/views/content_items/take_part.html.erb
app/views/shared/_national_statistics_logo.html.erb
lib/generators/format/templates/format.html.erb
test/integration/publication_test.rb
test/presenters/case_study_presenter_test.rb
test/presenters/content_item_presenter_test.rb
test/presenters/publication_presenter_test.rb

Depends on https://github.com/alphagov/govuk-content-schemas/pull/304 for passing tests
* Use `document_type` not `format` for title context on all formats. Publications have varying document types which need to be used as the context in the title component. For all formats without varying document types, the value of document_type will match format. Removes the old approach used by Case Studies (“format_display_type”)
* Protect against duplicate links appearing in `part_of` and `from`
* Include ministers in `from`
* Include related statistical data sets and topical events in `part_of`
* Show national statistics logo when document_type is national_statistics
Example based on https://www.gov.uk/government/statistics/affordable-housing-supply-in-england-2011-to-2012 …

Add further publication features

---

config/application.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb

This application doesn’t send email and probably never will. We can skip loading the ActionMailer framework so that the app loads faster and uses less memory.

Don't load ActionMailer framework

---

test/presenters/case_study_presenter_test.rb

Master is currently failing on CI because this test uses example data, which has recently changed. The reason that this wasn’t picked up in the PR on govuk-content-schemas is that CI doesn’t run all the tests for those builds. We will fix this in a separate PR.
cc @fofr

Make organisations test more robust

---

app/presenters/linkable.rb
test/presenters/case_study_presenter_test.rb

Currently the publishing-api contains link types `organisations`, `lead_organisations` and `supporting_organisations`. The leads and supporting orgs are only needed to put certain organisations at the front of the lists in the metadata.
In https://github.com/alphagov/govuk-content-schemas/pull/306 we changed the way this is modelled. This commit makes the frontend changes for that.
Can’t be merged/deployed before https://github.com/alphagov/whitehall/pull/2585 is deployed and all content from whitehall is republished.
Trello: https://trello.com/c/us3MI1n9/602-fix-organisation-tagging

Use `emphasised_organisations` to specify important orgs

---

jenkins-schema.sh
jenkins.sh
lib/tasks/testing.rake
test/test_helper.rb

Currently this app only runs a specific set of tests when triggered by a new PR on govuk-content-schemas. This tripped us up today because some tests that have been excluded are using the content schema examples in the tests (#147).
The tests for this repo are really fast, so it’s not a problem to run the entire test suite for each change on govuk-content-schemas. This will prevents test runs to pass by accident and makes the build process easier to understand.
This PR also updates `jenkins.sh` to be more modern.
@fofr

Run full suite of tests when contract testing on CI

---

jenkins-schema.sh

Because `INITIATING_REPO_NAME ` is not set in jenkins.sh (https://github.com/alphagov/government-frontend/blob/85e28836f873df4cdbcaf4b317eb42c67d2ce81a/jenkins.sh#L3), jenkins sends a message to GitHub about the wrong repository. This causes the gouk-content-schema branch tests to look like they’re not finished.

Fix jenkins status reporting back to GitHub

---

jenkins-schema.sh
jenkins.sh

So, argh. In previous commits I’ve changed the jenkins.sh to a more modern version, taken from the govuk_rails_template. This actually broke schema tests (because it always tested against
govuk-content-schemas/master, not the thing being tested).
This version is copied from collections-publisher, which currently works. I really hope that it works here too.

Change to a known-working version of jenkins.sh

---

app/presenters/html_publication_presenter.rb
app/views/content_items/html_publication.html.erb
test/presenters/html_publication_presenter_test.rb

- Use parent's `document_type` instead of `format_sub_type` key
- Organisation branding information is nested within the linked organisation's `details` hash

Use correct data for HTML Publications

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/views/_document-collection.scss
app/presenters/document_collection_presenter.rb
app/views/content_items/document_collection.html.erb
test/integration/document_collection_test.rb
test/presenters/document_collection_presenter_test.rb

Depends on https://github.com/alphagov/govuk-content-schemas/pull/312
* List each collection group with its ordered document list
* List the contents of the collection based on groups
* Generate an ID for each group heading, using hyphens to match the pattern in Whitehall and to keep existing fragment links working
* __List of each group’s documents is simpler than on Whitehall because document type and date are not easily available yet__
Include examples based on:
https://www.gov.uk/government/collections/national-driving-and-riding-standards
https://www.gov.uk/government/collections/financial-sanctions-regime-specific-consolidated-lists-and-releases
https://trello.com/c/PMeMQb5E/410-11-document-collection-migration-mvp-content-schema-examples-and-front-end-work

Add document collections format

---

app/assets/stylesheets/views/_document-collection.scss
app/presenters/document_collection_presenter.rb
app/views/content_items/document_collection.html.erb
config/locales/en.yml
test/integration/document_collection_test.rb
test/presenters/document_collection_presenter_test.rb

Relies on https://github.com/alphagov/govuk-content-schemas/pull/321
As part of https://trello.com/c/ZWU9N8Bc/414-add-missing-details-to-document-list-for-document-collection-format-medium
**Placeholder document_type is still an issue but if you run this with the examples you can check the render as below.**
Preview of update
----
Before:
After:
Small viewports:
Before:
After:
How to test
----
Using the govuk-puppet vagrant instance
```
cd /var/govuk/development
bowl government-frontend --without content-store
```
(Separate instance)
```
cd /var/govuk/govuk-content-schemas
bundle exec dummy_content_store
```
Open up http://government-frontend.dev.gov.uk/government/collections/national-driving-and-riding-standards
(You can compare against …

Add missing document list details

---

app/controllers/content_items_controller.rb
app/presenters/content_item_presenter.rb
test/presenters/content_item_presenter_test.rb

format sometimes matches the document_type. format is actually
deprecated now, so we should use schema_name when we mean schema_name.
/cc @steventux @danielroseman

Use schema_name instead of format

---

app/presenters/content_item_presenter.rb
app/views/content_items/detailed_guide.html.erb
test/integration/detailed_guide_test.rb

Part of migrating detailed guides.
Depends on https://github.com/alphagov/govuk-content-schemas/pull/337.
cc @nickcolley

Display translations for detailed guides if available

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/helpers/_back-to-content.scss
app/assets/stylesheets/views/_detailed-guide.scss
app/assets/stylesheets/views/_html-publication.scss
app/views/content_items/detailed_guide.html.erb
test/integration/detailed_guide_test.rb

Re-uses existing styles from `.html-publication .back-to-content`.
cc @nickcolley

Add .back-to-content link to detailed guide presenter

---

app/assets/stylesheets/helpers/_available-languages.scss
app/views/shared/_available_languages.html.erb

- Adds a margin to the bottom
- Fixes the top margin so it is inline with the govuk-title (this shouldn't be part of the component long term, since it ties it to the overall view)
- Updates styles so they're not using magic numbers and replace with gutters.
Before
After
- Check this branch (`avaliable-languages-component-fix-spacing`)
- Open http://government-frontend.dev.gov.uk/guidance/prepare-a-charity-annual-return
- Change the viewport size
- Spacing should be consistent with https://gov.uk/guidance/prepare-a-charity-annual-return
- Change the viewport size

Update available-languages to fix the spacing on smaller viewports

---

Gemfile
app/presenters/breadcrumbs.rb
app/presenters/case_study_presenter.rb
app/presenters/content_item_presenter.rb
app/presenters/detailed_guide_presenter.rb
app/presenters/document_collection_presenter.rb
app/presenters/html_publication_presenter.rb
app/presenters/publication_presenter.rb
app/presenters/topical_event_about_page_presenter.rb
app/views/content_items/case_study.html.erb
app/views/content_items/detailed_guide.html.erb
app/views/content_items/document_collection.html.erb
app/views/content_items/publication.html.erb
app/views/content_items/topical_event_about_page.html.erb
app/views/shared/_breadcrumbs.html.erb
test/presenters/breadcrumbs_test.rb

Some items have parents, so we should display the breadcrumb components when their data is available. 
I am going to leave a couple of comments (in Whitehall) to the document types that yet have to be migrated to government-frontend but that should have breadcrumbs. 
https://trello.com/c/5HYjGVif/13-breadcrumb-for-government-frontend-content-2
worked on it with @carolinegreen.
|doc type| breadcrumbs required | migration status |
| --- | --- | --- |
|case study| yes | complete |
|detailed guide| yes | in progress - almost complete |
|document collection placeholder| yes |  not started|
|generic edition| yes | not started |
|html attachment| yes | ongoing |
|publication| yes |not started |
|topical event about page| yes | complete |
|coming soon| no | not relevant |
|contact| no | not …

Add breadcrumbs where needed

---

Gemfile
app/presenters/breadcrumbs.rb
app/presenters/case_study_presenter.rb
app/presenters/content_item_presenter.rb
app/presenters/detailed_guide_presenter.rb
app/presenters/document_collection_presenter.rb
app/presenters/html_publication_presenter.rb
app/presenters/publication_presenter.rb
app/presenters/topical_event_about_page_presenter.rb
app/views/content_items/case_study.html.erb
app/views/content_items/detailed_guide.html.erb
app/views/content_items/document_collection.html.erb
app/views/content_items/publication.html.erb
app/views/content_items/topical_event_about_page.html.erb
app/views/shared/_breadcrumbs.html.erb
test/presenters/breadcrumbs_test.rb

This reverts commit 4a55298a211c542ac9f790ebf15a5c8f56d07f10, reinstating the Breadcrumb functionality originally added by @jackscotti & @MatMoore in https://github.com/alphagov/government-frontend/commit/d51d8f48e59adfde2a64b068f47910e9e0534cd9

Revert "Revert "Add breadcrumbs where needed""

---

Gemfile
Gemfile.lock
README.md
startup.sh

Fixes SystemStackError issues in production
Also add `--live` option to `startup.sh` to easily run the app against live content store and static.

Upgrade slimmer to 9.3.2

---

README.md

This adds a table to the readme with the migration status for the formats this app can render (I've used all presenters classes for this).
For an outsider it's quite difficult to find out which things are in progress and which are "real".

Add migration status of formats to readme

---

Gemfile
Gemfile.lock
app/helpers/gone_helper.rb
app/presenters/gone_presenter.rb
app/views/content_items/gone.html.erb
test/helpers/gone_helper_test.rb
test/presenters/gone_presenter_test.rb
test/test_helper.rb

This has been added to allow `gone` items with an `explanation` or `alternative_path` to be rendered.
These are created by unpublishing within Whitehall when the reason is 'Published in error' but 'redirect?' is not selected.
This will require https://github.com/alphagov/govuk-content-schemas/pull/372 to be merged before the tests will pass.

Add `gone` format

---

app/views/content_items/case_study.html.erb
app/views/content_items/detailed_guide.html.erb
app/views/content_items/document_collection.html.erb
app/views/content_items/html_publication.html.erb
app/views/content_items/publication.html.erb
app/views/content_items/statistics_announcement.html.erb
app/views/content_items/take_part.html.erb
app/views/content_items/topical_event_about_page.html.erb
app/views/content_items/working_group.html.erb

The meta description tag is defined in the parent layout, but none of the content items currently use it. This commit adds meta description tags to all content items, the contents of which are set to the `description` associated with the content. This adds descriptions to external search engine results when the pages are re-indexed.
Trello: https://trello.com/c/bbAwFAQ1/108-add-meta-descriptions-to-pages-missing-them

Add meta descriptions to content items

---

app/presenters/breadcrumbs.rb
test/presenters/breadcrumbs_test.rb

This fixes a bug in the breadcrumbs presenter.
The presenter is tested with an example from govuk-content-schemas. But the example contains an error: it uses a structure like `links -> parent -> parent`. This is not how the publishing-api expands the links, it nests it like `links -> parent -> links -> parent`.
However, because the liberal way the frontend `links` hash is validated, the example was considered valid. This is tackled in https://github.com/alphagov/govuk-content-schemas/pull/389.

Fix breadcrumb presenter

---

app/presenters/detailed_guide_presenter.rb
app/views/content_items/detailed_guide.html.erb
test/presenters/detailed_guide_presenter_test.rb

This has been changed in the schema to `related_mainstream_content` to make it more consisitent.

Rename `related_mainstream` for DetailedGuide

---

app/views/content_items/fatality_notice.html.erb

Adds `average_title_length: 'long'` to the title component to handle long titles appropriately.

Fix Fatality Notice title length

---

test/integration/document_collection_test.rb

We've added individual examples for each feature to the content
schemas and also updated them to support a top level withdrawn
field instead of within the details hash.
Mobbed with @andrewgarner @MatMoore @gpeng 
[Trello](https://trello.com/c/DoIbAkZB/428-11-document-collection-migration-implement-publishing-of-format-to-publishing-api)

Support additional document collection examples

---

app/assets/stylesheets/views/_detailed-guide.scss
app/presenters/detailed_guide_presenter.rb
app/views/content_items/detailed_guide.html.erb

One Detailed guide has a European Structural and Investment Fund logo
which must be displayed for regulatory reasons. This was missed during
migration.
How it looked in Whitehall: http://webarchive.nationalarchives.gov.uk/20160806171559/https://www.gov.uk/guidance/england-2014-to-2020-european-structural-and-investment-funds
Screenshots of Government Frontend at various break points:

Display logo image for Detailed guides if provided

---

config/locales/en.yml

Currently statistics announcements have the document type `national` or `official`. There are no translations for these, causing I18n-missing errors on production (in the `<title>` tag). This commit adds the translations.
In addition, it adds translations for the *new* document types of this format. These will be changed in
https://github.com/alphagov/whitehall/pull/2783.

Add translations for statistics announcements

---

.gitignore
Gemfile
Gemfile.lock
config/application.rb
config/initializers/airbrake.rb
config/initializers/gds_api.rb

This fixes some deprecation warnings.
The new version of the Airbrake gem requires a new config, which will
be populated by env vars rather than by overwriting on deployment.
This depends on https://github.com/alphagov/govuk-puppet/pull/5009, https://github.gds/gds/deployment/pull/1130 and https://github.gds/gds/alphagov-deployment/pull/1276

Upgrade airbrake and gds-api-adapters gems.

---

app/presenters/document_collection_presenter.rb
test/presenters/document_collection_presenter_test.rb

Add functionality to DocumentCollectionPresenter to mimic current behaviour in Whitehall.
* Don't present documents that are in the groups but not in the links.
* Don't present groups that have empty collections.
[Trello](https://trello.com/c/DoIbAkZB/428-11-document-collection-migration-implement-publishing-of-format-to-publishing-api)
Mobbed on with @andrewgarner @bevanloon @gpeng @mgrassotti @Rosa-Fox

Fix document collection scoping

---

app/assets/stylesheets/helpers/_sidebar-with-body.scss
app/assets/stylesheets/views/_detailed-guide.scss
app/assets/stylesheets/views/_topical-event-about-page.scss
app/assets/stylesheets/views/_working-group.scss
app/views/content_items/document_collection.html.erb

This protects the first 'third' column in the event that there are no contents entries.
Also refactors the relevant class out into the `sidebar-with-body` helper which fixes a bug in working groups and removes some duplication.

Fix DocumentCollection contents styling

---

app/presenters/document_collection_presenter.rb
test/presenters/document_collection_presenter_test.rb

When all of the documents in a collection have been unpublished the `links#documents` element is not present in the json. This commit handles that case.
Depends on https://github.com/alphagov/govuk-content-schemas/pull/438

Handle missing `links#documents` for Document Collections

---

app/presenters/document_collection_presenter.rb

Use `Array()` rather than `array || []`.
Minor amendment suggested after https://github.com/alphagov/government-frontend/pull/197 was merged.
/cc @andrewgarner

Small refactor to Document Collection presenter

---

app/presenters/content_item_presenter.rb
app/views/layouts/application.html.erb
test/integration/content_item_test.rb
test/test_helper.rb

Trello: https://trello.com/c/nYKudXNT/512-fix-whitehall-admin-bookmarklet-for-migrated-formats-medium
In order to preserve the whitehall admin bookmarklet functionality, we
are going to expose the content_id for each content item. This id will
be used to redirect to the related admin page.

Expose the content_id for each content item

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/views/_statistical-data-set.scss
app/presenters/statistical_data_set_presenter.rb
app/views/content_items/statistical_data_set.html.erb
lib/generators/format/templates/format_presenter_test.rb.erb
test/integration/statistical_data_set_test.rb
test/presenters/statistical_data_set_presenter_test.rb

Add support for rendering Statistical Data Sets
[Trello](https://trello.com/c/3OZ36DPk)
Paired with @fofr and @tvararu 
Related pull request in [govuk-content-schemas](https://github.com/alphagov/govuk-content-schemas/pull/440)
An example with block attachments has also been created - screenshots below show the block attached element:

Add Statistical Data Sets

---

test/presenters/case_study_presenter_test.rb
test/presenters/coming_soon_presenter_test.rb
test/presenters/detailed_guide_presenter_test.rb
test/presenters/document_collection_presenter_test.rb
test/presenters/html_publication_presenter_test.rb
test/presenters/publication_presenter_test.rb
test/presenters/statistical_data_set_presenter_test.rb
test/presenters/take_part_presenter_test.rb
test/presenters/topical_event_about_page_presenter_test.rb
test/presenters/unpublishing_presenter_test.rb

The content item attribute `format` is deprecated.
alphagov/govuk-content-schemas#444 attempts to remove `format` from the frontend, but the tests for this application fail without `format` in the examples. This is because the tests are testing kind of the wrong thing.
For example:
```
assert_equal schema_item['format'], presented_item.format
```
Checks the string in `presented_item.format` which actually points to `schema_item['schema_name']`. Because they're `format` and `schema_name` are identical in the examples this worked. Now that we've removed `format` it doesn't anymore.
https://trello.com/c/C8A9bnuO/344-work-on-making-the-document-type-concept-clearer

Use `schema_name` consistently

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/helpers/_notice.scss
app/assets/stylesheets/views/_consultation.scss
app/assets/stylesheets/views/_publication.scss
app/presenters/consultation_presenter.rb
app/presenters/content_item_presenter.rb
app/presenters/html_publication_presenter.rb
app/presenters/updatable.rb
app/presenters/withdrawable.rb
app/views/content_items/consultation.html.erb
config/locales/en.yml
test/integration/consultation_test.rb
test/presenters/consultation_presenter_test.rb

Tests will fail until the corresponding schema changes have been merged and deployed: https://github.com/alphagov/govuk-content-schemas/pull/445
Main story:
https://trello.com/c/QseqtCaJ/509-consultations-migration-basic-content-schema-examples-and-front-end-work-large
Ports the following features from Whitehall:
* Display of consultation description (the body in content item)
* Display of consultation summary (the description in content item)
* Open and closing date and date ranges
* Includes fix for showing an unopened consultation as "opening on" rather than already closed
* Uses a legible date format, "10 June 2015 10:00am" is now "10am on 10 June 2015"
* When the time is 12:00am, it shows midday
* When the time is midnight it either hides the time for opening date or rolls back 1 …

Render the consultation format

---

app/views/content_items/consultation.html.erb
test/integration/consultation_test.rb

The date that the consultation closes is useful information for users.
@andrewgarner

Show closing date on unopened consultations

---

app/views/shared/_available_languages.html.erb

This commit adds the HTML lang attribute to links to translated content. This ensures that the language name is understood correctly by screen readers and browsers, and therefore read correctly. Fixes https://github.com/alphagov/whitehall/issues/2873.

Add lang attribute to page translation links

---

app/presenters/document_collection_presenter.rb
test/presenters/document_collection_presenter_test.rb

This brings government-frontend in line with Whitehall, which doesn't show withdrawn documents.
Trello:
https://trello.com/c/IFfWVlb6/533-filter-out-withdrawn-documents-in-document-collections-medium
Follow-up to:
- https://github.com/alphagov/govuk-content-schemas/pull/454
- https://github.com/alphagov/publishing-api/pull/627
Depends on:
- https://github.com/alphagov/govuk-content-schemas/pull/459
Below screenshots use the fictional `/government/collections/with-withdrawn-links-documents` example I created that has `Financial sanctions, Somalia` marked as withdrawn.

Don't display Document Collection withdrawn documents

---

jenkins.sh

This reverts commit b029b9d2fd1e4133becdc2fc972b6d53da1db8b1.
`jenkins.sh` [was removed as part of moving to the new Jenkins](https://github.com/alphagov/government-frontend/pull/206/commits/b029b9d2fd1e4133becdc2fc972b6d53da1db8b1) but it is needed for content schemas (see `jenkins-schemas.sh`)

Revert "Remove jenkins.sh"

---

config/initializers/jasmine_rails.rb

This is necessary to prevent it being referenced in routes.rb in production, where the module doesn't exist.

Monkey patch JasmineRails only if defined

---

app/views/content_items/statistical_data_set.html.erb

Statistical Data Sets should render the `meta name="description"` tag.
Screenshots show a before and after of the source from a rendered example.  
<table>
<tr><th>Before</td><th>After</th></tr>
<tr><td valign="top"><img width="260" alt="screen shot 2016-12-21 at 14 26 40" src="https://cloud.githubusercontent.com/assets/647311/21393238/808a1de2-c78b-11e6-8d6c-787c8d99642d.png"></td><td valign="top"><img width="260" alt="screen shot 2016-12-21 at 14 27 57" src="https://cloud.githubusercontent.com/assets/647311/21392963/3e60ac70-c78a-11e6-8081-07bd2f3db6cc.png"></td></tr>
</table>

Add `:meta_description` to Statistical Data Set

---

app/presenters/case_study_presenter.rb
app/presenters/consultation_presenter.rb
app/presenters/content_item_presenter.rb
app/presenters/detailed_guide_presenter.rb
app/presenters/document_collection_presenter.rb
app/presenters/fatality_notice_presenter.rb
app/presenters/linkable.rb
app/presenters/metadata.rb
app/presenters/national_applicability.rb
app/presenters/publication_presenter.rb
app/presenters/statistical_data_set_presenter.rb
app/presenters/statistics_announcement_presenter.rb
app/presenters/updatable.rb
app/views/content_items/case_study.html.erb
app/views/content_items/consultation.html.erb
app/views/content_items/detailed_guide.html.erb
app/views/content_items/document_collection.html.erb
app/views/content_items/fatality_notice.html.erb
app/views/content_items/publication.html.erb
app/views/content_items/statistical_data_set.html.erb
app/views/content_items/statistics_announcement.html.erb
app/views/shared/_metadata.html.erb
test/integration/fatality_notice_test.rb
test/presenters/case_study_presenter_test.rb
test/presenters/statistics_announcement_presenter_test.rb

* Create a metadata module that provides all the parameters to be passed to the metadata and document footer metadata components
* Module makes it hard to miss out an aspect of the metadata
* Makes it easy to iterate across formats
* Abstracts away the text direction, so it can't be forgotten
* Update case studies to behave in the same was as other formats
* Use full history rather than short history like other formats
* Simplify fatality notices by moving image into presenter
* Remove 'withdrawable' from format presenters, it's redundant
* Stop rendering links to policy_areas on stat announcements, they are being deprecated, no
other format links to them

DRY up views by moving metadata logic into module

---

app/presenters/fatality_notice_presenter.rb

When a draft is initially created there is no field of operation link
available due to the known lack of draft links issue.
This is a quick fix to allow a notice to be published. Tests will be
added in a subsequent commit.

Handle nil `field_of_operation` for fatality notice

---

app/views/content_items/fatality_notice.html.erb

Part of previous temp fix to allow publication of a pending fatality notice. More complete fix will follow.

Handle nil field of operation in fatality notice view

---

app/views/shared/_share_buttons.html.erb

Fixes #217
We're using `[target=_blank]` which has a vulnerability
https://mathiasbynens.github.io/rel-noopener/
“To prevent pages from abusing window.opener, use rel=noopener. This
ensures window.opener is null in Chrome 49 and Opera 36.”
“For older browsers, you could use rel=noreferrer which also disables
the Referer HTTP header”
@nickcolley

Add noopener and noreferrer to new window links

---

app/assets/stylesheets/views/_html-publication.scss

Include a default margin beneath the blue block of contents.
Coincides with a component change in static: https://github.com/alphagov/static/pull/870

Add space beneath HTML publication contents

---

app/assets/stylesheets/views/_html-publication.scss
app/presenters/html_publication_presenter.rb
app/views/content_items/html_publication.html.erb
test/integration/html_publication_test.rb
test/presenters/html_publication_presenter_test.rb

Not all HTML publications have a list of headings. When there are none, don’t include the empty list or its associated heading.
@gpeng Can you confirm how we publish headings for HTML publications without any headings? Is it passed through as an empty ordered list as in the example? This exists as a bug on live, and I've presumed the logic hasn't been fixed: https://www.gov.uk/government/publications/canada-united-kingdom-joint-declaration/canada-united-kingdom-joint-declaration

Don't show empty contents lists on HTML publications

---

app/presenters/case_study_presenter.rb
app/presenters/consultation_presenter.rb
app/presenters/detailed_guide_presenter.rb
app/presenters/document_collection_presenter.rb
app/presenters/fatality_notice_presenter.rb
app/presenters/metadata.rb
app/presenters/national_applicability.rb
app/presenters/speech_presenter.rb
app/presenters/statistical_data_set_presenter.rb
app/presenters/statistics_announcement_presenter.rb
app/presenters/take_part_presenter.rb
app/presenters/title_and_context.rb
app/presenters/topical_event_about_page_presenter.rb
app/presenters/working_group_presenter.rb
app/views/content_items/case_study.html.erb
app/views/content_items/consultation.html.erb
app/views/content_items/detailed_guide.html.erb
app/views/content_items/document_collection.html.erb
app/views/content_items/fatality_notice.html.erb
app/views/content_items/speech.html.erb
app/views/content_items/statistical_data_set.html.erb
app/views/content_items/statistics_announcement.html.erb
app/views/content_items/take_part.html.erb
app/views/content_items/topical_event_about_page.html.erb
app/views/content_items/working_group.html.erb
app/views/shared/_title_and_translations.html.erb

Clean up each format’s template by moving format specific logic into module, with overrides in format presenters.
Default:
* Content item title
* Context based on document type
* Long title length
This makes it difficult to include titles with the wrong attributes.
It also makes it easy to link to translations to any format – if a format has translations, then the links will display – protecting against accidental omission as with the speeches format.
One further commit:
* Protect against overwriting properties on the `other` hash provided to metadata and document footer components
A template for a standard format is now as simple as:
```
<%= content_for :page_class, @content_item.format.dasherize %>
<%= content_for :title, "#{@content_item.page_title} - …
```

Refactor title and context into module

---

config/locales/en.yml

The format is singular:
https://github.com/alphagov/whitehall/pull/2783/files
Fixes:
`translation missing: en.content_item.format.official_statistics_announcement`
@tijmenb Do you know if it's ok to remove `national` and `official` keys now?

Make official stats announcements translation key singular

---

app/assets/stylesheets/views/_speech.scss
app/presenters/speech_presenter.rb
app/views/content_items/speech.html.erb
test/integration/speech_test.rb
test/presenters/speech_presenter_test.rb

* Add language switcher
* Switch to using the new Metadata module which adds right-to-left support
* Add right to left styling for speeches (matches case-studies approach)
Tests depend on https://github.com/alphagov/govuk-content-schemas/pull/472
Note that in both old and new the helper text for the format (eg Transcript of the speech, exactly as it was delivered) is not translated. We ought to fix this when migrating the format.
| Old | New |
| --- | --- |
| ![translated-speech-old](https://cloud.githubusercontent.com/assets/319055/21614795/eafb94f2-d1d2-11e6-896b-cd9ce9382149.png) | ![translated-speech-new](https://cloud.githubusercontent.com/assets/319055/21614799/f022eed0-d1d2-11e6-8b36-1740c20e77ec.png) |
Part of https://trello.com/c/TWsLTRzc/547-speech-migration-1-mvp-content-schema- …

Allow speeches to be translated

---

app/presenters/extracts_headings.rb
test/presenters/extracts_headings_test.rb

When extracting headings from content, discard trailing colons. The colon may make sense in the body of content, but it’s incorrect in a list of contents.

Strip trailing colons from contents list

---

app/assets/stylesheets/views/_case-studies.scss
app/assets/stylesheets/views/_unpublishing.scss
app/views/content_items/case_study.html.erb
app/views/content_items/coming_soon.html.erb
app/views/content_items/consultation.html.erb
app/views/content_items/detailed_guide.html.erb
app/views/content_items/document_collection.html.erb
app/views/content_items/fatality_notice.html.erb
app/views/content_items/gone.html.erb
app/views/content_items/html_publication.html.erb
app/views/content_items/publication.html.erb
app/views/content_items/speech.html.erb
app/views/content_items/statistical_data_set.html.erb
app/views/content_items/statistics_announcement.html.erb
app/views/content_items/take_part.html.erb
app/views/content_items/topical_event_about_page.html.erb
app/views/content_items/unpublishing.html.erb
app/views/content_items/working_group.html.erb
app/views/layouts/application.html.erb
lib/generators/format/templates/format.html.erb

When adding formats it's easy to forget to set the meta description to the content item’s description. This is a sensible default. Description isn't always present (eg html publications), in those cases omit the meta tag.
Almost all formats set the page class consistently to the dasherized version of the format name. Make those that were slightly different consistent and switch responsibility to the base layout, DRYing up the format templates. This reduces the risk of a format being accidentally added with a different page_class behaviour.

Move meta description and page class to base layout

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/views/_world-location-news-article.scss
app/presenters/world_location_news_article_presenter.rb
app/views/content_items/consultation.html.erb
app/views/content_items/world_location_news_article.html.erb
app/views/shared/_history_notice.html.erb
app/views/shared/_share_buttons.html.erb
config/locales/en.yml
test/integration/detailed_guide_test.rb
test/integration/document_collection_test.rb
test/integration/publication_test.rb
test/integration/statistical_data_set_test.rb
test/integration/world_location_news_article_test.rb
test/presenters/world_location_news_article_presenter_test.rb

Tests will fail until the corresponding schema changes have been merged and deployed: 
https://github.com/alphagov/govuk-content-schemas/pull/476
[Trello card](https://trello.com/c/UExU1tXe)
Add presenter, view and related artefacts needed to support rendering World Location News Articles in government-frontend.
| Feature | Old | New |
|---|---|---|
| Simple example | ![whitehall_basic](https://cloud.githubusercontent.com/assets/647311/21720179/abfd70d8-d419-11e6-8620-1e402e4af740.png) | ![government-frontent_basic](https://cloud.githubusercontent.com/assets/647311/21720192/bca90172-d419-11e6-995f-1909d7b8c91b.png) |
| With attachments | ![whitehall_attachments](https://cloud.githubusercontent.com/assets/647311/21720262/02d15334-d41a-11e6-9e49-02eac269a284.png) | …

World Location News Article front-end

---

Gemfile
Gemfile.lock

This ensures the GOVUK_FACT_CHECK_ID header is passed through on
upstream requests.

Bump gds-api-adapters to 37.5.1.

---

app/views/content_items/case_study.html.erb
app/views/content_items/detailed_guide.html.erb
app/views/content_items/document_collection.html.erb
app/views/content_items/publication.html.erb
app/views/content_items/topical_event_about_page.html.erb
app/views/layouts/application.html.erb

Currently we don't show the breadcrumbs if the format traditionally doesn't have them.
On other pages on GOV.UK we've introduced the breadcrumbs, whether or not they're set. For example, https://www.gov.uk/aaib-reports just has a "Home" breadcrumb, because
https://www.gov.uk/aaib-reports/aaib-investigation-to-airbus-a319-111-g-ezfj has a breadcrumb to that page.
This adds consistent breadcrumbs to all pages. This means that we'll show empty "Home" breadcrumbs for fatality notices, statistics announcements, statistical data sets, "take part" pages and groups. Note that it's super easy to set the breadcrumb for these pages, by adding a `parent` link to the presenter in Whitehall. 
This should make https://github.com/alphagov/government-frontend/pull/237 a little easier.
@nickcolley @fofr …

Show breadcrumbs consistently

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/helpers/_share-buttons.scss
app/assets/stylesheets/views/_news-article.scss
app/assets/stylesheets/views/_world-location-news-article.scss
app/presenters/news_article_presenter.rb
app/presenters/world_location_news_article_presenter.rb
app/views/content_items/news_article.html.erb
app/views/content_items/world_location_news_article.html.erb
test/integration/news_article_test.rb
test/integration/world_location_news_article_test.rb
test/presenters/news_article_presenter_test.rb

Tests will fail until the schema and examples have been merged and deployed: https://github.com/alphagov/govuk-content-schemas/pull/488
* Render the news article format, with each of its sub-types: news_story, press_release and government_response (identical except for the title context provided by `document_type`)
* Includes a couple of fixes for world location news article
* Allow news and world location news to be translated rtl
* Fix rtl rendering of share buttons
| Type | Old | New |
| ----- | --- | ----- |
| News story | ![news_story_old](https://cloud.githubusercontent.com/assets/319055/22061499/190a9690-dd6d-11e6-8e2a-507949e3b19c.png) | ![news_story_new](https://cloud.githubusercontent.com/assets/319055/22061503/1dc00b3e-dd6d-11e6-9ccc-ea4ade37096b.png)
| Translated | …

Render news article format

---

app/presenters/contents_list.rb
app/presenters/detailed_guide_presenter.rb
app/presenters/document_collection_presenter.rb
app/presenters/statistical_data_set_presenter.rb
app/presenters/topical_event_about_page_presenter.rb
app/presenters/working_group_presenter.rb
app/views/shared/_sidebar_contents.html.erb
test/presenter_test_helper.rb
test/presenters/contents_list_test.rb
test/presenters/detailed_guide_presenter_test.rb
test/presenters/document_collection_presenter_test.rb
test/presenters/statistical_data_set_presenter_test.rb
test/presenters/topical_event_about_page_presenter_test.rb

* Move contents logic into extracts headings module
* Provide new helper methods for contents_items and contents_link allowing presenters to override them if needed
* Override content_items method in collections to use a list of groups
* Add extra headings to working groups when appropriate
* Add link tracking module and attributes to all contents links
Category: contentsClicked
Action: leftColumnH2
Label: ID of the heading
Depends on https://github.com/alphagov/static/pull/883
https://trello.com/c/62Gy8pyj/77-track-interactions-with-contents-lists-1-s
cc @nickcolley

Add link tracking to left-hand contents list

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/helpers/_organisation-links.scss
app/assets/stylesheets/views/_corporate-information-page.scss
app/presenters/corporate_information_page_presenter.rb
app/presenters/html_publication_presenter.rb
app/presenters/organisation_branding.rb
app/views/content_items/corporate_information_page.html.erb
app/views/content_items/html_publication.html.erb
test/integration/corporate_information_page_test.rb
test/presenters/corporate_information_page_presenter_test.rb
test/presenters/html_publication_presenter_test.rb
test/presenters/organisation_branding_test.rb
test/test_helper.rb

Goes with https://github.com/alphagov/govuk-content-schemas/pull/501 (tests will fail until this is merged and deployed)
Part of https://trello.com/c/8ySlDVSs/578-corp-info-migration-1-mvp-content-schema-examples-and-front-end-work
* Minimum viable corporate information page format and rendering, handling of larger organisation logos and complex logic at the foot of About pages has been moved into separate cards:
* https://trello.com/c/HtSGDoRb/835-add-organsation-logos-that-are-images-to-content-item
* https://trello.com/c/8syU3iNh/836-add-corporate-information-block-to-about-pages-corporate-information-pages
* Upgrades frontend toolkit to version 5 to pick up organisation colours, used for branding
* Org logo logic moved into shareable module
* Design updated to match other formats, …

Render corporate information page format

---

app/views/content_items/publication.html.erb
app/views/shared/_title_and_translations.html.erb
app/views/shared/_translations.html.erb

Publications can be translated but we have neglected to add the necessary code to render the locale choice UI in the publication view.
This PR remedies that along with a small refactor to avoid duplication.
There could be an issue if National Statistics type publications are translated as this might break the grid but a) there are none in the Whitehall database, b) it seems unlikely that that sub-type would be translated and c) the quick test one that I knocked up appears to be OK. So... I think we can proceed without worrying about that for now to unblock deploying [Whitehall](https://github.com/alphagov/whitehall/pull/2986)
Before:
After:
Test with national statistics logo and translations:

Add translations to publications

---

Gemfile
Gemfile.lock
app/controllers/content_items_controller.rb
app/models/education_navigation_ab_test_request.rb
app/presenters/ab_testable.rb
app/presenters/content_item_presenter.rb
app/presenters/metadata.rb
app/views/content_items/case_study.html.erb
app/views/content_items/consultation.html.erb
app/views/content_items/detailed_guide.html+new_navigation.erb
app/views/content_items/detailed_guide.html.erb
app/views/content_items/document_collection.html.erb
app/views/content_items/fatality_notice.html.erb
app/views/content_items/publication.html.erb
app/views/content_items/speech.html.erb
app/views/content_items/statistical_data_set.html.erb
app/views/content_items/world_location_news_article.html.erb
app/views/layouts/application.html.erb
app/views/shared/_breadcrumbs.html+new_navigation.erb
app/views/shared/_breadcrumbs.html.erb
app/views/shared/_footer.html+new_navigation.erb
app/views/shared/_footer.html.erb
app/views/shared/_metadata.html+new_navigation.erb
app/views/shared/_metadata.html.erb
app/views/shared/_title_and_translations.html+new_navigation.erb
app/views/shared/_title_and_translations.html.erb
test/controllers/content_items_controller_test.rb

Add functionality to check for A/B Testing, and display content according to which "bucket" the user has been added to.
This WIP PR adds a helper method to the controller to check for A/B bucket (with associated tests).
As a proof-of-concept, it also updates two of the `content_item` views to show either an A or B view. Currently the only difference between the two is the display of "normal" breadcrumbs (view A) or "taxon" breadcrumbs (view B).
If we continue in this style, we should add A/B views for _all_ Content Items. Is this the best approach? If so, should we be grouping them in subfolders under `content_items` to reduce clutter? Is there any scope for commonising, or is that a waste of time, given that - if testing is successful - we'd just want to delete all the "A" views anyway …

Navigation AB Test

---

app/presenters/html_publication_presenter.rb
app/presenters/organisation_branding.rb
app/views/content_items/corporate_information_page.html.erb
test/integration/corporate_information_page_test.rb
test/presenters/html_publication_presenter_test.rb
test/presenters/organisation_branding_test.rb

Goes with:
* https://github.com/alphagov/govuk-content-schemas/pull/514 (tests will fail until merged and deployed)
* https://github.com/alphagov/static/pull/894
Part of https://trello.com/c/HtSGDoRb/594-add-organisation-logos-that-are-images-to-content-item-2
* Pass custom organisation images to component
* Restrict width of component to 25% to match HTML publication
* Include image only when provided
* Don't show custom logos on HTML pubs with many orgs

Render custom organisation logos when provided

---

Gemfile
Gemfile.lock

The new version of navigation helpers will display the current page in the breadcrumbs.
Dependent on:
Trello: https://trello.com/c/MVM5bueS/386-add-current-page-to-taxonomy-breadcrumbs

[Do not merge] Bump navigation helper version

---

app/models/education_navigation_ab_test_request.rb
test/controllers/content_items_controller_test.rb

The name of the A/B test must match the cookie name exactly. The name of this test is defined as EducationNavigation in alphagov/govuk-cdn-config#17.

Fix casing of A/B test name

---

Gemfile
Gemfile.lock

Removes deprecation warnings when running the jasmine tests

Update jasmine-rails to 0.14.1

---

app/controllers/content_items_controller.rb
app/models/education_navigation_ab_test_request.rb
app/views/content_items/detailed_guide.html+new_navigation.erb
app/views/content_items/detailed_guide.html.erb
app/views/content_items/document_collection.html+new_navigation.erb
app/views/content_items/publication.html+new_navigation.erb
app/views/layouts/application.html.erb
app/views/shared/_national_statistics_logo.html+new_navigation.erb
app/views/shared/_translations.html+new_navigation.erb
test/controllers/content_items_controller_test.rb

This extends the styling changes made in https://github.com/alphagov/government-frontend/pull/237 to also encompass the following content item schemas:
- `document_collection`
- `publication`
The changes are to:
- Add a `meta` tag to these documents to indicate that they are in an A/B test (when their content is tagged to a taxon)
- Set the `Vary` header on responses from these documents
- Move the content for these documents into the left two thirds of the page (when the user is in the "B" group)
https://trello.com/c/jd56fcgd/338-changes-to-education-related-content-pages-as-part-of-the-new-navigation-in-government-frontend-part-2

Education navigation ab testing

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
config/environments/production.rb
test/test_helper.rb

Most important: https://github.com/alphagov/slimmer/pull/191, which maybe fixes a memory leak in the components.
Changelog:
* Fix memory leak in components
* Bugfix for request URI's encoded as ASCII
* Bugfix for caching behaviour
* Use `Rails.cache` as the cache for templates, locales and components.
You can
remove `config.slimmer.use_cache` for your application, as you can no
longer
opt-out of caching.
* Add a `User-Agent` header to all outgoing API requests
* Removes the need_id meta tag, which is no longer used.
* Removes the functionality for breadcrumbs, related links and
artefact-powered
metatags.
* Drop support for old Rails & Ruby versions. This gem now supports
Rails 4.2 and 5.X
on Ruby 2.1 and 2.2.
* Renames `Slimmer::SharedTemplates` to `Slimmer::GovukComponents` …

Bump slimmer gem to fix memory leak

---

app/views/shared/_share_buttons.html.erb

* The links aren’t useful when printed
* The long dynamic URLs don’t read well
(This also highlights that when printing there is no clear "end of content" point)

Don't print share links

---

test/wraith/config-staging-vs-production.yaml
test/wraith/config.yaml

I'm not sure why this works.
We were seeing errors when trying to run the wraith tests from the VM:
```
Error with page https://www.gov.uk/government/case-studies/doing-business-in-spain.es
```
Add phantomjs option:
```yaml
phantomjs_options: --ignore-ssl-errors=true --ssl-protocol=tlsv1
```
* Use TLS v1 when requesting https://www.gov.uk/… from within the VM (all other versions reported errors)
* Ignore SSL errors when accessing staging (production works fine with just TLS, but staging would fail)
PhantomJS depends on the system OpenSSL library.
http://phantomjs.org/api/command-line.html
Default is SSLv3

Fix wraith when running against prod/staging from within VM

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/helpers/_taxonomy-sidebar.scss
app/assets/stylesheets/views/_detailed-guide.scss
app/assets/stylesheets/views/_document-collection.scss
app/assets/stylesheets/views/_publication.scss
app/controllers/content_items_controller.rb
app/presenters/content_item_presenter.rb
app/views/content_items/detailed_guide.html+new_navigation.erb
app/views/content_items/document_collection.html+new_navigation.erb
app/views/content_items/publication.html+new_navigation.erb
test/controllers/content_items_controller_test.rb

Use the taxonomy sidebar component in static and rework the tests to
assert for the presence of the sidebar where appropriate.
Along with the taxon breadcrumbs this change is part of the education nav AB test.
Note that this PR adds the sidebar only - the breadcrumbs are already implemented in this repo.
https://trello.com/c/0BD3POzu/403-show-parent-taxons-in-the-side-navigation-on-all-education-content-pages

Add taxonomy sidebar to pages displaying the new navigation

---

app/helpers/application_helper.rb
test/integration/fatality_notice_test.rb
test/integration/news_article_test.rb
test/integration/publication_test.rb
test/test_helper.rb

Hiya 👋 
I spotted the broken active nav when someone on Twitter linked to a news article. There was an issue already. This fixes it.
---
Current nav is based on part of the path, which works for common cases like 'publications', but some don't follow the convention, like news articles (with 'government/news/slug') that sit under 'announcements'.
Add a hash to map paths that don't follow the convention.
Add tests to for news articles getting the right active nav, and another to a format that does follow the convention, to ensure that still works.
I'm not sure if there are formats other than news articles that need a mapping, but they'd be easy to add now.
---
**Cyber Screenshot:**
🎉

Fix #181: Highlight nav correctly for news articles

---

README.md
app/presenters/travel_advice_presenter.rb

`map!` was directly manipulating `content_item["details"]["alert_status”]`
We should protect content_item from being manipulated
Also adds travel advice to the supported formats table in README.

Avoid use of `map!` on travel advice

---

Gemfile
Gemfile.lock

Bumping the `govuk_navigation_helpers` version will show the latest version of the taxonomy sidebar when viewing the new education navigation in the A/B test.
https://trello.com/c/EJXC60k1/429-add-more-like-this-results-to-side-navigation-in-frontend-apps

Bump Navigation Helpers version

---

Gemfile
Gemfile.lock
app/models/education_navigation_ab_test_request.rb
test/controllers/content_items_controller_test.rb
test/test_helper.rb

Main changes are:
- passing in the request headers to the variant checker;
- setting the acceptance testing framework in the configuration of the
gem.
Gem changes: https://github.com/alphagov/govuk_ab_testing/pull/20
Trello: https://trello.com/c/t4n8kPpx/434-make-sure-collections-can-be-toggled-with-the-a-b-test-and-react-to-it

Upgrade govuk_ab_testing to 1.0.1

---

Gemfile
Gemfile.lock
app/controllers/content_items_controller.rb
app/presenters/travel_advice_presenter.rb
app/views/content_items/travel_advice.atom.builder
app/views/content_items/travel_advice.html.erb
config/routes.rb
test/controllers/content_items_controller_test.rb
test/integration/travel_advice_atom_feed_test.rb
test/integration/travel_advice_test.rb
test/presenters/travel_advice_presenter_test.rb
test/wraith/config.yaml

https://trello.com/c/mNRwOtHL/139-2-render-travel-advice-atom-feeds-in-government-frontend-m
Render atom feeds for travel advice countries. Output of atom feed is identical to multipage-frontend’s (and live). Template and tests ported from multipage-frontend.
__When reviewing please double-check the routing logic and tests__
Add support for rendering atom routes:
* Update routing to allow atom format
* Use a regex to constrain matches on locale and format
* Test that all supported locales work with regex
* Append the locale when matched to the content_item_path
* Return 406 when unacceptable format requested
Paired with @andrewgarner
Example feed:
Matches: https://www.gov.uk/foreign-travel-advice/thailand.atom
```
<?xml version="1.0" encoding="UTF-8"?>
<feed xml:lang="en-US" …
```

Add atom feeds to travel advice

---

app/views/content_items/detailed_guide.html+new_navigation.erb
app/views/content_items/document_collection.html+new_navigation.erb
app/views/content_items/publication.html+new_navigation.erb

The Whitehall navigation in the header is not compatible with the new Education navigation being A/B tested.
This change removes that navigation for all "B" variants of the education navigation pages.
https://trello.com/c/PkN40aGb/479-don-t-show-whitehall-navigation-in-government-frontend-a-b-test

Remove Whitehall header navigation from new navigation pages

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/views/_specialist-document.scss
app/presenters/specialist_document_presenter.rb
app/presenters/updatable.rb
app/views/content_items/specialist_document.html.erb
test/integration/specialist_document_test.rb
test/presenters/specialist_document_presenter_test.rb
test/presenters/updatable_test.rb

https://trello.com/c/h9hITGPy/158-render-specialist-content-in-government-frontend
Tests depend on merge and deploy of https://github.com/alphagov/govuk-content-schemas/pull/548
This is the first part of switching specialist content to government-frontend
* Renders with an incomplete metadata and footer
* Metadata is pending https://trello.com/c/6CBttvZL/ and is covered by a later story: https://trello.com/c/al2fPH5p/
* Renders with existing contents list rather than the nested version currently on specialist frontend
* Use the oldest entry in the change history to determine first published date – this matches specialist frontend but should be updated when https://trello.com/c/xCJ3RN6W/ is ready
* Display change history in reverse chronological order, matching all other formats
Note: This …

Render specialist documents

---

app/models/education_navigation_ab_test_request.rb
test/controllers/content_items_controller_test.rb

This means we can toggle the A/B variant in production via the chrome
extension.  When we rollout the new navigation with a Fastly
configuration change, the % of users we select will start seeing these
new pages.
Trello: https://trello.com/c/940kowVa/484-remove-enable-new-navigation-check-from-repos-and-from-puppet

Remove the New Navigation feature flag

---

test/presenters/updatable_test.rb

If first_public_at is not present, change_history in `app/presenters/updatable.rb` should be empty. Add a test for this to ensure we don't introduce a regression in a future version.

Add test for absence of first_public_at

---

app/assets/stylesheets/views/_contact.scss
app/presenters/contact_presenter.rb
app/views/content_items/contact.html.erb
test/integration/contact_test.rb
test/presenters/contact_presenter_test.rb

Make contacts more like contacts frontend:
* Only render phone headings when there are multiple numbers
* Render telephone numbers in bold so they can be found easily
General improvements:
* Move description of phone number above the number, this is consistent with postal addresses and works well with existing content. eg Description says when you should use number and what things you'll need when you make the call
On contacts, when many phone numbers are listed, these are presented using h3 titles (h2: Phone, h3: Type of number). Within this “Opening times” and “Best time to call” are presented as h4s.
In a list of numbers the distinction between phone numbers and these h4 headings was being lost, making the list hard to scan.
* Reduce the visual importance of  specific h4s by making …

Improve layout of contacts content

---

app/controllers/content_items_controller.rb
app/presenters/travel_advice_presenter.rb
app/views/content_items/travel_advice.html+print.erb
app/views/content_items/travel_advice.html.erb
app/views/shared/_travel_advice_summary.html.erb
config/routes.rb
test/controllers/content_items_controller_test.rb
test/integration/travel_advice_print_test.rb
test/presenters/travel_advice_presenter_test.rb

https://trello.com/c/MluRcP1W/138-2-render-travel-advice-print-page-in-government-frontend-m
* Add route for handling print requests
* Render a print view showing all parts
* Use variants to indicate which template to render
* Render summary and all parts using standard template rather than slimmer’s print version – this applies the print styles we use across GOV.UK rather than the broken bespoke slimmer ones
* Indicate that the link to the print page is an alternate version
* Don’t index the print version
* Add “Print” to title element for unique title
Note that we opted against general line-length improvements to print: https://github.com/alphagov/static/pull/913
When reviewing I recommend comparing the PDF versions. (ProTip: You can drag and drop PDFs to PRs)
| Old | New |
|--|--| …

Add print view for travel advice

---

app/views/content_items/contact.html.erb

HMRC Content have requested a change from 'Online forms' to 'Online'
James Low: 'It’s just that not all of our online channels that we want to offer users in preference to calling us are forms'
As part of https://trello.com/c/6cASC737/166-1-hmrc-engagement-with-contacts-fe-s

Update Contact page 'Online forms' header to 'Online'

---

app/presenters/contact_presenter.rb
test/presenters/contact_presenter_test.rb

Ideally this would be coming from the parents links in the content api, but
this is blocked until the publishing platform has completed
https://trello.com/c/0OvN0dtQ/
we wish to get the page out before the code rots, so we copied over
the way contacts-frontend was doing it initially
is dependent on 
https://github.com/alphagov/govuk-content-schemas/pull/556

Add breadcrumbs to contacts page

---

app/views/content_items/detailed_guide.html+new_navigation.erb
app/views/content_items/document_collection.html+new_navigation.erb

The "sticky" contents link can overlap the sidebar content on the new navigation. Remove this link for now in absence of any designs, especially since we were talking about removing it anyway.
https://trello.com/c/Pc0HAKXJ/60-on-content-pages-with-a-contents-element-and-a-long-sidebar-the-two-elements-overlap

Remove sticky contents link from new navigation

---

app/presenters/contact_presenter.rb
test/presenters/contact_presenter_test.rb

* `more_info_contact_form` is both optional and nullable
* Protect against both cases and test each

Protect against `more_info_contact_form` not existing

---

app/presenters/travel_advice_presenter.rb
test/integration/travel_advice_print_test.rb
test/integration/travel_advice_test.rb
test/presenters/travel_advice_presenter_test.rb

The FCO Content team have decided we can simplify the two titles currently on live
to just 'Summary'
Live
---
Proposed

Update Foreign Travel Advice title to Summary

---

.gitignore
README.md

I constantly find myself deleting wraith stuff out, this makes it easier for a dev to have multiple configs :cat:

Add a gitignore so you can have wip for your wraith configs

---

app/presenters/travel_advice_presenter.rb
test/integration/travel_advice_test.rb
test/presenters/travel_advice_presenter_test.rb

1. Protect against unexpected alert status types. Alert status should be an enum in the schema: alphagov/govuk-content-schemas#568
2. Handle change description being an empty string
* Change description is required, but it could be empty
* Capitalise fails on nil
* Handle an empty latest update a little more cleanly
* Test against randomly generated content

Make travel advice more resilient

---

app/views/shared/_breadcrumbs.html+new_navigation.erb

Pass `collapse_on_mobile` parameter to enable the collapse of the taxonomy breadcrumbs to a single back link.
https://trello.com/c/Y7OirowB/472-mobile-version-of-breadcrumbs-should-only-show-previous-link

Enable taxonomy breadcrumb back link on mobile

---

app/presenters/html_publication_presenter.rb
app/presenters/organisation_branding.rb
app/presenters/topical_event_about_page_presenter.rb
app/views/content_items/html_publication.html.erb
test/integration/case_study_test.rb
test/integration/html_publication_test.rb
test/integration/topical_event_about_page_test.rb
test/integration/working_group_test.rb

This tests 4 further formats against random content.
Frontend principles:
1. Attempt to give the users what they need by rendering anything that's provided by the content-store
2. Report back to us when crucial data is missing so it can be fixed (ie not masking errors)
This PR only does part 1, ie the frontend will not fall over and users will see content, but we won't know that it's broken. When this happens how should we be reporting it? Send to Errbit while still rendering content? This mostly applies to HTML publications and their relationship with other content (organisations, parent).
---
1. HTML Publications
* Protect against parent document type not existing
* Protect against no organisations
* Protect against organisations with no logo
2. Topical event about pages
* Protect …

Make more formats resilient

---

Gemfile
Gemfile.lock
app/assets/javascripts/mouseflow.js
app/controllers/application_controller.rb
app/models/benchmarking_ab_test_request.rb
app/views/layouts/application.html.erb
config/application.rb
config/initializers/assets.rb
test/controllers/content_items_controller_test.rb

We are going to conduct a 2nd round of Benchmarking in GOV.UK. The idea is that we will try it with the new Education Navigation enabled across GOV.UK and see how it performs against the current navigation patterns (mainstream browse pages, topics, etc).
Besides checking if people actually complete the tasks, we would also like to know more details about how they use the new navigation pages and also about the new orientation in content pages. In order to do that, we will track mouse movements and gather the results in a heatmap. We are using a software called mouseflow to do this.
The tracking code will only be present for the people doing the benchmarking test (around 60 people). It will be behind a new A/B test so the tracking doesn't run for other GOV.UK users. These 60 users will be …

Mouse tracking

---

app/views/content_items/detailed_guide.html.erb
app/views/content_items/html_publication.html.erb
app/views/shared/_back_to_content_link.html.erb
test/integration/detailed_guide_test.rb

Track clicks on the floating "Contents" link that appears when scrolling down the page on:
- Detailed guides
- HTML publications
The following event will be tracked:
- category: `contentsClicked`
- action: `backToContentsLinkClicked`
- label: `Contents`
https://trello.com/c/DpEK2IwV/518-track-clicks-on-floating-contents-link-on-detailed-guide-pages

Track clicks on the floating Contents link

---

app/assets/stylesheets/views/_publication.scss

* Render right to left languages correctly on publications
* Matches pattern used by other formats, but ought to be updated as
it’s easily omitted
* Fixes https://govuk.zendesk.com/agent/tickets/1968274 (https://www.gov.uk/government/publications/midlands-engine-investment-portfolio.ar)
cc @36degrees @nickcolley

Add rtl styles to publications

---

app/assets/javascripts/webchat/library.js
spec/javascripts/helpers/lolex.js
spec/javascripts/support/jasmine.yml
spec/javascripts/webchat.spec.js

previous functionality was to send analytics on every state change,
this now only sends state changes to analytics as opposed to every
time we poll.
it alos includes lolex so we can do fake timers to test this,
recommendation from @nickcolley

Stop the webchat events firing on every ajax check

---

app/presenters/consultation_presenter.rb
app/presenters/content_item_presenter.rb
app/presenters/document_collection_presenter.rb
app/presenters/statistics_announcement_presenter.rb
app/presenters/topical_event_about_page_presenter.rb
app/presenters/travel_advice_presenter.rb
app/presenters/updatable.rb
config/application.rb
test/integration/consultation_test.rb
test/presenters/consultation_presenter_test.rb
test/presenters/document_collection_presenter_test.rb

Most dates in content items are UTC, occasionally some are BST. Any UTC dates during daylight savings time would render an hour out – when the time is around midnight, then the date will also be wrong.
via https://govuk.zendesk.com/agent/tickets/2044273
On: https://www.gov.uk/government/publications/your-new-state-pension-explained
```json
"public_updated_at": "2017-04-09T23:15:05.000+00:00",
"public_timestamp": "2017-04-10T00:15:05.000+01:00",
```
Those two dates are the same when taking into account time zone. But they rendered as:
* Use London timezone
* Update all uses of Time.parse to Time.zone.parse
* Replace most uses of DateTime.parse with Time.zone.parse
* Fix tests now they correctly handle the daylight savings time (DST)
* Include comment about far future dates having no DST
* …

Use London timezone

---

app/views/content_items/html_publication.html.erb

A snippet of code was used from this website:
https://makandracards.com/makandra/11133-how-to-test-print-stylesheets-with-cucumber-and-capybara
However, this snippet referenced a stylesheet called screen.css that was
never implemented on our end.
Since we never created the stylesheet, but we referenced it, all HTML
publications have been trying and failing to fetch this stylesheet,
resulting in a 404.
We don’t actually need screen.css, so this Pull Request removes the
reference to it.

Remove redundant stylesheet link

---

Gemfile
Gemfile.lock
README.md

this gem is not official as far as i can tell,
and only downloads a binary, instead list as a
dependency in the readme, and leave it as an excercise
to the reader/vm to have phantomjs

Remove the phantom gem, the only thing this does is download a binary

---

app/assets/stylesheets/helpers/_description.scss

A max width of 30em gives us around 60-70 characters based on the current font-size
which is regarded as a decent line-length for reading.
Change recommended by Mia Allers
Before
After
---
Before
After

Add max-width to give more readable line-length to description

---

app/controllers/travel_advice_controller.rb
test/controllers/travel_advice_controller_test.rb

https://trello.com/c/SEGfmX1v/912-1935680-enable-access-control-allow-origin-header-in-rss-feeds
Allow users to call the data in the Travel Advice atom feed via an AJAX request.
See https://govuk.zendesk.com/agent/tickets/1935680
and https://github.com/alphagov/frontend/pull/1210

Add Access-Control-Allow-Origin header to TA country pages

---

app/controllers/content_items_controller.rb
app/controllers/travel_advice_controller.rb
test/controllers/content_items_controller_test.rb
test/controllers/travel_advice_controller_test.rb

An update to https://github.com/alphagov/government-frontend/pull/326
We should add this header for all atom pages served by government-frontend
so move the logic into the parent ContentItemsController.

Move Access-Control-Allow-Origin header into parent controller

---

app/presenters/specialist_document_presenter.rb
test/integration/specialist_document_test.rb
test/presenters/specialist_document_presenter_test.rb

https://trello.com/c/al2fPH5p/192-1-render-missing-finder-metadata-in-government-frontend
* Add facet values to metadata and document footer now they're provided by the finder in the links hash. Assumes that all possible facet values could be multiple and so normalizes values as an array before working with them. Multiple values get joined with a comma.
* Add custom breadcrumb based on finder
* Fix logic for display of `updated` field in metadata and footer
* Sends Airbrake notifications when missing finder or forbidden facet value found
* The random content generator doesn't create random facets and values
| Facet type | Allowed values | Filterable | Displays |
|--|--|--|--|
| Text | True | True | Shows the allowed value labels with links to the filtered results
| Text | True | False | …

Add facet metadata to specialist documents

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/helpers/_button.scss
app/controllers/travel_advice_controller.rb
app/presenters/specialist_document_presenter.rb
app/views/content_items/specialist_document.html.erb
app/views/shared/_button.html.erb
test/integration/specialist_document_test.rb
test/presenters/specialist_document_presenter_test.rb

I've added the button in a way that it should be easy to move to be a [GOV.UK Publishing Component](http://govuk-component-guide.herokuapp.com/)
cc @rubenarakelyan I've ended up using the same approach you started with using GOV.UK Elements but I've tried to reduce the amount of global conflict by only adding what's needed with some added comments. Apologies for making you change it the first time!

Add buttons rendering to specialist documents

---

app/presenters/html_publication_presenter.rb
app/views/content_items/html_publication/_print_meta_data.html.erb
test/integration/html_publication_test.rb
test/presenters/html_publication_presenter_test.rb

[Trello card](https://trello.com/c/OEZIdXTE/135-separate-file-attachment-form-and-html-attachment-form)
Depends on: 
https://github.com/alphagov/whitehall/pull/3170
https://github.com/alphagov/govuk-content-schemas/pull/607
It was pointed out that the "ISBN (web version)" field is showing up not only in the HTML Attachments form, but also in the File Attachments form. This is becoming confusing to people, as they were entering the Print ISBN in that field. The two forms will now show different content. 
This PR will separate the "ISBN (web version)" field into "Print ISBN" and "Web ISBN". 
Both fields are optional and will appear (if present) when an HTML publication is printed.

Splits ISBN into print ISBN and web ISBN

---

app/assets/stylesheets/helpers/_dash-list.scss
app/helpers/typography_helper.rb
app/presenters/contents_list.rb
app/presenters/specialist_document_presenter.rb
app/views/content_items/specialist_document.html.erb
app/views/shared/_nested_content_item.html.erb
app/views/shared/_sidebar_contents.html.erb
test/integration/specialist_document_test.rb
test/presenters/specialist_document_presenter_test.rb

https://trello.com/c/phs722pV/186-1-add-new-contents-list
* Use an em dash for all contents lists
* Include a two level contents list (based on h2s and h3s)
* Style the h2s without a list marker and in bold
* h3s appear like standard contents lists
* h4s and further, although appearing in the `headers` hash are not displayed – at this level the contents list stops being useful
* Markup mostly ported from specialist-frontend
* Move strip_trailing_colons into shared helper
| Nested | Normal |
|--|--|
|![screen shot 2017-04-19 at 11 24 55](https://cloud.githubusercontent.com/assets/319055/25177735/e26b741c-24fa-11e7-947e-89771ee545ea.png)|![screen shot 2017-04-19 at 11 25 00](https://cloud.githubusercontent.com/assets/319055/25177736/e285ba66-24fa-11e7-86e9-c60358e98aa9.png)|
On older …

Render nested contents for specialist documents

---

app/views/shared/_description.html.erb

Avoid printing an empty paragraph when there is no description.
* Some specialist documents have no description
* Description is required, but it can be an empty string
Live example:
https://www.gov.uk/aaib-reports/vans-rv-9a-g-cdmf-2-september-2007

Don't render description when there isn't one

---

Gemfile
Gemfile.lock

This fixes the issue with repeated related links across different
taxons.
Trello: https://trello.com/c/I4rs80n1/80-remove-duplicated-related-links-across-all-parent-taxons

Upgrade to govuk_navigation_helpers 6.0.1

---

app/assets/stylesheets/views/_specialist-document.scss
app/presenters/specialist_document_presenter.rb
test/integration/specialist_document_test.rb
test/presenters/specialist_document_presenter_test.rb
test/wraith/config.yaml

* Add most popular specialist docs to wraith - example output: shy-coil.surge.sh/gallery.html
* Pass array of facet values to components to match specialist-frontend
* When multiple values are passed to the document footer it render each of them on a new line.
* When multiple values are passed to metadata it joins them and puts 'and' between the last two values
* Group date facets together. Makes dates more comparable and matches specialist-frontend ordering.
* Give specialist metadata more room using same CSS hack as specialist-frontend
* Use first_published_at in facets as canonical value
Some specialist document types (drug safety updates, DFID research outcomes) include a “first_published_at” facet.
These documents have been published earlier, in a publication elsewhere. eg Time …

Tweak specialist documents to match specialist-frontend rendering

---

app/presenters/specialist_document_presenter.rb
test/presenters/specialist_document_presenter_test.rb

If a facet has no value, ignore it.
Fixes:
Seen on staging, a CMA case has a date facet set to an empty string:
https://www.gov.uk/api/content/cma-cases/midcounties-co-operative-harry-tuffin-investments
`"opened_date": “”`
__Object must be a Date, DateTime or Time object. nil given.__
See also:
https://www.gov.uk/api/content/cma-cases/higher-education-sector-call-for-information
`"outcome_type": "",`
Gives:
```ruby
{
"error_message" => "Facet value '' not an allowed value for facet 'Outcome' on /cma-cases/higher-education-sector-call-for-information content item"
}
```

Ignore facets that are set to empty strings

---

README.md

Publications and Document Collections have their draft rendered by
government-frontend. Update README to reflect this by removing the
explicit exceptions in the list of formats.

Update README to remove draft rendering exceptions

---

app/models/education_navigation_ab_test_request.rb

More details on what guidance is in here:
https://github.com/alphagov/govuk_document_types/blob/master/data/supertypes.yml#L6-L27
We should be showing the new navigation elements for all those document
types. This PR extends the list to the ones that have education content
and were missing from this repository.

Extend the schema list for Education Navigation

---

app/assets/stylesheets/views/_guide.scss
app/views/content_items/_body_with_related_links.html.erb
app/views/content_items/guide.html+print.erb
app/views/content_items/guide.html.erb

Part of https://trello.com/c/g01dZWdI/238-3-render-guides-in-government-frontend-sprint-2
See: https://github.com/alphagov/static/pull/1020
Content on mainstream was not written with expansion enabled, some links to YouTube expand in ways that break content:
eg A link to a video in a list: http://www.gov.uk/attendance-allowance/what-youll-get

Tweaks to Guides to match live

---

app/assets/stylesheets/helpers/_button.scss
app/views/shared/_button.html.erb
test/integration/specialist_document_test.rb

Publishers copy and paste markup into mainstream content to render
buttons. Buttons should be a markdown pattern/component/combination.
* For now, make sure they render correctly so we can switch guides
* Fix bug on live where focus/active state shows in blue (Element button styles aren’t specific enough to override govspeak ones)
* Rename `button-info` to `button-info-text` so it’s not confused as a button type.
Steps to take after this:
* Add markdown pattern for buttons and start buttons
* Move styling of buttons into static component that can be shared with govspeak

Style buttons in govspeak as start buttons

---

startup.sh

If you use `./startup.sh --live`, you should also be able to override
the locations of static or the content store using the normal
environment variables

Allow overriding the defaults for `--live`

---

app/models/education_navigation_ab_test_request.rb
app/views/content_items/contact.html.erb
app/views/content_items/guide.html.erb
app/views/shared/_related_items.html+new_navigation.erb
app/views/shared/_related_items.html.erb
test/controllers/content_items_controller_test.rb

* AB tests are being run against guides on frontend, port the same logic here
* Update contacts so AB tests for contacts  work
* Run test suite for AB tests against all supported test schemas
* Switch to shared related links template to pick up ‘new navigation’ variant on contacts and guides
cc @nickcolley @carvil

Run AB tests on guides and contacts

---

app/services/mainstream_content_fetcher.rb
app/views/shared/_related_items.html+new_navigation.erb
config/mainstream_content_with_curated_sidebar.json
test/controllers/content_items_controller_test.rb

We are in the process of releasing the new navigation for Education
content. One item that needs to be solved from a product perspective is
how to deal with curated related links. Until that's solved, some
content items still need to show the old related links instead of the
new navigation for users in the B group of our A/B test.
These overrides existed in the `frontend` application. Since `answers`
were ported to `government-frontend`, we also need to port the override.
Trello: https://trello.com/c/U6JKZN6s/115-make-sure-we-override-the-related-links-on-some-mainstream-content-that-was-recently-moved-to-government-frontend

Show old related links for selected content items

---

app/presenters/guide_presenter.rb
app/views/content_items/guide.html.erb
app/views/content_items/travel_advice.html.erb
config/locales/cy.yml
config/locales/en.yml

* Port translations from alphagov/frontend: https://github.com/alphagov/frontend/blob/dab7d54bf45d1ca529896c0c618bde2f3d433cf9/config/locales/cy.yml
* Welsh literally means: “Navigate to next/previous part” and “Printer friendly page”

Translate print and page navigation into Welsh

---

app/presenters/corporate_information_page_presenter.rb
test/presenters/corporate_information_page_presenter_test.rb

When previewing a Corporate Information page in Whitehall, a bug was found
where the content didn't display. This is because Corporate Information pages
don't currently use edition links, and so the CorporateInformationPagePresenter
couldn't find `organisations` in the `links` hash.  This fix allows
CorporateInformationPagePresenter to handle this more gracefully.

Fix CorporateInformationPage Preview bug

---

app/views/content_items/_body_with_related_links.html.erb
app/views/content_items/guide.html+print.erb
app/views/content_items/guide.html.erb

we missed this out on the migration, it is generally not allowed,
but mainstream uses it quite a lot.

Add bold back into mainstream content

---

config/mainstream_content_with_curated_sidebar.json

We are in the process of releasing the new navigation for Education
content. One item that needs to be solved from a product perspective is
how to deal with curated related links. Until that's solved, some
content items still need to show the old related links instead of the
new navigation for users in the B group of our A/B test.
These overrides existed in the frontend application. Since guides
were ported to government-frontend, we also need to port the override.
Trello: https://trello.com/c/U6JKZN6s/115-make-sure-we-override-the-related-links-on-some-mainstream-content-that-was-recently-moved-to-government-frontend
In order to prevent this happening in the future, I added a Smokey test:
- https://github.com/alphagov/smokey/pull/262
Which is failing (tested the branch on staging …

Show old related links for selected Guides

---

app/presenters/guide_presenter.rb
app/presenters/parts.rb
app/presenters/travel_advice_presenter.rb
app/views/content_items/travel_advice.html+print.erb
app/views/content_items/travel_advice.html.erb
test/integration/guide_test.rb
test/integration/travel_advice_test.rb
test/presenters/guide_presenter_test.rb
test/presenters/parts_test.rb
test/presenters/travel_advice_presenter_test.rb

* When linking to the first part of a guide, link to the base path. eg: www.gov.uk/attendance-allowance/overview is identical to www.gov.uk/attendance-allowance – avoids duplicate URLs with the same content.
* This also works with travel advice summaries. Summaries are not included as a part by the content item, but for all purposes, the frontend renders it as a part. Coerce summary into being the first part, which conveniently has no slug, so links to the base_path like the first part of a guide.
* Now parts logic is common between travel advice and guides the logic for next and previous pagination can be shared
* Add pagination to travel advice, ensuring that the link to the first part is without slug

Add pagination to travel advice

---

config/locales/en.yml

`world_news_story` is a new sub-type of `NewsArticle` that we are migrating the `WorldLocationNewsArticle` format to.
This commit adds it to the `en.yml` file to allow it to be rendered without a missing translation warning.

Add `world_news_story` to en.yml

---

app/assets/javascripts/modules/ukvi_ab_test.js
app/presenters/guide_presenter.rb
app/presenters/ukvi_ab_test.rb
app/views/ab_testing/_ukvi_knowledge_of_english_section.html.erb
app/views/ab_testing/_ukvi_overview_section.html.erb
app/views/content_items/guide.html.erb
test/presenters/ukvi_ab_test_test.rb

Supersedes https://github.com/alphagov/frontend/pull/1228
Still suffers from some of the problems highlighted here: https://github.com/alphagov/frontend/pull/1228#pullrequestreview-37664574
We want to avoid those problems but need to get the test out on Monday.
* Add unit test for Ukvi AB test – check that only two guides run the
test, and only on two specific parts
* Use JS module pattern for handling content switch on frontend
Sets up a frontend AB test for the following UKVI page sections:
- /remain-in-uk-family/*
- /join-family-in-uk/*
Cohorts across the aforementioned UKVI page sections fall under the
following:
- original (with a 50% weighting)
- spouseProminent (with a 50% weighting)

Add UKVI AB test with presenter and JS module

---

app/presenters/body.rb
app/presenters/case_study_presenter.rb
app/presenters/consultation_presenter.rb
app/presenters/corporate_information_page_presenter.rb
app/presenters/detailed_guide_presenter.rb
app/presenters/document_collection_presenter.rb
app/presenters/fatality_notice_presenter.rb
app/presenters/html_publication_presenter.rb
app/presenters/news_article_presenter.rb
app/presenters/specialist_document_presenter.rb
app/presenters/speech_presenter.rb
app/presenters/statistical_data_set_presenter.rb
app/presenters/take_part_presenter.rb
app/presenters/topical_event_about_page_presenter.rb
app/presenters/working_group_presenter.rb
app/presenters/world_location_news_article_presenter.rb
app/views/content_items/consultation.html.erb
app/views/content_items/detailed_guide.html+new_navigation.erb
app/views/content_items/detailed_guide.html.erb
app/views/content_items/document_collection.html+new_navigation.erb
app/views/content_items/document_collection.html.erb
app/views/content_items/specialist_document.html.erb

* Include `Body` module on all presenters that pull out `details.body`
* Provide a standard method for rendering the govspeak component with the body text

Use a shared body module

---

app/controllers/content_items_controller.rb
app/presenters/guide_presenter.rb
test/integration/guide_test.rb
test/presenters/guide_presenter_test.rb

Fact checkers are given an access token to let them view content without a sign on account. For multi page content this token doesn’t persist when fact checkers click part navigation.
* When tokens exist append them to part links in navigation and pagination
* Loosely based on https://github.com/alphagov/frontend/pull/1133/files#diff-55c5b7aecfb519d0e4880eaf2788eb6eR127 (default_url_params don’t work unless you’re
using Rails path helpers)
Ideally government-frontend would only do this on the draft stack, but it has no knowledge of what content store/stack it is using.
cc @davidbasalla @whoojemaflip @suzannehamilton

Append draft access token to parts links on guides

---

README.md
lib/helpers/document_types_helper.rb
lib/helpers/wraith_config_helper.rb
lib/tasks/wraith.rake

__As__ a developer
__I want__ a up-to-date config of all document types in government-frontend
__So__ that I can use this for wraith testing with more confidence
Trello: https://trello.com/c/WqIzOp6X/358-1-make-wraith-rake-task-cover-all-document-in-government-frontend
This PR adds two new `rake` tasks:
`wraith:update_document_types` - generates a file of example pages and document_types rendered by `government_frontend`
`wraith:all_document_types` - runs visual regression tests across all examples found via `wraith:update_document_types`
http://axiomatic-reaction.surge.sh/wip-config-all-document-types.yaml

Visual regression testing across document_types

---

app/views/content_items/html_publication.html.erb
app/views/layouts/application.html.erb
app/views/shared/_webchat.html.erb

Reverts alphagov/government-frontend#331
There is a bug in versions of Firefox < v52 (https://bugzilla.mozilla.org/show_bug.cgi?id=1269241) where the SHA integrity check fails as mismatched for stylesheets. 
This meant that older versions of Firefox did not receive `government-frontend` application specific styles - this lead to broken layouts in formats rendered by `government-frontend`.
Reverting this for now until we have time to investigate further cc: @h-lame

Revert "Adds SRI"

---

app/assets/stylesheets/helpers/_button.scss
app/controllers/concerns/epilepsy_driving_start_button_variant_ab_testable.rb
app/controllers/content_items_controller.rb
app/presenters/answer_presenter.rb
app/views/content_items/_body_with_related_links.html.erb
test/controllers/content_items_controller_test.rb

Trello card: https://trello.com/c/9ZPkxHjH
Content Team want to AB Test changing the call to action on [Epilepsy and Driving](https://www.gov.uk/epilepsy-and-driving) page from a link within the body of text to a Start Button.
The test is to run for 30 days. Related PR for Fastly config is https://github.com/alphagov/fastly-configure/pull/23
The downside is that as the B variant body content is hard coded, the A variant can't be changed during the course of the test.
[Page on GOV.UK](https://www.gov.uk/epilepsy-and-driving)
[Preview](https://government-frontend-pr-369.herokuapp.com/epilepsy-and-driving)
If you have the `GOVUK-ABTest-EpilepsyDrivingStart` request header set with a value of `B` you will see the start button.

Add epilepsy driving start ab test

---

app/assets/javascripts/webchat/library.js
spec/javascripts/webchat.spec.js

HMRC (Jonathan Lewis I CDIO Digital Services) are trying to reduce the
amount of people going through to their webchat, they've asked us to
increase the timeout so that there's less chance of a user seeing a stale
'available' state which would allow them to proceed.
We want to make sure we can revert and deploy this if HMRC decide this has impacted them negatively.
Marked as [Do not merge] while we talk with HMRC about when we can deploy this.

Reduce timeout from 15s to 10s for Webchat availability polling

---

Gemfile
Gemfile.lock
config/environments/production.rb

Memcached is now available on the frontend boxes, so use that instead of the in-process cache.

Use memcached in production.

---

Gemfile
Gemfile.lock

We're trying to make government-frontend's errors less noisy so they're more actionable.
Example of the error in errbit: https://errbit.publishing.service.gov.uk/apps/546493f90da1150e4e001cfc/problems/5908989565786317fcf23200
This change adds a gem that was present in alphagov/frontend (https://github.com/alphagov/frontend/blob/master/Gemfile#L15)
Up for discussion if there's a better way to do this these days though, let me know 👍 
https://trello.com/c/mA90nTTZ/89-silence-ip-spoofing-warnings-in-errbit

Strip client IP and remove noisy errors in production

---

test/integration/guide_test.rb
test/integration/html_publication_test.rb
test/test_helper.rb

The `JSON.parse` method omitted `content_store_has_item` which meant the content store wasn’t always stubbed with the example – sometimes this test would fail, sometimes it would pass, depending on the tests that ran before it.
Avoid risk that this could happen again by updating `setup_and_visit_content_item` to take URL params.

Fix intermittent test failure on guides

---

app/controllers/content_items_controller.rb
test/controllers/content_items_controller_test.rb

I'm not sure this should be dealt with at this level since
I believe the characters used in our test (and seen in our error reporting)
is valid per the URL spec, but I'd like to make sure users see a
consistent error page and status code.
I'd love a better solution if anyone has any ideas.

Ensure GdsAPI::InvalidUrl exception results in a 404

---

app/assets/javascripts/modules/track-html-publication-contents.js
app/views/content_items/html_publication.html.erb
spec/javascripts/track-html-publication-contents.spec.js

* Track clicks on contents lists
* We can’t modify HTML Pub contents lists easily, instead write a new
module to add event listeners on the parent and track links via click
events within it
* Use category and action defined on parent container
* Use the target of the link as the label
When we move the position of contents lists, and if we use the standard ContentsList functionality, then this custom tracking can be removed.
https://trello.com/c/z3YCn9zf/424-implement-ga-tracking-on-html-publication-content-list
@nickcolley @andysellick

Add link tracking to HTML Publication contents lists

---

Gemfile
Gemfile.lock

* Rails 5 compatibility, stops deprecation warning
More details: https://github.com/alext/rack_strip_client_ip/pull/1

Bump rack_strip_client_ip to 0.0.2

---

app/presenters/linkable.rb
app/services/world_location_base_path.rb
test/services/world_location_base_path_test.rb

World location links are becoming base_path-less and will no longer support translations. We still need to generate a link to these in the frontend end. 
Initially, in this commit the link will continue to point to the Whitehall representation of the world location.
In a subsequent commit, once the routing is in place, the `WorldLocationBasePath` class will be updated to generate a link to the new `/world/<slug>` taxon.
This PR needs https://github.com/alphagov/govuk-content-schemas/pull/629 to be deployed before CI will pass.
Part of [Trello](https://trello.com/c/6tio72jl/221-split-world-locations-from-international-delegations-in-whitehall)

Fix world location links

---

test/integration/world_location_news_article_test.rb

This test expects an incorrect base_path from the schema examples. The examples are fixed but schemas can't pass CI currently as this test fails now the base_path has been removed and is being inferred from the world location title.
This commit will be updated with the correct test once schemas are deployed.

Fix WLNA metadata test

---

test/integration/world_location_news_article_test.rb

Fixes linter error introduced in https://github.com/alphagov/government-frontend/pull/389 which didn't arise until that PR was merged into master.

Fix linter error

---

app/presenters/contact_presenter.rb
test/presenters/contact_presenter_test.rb

The postcode was displaying in an odd position in address blocks,
between the locality and region. This moves the postcode down a line,
so it will display at the bottom of the address, just above the country.

Move the Postcode line in the presented Postal Address

---

test/integration/case_study_test.rb
test/integration/world_location_news_article_test.rb

The links for world locations are now base_path-less in the schema examples. 
This PR:
* removes a temporary fix to a test that was preventing the schema changes from being merged. 
* adds a test on a document type other than `WorldLocationNewsArticle` for the base_path-less world location links as WLNA will be being removed very soon
[Trello](https://trello.com/c/6tio72jl/221-split-world-locations-from-international-delegations-in-whitehall)

Update tests for new world location links

---

app/assets/stylesheets/helpers/_back-to-content.scss
app/assets/stylesheets/print.scss
app/assets/stylesheets/print/_html-publication.scss
app/assets/stylesheets/views/_html-publication.scss
app/helpers/contents_list_helper.rb
app/presenters/contents_list.rb
app/presenters/html_publication_presenter.rb
app/views/content_items/html_publication.html.erb
app/views/shared/_sidebar_contents.html.erb
test/helpers/contents_list_helper_test.rb
test/integration/detailed_guide_test.rb
test/integration/guide_test.rb
test/integration/html_publication_test.rb
test/presenters/contents_list_test.rb
test/presenters/html_publication_presenter_test.rb
test/wraith/config.yaml

Goes alongside this static PR: https://github.com/alphagov/static/issues/1073
* Contents moved into left nav area and uses ContentsList for output
* Contents adjusted so number and text of link are wrapped in separate spans for better styling and test added
* Contents styled with indented numbering if numbering present
* Contents link overlap fixed with some z-indexing, background and box shadow on contents list, so the contents link disappears behind
* Content heading numbering size reduced and repositioned to be inline
* Publication header (blue box) padding made even and publication date font size reduced and moved up
* Print view fixed following layout changes, print styles updated and hidden crown copyright text moved out of header and below contents list to maintain original print …

Move HTML Publication contents list from top to left

---

app/services/world_location_base_path.rb
test/integration/case_study_test.rb
test/integration/world_location_news_article_test.rb
test/presenters/case_study_presenter_test.rb
test/services/world_location_base_path_test.rb

Content that was previously at `/government/world/` has been moved to `/world/`. This commit updates the `WorldLocationBasePath` class to use the new `base_path` prefix for world links.
[Trello](https://trello.com/c/081lboCr/253-update-government-frontend-worldlocationbasepath-to-point-to-world)

Update WorldLocationBasePath for new route

---

Gemfile
Gemfile.lock
test/integration/government_navigation_test.rb
test/integration/guide_print_test.rb
test/integration/phase_label_test.rb
test/integration/topical_event_about_page_test.rb
test/integration/travel_advice_atom_feed_test.rb
test/integration/travel_advice_print_test.rb
test/integration/travel_advice_test.rb
test/support/govuk_content_schema_examples.rb
test/test_helper.rb

This gem can also fetch the examples. It has a slightly nicer interface which means we don't have to mess around with JSON deserialisation.

Use govuk_schemas gem for examples too

---

app/assets/stylesheets/views/_html-publication.scss
app/helpers/contents_list_helper.rb
test/helpers/contents_list_helper_test.rb

Publishers can enter custom numbers. Add support for the forms:
* Numbers without periods (1)
* Numbers with decimals (1.2)
* Allow long numbers to be spaced correctly and not wrap badly (100.)
* Ignore numbers bigger than 999 (eg 2014)
* Ignore contents items that are just numbers
A list of HTML publications with custom numbering:
https://gist.github.com/fofr/622c0c52dfee41cde9402c56ec5d67ea
https://www.gov.uk/government/publications/xbrl-guide-for-uk-businesses/xbrl-guide-for-uk-businesses
| Old | New |
|-|-|
|![screen shot 2017-06-29 at 16 49 17](https://user-images.githubusercontent.com/319055/27697106-3c9176ee-5ceb-11e7-8675-7a308e9f6833.png)|![screen shot 2017-06-29 at 16 51 16](https://user-images.githubusercontent.com/319055/27697105-3c8f2222-5ceb-11e7-9230-f6f15f35cd55.png)| …

Allow HTML pub contents to render cleanly with custom numbers

---

app/views/content_items/_document_collection_body.html.erb
app/views/content_items/document_collection.html+new_navigation.erb
app/views/content_items/document_collection.html.erb
test/integration/document_collection_test.rb

In this PR:
- Move the main body of document collections into partial, in order to reuse across the old and new navigation partials;
- Add tracking attributes to all links within document collections.
Here is an example tracking event:
```
ga("send", {hitType: "event", eventCategory: "navDocumentCollectionLinkClicked", eventAction: "3.2", eventLabel: "/government/publications/2017-national-curriculum-assessment-results-at-the-end-of-key-stage-2-information-for-parents", dimension15: "200", dimension16: "unknown", dimension11: "2", dimension2: "document_collection", dimension3: "education", dimension4: "e1046852-d15f-4990-a2d5-d813926b2edb", dimension6: "2015-conservative-government", dimension7: "non-political", dimension9: "<EA243>", dimension17: "document_collection", dimension20: …
```

Track document collection clicks

---

Gemfile
Gemfile.lock
app/views/content_items/html_publication.html.erb
app/views/layouts/application.html.erb
app/views/shared/_webchat.html.erb

This is take 2 of: https://trello.com/c/oFhtO0Gm/146-enable-subresource-integrity-sri-on-government-frontend-l
This attempt uses the new [asset_bom_removal-rails](https://github.com/alphagov/asset_bom_removal-rails) gem to remove the utf-8 BOM from compressed CSS files and avoid triggering the bug in Firefox < 52 that was stopping us from deploying the previous version (see https://trello.com/c/UcJJBH0k/183-investigate-bom-issue-with-asset-compilation for more details on this).
Take 1 of this was done in #331, and subsequently reverted in #368 when we found the bug.

Add sri again

---

Gemfile
Gemfile.lock
app/views/content_items/html_publication.html.erb
app/views/layouts/application.html.erb
app/views/shared/_webchat.html.erb

Reverts alphagov/government-frontend#400
Turns out the BOM removal does it's job too well and strips 2 characters from the start of the CSS file as well as the BOM.  We need to roll this back while we fix the BOM removal gem.  (See https://assets.publishing.service.gov.uk/government-frontend/application-acf2d14564cab50b1e96d787cd3889dae8d548ec68a47a165b5f93fcb0606dfc.css which starts `vailable-languages` and should be `.available-languages`)

Revert "Add sri again"

---

config/initializers/govuk_publishing_components.rb
config/routes.rb

- govuk publishing components is only included when in dev and test environments
- the initialiser doesn't therefore work in production
- only run the initialiser if the module is defined

Check GovukPublishingComponents exists before init

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_download-link.scss
app/assets/stylesheets/views/_travel-advice.scss
app/views/components/_download-link.html.erb
app/views/components/docs/download-link.yml
app/views/shared/_travel_advice_summary.html.erb
test/components/download_link_test.rb

- Replaces the existing download map link in travel advice pages.
- Takes parameters for href and link text
- Deliberately errors if no href is provided
- Documented in the component guide (shown below):

Create download link component

---

Gemfile
Gemfile.lock
app/views/content_items/html_publication.html.erb
app/views/layouts/application.html.erb
app/views/shared/_webchat.html.erb

This is version 3 of #331 and #400.  In both cases we added SRI and then realised that it broke something so had to revert them (#368 and #401 respectively).  Hopefully this version will last a bit longer.
The problem last time was that the BOM removal gem was overzealous and removed 2 extra characters from the CSS file when it removed the BOM.  We fixed this in the gem (see https://github.com/alphagov/asset_bom_removal-rails/pull/6 for the full details) and so this PR repeats #400 and bumps the included gem version.
For: https://trello.com/c/oFhtO0Gm/146-enable-subresource-integrity-sri-on-government-frontend-l

Add SRI again (again)

---

app/views/content_items/consultation.html.erb

When a consultation has many attachments, the description is below the
documents and users may miss important information.
This was brought up in the Snook discovery into Consultations.

Move description above documents

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_subscription-links.scss
app/assets/stylesheets/views/_travel-advice.scss
app/views/components/_subscription-links.html.erb
app/views/components/docs/subscription-links.yml
app/views/content_items/travel_advice.html.erb
test/components/subscription_links_test.rb

- displays email alerts and subscribe to feed links
- accepts link values for either link or both
- displays nothing if nothing passed
https://trello.com/c/qcNOt0MY/40-1-convert-subscription-links-to-components

Add subscription links component

---

Gemfile
Gemfile.lock
config/routes.rb

We need the component guide to be available in Heroku preview apps to check components in pull requests and to link to versions of the guide.
* We don't want the component guide to render in production mode
* Heroku review apps have the production environment set
* Make a special case for including the guide when a HEROKU env
variable has been set
* This allows us to link users to a PR's component guide or master’s
https://government-frontend-pr-416.herokuapp.com/component-guide

Allow component guide to render on Heroku

---

config/initializers/govuk_publishing_components.rb

Make the component guide visible to developers working on the application.
https://trello.com/c/kXABQ1vo/61-1-echo-the-link-from-application-boot

Link to component guide when starting app in dev mode

---

app/views/content_items/consultation.html.erb

- restore line break between summary text and consultation held on another website text
Wrong:
Better:

Fix banner extra paragraph layout

---

app/assets/javascripts/webchat/library.js
spec/javascripts/webchat.spec.js

Graham Orr from HMRC:
"We have previously requested that all webchat links have their update time reduced from 15 to 10 seconds as an experiment.
The experiment was a success and we would now like the webchat update time to be lowered from 10 seconds down to 5 seconds."
Do not merge until Monday 07/08/17

Reduce timeout from 10s to 5s for Webchat availability polling

---

app/views/components/_translation-nav.html.erb
test/components/translation_nav_test.rb

Fix issue where “English” is showing by itself on all English detailed guides.
Update translation nav component to only output navigation if there’s
more than one available translation. If there's only one then it's
the current page and the text is redundant.
Fixes:

Don't render translations when only one available

---

app/views/content_items/consultation.html.erb

This commit fixes the notice title for unopened consultations, which was incorrect following the move from the notice pattern to the notice component.

Fix the title of the notice for unopened consultations

---

app/views/layouts/application.html.erb

- skip to content link now bypasses the breadcrumb
- change made to keep us consistent following the same change to Elements
https://trello.com/c/IsxWIQXQ/21-2-investigate-work-needed-to-have-breadcrumbs-consistent-with-govuk-elements

Move the breadcrumb outside of the main element

---

Gemfile
Gemfile.lock
config/initializers/airbrake.rb

We’re seeing some errors with Airbrake 5:
`Airbrake: falling back to sync delivery because there are no running async workers`
`Airbrake: unexpected code (200). Body: {“notice”: … }`
Also fixes other incompatibilities outlined in
https://docs.publishing.service.gov.uk/manual/upgrade-rails.html#airbrake
Downgrades to version 4 with custom branch we are using along with default config:
https://github.com/alphagov/govuk-rails-app-template/blob/master/templates/config/initializers/airbrake.rb
See also:
https://github.com/errbit/errbit/issues/1087#issuecomment-227627038

Downgrade Airbrake and use standard config

---

app/controllers/content_items_controller.rb
test/controllers/content_items_controller_test.rb

When a request is made for an unsupported format, eg text/javascript, the lack of a respond_to block meant we attempted to render it without a layout.
This led to a body being sent to slimmer without a #wrapper element,
causing the error:
`> undefined method 'to_html' for nil:NilClass`
in the BodyInserter processor
* Add a respond_to block to respond only to known formats
* Catch unknown format errors and return 406 (not acceptable)
This matches: https://github.com/alphagov/finder-frontend/pull/271
`format.html` must come before `format.atom` in the block. If a browser sends an unspecific accepts header, eg `*/*`, Rails falls through to the first format/variant declared in `respond_to`.
See also: https://github.com/gds-attic/multipage-frontend/pull/23

Return 406 status for unsupported formats

---

app/presenters/specialist_document_presenter.rb
test/presenters/specialist_document_presenter_test.rb

For certain AAIB reports the publish date is the date the site was scraped rather than the date the report was first published. Ideally the data in the content item would be correct.
https://trello.com/c/FhAbqDhg/
https://govuk.zendesk.com/agent/tickets/2293473
Example:
https://www.gov.uk/aaib-reports/lockheed-l1011-385-1-15-g-bhbr-19-december-1989
Also memoize the result of first_public_at to avoid repetitive sorting of the change history, which could be timely if long.

Suppress first published date for  bulk published specialist documents

---

app/views/content_items/consultation.html.erb

Make it possible to link to this part of a consultation (eg where the banner is)

Add missing ID from consultations

---

app/assets/stylesheets/components/_figure.scss
app/assets/stylesheets/helpers/_sidebar-with-body.scss
app/assets/stylesheets/views/_travel-advice.scss
app/views/components/_figure.html.erb
app/views/components/docs/figure.yml
app/views/shared/_sidebar_image.html.erb
app/views/shared/_travel_advice_summary.html.erb
test/components/figure_test.rb

The image component:
* Replaces existing responsive sidebar images
* Takes parameters for href, alt text and caption
* Deliberately errors if no href or alt text is given
* Is documented in the component guide (shown below)
Note: rendering of this component in the component guide currently uses an image URL from a GOV.UK page - if there are any other suggestions for images to use as an example in the guide, feel free to suggest.
Examples:
* [Case Study](https://government-frontend-pr-448.herokuapp.com/government/case-studies/2013-elections-in-swaziland)
* [News Article](https://government-frontend-pr-448.herokuapp.com/government/news/the-personal-independence-payment-amendment-regulations-2017-statement-by-paul-gray)
* [Travel Advice](https://government-frontend-pr-448.herokuapp.com/foreig …

Create figure component

---

app/helpers/contents_list_helper.rb
app/views/components/_banner.html.erb
app/views/components/_notice.html.erb
app/views/components/docs/banner.yml
app/views/components/docs/contents-list.yml
app/views/components/docs/download-link.yml
app/views/components/docs/heading.yml
app/views/components/docs/lead-paragraph.yml
app/views/components/docs/notice.yml
app/views/components/docs/print-link.yml
app/views/components/docs/share-links.yml
app/views/components/docs/subscription-links.yml
app/views/components/docs/translation-nav.yml
test/components/banner_test.rb
test/components/notice_test.rb
test/helpers/contents_list_helper_test.rb

Updates to accessibility acceptance criteria following a review from @LJWatson, with corresponding updates to improve accessibility of components.
The updated components and guide are available for [review on Heroku](https://government-frontend-pr-449.herokuapp.com/component-guide).
* Update accessibility acceptance criteria for banner, notice, contents list and link components
* Put space between contents number and text for better screen reader pronunciation
* Put notices and banners in `<section>` elements and include aria-label to give an accessible name
This doesn't include fixes for issues we're tracking separately in #441, #442 and #443

Improve accessibility and accessibility documentation of components

---

app/assets/stylesheets/components/_translation-nav.scss
app/views/components/_translation-nav.html.erb
app/views/components/docs/translation-nav.yml
config/locales/en.yml
test/components/translation_nav_test.rb
test/integration/news_article_test.rb
test/integration/world_location_news_article_test.rb

Best reviewed commit by commit.
https://government-frontend-pr-453.herokuapp.com/component-guide/translation-nav
* Switch to a nav element with an aria-label that can be translated (we don't have translations yet)
* Include the lang element on the currently active navigation element as a precaution
* Add links to WCAG for providing lang context and link to example video of pronunciation
* Include tests for each accessibility change to avoid regressions
Also includes some small cleanups:
* removes double double underscore from BEM
* simplifies tests
* whitespace in locale file
* tweak to fixture input (Français)
Fixes #443

Improve translation navigation accessibility

---

app/views/components/_notice.html.erb
app/views/components/docs/notice.yml
test/components/notice_test.rb

The notice component was not accessible as headings were being used without any content following.
A check is now done to see if description is present before placing the title in a heading or paragraph.
Fixes issue #442

Only use heading in notice if description present

---

app/views/content_items/publication.html+new_navigation.erb
app/views/content_items/publication.html.erb
config/environments/development.rb
config/environments/test.rb

Raise errors for missing translations in dev and test
* Catch missing translations
* Fix incorrect reference to translation: Change `publication` to `publications`

Raise errors for missing translations in dev and test

---

app/services/world_location_base_path.rb
test/integration/case_study_test.rb
test/integration/world_location_news_article_test.rb
test/presenters/case_study_presenter_test.rb
test/services/world_location_base_path_test.rb

This commit changes the generated path for world locations to point to `/world/location/news` since most things tagged to a world location and rendered by government-frontend are things that would appear on the world location news page.
Trello: https://trello.com/c/9RRoTUXO/128-change-world-location-path-in-government-frontend-to-world-location-news

Change path for world locations

---

app/views/content_items/corporate_information_page.html.erb
config/locales/en.yml
test/integration/corporate_information_page_test.rb

Withdrawal notices are now included on corporate information pages when the content_item includes withdrawn_notice data.
**Before:**
**After:**
Examples of withdrawn corporate information pages:
- [Monitor Media Enquiries](https://www.gov.uk/government/organisations/monitor/about/media-enquiries)
- [Highways Agency About Page](https://www.gov.uk/government/organisations/highways-agency/about)
- [DSA Statistics](https://www.gov.uk/government/organisations/driving-standards-agency/about/statistics)

Include withdrawn notice on corporate info pages

---

app/helpers/application_helper.rb
app/views/shared/_breadcrumbs.html+new_navigation.erb
test/helpers/application_helper_test.rb

For: https://trello.com/c/Bo5SQrIm/215-add-page-tracking-custom-dimension-into-education-beta-survey-banner
This lets the survey team know where each response has come from and
allows them to filter by section of the site.

Add current_path to the survey link in the beta banner

---

app/assets/stylesheets/components/_document-list.scss
app/assets/stylesheets/views/_document-collection.scss
app/presenters/document_collection_presenter.rb
app/views/components/_document-list.html.erb
app/views/components/docs/document-list.yml
app/views/content_items/_document_collection_body.html.erb
test/components/document_list_test.rb
test/integration/document_collection_test.rb
test/presenters/document_collection_presenter_test.rb

- accepts a content item and outputs a list of lists and information from it
- accepts an optional parameter to add tracking to the links
- possible point of contention: for the date object had to add a check/convert to date object part in order to get component guide to render. Open to better solution if one can be found.
(was called collection list component until part way through development when it became clear the name wasn't clear enough)
https://trello.com/c/JlNtwQ5G/75-2-convert-collection-list-to-document-list-component

Create document list component

---

Gemfile
Gemfile.lock
app/views/components/_figure.html.erb
config/environments/test.rb
test/components/all_components.rb

This PR prepares government-frontend to be able to pick up throw accessibility errors from the component guide.
Related PR: https://github.com/alphagov/govuk_publishing_components/pull/33

Test component guide

---

app/assets/stylesheets/views/_detailed-guide.scss

Fixes the mixture of rtl and ltr alignment currently showing.
https://trello.com/c/Rew0qb06/116-arabic-translation-template-issue-1
See:
https://www.gov.uk/guidance/mod-decisions-on-alleged-human-rights-breaches-during-operation-telic.ar
https://government-frontend-pr-464.herokuapp.com/guidance/mod-decisions-on-alleged-human-rights-breaches-during-operation-telic.ar

Add right to left styles to detailed guides

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_contents-list.scss
app/views/components/docs/banner.yml
app/views/components/docs/contents-list.yml
app/views/components/docs/document-list.yml
app/views/components/docs/download-link.yml
app/views/components/docs/figure.yml
app/views/components/docs/heading.yml
app/views/components/docs/lead-paragraph.yml
app/views/components/docs/notice.yml
app/views/components/docs/print-link.yml
app/views/components/docs/share-links.yml
app/views/components/docs/subscription-links.yml
app/views/components/docs/translation-nav.yml

Best reviewed with `?w=1` or commit by commit
* Update example documentation to new format (see https://github.com/alphagov/govuk_publishing_components/pull/37)
* Add right to left examples
* Add HTML examples to banner
* Fix bug with right to left contents lists
https://government-frontend-pr-465.herokuapp.com/component-guide

Add right to left and HTML examples to component guide

---

app/controllers/content_items_controller.rb
test/controllers/content_items_controller_test.rb

Content store now falls through to any matching prefix when a content item is not found. This commit adds support for this returning a 404 when a `special_route` is returned by content store. Currently this causes a 500.
This PR requires https://github.com/alphagov/govuk-content-schemas/pull/639 to be deployed.

Handle `special_route` document type correctly

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/helpers/_add-title-margin.scss
app/assets/stylesheets/helpers/_national_statistics_logo.scss
app/assets/stylesheets/views/_answer.scss
app/assets/stylesheets/views/_contact.scss
app/assets/stylesheets/views/_guide.scss
app/assets/stylesheets/views/_help-page.scss
app/assets/stylesheets/views/_publication.scss
app/assets/stylesheets/views/_statistics_announcement.scss
app/assets/stylesheets/views/_travel-advice.scss
app/views/shared/_national_statistics_logo.html+new_navigation.erb
app/views/shared/_national_statistics_logo.html.erb
app/views/shared/_withdrawal_notice.html.erb
test/integration/publication_test.rb
test/integration/statistics_announcement_test.rb

As part of auditing government-frontend I found these issues that seemed easier to fix at the time, can close and make into cards if needed.
National statistics:
Before:
After:
Maps:
- No change
Withdrawal Notice Partial:
- I think this was left around and we forgot to delete it

Make title spacing consistent and remove unneeded CSS

---

app/presenters/corporate_information_page_presenter.rb
app/presenters/guide_presenter.rb
app/presenters/travel_advice_presenter.rb
test/presenters/corporate_information_page_presenter_test.rb
test/presenters/guide_presenter_test.rb
test/presenters/travel_advice_presenter_test.rb

This cover a few edge cases where custom page_titles
where being generated
https://trello.com/c/Mn8Yk9Z6/278-add-withdrawn-to-page-title

Ensure Withdrawn is included on all withdrawn content

---

app/assets/stylesheets/components/_banner.scss
app/views/components/_banner.html.erb

- ordering of aside and main banner content changed so aside occurs in the dom after the main content, so screen readers should read the heading first (unless you're using VoiceOver in Chrome, which has weird issues that we've decided to ignore as they're out of our control)
- changed aside element to an aside
- appearance of component should not have changed at all
https://government-frontend-pr-470.herokuapp.com/component-guide/banner
https://trello.com/c/J6907ojp/93-2-banner-component-is-inaccessible-to-screen-reader-users

Improve banner accessibility

---

app.json

We want to keep the S3 bucket credentials secret. To do this we can require their existence in app.json and define their values in the 'parent' (i.e. master build) of the app in the heroku dashboard.

Add placeholder env-vars for S3 credentials

---

Gemfile
Gemfile.lock

This updates the govuk_publishing_components gem to allow for warnings to appear in the guide.
See the [changelog for full details](https://github.com/alphagov/govuk_publishing_components/blob/master/CHANGELOG.md)

Bump govuk_publishing_components gem to add axe warnings

---

app/presenters/parts.rb
test/controllers/content_items_controller_test.rb
test/presenters/parts_test.rb

[Trello](https://trello.com/c/ST5fkS0a/285-implement-redirect-from-default-chaptered-guides-pages)
- Internal links within a guide now point to the `base_path`, not to the `base_path` + `slug` of the first part. However, the longer URL is still accessible without redirecting to its shorter equivalent if entered manually into the address bar.
- This is not ideal for analytics, as we have to deal with two URLs for the same page.
- This PR solves this issue by redirecting the slug of the first part to /base_path.

Redirect to base_path/ for first part of guides

---

app/presenters/html_publication_presenter.rb
app/presenters/withdrawable.rb
app/views/content_items/html_publication.html.erb
test/integration/html_publication_test.rb

- uses notice component
- requires update to translations, have copied the lines for 'publication' as 'html publication' wouldn't make sense to most people
- updated non-English language files as well, used the translation for 'publication' there as well
https://trello.com/c/23VcfUo2/137-1-add-withdrawn-notice-to-html-publications
Examples:
- https://government-frontend-pr-474.herokuapp.com/government/publications/dependants-of-students-and-prospective-students-sty01/dependants-of-students-and-prospective-students-sty01
- https://government-frontend-pr-474.herokuapp.com/government/publications/fees-for-civil-and-family-courts/court-fees-for-the-high-court-county-court-and-family-court
- https://government-frontend-pr-474.herokuapp.com/government/publications/ex35-6ne-environmental-permit-a …

Add withdrawn notice to html publications

---

Gemfile
Gemfile.lock

- Add links to component guide homepage
- Add dark_background context to examples
- Add optional descriptions to examples

Bump govuk_publishing_components gem to 1.5.0

---

Gemfile
Gemfile.lock

Update guide gem to allow inclusion of government-frontend heroku component guide in iframe.
This will allow the [VisualDiffTool](https://github.com/alphagov/govuk_publishing_components/pull/61) to be run against component guide

Update guide gem

---

app/presenters/detailed_guide_presenter.rb
test/presenters/detailed_guide_presenter_test.rb

User reported incorrect translation in Arabic in zendesk ticket
https://govuk.zendesk.com/agent/tickets/2319144
This led to us noticing a discrepency between English and all
other languages. This is remedied by using the "guidance"
context in the title for all detailed guides as English had
been updated to say "Guidance" already.

Force "guidance" context in detailed guides title

---

app/views/components/docs/back-to-top.yml
app/views/components/docs/contents-list.yml
app/views/components/docs/document-list.yml
app/views/components/docs/download-link.yml
app/views/components/docs/print-link.yml
app/views/components/docs/share-links.yml
app/views/components/docs/subscription-links.yml
app/views/components/docs/translation-nav.yml

- replaces all instances of link accessibility criteria with the shared version pulled from the gem
- all other existing component specific accessibility criteria should remain
https://trello.com/c/qS1pfVle/132-2-accessibility-criteria-universal-criteria-for-all-components
https://government-frontend-pr-482.herokuapp.com/component-guide

Add shared accessibility criteria to components

---

Gemfile
Gemfile.lock

Update guide gem to include:
* Removal of cookie/survey banners in component guide
* Fix for aXe accessibility testing in government-frontend integration tests

Update govuk_publishing_components to 1.7.0

---

app/assets/stylesheets/views/_html-publication.scss
app/views/content_items/html_publication.html.erb

Replaces the html-publication-title with the static title component (pub-c-title).
**Before:**
**After:**
**Note: can only be merged and deployed after static title spacing changes have been deployed**

Include static title component in html publication

---

docs/PULL_REQUEST_TEMPLATE

Indicate where component guide and visual regression test results are available.
We can’t automatically generate the `XXX` part of the template
Following this guide:
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

Add a PR template with component guide and visual regression links

---

README.md

The component guide URL referred to in this repo has changed.

Update references to component guide

---

Gemfile
Gemfile.lock

Update govuk_publishing_components gem to 1.8.2 to:
* hide cookie and survey banners in the government-frontend component guide
* fix syntax highlighting in the government-frontend component guide
https://government-frontend-pr-488.herokuapp.com/component-guide
https://government-frontend-pr-488.surge.sh/gallery.html

Update guide gem to 1.8.2

---

Gemfile
Gemfile.lock

Includes the following:
* Render accessibility violations in component guide
* Remove hover styles in component guide
* Include check for components without documentation (when running `bundle exec rake` )
https://government-frontend-pr-496.herokuapp.com/component-guide
https://government-frontend-pr-496.surge.sh/gallery.html

Update guide gem to 1.11.0

---

app/assets/stylesheets/views/_html-publication.scss

HTML publication headers currently don't meet WCAG AA colour contrast ratio for normal text. Changing this from $light-blue to $govuk-blue fixes this.
**Before:**
**After:**
Previous ratio was 3.72:1, new ratio is 6.68:1 (need to meet 4.5:1)
Live page: https://government-frontend-pr-497.herokuapp.com/government/publications/budget-2016-documents/budget-2016
https://government-frontend-pr-497.herokuapp.com/component-guide
https://government-frontend-pr-497.surge.sh/gallery.html

Fix colour contrast in publication headers

---

app/assets/stylesheets/components/_publication-header.scss
app/assets/stylesheets/views/_html-publication.scss
app/views/components/_publication-header.html.erb
app/views/components/docs/publication-header.yml
app/views/content_items/html_publication.html.erb
test/components/publication_header_test.rb
test/integration/html_publication_test.rb

Replace the existing html publication header with a component which makes use of govuk-title component.
In component guide:
https://government-frontend-pr-499.herokuapp.com/component-guide
https://government-frontend-pr-499.surge.sh/gallery.html

Create publication header component

---

app/helpers/typography_helper.rb
app/presenters/statistics_announcement_presenter.rb
app/views/content_items/statistics_announcement.html.erb
test/integration/statistics_announcement_test.rb
test/presenters/statistics_announcement_presenter_test.rb

When viewing statistical announcements that have a `display_date` in the future, users think they are looking at an actual released statistic and find it confusing that there is nothing there. Add a notice to the page to inform the users that the announcement is forthcoming.
Some examples:
https://government-frontend-pr-498.herokuapp.com/government/statistics/announcements/construction-output-in-great-britain-aug-2017
https://government-frontend-pr-498.herokuapp.com/government/statistics/announcements/business-population-estimates-2017
[Trello](https://trello.com/c/prArYYxS/153-were-sending-emails-about-stats-announcements-and-we-shouldnt-be)

Add forthcoming notice to statistics announcements

---

app/helpers/statistics_announcement_helper.rb
app/presenters/statistics_announcement_presenter.rb
test/helpers/statistics_announcement_helper_test.rb
test/integration/statistics_announcement_test.rb

Add a helper to improve the clarity of the forthcoming notification on Statistical Announcements.
Statistical Announcements can have three different date formats:
* Exact e.g. `10th January 2018 9:30am (provisional)`
* One month e.g. `January 2018 (provisional)`
* Two month e.g. `January to February 2018 (provisional)`
To improve the clarity of the notice, we want to add `on`, `in` or `between` before the date component. In addition, when we are working with a two month date range, we want to substitute `and` for the `to` (`...between January and February...`) so we do not imply that the publication is only available between the two months.
Example of an exact date:
https://government-frontend-pr-502.herokuapp.com/government/statistics/announcements/12-week-maternal-assessment-for-q4-20161 …

Add clarity to stats announcement forthcoming notice

---

config/locales/he.yml

This commit adds `rtl` to the he.yml locale as Hebrew should read right
to left.
Fixes [Zendesk](https://govuk.zendesk.com/agent/tickets/2496478)
Example with the issue: 
https://www.gov.uk/government/news/foreign-secretary-article-on-the-balfour-declaration
After:

Hebrew is a right-to-left language

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/helpers/_taxonomy-sidebar.scss
app/assets/stylesheets/views/_detailed-guide.scss
app/assets/stylesheets/views/_document-collection.scss
app/assets/stylesheets/views/_publication.scss
app/views/content_items/detailed_guide.html+new_navigation.erb
app/views/content_items/document_collection.html+new_navigation.erb
app/views/content_items/publication.html+new_navigation.erb

* Use the `add-title-margin` class
* Avoid styling components, this breaks their isolation
* Makes taxonomy component spacing behave in the same way as related links component
Part of:
https://trello.com/c/FN3ppmn2/60-update-taxonomy-related-links-in-right-column-to-match-the-design-used-by-mainstream-browse-related-links

Remove bespoke taxonomy sidebar component styles

---

app.json
startup.sh

Rummager/search is a dependency of the navigation helpers (it uses it to show related content). We normally don't notice this because the govuk_navigation_helpers gem is designed to fail gracefully when rummager isn't available.

Set environment vars for Rummager

---

app/assets/stylesheets/views/_detailed-guide.scss
app/assets/stylesheets/views/_document-collection.scss

`govuk-taxonomy-sidebar` styles were removed in https://github.com/alphagov/government-frontend/pull/507 but the styles for `add-title-margin` were not being included on detailed guides and collections.
https://www.gov.uk/government/collections/national-curriculum
https://government-frontend-pr-514.herokuapp.com/government/collections/national-curriculum
https://www.gov.uk/guidance/student-bursary-support-service-demonstration-videos-for-education-institutions
https://government-frontend-pr-514.herokuapp.com/guidance/student-bursary-support-service-demonstration-videos-for-education-institutions

Include title margin styles on detailed guides & collections

---

app/presenters/content_item/metadata.rb
app/views/shared/_footer.html+taxonomy_navigation.erb
app/views/shared/_metadata.html+taxonomy_navigation.erb

* Don’t hide the `part of` bits of metadata on new taxonomy pages
* We will be iterating what nav is shown in future multivariate tests
* Part of includes both trivially related things and important related
things – we need to do better in distinguishing them
Review app vs live:
https://government-frontend-pr-516.herokuapp.com/government/publications/national-apprenticeship-awards-apprentice-categories
https://www.gov.uk/government/publications/national-apprenticeship-awards-apprentice-categories?ABTest-EducationNavigation=B
https://trello.com/c/zuBOPznV/74-remove-ab-test-from-government-frontend

Use the same metadata for all pages

---

app/views/shared/_breadcrumbs.html+taxonomy_navigation.erb

* We are rolling out taxonomy navigation as the live variant on certain
pages, meaning it’s no longer a test version
* The survey in it’s current form on these pages isn’t required. A new
survey will be used on newer test variants
* The AB test has been disabled
Compare live, integration and this branch:
https://www.gov.uk/government/publications/national-apprenticeship-awards-apprentice-categories?ABTest-EducationNavigation=B
https://www-origin.integration.publishing.service.gov.uk/government/publications/national-apprenticeship-awards-apprentice-categories
https://government-frontend-pr-517.herokuapp.com/government/publications/national-apprenticeship-awards-apprentice-categories
https://trello.com/c/zuBOPznV/74-remove-ab-test-from-government-frontend
cc @vanitabarrett

Remove the beta banner from taxonomy navigation pages

---

app/controllers/concerns/tasklist_ab_testable.rb

We want to keep these lists in sync so that it's easy to tell if either is out
of date.  These lists are used to determine which pages should show a learn-to-drive-a-car
task list. 
By doing this sync, we add `driving-test/what-to-take` which was missing (and
is rendered by govt-frontend) and sort them so it's easier to what's there.
We also add the chapters for `/pass-plus` so they get a task list rendered too.
The corresponding pass-plus PR in Frontend is https://github.com/alphagov/frontend/pull/1300

Add pass-plus chapters and sync tasklist pages with list in frontend

---

app/controllers/content_items_controller.rb
app/models/traffic_signs_summary_ab_test_request.rb
app/views/layouts/application.html.erb
test/controllers/content_items_controller_test.rb

The TrafficSignsSummary A/B test will test a content improvement to the
summary of the [Know your traffic signs][1] publication.
[1]: https://www.gov.uk/government/publications/know-your-traffic-signs
https://government-frontend-pr-515.surge.sh/gallery.html

Add the TrafficSignsSummary A/B test

---

app/controllers/concerns/tasklist_ab_testable.rb
app/controllers/concerns/tasklist_header_ab_testable.rb
app/controllers/concerns/tasklist_pages.rb

The tasklist header also needs to be shown on secondary pages that are part of the A/B test.
Some refactoring has been done to improve dependency issues.

Add tasklist header A/B test to secondary pages

---

app/assets/stylesheets/components/_published-dates.scss
app/views/components/_published-dates.html.erb
app/views/components/docs/published-dates.yml
config/locales/en.yml
test/components/published_dates_test.rb

Published dates component to be used within metadata block. 
**Also links to expandable full page history**
Trello Story: https://trello.com/c/UTBixmPW/85-convert-published-dates-into-a-component-for-universalnonav-variant
https://government-frontend-pr-529.herokuapp.com/component-guide/published-dates
https://government-frontend-pr-529.surge.sh/gallery.html

Published dates component

---

app/controllers/concerns/content_navigation_ab_testable.rb
app/controllers/content_items_controller.rb
app/presenters/content_item_presenter.rb
app/views/layouts/application.html.erb
test/controllers/content_items_controller_test.rb
test/controllers/content_navigation_ab_testing_content_items_controller_test.rb

First pass at adding the content navigation multivariate test. This adds the logic to respond to test bucket, without any of the markup changes or variations.
Start with 4 variants matching https://github.com/alphagov/cdn-configs/pull/17
original, no nav, taxonomy nav, mainstream nav
* Follow “concern” pattern setup in #513 for task list AB test
* Only content with the document types listed are part of the test
* The content must also be tagged to a taxon
* Use a “universal_navigation” variant for all multivariate tests
except original – they are largely the same, significant differences
with original shouldn’t be repeated
Part of:
https://trello.com/c/sVQSGE2e/16-create-multivariant-test-for-content-pages
https://trello.com/c/1caGTIJn/77-create-no-navigation-test-variant-based-on-first-un …

Add content navigation multivariate test

---

app/models/navigation_type.rb
test/controllers/content_items_controller_test.rb

We now determine which navigation to show according to a complex decision tree:
When we rolled it out we thought that it would be good to always show the new navigation if the content is tagged to the world wide taxonomy (https://github.com/alphagov/government-frontend/pull/510), because it would be closest to what the B-variant was.
This had unintended effects of showing the world wide navigation on some mainstream pages, because they're tagged to the "generic" taxons in the world wide taxonomy.
https://trello.com/c/TqnWwFif

Don't show new nav for world wide mainstream pages

---

config/locales/fa.yml

We've received a [Zendesk ticket](https://govuk.zendesk.com/agent/tickets/2512759) informing us that our Farsi/Persian content is currently left-aligned, however it is a language that reads right-to-left and so should be right-aligned.  This is already in place for other "right-to-left" languages such as Hebrew (see [example](https://www.gov.uk/government/speeches/ambassador-quarreys-speech-for-international-holocaust-remembrance-day.he)).
This PR sets the direction of Farsi content to `rtl` in its locale YAML file to
enable correct alignment.

Enable right-to-left text direction for Farsi content

---

app/views/components/_published-dates.html.erb
test/components/published_dates_test.rb

Component was incorrectly applying the history id to the component each time, as the check for history should have been checking for history.any?
Updated to include this check, component now only contains history id if a history item has been passed to it.
https://government-frontend-pr-537.herokuapp.com/component-guide/published-dates
https://government-frontend-pr-537.surge.sh/gallery.html

Fix link to history behaviour

---

app/assets/stylesheets/components/_content-metadata.scss
app/views/components/_content-metadata.html.erb
app/views/components/docs/content-metadata.yml
app/views/content_items/detailed_guide.html.erb
test/components/content_metadata_test.rb

- Presents publisher metadata
- Passes params to published date component to display published and updated metadata
https://government-frontend-pr-534.herokuapp.com/component-guide

Add content metadata component

---

app/assets/stylesheets/components/_published-dates.scss
app/assets/stylesheets/helpers/_parts.scss
app/assets/stylesheets/mixins/_margins.scss
app/presenters/content_item/linkable.rb
app/views/components/docs/content-metadata.yml
app/views/content_items/_body_with_related_links.html+universal_navigation.erb
app/views/content_items/_guide_body.html.erb
app/views/content_items/_publication_inline_body.html.erb
app/views/content_items/detailed_guide.html+universal_navigation.erb
app/views/content_items/guide.html+universal_navigation.erb
app/views/content_items/guide.html.erb
app/views/content_items/publication.html+taxonomy_navigation.erb
app/views/content_items/publication.html+universal_navigation.erb
app/views/layouts/application.html.erb
test/controllers/content_navigation_ab_testing_content_items_controller_test.rb
test/integration/answer_test.rb
test/integration/contact_test.rb
test/integration/detailed_guide_test.rb
test/integration/html_publication_test.rb
test/integration/publication_test.rb

Raising this PR in case I need to handover the work at short notice.
Creates a universal layout for:
* guides
* answers
* publications (statutory guidance only)
* detailed guides
Tests are applied to these pages based on logic in #526 
https://gist.github.com/fofr/cbf398e868ac2e3052be5a666635ee6a
When the "UniversalNoNav" variant is set:
* no breadcrumbs display
* no related links or taxonomy sidebar displays
* no metadata or document footer components display
* all content is inline in a left column, with an empty column to the right
Still to do:
To test on Heroku:
* Use the ModHeader extension and set:
Header: `GOVUK-ABTest-ContentNavigation`
Value: `UniversalNoNav`
* Use slugs from gist and visit the review app, eg:
https://government-frontend-pr-535.herokuapp.com/guidance/schools-finan …

Create universal layout with no navigation variant

---

app/controllers/application_controller.rb
config/tasklists/learn-to-drive-a-car.json
test/unit/tasklist_content_test.rb

This commit fixes the implementation as it was changed during
https://github.com/alphagov/static/commit/c36c0b7d217750bea8f355d428c022bf74af615e
Trello:
https://trello.com/c/fFItiXlt/299-fix-accordion-functionality-on-learning-to-drive-in-sidebar-navigation

Fix "open step" on TaskList Sidebar

---

app/assets/stylesheets/components/_content-metadata.scss
app/presenters/content_item/linkable.rb
app/presenters/content_item/metadata.rb
app/presenters/content_item/national_applicability.rb
app/views/components/_content-metadata.html.erb
app/views/components/docs/content-metadata.yml
app/views/content_items/detailed_guide.html+universal_navigation.erb
app/views/content_items/publication.html+universal_navigation.erb
test/components/content_metadata_test.rb

Allow content metadata to render any metadata types
* Use pattern from static metadata component:
https://govuk-static.herokuapp.com/component-guide/metadata
* Allow further metadata to be added easily as design is iterated
* This allows us to easily add national applicability
Add national applicability to content metadata
* Move content_metadata params into metadata presenter module
* Decorate with “Applies to” when National Applicability applies
* Add “Applies to” to the beginning of the hash to appear before “From”
* Use existing methods for generating “Applies to” from content item
* Improve rendering of component when no dates provided
https://government-frontend-pr-539.herokuapp.com/component-guide/content-metadata

Add national applicability to universal navigation variant

---

Gemfile
Gemfile.lock
test/controllers/content_items_controller_test.rb
test/support/govuk_content_schema_examples.rb

This update ensures that only taxons from the three published taxon branches (education, childcare-parenting and world) get shown for breadcrumbs and the side bar taxon links. 
This solves the specific problem that draft taxons were showing up on the draft stack when publishers were previewing their content. That was not a good user experience for them, as when published, those taxons and breadcrumbs would not be on the live site.
See https://github.com/alphagov/govuk_navigation_helpers/pull/82 for more details.
The 'About the route', 'Welfare Reform' and 'Work' taxons are draft taxons and show up in the left side bar and breadcrumbs (when previewing this on the draft stack). Only 'Educations in prisons' is a published taxon.
Only the published taxon 'Educations in prisons' shows up in …

Upgrade govuk_navigation_helpers to v7.0

---

app/controllers/concerns/tasklist_ab_testable.rb
app/controllers/content_items_controller.rb
app/views/content_items/publication_with_tasklist_sidebar.html.erb

This will show the tasklist sidebar on a specific publication page that
is part of learn to drive.
Trello: https://trello.com/c/WWZn2kNO/

Show tasklist sidebar on publication content

---

app/controllers/development_controller.rb
app/views/development/index.html.erb
config/routes.rb

This adds a page at the root of the site that will be visible in development and on Heroku review apps.
It has the following things that would be useful in development:
- Links to the component guide
- The URLs of the content store, rummager, static, so it's clear which version we are using
- Link to the canonical example of a template (the one named after the schema)*
- Link to a random version of the template*
- List of links to pages rendered by government-frontend. I've reused the wraith config for this, it seemed like a nice representative list of different pages.
https://trello.com/c/IoHKyhoX
`*` will work after https://github.com/alphagov/govuk-content-schemas/pull/665 is merged and we point the Heroku review apps to the [example content store Heroku …

Add a homepage for developers

---

app.json

This points Heroku apps to the example content store, so that we can use the examples and random content. For all other pages the app will keep working in the same way because it forwards to the real content store (https://github.com/alphagov/govuk-content-schemas/pull/665).
https://trello.com/c/IoHKyhoX

Point to example content store

---

app/presenters/contact_presenter.rb

For [Trello card](https://trello.com/c/klzfs7R8/186-add-webchat-to-a-hmrc-contact-page)
This adds HMRC webchat to
https://www.gov.uk/government/organisations/hm-revenue-customs/contact/online-services-helpdesk

Add HMRC webchat to contact page

---

app/assets/stylesheets/components/_fieldset.scss
app/assets/stylesheets/components/helpers/_clearfix.scss
app/views/components/_fieldset.html.erb
app/views/components/docs/fieldset.yml

https://government-frontend-pr-561.herokuapp.com/component-guide/fieldset
https://trello.com/c/RRbQOeUK/243-create-a-fieldset-component-1

Add fieldset component

---

app/assets/stylesheets/components/_error-message.scss
app/views/components/_error-message.html.erb
app/views/components/docs/error-message.yml
test/components/error_message_test.rb

Used in labels and legends to show what the error is.
Forked from GOV.UK Frontend
https://government-frontend-pr-562.herokuapp.com/component-guide/error-message
https://trello.com/c/4p6T0Kbl/247-create-an-error-message-component-05

Add error message component

---

Gemfile
Gemfile.lock
app/presenters/content_item_presenter.rb
test/presenters/content_item_presenter_test.rb

Wraps the govuk_navigation_helpers related_navigation_sidebar method in the content item presenter so that it is accessible within views. This will allow us to simply pass `@content_item.related_navigation_sidebar` to the sidebar component when we want to render it on content pages (full example below):
`<%= render 'components/related-navigation-sidebar', @content_item.related_navigation_sidebar %>`
**Note: the above code will only work once https://github.com/alphagov/government-frontend/pull/556 has been merged, as this renames the component and allows it to display external and contact links. Otherwise, use `render 'components/navigation-sidebar'`**
To-Do:
Dependent on: https://github.com/alphagov/govuk_navigation_helpers/pull/85

Add logic to link up with govuk_navigation_helpers

---

Gemfile
Gemfile.lock
app/views/components/_related-navigation.html.erb
app/views/components/docs/related-navigation.yml
config/locales/en.yml
test/components/related_navigation_test.rb
test/presenters/content_item_presenter_test.rb

When testing the image formats universal layout, we noticed that speeches show related world locations  in the metadata [on the live page](https://www.gov.uk/government/speeches/2014-hillary-clinton-prize-for-women-peace-and-security), but [not on universal layout at all](https://government-frontend-pr-541.herokuapp.com/government/speeches/2014-hillary-clinton-prize-for-women-peace-and-security). We need to show these in the related navigation.
This PR uses the latest version of `govuk_navigation_helpers` which has been updated to return world locations https://github.com/alphagov/govuk_navigation_helpers/pull/88
https://government-frontend-pr-565.herokuapp.com/component-guide
https://government-frontend-pr-565.surge.sh/gallery.html

Add world locations to related nav component

---

app/assets/javascripts/modules/track-radio-group.js
spec/javascripts/track-radio-group.spec.js

We want to see what users are selecting when going through the sign in option journey.
This module allows us to do so by firing an event when they submit the form.
This is based on something we used for the A/B test but refactored to use the module format.
- https://github.com/alphagov/government-frontend/pull/544/files#diff-d9e8d7c7a844d60076e6152e0911dbb2
- https://github.com/alphagov/government-frontend/pull/544/files#diff-3952895e8eee3e0496e344cded23e0d3
Tested this in a page (since we're not using it just yet) with the following results:
Part of https://trello.com/c/ApvFOYTk/263-add-analytics-tracking-to-page-to-track-radio-button-selection-3

Add track radio group module

---

app/assets/stylesheets/components/_back-link.scss
app/assets/stylesheets/components/_error-message.scss
app/assets/stylesheets/components/_fieldset.scss
app/assets/stylesheets/components/_label.scss
app/assets/stylesheets/components/_radio.scss
app/assets/stylesheets/components/helpers/_px-to-em.scss
app/assets/stylesheets/components/helpers/_variables.scss
app/views/components/_back-link.html.erb
app/views/components/docs/back-link.yml
config/locales/en.yml
test/components/back_link_test.rb

Best viewed commit by commit.
Includes a refactoring to avoid duplicating variables and possible conflicts in the future.
https://government-frontend-pr-568.herokuapp.com/component-guide/back-link
Todo:
Default state
Hover state
Touch/focus state
As part of https://trello.com/c/vsmhbjLt/245-build-the-choose-sign-in-options-template-2

Add back link component

---

app/assets/javascripts/application.js
app/assets/javascripts/components/error-summary.js
app/assets/stylesheets/components/_error-summary.scss
app/assets/stylesheets/components/helpers/_variables.scss
app/views/components/_error-summary.html.erb
app/views/components/docs/error-summary.yml
spec/javascripts/error-summary.spec.js
test/components/error_summary_test.rb

https://government-frontend-pr-589.herokuapp.com/component-guide/error-summary
Part of https://trello.com/c/1ckIbeBr/246-create-an-error-summary-component-1

Add error summary component

---

app/controllers/content_items_controller.rb
app/presenters/service_sign_in/choose_sign_in_presenter.rb
app/views/content_items/service_sign_in/_choose_sign_in.html.erb
config/routes.rb
test/controllers/content_items_controller_test.rb

Trello card: https://trello.com/c/zsPE3IXV
Add routing to the radio buttons on the `choose sign in` page of the service_sign_in format.
The actual error handling, that displays an error message to the user, will be added in another PR. Reloading the `choose sign in` page if the user doesn't select an option just stops an exception from being raised.

Route radio buttons on choose sign in page

---

app/helpers/related_navigation_helper.rb
app/views/components/_related-navigation.html.erb
app/views/components/docs/related-navigation.yml
test/components/related_navigation_test.rb

Adding Show More/Show Fewer button for long sections of the related navigation component.
https://government-frontend-pr-575.herokuapp.com/component-guide/related-navigation/with_extensive_world_locations
**Note: the link above makes it look like the list is indented. This is an issue with the component guide rather than the component itself, on live pages the component will not be indented.**
Example page: https://government-frontend-pr-575.herokuapp.com/government/news/chevening-scholarship-places-in-developing-countries-tripled-for-201516
https://government-frontend-pr-575.surge.sh/gallery.html

Add progressive disclosure to long related nav

---

app/assets/stylesheets/components/_error-message.scss
app/controllers/content_items_controller.rb
app/presenters/service_sign_in/choose_sign_in_presenter.rb
app/views/content_items/service_sign_in/_choose_sign_in.html.erb
config/locales/en.yml
test/controllers/content_items_controller_test.rb
test/integration/service_sign_in/choose_sign_in_test.rb
test/presenters/service_sign_in/choose_sign_in_presenter_test.rb

Add error handling to choose_sign_in template
We try not to use cookies where possible (alphagov/calculators@29c666a).
This implementation avoids using flashing (with a session) and instead sets an instance variable and re-renders the view.
Other considered alternative was redirecting with query params set.
- https://government-frontend-pr-605.herokuapp.com/examples/service_sign_in/service_sign_in/choose-sign-in
As part of  https://trello.com/c/vsmhbjLt/245-build-the-choose-sign-in-options-template-2

Add error handling to choose_sign_in template

---

config/locales/cy.yml
test/integration/service_sign_in/choose_sign_in_test.rb

Trello card: https://trello.com/c/T5zKxHRw
Depends on PR: https://github.com/alphagov/government-frontend/pull/610
Add the Welsh translation to the locales for:
* Back link
* Continue button
* Error messages

Add Welsh translations for service_sign_in pages

---

app/controllers/application_controller.rb

Related to: PR #610 
When we tried submitting a radio button on the choose-sign-in page the
following error is thrown:
`Can't verify CSRF token authenticity.`
As we are not submitting and sensitive data, and are just redirecting users,
we don't need this protection on the form.
We don't currently have a session store due to the layers of caching, so we
did not try to set the authenticity token, and have instead disabled it.
We did not reproduce this issue on Heroku and will investigate why later.

Turn off CSRF protection on service_sign_in POST route

---

Gemfile
Gemfile.lock
app/presenters/content_item_presenter.rb
app/views/components/_related-navigation.html.erb
app/views/components/docs/related-navigation.yml
config/locales/en.yml
test/components/related_navigation_test.rb
test/presenters/content_item_presenter_test.rb

... in the related navigation component
The new related navigation is not displaying topical events or worldwide organisations. We want to display both of these.
**Worldwide organisations example (before and after):**
[Live example](https://government-frontend-pr-609.herokuapp.com/government/news/paralympic-legacy-and-disability-rights)
**Topical events example (before and after):**
[Live example](https://government-frontend-pr-609.herokuapp.com/government/news/uk-china-relations-flourish-at-the-2017-people-to-people-dialogue)
[Component Guide link](https://government-frontend-pr-609.herokuapp.com/component-guide/related-navigation)

Add worldwide organisations to published by

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_publisher-metadata.scss
app/assets/stylesheets/helpers/_publisher-metadata-with-logo.scss
app/assets/stylesheets/views/_publication.scss
app/views/content_items/case_study.html.erb
app/views/content_items/fatality_notice.html.erb
app/views/content_items/news_article.html.erb
app/views/content_items/speech.html.erb
app/views/content_items/world_location_news_article.html.erb
app/views/shared/_publisher_metadata_with_logo.html.erb

https://trello.com/c/Q9io9cQU/132-move-publications-format-to-universal-design
When moving publications to the new layout we wanted
to combine the publisher metadata with an optional
logo and make the combination span all 3 columns.
This change needs to be reflected in formats which
won't have logos but will have a full width publisher
metadata border.
I've made a partial rendering the metadata component
in a 2/3 width column and the logo in the 1/3 column
because it seemed the most reasonable way to combine
both without compromising the component design.
https://government-frontend-pr-616.herokuapp.com/government/case-studies/who-will-and-won-t-be-enrolled-into-a-workplace-pension-fictional-case-studies
https://government-frontend-pr-616.herokuapp.com/government/news/apprenticeships-will- …

Make publisher metadata styling consistent

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/views/_consultation.scss
app/views/components/_banner.html.erb
app/views/components/docs/banner.yml
test/components/banner_test.rb

Part of https://trello.com/c/q0PNOZkj/117-move-formats-with-images-to-universal-layout
Deleted the 1/3rd column for the aside. Made consultation date range
bold.

Some tweaks to the type on the banners.

---

app/controllers/content_items_controller.rb
app/views/shared/_sidebar_navigation.html.erb

The publication template has changed and we should no longer override this.
We were also passing the incorrect locals into the partial.

Fix sidebar rendering on publications

---

app/assets/stylesheets/components/_important-metadata.scss
app/assets/stylesheets/components/_notice.scss
app/assets/stylesheets/views/_statistics_announcement.scss
app/presenters/statistics_announcement_presenter.rb
app/views/components/_important-metadata.html.erb
app/views/components/_notice.html.erb
app/views/components/docs/important-metadata.yml
app/views/content_items/statistics_announcement.html.erb
app/views/shared/_publisher_metadata_with_logo.html.erb
test/components/important_metadata_test.rb
test/integration/statistics_announcement_test.rb

Moving statistics announcements over to universal layout.
Example pages: 
- [Official Statistics Announcement](https://government-frontend-pr-602.herokuapp.com/government/statistics/announcements/ni-tourism-statistics-oct-13-to-sep-14)
- [Statistics Announcement](https://government-frontend-pr-602.herokuapp.com/government/statistics/announcements/vat-factsheet-2014-15)
- [Cancelled Statistics Announcement](https://government-frontend-pr-602.herokuapp.com/government/statistics/announcements/delayed-transfers-of-care-for-october-2015)
- [Statistics Announcement with changed release date](https://government-frontend-pr-602.herokuapp.com/government/statistics/announcements/museums-and-galleries-monthly-visits--8)

Statistics announcements to universal layout

---

Gemfile
Gemfile.lock
app/controllers/content_items_controller.rb

By using this we inherit the updated tasklist content in https://github.com/alphagov/govuk_navigation_helpers/pull/99.
We also remove the bits that rely on things that were removed in https://github.com/alphagov/govuk_navigation_helpers/pull/98.
This was around special handling for publications before they were moved to a template which had a sidebar.  
We'd already removed some of this in https://github.com/alphagov/government-frontend/pull/621, so this is not called from anywhere.

Update tasklist content

---

app/assets/stylesheets/components/_figure.scss
app/views/components/_figure.html.erb

- Border spans whole component
- Remove camera icon

Update figure layout

---

app/views/components/_publisher-metadata.html.erb
test/integration/case_study_test.rb
test/integration/news_article_test.rb
test/integration/speech_test.rb
test/integration/world_location_news_article_test.rb

Depends on https://github.com/alphagov/govuk-content-schemas/pull/682
Refactors and re-enables some integration tests for formats which have been redesigned and links moved to the navigation sidebar.

Enable skipped integration tests

---

Gemfile
Gemfile.lock
app/views/components/_related-navigation.html.erb
config/locales/en.yml
test/components/related_navigation_test.rb
test/presenters/content_item_presenter_test.rb

https://govuk.zendesk.com/agent/tickets/2538570
- Add tests to support this change.
Review app example:
https://government-frontend-pr-628.herokuapp.com/government/statistics/air-quality-statistics

Add statistical data sets to sidebar navigation

---

test/wraith/config-service-sign-in.yaml

Can be run with `bundle exec wraith capture test/wraith/config-service-sign-in.yaml`
As part of https://trello.com/c/Cw4dF2PB/292-add-new-template-urls-to-wraith-testing

Add service sign-in config for wraith

---

app/controllers/content_items_controller.rb
app/presenters/content_item_presenter.rb
app/presenters/service_sign_in/choose_sign_in_presenter.rb
app/presenters/service_sign_in/create_new_account_presenter.rb
app/presenters/service_sign_in/paths.rb
test/controllers/content_items_controller_test.rb
test/controllers/service_sign_in_content_item_controller_test.rb

This approach mirrors the existing way that guides handles redirects.
Makes sure that only the routes specified in the content_item for service sign-in pages results in a page, and any other routes get redirected to the choose-sign-in page.
- [Default](https://government-frontend-pr-626.herokuapp.com/log-in-file-self-assessment-tax-return/sign-in/prove-identity)
- [Create new account](https://government-frontend-pr-626.herokuapp.com/log-in-file-self-assessment-tax-return/sign-in/register-self-assessment)
- [Redirected root](https://government-frontend-pr-626.herokuapp.com/log-in-file-self-assessment-tax-return/sign-in)
- [Redirected suffix](https://government-frontend-pr-626.herokuapp.com/log-in-file-self-assessment-tax-return/sign-in/invalid-url)
- …

Redirect service sign in page root

---

app/views/shared/_sidebar_navigation.html.erb
app/views/shared/_sidebar_tasklist.html.erb

- top margin applied to task list sidebar only if it is not appearing on a universal layout page
Example of problem (in universal layout):
Fix (in universal layout):
Example of layout required in all other layouts (note deliberate margin above task list):
https://government-frontend-pr-629.herokuapp.com/component-guide
https://government-frontend-pr-629.surge.sh/gallery.html

Add logic to handle different layouts

---

Gemfile
Gemfile.lock

There have been changes in `govuk_navigation_helpers` so we need to bump the gem version.
Related PR's:
Update to tasklists - https://github.com/alphagov/govuk_navigation_helpers/pull/104
Bump version to 8.1.1 - https://github.com/alphagov/govuk_navigation_helpers/pull/105

Bump govuk_navigation_helpers version to 8.1.1

---

Jenkinsfile

Hey :wave:,
We've tagged all the tests in the E2E repo which interact and depend on the government-frontend application in some way.
By only running the tests which interact with the government-frontend app we can reduce the running time of the E2E tests for commits against this app without reducing the confidence that the E2E tests bring. 🎉

Only run E2E tests which involve government-frontend

---

app/assets/stylesheets/components/_related-navigation.scss

Done in order to visually tighten up the grouping.
https://government-frontend-pr-633.herokuapp.com/component-guide
Before:
After:
Link to check:
https://www.gov.uk/government/publications/russia-tax-treaties

Reduced the spacing between on related nav

---

app/views/shared/_publisher_metadata_with_logo.html.erb

Remove unused variable in publisher metadata with logo partial.
At the moment, there's no use case for passing in other data to this partial, all uses use the default @content_item.publisher_metadata.
[Example page including partial](https://government-frontend-pr-654.herokuapp.com/government/statistics/primary-school-performance-tables-2017)

Remove unused 'metadata' variable

---

app/views/content_items/publication.html.erb

Because of the way we use template variants, when we call the shared/translations partial it sometimes renders the shared/translations+taxonomy_navigation variant.
Publications that are tagged to a new taxonomy use this variant to show an alternative breadcrumb, so we can't remove the variant completely for Publications.
The taxonomy_nav version of the translation partial expects to be inlined in content, so doesn’t have a grid class wrapping it. Because of Rails magic loading in this variant the code looks fine, and it only breaks on certain publications which meet the taxonomy nav criteria.
* Don’t use the shared translations template
This duplicates some code which can be DRY’d up when we no longer need
the taxonomy_nav variants.

Render translations correctly on publications tagged to a taxon

---

app/views/components/_published-dates.html.erb

The `time` element in the `published-dates` component specified two class attributes
for two CSS classes, this is causing the E2E tests to return the failure:
`RuntimeError: In backend response: '126:117: ERROR: Attribute class redefined'`
See https://github.com/alphagov/government-frontend/pull/659#issuecomment-355234836 for full context. Thanks @adrianclay for clarifying this.
Also: Linting, where were you? Too busy with whitespace?

Specify all css classes in one attribute

---

Gemfile
Gemfile.lock

Update govuk_navigation_helpers to 8.2.0 to include:
* Update related navigation sidebar helper to return mainstream topics alongside whitehall topics
* Update content in the /end-a-civil-partnership, /get-a-divorce tasklists

Bump govuk_navigation_helpers to 8.2.0

---

app/presenters/consultation_presenter.rb
app/views/content_items/consultation.html.erb
test/integration/consultation_test.rb

**Before:**
**After:**
**Links to Test:**
- [Open Consultation](https://government-frontend-pr-650.herokuapp.com/government/consultations/keeping-children-safe-in-education-proposed-revisions)
- [Closed Consultation](https://government-frontend-pr-650.herokuapp.com/government/consultations/offensive-and-dangerous-weapons-new-legislation)
- [Consultation Outcome](https://government-frontend-pr-650.herokuapp.com/government/consultations/short-inspections-of-good-schools-maintained-schools-and-academies)
- [Consultation with History Notice](https://government-frontend-pr-650.herokuapp.com/government/consultations/science-advisory-council-sac-and-the-advisory-committee-on-releases-to-the-environment-acre-triennial-review-2014)
- [Consultation with …

Move consultations to universal layout

---

app/assets/stylesheets/components/_contents-list-with-body.scss
app/views/components/_contents-list-with-body.html.erb
app/views/components/_published-dates.html.erb
app/views/components/docs/contents-list-with-body.yml
app/views/content_items/specialist_document.html.erb
test/components/contents_list_with_body_test.rb
test/integration/specialist_document_test.rb

https://trello.com/c/OvoXIWYp/184-move-specialist-documents-to-universal-design
Moves specialist documents to universal layout. This format contains extensive metadata specific to the various document types and often long content lists.
- Adds a `contents-list-with-body` component which decorates content with a `contents-list` and `back-to-top` link
- https://government-frontend-pr-659.herokuapp.com/cma-cases/euro-car-parts-andrew-page-merger-inquiry
- https://government-frontend-pr-659.herokuapp.com/aaib-reports/aaib-investigation-to-agusta-aw139-g-cipw
- https://government-frontend-pr-659.herokuapp.com/business-finance-support/business-development-grant-scheme-scarborough-borough
- https://government-frontend-pr-659.herokuapp.com/drug-safety-update/paraffin-based-treatments-risk-of-fire- …

Move specialist documents to universal layout

---

config/application.rb
test/controllers/task_list_ab_testing_content_items_controller_test.rb
test/controllers/task_list_header_ab_testing_content_items_controller_test.rb

We weren't testing publications or answers here which missed a breaking change.
We also had a require for the govuk_publishing_components gem which we no longer needed as we always load it in the Gemfile now (since https://github.com/alphagov/government-frontend/pull/578)

Increase test coverage of tasklists

---

app/assets/javascripts/webchat.js
app/assets/javascripts/webchat/library.js
app/presenters/contact_presenter.rb
spec/javascripts/webchat.spec.js
test/presenters/contact_presenter_test.rb

Trello card: https://trello.com/c/ebGpJZui
We have been working with HMRC to update their Webchat API. We are asking them to normalise their endpoints and responses to match that in the [reference-webchat-proxy](https://github.com/alphagov/reference-webchat-proxy) to make it easier for us to allow other departments to set up their own webchats.
HMRC have done their side of the work so we are ready to call the new endpoints.
At the moment we are only doing a one-to-one replacement. When another department is ready to add Webchat to their contact pages, we will have to think about how we are going to store which endpoint to call and whether this is something we should add to Publisher.

Update hmrc webchat endpoints

---

app/views/components/_important-metadata.html.erb
app/views/components/docs/important-metadata.yml

* Include example with multiples
https://government-frontend-pr-676.herokuapp.com/component-guide/important-metadata/with_multiple_items_per_thing

Put space between items in important metadata

---

app/assets/stylesheets/views/_travel-advice.scss
app/views/shared/_travel_advice_summary.html.erb

https://govuk.zendesk.com/agent/tickets/2546303
This was an unintended consequence of [trying to isolate travel advice
figure styling from changes made in the universal layout design](https://github.com/alphagov/government-frontend/commit/4c5c866f8229ed05d01cbfcb30768f9159c25f52).
Updated so that if a large map image is used it should be constrained
to the body column width.
https://government-frontend-pr-688.herokuapp.com/foreign-travel-advice/tunisia
cc @boffbowsh @fofr

Constrain map image to column width

---

test/integration/statistics_announcement_test.rb
test/presenters/service_sign_in/choose_sign_in_presenter_test.rb

Fixes:
>DEPRECATED: Use assert_nil if expecting nil from test/presenters/service_sign_in/choose_sign_in_presenter_test.rb:40. This will fail in Minitest 6.
>Unused parameters passed to Capybara::Queries::TextQuery

Fix some warnings when running the test suite

---

app/views/components/_important-metadata.html.erb
app/views/shared/_publisher_metadata_with_logo.html.erb
app/views/shared/_sidebar_navigation.html.erb
app/views/shared/_travel_advice_summary.html.erb

I mistakenly (and inconsistently :-1:) added these chars to a few erb files.
[While `erb_trim_mode` removes trailing whitespace](https://apidock.com/rails/v4.2.1/ActionView/Base) it's not necessary and not consistent in this app so I've found and replaced all instances.

Remove ERB trim mode chars

---

app/assets/stylesheets/components/_contents-list-with-body.scss
app/views/components/_contents-list-with-body.html.erb
app/views/components/docs/contents-list-with-body.yml
test/components/contents_list_with_body_test.rb

This component accepts a block and decorates the given block with a contents list and back
to top link if the contents parameter is not empty.
I've split the component from https://github.com/alphagov/government-frontend/pull/659 as we can't merge the changes to specialist document layout yet.
This component is shared across several other formats such as document collections, corporate information pages and detailed guides, hence this PR to introduce it standalone. It has been tested and approved in https://github.com/alphagov/government-frontend/pull/659.
https://government-frontend-pr-685.herokuapp.com/component-guide
Content list with body:
https://government-frontend-pr-685.herokuapp.com/component-guide/contents-list-with-body

Create contents-list-with-body component

---

docs/PULL_REQUEST_TEMPLATE

Visual regression from https://github.com/alphagov/govuk-visual-regression has stopped working because uploading to Surge from Heroku no longer works.
* Remove the misleading links.
* Make it clearer that the link needs a PR number inserting into it
See https://github.com/alphagov/govuk-visual-regression/issues/3

Remove visual regression link from PR template

---

Gemfile
Gemfile.lock

We had been [using a monkey-patched version of jasmine-rails](https://github.com/alphagov/government-frontend/pull/447) because of an issue with the
[OfflineAssetPaths monkey-patch](https://github.com/searls/jasmine-rails/issues/213) in the gem itself.
This was fixed in [PR #214](https://github.com/searls/jasmine-rails/pull/214) and released in [v0.14.3](https://github.com/searls/jasmine-rails/blob/832bf7f5f203f09801b395e5c95b5d23df83a3bf/CHANGELOG.md#v0143-2017-09-27) so we should be OK to return to the rubygems version.

Return to rubygems version of jasmine-rails

---

Gemfile
Gemfile.lock
app/controllers/randomly_generated_content_item_controller.rb
test/integration/service_sign_in/choose_sign_in_test.rb
test/integration/service_sign_in/create_new_account_test.rb
test/test_helper.rb

This fixes lots of:
>warning: constant ::Fixnum is deprecated

Update to govuk_schemas-3.1 to fix some deprecation warnings

---

app/views/components/docs/contents-list-with-body.yml
app/views/content_items/working_group.html.erb

https://trello.com/c/oLC1enhS/133-move-formats-that-have-a-content-list-to-universal-design
https://government-frontend-pr-637.herokuapp.com/government/groups/joint-vat-consultative-committee-jvcc

Move working group pages to universal layout

---

app/views/content_items/statistical_data_set.html.erb
test/integration/statistical_data_set_test.rb

Trello https://trello.com/c/yreeM1zm/199-move-statistical-data-sets-to-universal-layout
---
Example of new layout:
https://government-frontend-pr-695.herokuapp.com/component-guide
Example on heroku:
https://government-frontend-pr-695.herokuapp.com/government/statistical-data-sets/tra04-pedal-cycle-traffic

Move statistical data sets to univeral layout

---

app/views/content_items/corporate_information_page.html.erb

Trello: https://trello.com/c/ZWoMdsNS/201-move-corporate-information-page-to-universal-layout
https://government-frontend-pr-697.herokuapp.com/government/organisations/public-health-england/about/equality-and-diversity
---
https://government-frontend-pr-697.herokuapp.com/component-guide

Move corporate information page to universal layout

---

test/integration/specialist_document_test.rb

We need to remove this check as we are renaming the field in content schema
and if we leave this value in we are unabel to get a green build.
We will investigate the value of adding this check back in with the update
link text once we have completed the content schema change.
https://trello.com/c/kRYLSnzm/3-countryside-stewardship-grants-rename-an-existing-category

Remove wildlife package test

---

config/locales/en.yml
test/components/related_navigation_test.rb

This was a change asked for on a Zen Desk ticket.
They wanted the "Locations" related link to be changed to "World locations" in the navigation side bar.
An example of the change is found here:
https://government-frontend-pr-704.herokuapp.com/government/news/dr-liam-fox-holds-uk-india-talks-as-ukef-boosts-trade-finance-support
https://government-frontend-pr-704.herokuapp.com/component-guide
Trello ticket:
https://trello.com/c/C9mkFHPT

Changed world_locations in locals file back to 'World locations'

---

Dockerfile

The publishing-e2e-tests are being built in production mode now, and as part of
that require the assets to be compiled into the image.

Add asset precompile step to Dockerfile

---

app/assets/stylesheets/components/_published-dates.scss
app/views/components/_published-dates.html.erb
app/views/components/docs/published-dates.yml
config/locales/en.yml
test/components/published_dates_test.rb
test/integration/fatality_notice_test.rb

- Add a top border to separate from rest of page
- Reword open/closed states to be more explicit
---
https://government-frontend-pr-698.herokuapp.com/component-guide
Before:
After:

Improve published dates component

---

app/views/content_items/case_study.html.erb
app/views/content_items/consultation.html.erb
app/views/content_items/fatality_notice.html.erb
app/views/content_items/news_article.html.erb
app/views/content_items/publication.html.erb
app/views/content_items/specialist_document.html.erb
app/views/content_items/speech.html.erb
app/views/content_items/statistics_announcement.html.erb
app/views/content_items/world_location_news_article.html.erb

For https://trello.com/c/LgveTTm5/197-ensure-components-are-consistently-ordered-in-all-formats
- In this PR we review all formats that are now using the universal layout to ensure that the ordering of components is correct.
- There were some common occurrences of components being in the wrong order, so below are some example screenshots of how the ordering has changed.  
- There were also a few occurrences where the important metadata component was present for formats that would never have that data populated, and there was a withdrawal notice present for a format that can't be withdrawn, so they have been removed in this instance.
- Finally there was one instance of translations code being used unnecessarily in a view, which has now been replaced by the shared translations partial. …

Fix universal layout component ordering

---

test/integration/case_study_test.rb
test/integration/consultation_test.rb
test/integration/document_collection_test.rb
test/integration/fatality_notice_test.rb
test/integration/news_article_test.rb
test/integration/publication_test.rb
test/integration/specialist_document_test.rb
test/integration/speech_test.rb
test/integration/statistical_data_set_test.rb
test/integration/statistics_announcement_test.rb
test/integration/world_location_news_article_test.rb
test/test_helper.rb

No Trello, this is a bit of cleanup to integration tests following recent format layout changes.
Amends a few test helper methods for publisher metadata, important metadata and related navigation:
* Adds helpful error messages to underlying `assert` methods.
* Accepts varying metadata argument types for simplicity.
* Uses new navigation test helpers across all relevant formats.
---
https://government-frontend-pr-716.herokuapp.com/component-guide

Update test helpers

---

config/initializers/govuk_publishing_components.rb
config/routes.rb

We are always requiring the `govuk_publishing_components` gem, so `GovukPublishingComponents` will always be defined, making these conditionals always true.
We used to specify the gem with `require: false`, but that's no longer the case since we're using the gem to ship the task list component (https://github.com/alphagov/government-frontend/pull/578).
cc @Davidslv

Remove redundant conditionals for publishing components

---

test/integration/specialist_document_test.rb
test/test_helper.rb

For: https://trello.com/c/qzSMAFHZ/6-3-moj-residential-tribunals-finder
As a consequence of adding a test for a new doc type: `residential-property-tribunal-decision`, we discovered that the tests were not doing what was expected (generate a random example of a certain document type).
This has been fixed in this PR.
We've also added more tests to include all of the specialist doc types available.
---
https://government-frontend-pr-712.herokuapp.com/component-guide

Fixes and expands tests for specialist doc types

---

test/integration/specialist_document_test.rb

Updates tests on government-frontend to check for a new document type for specialist documents: `residential_property_tribunal_decision`
Depends on: https://github.com/alphagov/govuk-content-schemas/pull/705 being merged and deployed.
For: https://trello.com/c/qzSMAFHZ/6-3-moj-residential-tribunals-finder
---
https://government-frontend-pr-708.herokuapp.com/component-guide

Adds test for new specialist doc type

---

app/views/components/_related-navigation.html.erb
app/views/components/docs/related-navigation.yml
test/components/related_navigation_test.rb
test/integration/document_collection_test.rb
test/integration/statistical_data_set_test.rb

https://trello.com/c/BeyCczNS/219-remove-published-by-label-in-org-component
http://government-frontend-pr-723.herokuapp.com/government/statistics/nhs-sickness-absence-rates-july-2016
http://government-frontend-pr-723.herokuapp.com/government/collections/intellectual-property-unjustified-threats-bill
https://government-frontend-pr-723.herokuapp.com/government/statistical-data-sets/uk-house-price-index-data-downloads-december-2016
These links are duplicated in the publisher metadata
component and are contentious in that they can show
multiple organisations, not necessarily the primary
publishing organisation. They should also never show
up for mainstream content.
---
https://government-frontend-pr-723.herokuapp.com/component-guide

Remove 'Published by' links from related navigation

---

app/controllers/content_items_controller.rb
test/controllers/content_items_controller_test.rb

Addresses: https://github.com/alphagov/government-frontend/issues/437
Rather than returning a 500 exception for a gone piece of content this
will return a 410 result.
The scenario this can occur in is when the following sequence occurs
- A content item is updated in the content-store to be gone
- A request is made for that piece of content, the router proxies to
government-frontend
- The content-store then updates the router that the content is gone
- Government-frontend requests the content from the content-store
- The content-store responds with a 410 response
- Government-frontend throws a 500 exception
A similar scenario also can occur with redirects however these are less
trivial to resolve.
---
https://government-frontend-pr-725.herokuapp.com/component-gu …

Return 410 when Content Store returns 410

---

app/presenters/content_item/organisation_branding.rb
test/presenters/content_item/organisation_branding_test.rb

Fixes an issue where 
/government/organisations/counter-fraud-and-security-management-service/about
is throwing errors due to having no organisation set.
eg
https://sentry.io/govuk/app-government-frontend/issues/436288507/
Pages render on live and error silently, but can be seen in a broken/fixed state on dev, eg:
http://government-frontend.dev.gov.uk/government/organisations/counter-fraud-and-security-management-service/about was failing before this fix.

Protect against missing org

---

app/assets/stylesheets/helpers/_parts.scss
app/assets/stylesheets/views/_guide.scss
app/views/content_items/travel_advice.html.erb

**Note:** We are awaiting departmental approval before this can be merged.
For https://trello.com/c/BluLBeZJ/150-move-travel-advice-format-to-universal-design
In this PR we move Travel Advice pages to use the universal layout.
Travel Advice pages have parts, which are also use by guides.  While moving guides to use the universal layout a temporary `parts-ul` mixin was created (see https://github.com/alphagov/government-frontend/pull/713) to correctly align the sidebar navigation with the top of the content body for guides, and prevent Travel Advice pages from having this change implemented before they were moved to use the new layout.  We now use this mixin temporarily for Travel Advice pages until we are able to coordinate deploys, as this format also needs to change the alignment of the …

Move Travel Advice to universal layout

---

app/controllers/content_items_controller.rb
test/controllers/content_items_controller_test.rb

See: https://github.com/alphagov/gds-api-adapters/pull/805 for context of this change
We currently have hundreds of errors in sentry:
https://sentry.io/govuk/app-government-frontend/?query=is%3Aunresolved++redirect
for this issue:
https://github.com/alphagov/government-frontend/issues/437
This utilises a method from GdsApiAdapters to determine the destination
of a redirect and return that if content-store returns a redirect.
---

Return a redirect when content-store returns a redirect

---

app/presenters/consultation_presenter.rb
app/presenters/content_item/metadata.rb
app/presenters/content_item/national_applicability.rb
app/presenters/detailed_guide_presenter.rb
app/presenters/fatality_notice_presenter.rb
app/presenters/publication_presenter.rb
app/presenters/specialist_document_presenter.rb
app/presenters/speech_presenter.rb
app/presenters/statistics_announcement_presenter.rb
app/views/content_items/consultation.html.erb
app/views/content_items/detailed_guide.html.erb
app/views/content_items/document_collection.html.erb
app/views/content_items/fatality_notice.html.erb
app/views/content_items/publication.html.erb
app/views/content_items/specialist_document.html.erb
app/views/content_items/speech.html.erb
app/views/content_items/statistical_data_set.html.erb
app/views/content_items/statistics_announcement.html.erb
app/views/shared/_footer.html.erb
test/presenters/specialist_document_presenter_test.rb
test/presenters/speech_presenter_test.rb
test/presenters/statistics_announcement_presenter_test.rb

https://trello.com/c/CfGoDBRh/218-simplify-metadata-presenter-module
Addresses some of the presenter tech debt caused by splitting metadata into two components.
---
https://government-frontend-pr-730.herokuapp.com/component-guide

Refactor metadata presenter

---

app/assets/stylesheets/components/_figure.scss
app/views/components/_figure.html.erb

This removes a div from the figure component. It is invalid
HTML to nest the figcaption within a div and it is not
necessary here. Relevant css has been switched to the figcaption
instead of the div with no visible difference.
Trello: https://trello.com/c/cH3Yn5yk/241-fix-invalid-html-around-figcaption
Examples:
https://government-frontend-pr-736.herokuapp.com/government/case-studies/out-of-syria-back-into-school
https://government-frontend-pr-736.herokuapp.com/government/case-studies/first-deployment-of-a-uk-team-of-experts-to-the-syrian-border
Padding:
Before:
After:
---
https://government-frontend-pr-736.herokuapp.com/component-guide

Remove invalid div from figure component

---

app/presenters/navigation/specialist_documents.rb
test/presenters/navigation/specialist_documents_test.rb

https://trello.com/c/nrAQ1eXm/198-iterate-related-navigation-to-show-other-similar-formats-from-the-same-organisation
Follow up from https://github.com/alphagov/government-frontend/pull/720
We don't want to filter specialist content by date of occurrence
as this provides too narrow (ie. empty) a result set.
https://government-frontend-pr-739.herokuapp.com/aaib-reports/boeing-737-3m8-g-ezyb-13-march-2002
---
https://government-frontend-pr-739.herokuapp.com/component-guide

Exclude date of occurrence from finder link

---

app/presenters/navigation/specialist_documents.rb
test/presenters/navigation/specialist_documents_test.rb

https://trello.com/c/nrAQ1eXm/198-iterate-related-navigation-to-show-other-similar-formats-from-the-same-organisation
Following up on https://github.com/alphagov/government-frontend/pull/739 we don't need to use any dates from metadata to filter the finders.
Date fields defined here: https://github.com/alphagov/govuk-content-schemas/blob/master/formats/shared/definitions/_specialist_document.jsonnet 
---
https://government-frontend-pr-740.herokuapp.com/component-guide

Exclude all specialist date facets from finder link

---

Gemfile
Gemfile.lock
app/presenters/content_item/contents_list.rb
app/presenters/specialist_document_presenter.rb
app/views/content_items/statistical_data_set.html.erb
app/views/content_items/topical_event_about_page.html.erb
test/integration/corporate_information_page_test.rb
test/integration/detailed_guide_test.rb
test/integration/document_collection_test.rb
test/integration/specialist_document_test.rb
test/integration/statistical_data_set_test.rb
test/integration/topical_event_about_page_test.rb
test/integration/working_group_test.rb
test/presenters/content_item/contents_list_test.rb
test/presenters/specialist_document_presenter_test.rb
test/test_helper.rb

For https://trello.com/c/2UIR4Sen/210-investigate-how-to-deal-with-short-content-lists
We have identified that there are occasions where it's not appropriate to display a contents list, for example when there is only one item on the list.  Having spiked an approach for displaying a contents list dependent on certain conditions, this PR implements the approach.  We've reached the below criteria for displaying a contents list in conjunction with Si Stephens-Manassiev in the content team:
1) We won't show a contents list that has one item.
2) We will show a contents list with 2 items if the first item's character count is over 415.
3) We will show a contents list with 2 items if the first item contains a table with more than 13 rows.
4) We will show a contents list with 2 items if the first …

Display contents lists under specific conditions

---

app/assets/stylesheets/helpers/_publisher-metadata-with-logo.scss
app/presenters/content_item/national_statistics_logo.rb
app/presenters/detailed_guide_presenter.rb
app/presenters/publication_presenter.rb
app/presenters/statistics_announcement_presenter.rb
app/views/shared/_publisher_metadata_with_logo.html.erb
test/integration/detailed_guide_test.rb
test/presenters/detailed_guide_presenter_test.rb

Responding to urgent ZD ticket https://govuk.zendesk.com/agent/tickets/2578725
https://government-frontend-pr-746.herokuapp.com/guidance/england-2014-to-2020-european-structural-and-investment-funds
Publisher metadata should render the relevant logo next to it,
previously this worked for National Statistics but the European
structural investment funds logo was not tested and therefore
not included in the move to a new layout.
This commit adds a presenter unit test and a format specific
integration test to cover the rendering of this logo.
---
https://government-frontend-pr-746.herokuapp.com/component-guide

Render European structural investment funds logo

---

app/controllers/content_items_controller.rb

This method isn't called from anywhere.

Remove unused method

---

app/presenters/contact_presenter.rb

The CIS webchat service is ending soon, so do not show it on their contact page.
https://trello.com/c/r7m8kVIo/64-remove-webchat-from-contact-page
Marked as DO NOT MERGE until we're ready to deploy it.

Remove Webchat section from Construction Industry Scheme contact page

---

app/presenters/detailed_guide_presenter.rb

I should have removed this as part of https://github.com/alphagov/government-frontend/pull/746
Images, specifically logos, appear next to the publisher metadata.
If a presenter instance responds to `:logo` then the returned hash
is used to present the logo. The method I'm removing here is a
duplication of this functionality.
---

Remove unused and untested method

---

app/presenters/navigation/publications.rb
test/presenters/navigation/publications_test.rb

https://govuk.zendesk.com/agent/tickets/2581092
Some document types need to capitalised, National Statistics for example.
Others like FOI releases contain acronyms which also need to stay in caps.
https://government-frontend-pr-754.herokuapp.com/government/statistics/security-situation-statistics-for-northern-ireland-period-ending-31-january-2018
https://government-frontend-pr-754.herokuapp.com/government/publications/dvsa-foi-disclosure-log-december-2017
---
https://government-frontend-pr-754.herokuapp.com/component-guide

Capitalise certain document types in finders link

---

app/views/components/_contents-list.html.erb
app/views/components/docs/contents-list.yml
test/components/contents_list_component_test.rb

Guide chapter headings are changing to match the format of Content
Lists. Rather than creating a new component it makes sense to
reuse this one. The main difference is that the guides have contents
that span different urls and it isn't desirable to link a page
directly to itself. This adds support for a list item without a link
in a contents list.
Additionally, tracking has been added, as per https://trello.com/c/prpbSir0/486-create-or-adapt-a-frontend-component-for-mainstream-guides-chapters-with-tracking - all links are labelled as content_item or nested_content_item for tracking purposes. This was a requirement for Guide chapter headings so it made sense to apply it across the board.
---
https://government-frontend-pr-753.herokuapp.com/component-guide

Add support for blank hrefs

---

app/presenters/contact_presenter.rb
test/presenters/contact_presenter_test.rb

This service will be unavailable between 19 Feb and 25 Feb 2018, after that
this code can be reverted.
https://govuk.zendesk.com/agent/tickets/2582003
---

Temporarily disable webchat for self-assessment-online-services-helpdesk

---

config/locales/en.yml

https://trello.com/c/Is4EnOqt/272-bug-employment-tribunal-decisions-missing-translation-for-finder-link
Employment tribunal decisions have a link to finder with a broken translation key:
https://www.gov.uk/employment-tribunal-decisions/miss-r-daley-v-charles-wilson-engineers-ltd-1801444-2017
Amended this looks like:
https://government-frontend-pr-771.herokuapp.com/miss-r-daley-v-charles-wilson-engineers-ltd-1801444-2017
---
https://government-frontend-pr-771.herokuapp.com/component-guide

Fix typo in key for employment tribunal decisions

---

app/views/components/_contents-list.html.erb
app/views/components/docs/contents-list.yml
test/components/contents_list_component_test.rb

This allows an aria-label to be added in order to contextualise
the contents list. It was requested by modelling services since
they will be using it for chapter headings on guides that were
previously contextualised for assistive technology.
---
https://government-frontend-pr-769.herokuapp.com/component-guide

Support aria-label in contents lists

---

app/presenters/content_item/contents_list.rb
test/presenters/content_item/contents_list_test.rb

Our contents lists appear according to whether the length
of content warrants it. This fix addresses a problem whereby
sections with content in list format were excluding the list
from the calculation of length.
Before:
After:
---
Examples:
https://government-frontend-pr-765.herokuapp.com/government/collections/rare-and-imported-pathogens-laboratory-ripl
https://government-frontend-pr-765.herokuapp.com/government/collections/fraud-error-debt-and-grants-function

Take lists into account when checking content length

---

app/presenters/navigation/announcements.rb
app/presenters/navigation/finders.rb
app/presenters/navigation/publications.rb
app/presenters/navigation/specialist_documents.rb
app/presenters/navigation/statistics.rb
test/integration/consultation_test.rb
test/integration/fatality_notice_test.rb
test/integration/news_article_test.rb
test/integration/publication_test.rb
test/integration/specialist_document_test.rb
test/integration/speech_test.rb
test/integration/statistical_data_set_test.rb
test/integration/statistics_announcement_test.rb
test/integration/world_location_news_article_test.rb
test/presenters/navigation/announcements_test.rb
test/presenters/navigation/publications_test.rb
test/presenters/navigation/statistics_test.rb

https://trello.com/c/Es6gHzer/271-rephrase-links-to-finders
The engagement for the existing links to finders was fairly low, we'd like to understand if the link text being more descriptive and accurate can improve this. 
- https://government-frontend-pr-773.herokuapp.com/government/speeches/opening-speech-by-lord-hill-of-oareford-on-the-second-reading-of-the-academies-bill
- https://government-frontend-pr-773.herokuapp.com/government/consultations/great-western-rail-franchise
- https://government-frontend-pr-773.herokuapp.com/government/statistics/announcements/criminal-court-statistics-quarterly-january-to-march-2018
---
Addresses https://github.com/alphagov/government-frontend/issues/745
https://government-frontend-pr-773.herokuapp.com/component-guide

Rephrase finder links with more detail, accuracy.

---

app/controllers/concerns/guide_nav_ab_testable.rb
app/controllers/content_items_controller.rb
app/presenters/content_item/parts.rb
app/views/content_items/guide.html.erb
app/views/layouts/application.html.erb
app/views/shared/_parts_navigation.html.erb
test/controllers/guide_chapter_nav_ab_test_controller_test.rb

The diffs are best viewed [without whitespace](https://github.com/alphagov/government-frontend/pull/774/files?w=1) because of indentation changes in markup
We want to test chapter navigation which does not use numbers, as we think this may not aid comprehension and may be confused with step by step navigation.
We're using the [contents-list component](https://government-frontend.herokuapp.com/component-guide/contents-list) as the alternate, because it fits our needs and is already used in other formats.
We are not including Education format as there are other tests inbound for this and we don't want to affect them.
https://trello.com/c/iYJRN2kM/487-set-up-an-a-b-test-for-mainstream-guide-chapter-changes

AB test guide chapter navigation

---

app/controllers/concerns/guide_nav_ab_testable.rb
test/controllers/guide_chapter_nav_ab_test_controller_test.rb

We actually want CD 64 not 61 for the guide chapter navigation test.

Correct custom dimension

---

app/views/components/_contents-list.html.erb
test/components/contents_list_component_test.rb

We need to add the track click data module to a parent element in order to pick
up link tracking on the content links.

Add track-click to contents-list

---

app/views/components/_notice.html.erb
app/views/components/_related-navigation.html.erb
app/views/components/docs/related-navigation.yml
test/components/notice_test.rb

This is based on feedback from the accessibility team and does the following:
- Moves the navigation title inside the navigation block
- Removes complementary role and aside (replaced with div)
- Adds a role of “region” to notice section and makes test for it more specific
The accessibility team have agreed that the navigation component should be marked up as navigation and not as tangential content (see [Trello card](https://trello.com/c/S96QAn30/274-improve-accessibilty-context-of-related-navigation-link-grouping)).
Example page:
https://government-frontend-pr-775.herokuapp.com/government/speeches/elizabeth-truss-calls-for-a-renaissance-in-maths

Improve accessibility labelling on Notice component and navigation

---

app/presenters/content_item/parts.rb
app/views/shared/_parts_navigation.html.erb
test/integration/guide_test.rb
test/presenters/content_item/parts_test.rb
test/presenters/travel_advice_presenter_test.rb

This is intentionally identical to [contents-list tracking](https://github.com/alphagov/government-frontend/blob/422cf974706b73e2f65f9bd1c1db43e9e4a56047/app/views/components/_contents-list.html.erb#L39-L46) as we want to directly compare the performance of both.
The tests are a little bit horrible because the addition of the tracking in the presenter means that we need to match long strings, but this does make it easier to update the test should the link change in future.

Link tracking on classic part navigation

---

app/assets/javascripts/application.js

Step by step navigation needs this from govuk_publishing_components.  We'll
look at perhaps moving this to a better namespace, but this should be fixed
soon as it causes script errors on pages with step by step navigation if it's
not there. (eg https://www.gov.uk/theory-test )

Add step navigation dependency

---

Gemfile
Gemfile.lock
app/helpers/related_navigation_sidebar_helper.rb

Addresses problems spotted here https://github.com/alphagov/government-frontend/pull/781
Rename a helper (module) so that it won't collide with a class with the same name introduced in v5.2.0 of the govuk_publishing_components gem.
cc @tijmenb @emmabeynon 
---
https://government-frontend-pr-790.herokuapp.com/component-guide

Rename helper module

---

app/lib/services.rb

By default, gds-api-adapters caches responses based on the `max-age` set in the response's cache control headers. This means that government-frontend can use a very stale max-age when setting cache headers on its own responses.
In the worst case scenario, this means that content changes can take up to 30 minutes to appear on the site.
Disabling this cache should not put much more load on the content store because responses are cached so heavily in Varnish and the CDN, and these handle cache headers correctly.
The plan is to let this run on staging for a day or so to see if it can handle the traffic replay without caching. If not, we can try to improve the caching - it looks like gds-api-adapters can also handle an `expires` header containing an actual date, so we could set that in …

Disable caching of content-store responses

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/views/_service_sign_in.scss
app/presenters/service_sign_in/choose_sign_in_presenter.rb
app/presenters/service_sign_in/create_new_account_presenter.rb
app/presenters/service_sign_in/verify_hub_trial_create_new_account_presenter.rb
app/services/presenter_builder.rb
app/views/content_items/service_sign_in.html.erb
app/views/content_items/service_sign_in/_verify_hub_trial_create_new_account.html.erb
test/integration/service_sign_in/verify_hub_trial_create_new_account_test.rb
test/presenters/service_sign_in/verify_hub_trial_create_new_account_presenter_test.rb

[PR description by @tijmenb)
This pull request implements 2 new "create account" pages as a trial. They're built by GOV.UK Verify and will run on the site for 2 weeks. Note that `HUB-39` refers to an issue on Verify's non-public issue tracker.
The [comment below](https://github.com/alphagov/government-frontend/pull/776#issuecomment-366957909) captures most of the reasoning behind the change.
Trello ticket on GOV.UK board: https://trello.com/b/a9IKJvu5

Trial new "create account" pages

---

app/presenters/contact_presenter.rb

For: https://trello.com/c/AM5NDpCB/80-1-add-webchat-back-on-25th-feb-2018
Reverts alphagov/government-frontend#742
The webchat section on Construction Industry Scheme contact page was to be removed from 18th -> 25th Feb.

Revert "Remove Webchat section from Construction Industry Scheme contact page"

---

app/presenters/service_sign_in/verify_hub_trial_create_new_account_presenter.rb
app/views/content_items/service_sign_in/_verify_hub_trial_create_new_account.html.erb
test/integration/service_sign_in/verify_hub_trial_create_new_account_test.rb
test/presenters/service_sign_in/verify_hub_trial_create_new_account_presenter_test.rb

Further to the trial new view for service signing create account page we have found some copy changes that are needed under the Create Account heading and in the Government gateway service section. This text must be set dynamically for each of the two services involved in the trial so for the time being this is being set as a property from the presenter. Should the trial prove successful we will add the copy in publisher as discussed. Tests have been updated.
This amendment has been added as a comment to the original text card: https://govukverify.atlassian.net/browse/HUB-39
Screenshots for each of the three services that hit this page are below (run locally)
http://localhost:3090/check-income-tax-current-year/sign-in/create-account 
and …

Hub 39 new create account page trial - copy change

---

app/views/content_items/_publication_inline_body.html.erb

https://govuk.zendesk.com/agent/tickets/2583792
https://trello.com/c/aPpXYR8h/294-translation-of-related-navigation-component
Fixes a pluralisation problem for publications 'Documents' heading.
We don't need a variable heading based on the number of documents attached to a publication, the heading should always be pluralised.
Production
PR
https://government-frontend-pr-804.herokuapp.com/government/publications/tb-restricted-cattle-application-to-hold-a-market-gathering-or-dedicated-sale.cy
---
https://government-frontend-pr-804.herokuapp.com/component-guide

Ensure we always pluralise the translation for 'Documents'

---

app/presenters/contact_presenter.rb

Reverts #800 and reinstate #742 (which means we remove webchat from the Construction Industry Scheme contact page).
We had some crossed wires about which of the two "remove webchat" stories we were doing needed to be reinstated on the 25th Feb.  We shouldn't have reinstated webchat on Construction Industry Scheme - it should be removed forever, we should have reinstated webchat on Self-assessment Online Services Helpdesk as it was a temporary trial from 19th to 25th.  The Self-assessment Online Services Helpdesk webchat removal was handled in #766 and gated so that it reinstated automatically, and, as it turns out, they decided the trial was good enough to keep it removed forever too which was handled in #805.

Revert "Revert "Remove Webchat section from Construction Industry Scheme contact page""

---

Gemfile.lock
app/controllers/application_controller.rb
app/views/content_items/publication.html.erb
app/views/layouts/application.html.erb
app/views/shared/_sidebar_navigation.html.erb
app/views/shared/_sidebar_step_nav.html.erb
app/views/shared/_step_nav_header.html.erb
test/controllers/step_navigation_controller_test.rb

We've moved the step by step navigation helpers to the publishing components, so we need to update the frontend apps.
This now reads the step by step navigation content from the content item rather than it being hardcoded in the govuk_navigation_helpers gem.
https://trello.com/c/ESb3nINX/442-government-frontend-renders-step-by-step-navigation-from-content-item

Render step by step navigation from content items

---

app/presenters/service_sign_in/verify_hub_trial_create_new_account_presenter.rb
app/services/presenter_builder.rb
test/presenters/service_sign_in/verify_hub_trial_create_new_account_presenter_test.rb

The Personal Tax Account service start page is moving to the new start page/interstitial page/create account pattern deployed in Q3 for Self Assessment, Company Car Tax and Check This Year's Tax. As with the other two services in the trial, the intention is to give people more information to help them make a more informed choice between Gateway and Verify. In the past we've seen similar changes drive more people to Verify.
Our Jira ticket: https://govukverify.atlassian.net/browse/HUB-73
This PR is to add the new trial design of the _create account_ page to the Personal Tax account Service. The change adds the new service route to the existing trial presenter and view.
There will be corresponding changes in publisher to move this service to the new start page and add the interstitial page. …

HUB-73 Add new sign-in page design to Personal Tax Account service

---

app/models/navigation_type.rb
app/views/shared/_sidebar_navigation.html.erb

The recent changes to the taxonomy exposed that we have duplicated logic between this application and the components. At the moment this app thinks that there are taxons, so it tries to show the sidebar. However, the `govuk_component/taxonomy_sidebar` component *doesn't* think there are taxons, because it only looks at the live ones.
This is a temporary fix, we will re-architect this so that the logic is simple and in only one place. I'm also sad about the lack of failing tests for this.

Fix sidebar taxon showing

---

config/locales/en.yml

We're receiving reports on collections of people seeing the message
```
translation missing: en.content_item.schema_name.coming_soon
```
For ex: https://www.gov.uk/government/collections/vat-information-sheets
---

Adds missing coming soon translation

---

app/views/shared/_webchat.html.erb

Message to try and avoid people incorrectly using the webchat when they want a
different department.
This only appears for the specific webchat instance:
https://trello.com/c/6Gt4ON2h/100-2-text-change-to-webchat

Add clarification message for tax credit webchat

---

app/controllers/content_items_controller.rb
test/controllers/service_sign_in_content_item_controller_test.rb

This works by checking that the path contains the string 'sign-in'. I was hoping to use a route constraint, but couldn't get it to work on a glob/catch all parameter.
---
https://government-frontend-pr-842.herokuapp.com/component-guide

Check content item is a sign in page before attempting to sign in

---

app/assets/stylesheets/components/_contents-list.scss

- restore underline by default, in line with (growing consensus of) link styles across GOV.UK
- slightly increase spacing between links on mobile but leave it as it is on desktop. It's still a bit close on mobile, but any further is going to push the height of longer lists of links too much
- also slightly increase indent spacing on links, to put more space between text and dash
Underline before:
Underline after:
Spacing on mobile before:
Spacing on mobile after:
---
https://government-frontend-pr-852.herokuapp.com/component-guide

Contents list style adjustments

---

Gemfile
Gemfile.lock

https://trello.com/c/lOtOV4wU/160-add-taxonomy-sidebar-to-all-pages-tagged-to-live-taxons
Updates `govuk_publishing_components` to `6.1.0` this relaxes the constraint that taxonomy navigation only shows for guidance.
Example:
https://government-frontend-pr-854.herokuapp.com/government/news/ve-day-events-and-general-information
---
https://government-frontend-pr-854.herokuapp.com/component-guide

Update govuk_publishing_components to 6.1.0

---

app/assets/stylesheets/components/_blue-box-campaign.scss
app/assets/stylesheets/components/_native-campaign.scss
app/controllers/concerns/contextual_comms_ab_testable.rb
app/controllers/content_items_controller.rb
app/views/components/_blue-box-campaign.html.erb
app/views/components/_native-campaign.html.erb
app/views/layouts/application.html.erb
app/views/shared/_sidebar_navigation.html.erb
test/components/blue_box_campaign_test.rb
test/components/native_campaign_test.rb
test/controllers/contextual_comms_ab_test_controller_test.rb

For https://trello.com/c/h0AKz5g2/55-overview-card-for-building-the-experiment-on-govuk
This adds an A/B/C test for the contextual comms experiment.  We are testing two campaign formats (Native and Blue Box) against a control of no campaign displayed.  We have four campaigns to promote and have selected a group of pages for each campaign on which the test will be conducted. After this test has concluded we intend to tear this code out.
To view the test variations in the browser, navigate to https://government-frontend-pr-850.herokuapp.com/armed-forces-pension-calculator and use the ModHeader Chrome extension to set a Request Header:
- Name: `GOVUK-ABTest-ContextualComms`
- Value: `BlueBoxCampaign`, `NativeCampaign` or `NoCampaign`.
**Page with variation "NoCampaign"**
**Page with …

Add Contextual comms A/B/C test

---

app/assets/stylesheets/components/_contents-list.scss
app/views/components/_contents-list.html.erb
app/views/components/docs/contents-list.yml
app/views/content_items/guide.html.erb
test/components/contents_list_component_test.rb

- change back to defaulting to not underlining any links by default
- add option on a per use basis to turn underline on
Yesterday we turned on underline on all links in the component by default, but realised that this isn't ideal, particularly when the links are numbered. Since we only (for now) want underline on guide chapter navigation, this option will let us turn it on where needed.
---
https://government-frontend-pr-856.herokuapp.com/component-guide

Contents list add underline option

---

docs/PULL_REQUEST_TEMPLATE

Visual regression tests on Heroku are working again, see: https://github.com/alphagov/govuk-visual-regression/pull/5
Add a link back into the PR template description for reference.
---

Re-instate regression test info in PR template

---

app/views/layouts/application.html.erb

See https://github.com/alphagov/govuk_template/issues/342
Currently we set the html level lang to "en" and add a lang attribute to the "main" element with the locale of the content.
This causes screen readers to interpret the page title in english. We should instead markup the title with the same langugage (both the title and main content are in the content item's language).
I think we should also update the core layout in static and/or govuk_template, to allow for a title lang variable to be passed in, but it doesn't seem to be necessary for formats rendered by government frontend (please correct me if I'm wrong).
Government frontend seems like a sensible place to start because it renders news which accounts for most non english content iirc.
--- …

Set title lang to match locale of content

---

Gemfile.lock

This allows government-frontend to run on Heroku as before

Bump Ruby version in Gemfile.lock

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js

Supercedes https://github.com/alphagov/government-frontend/pull/866
---
https://government-frontend-pr-871.surge.sh/gallery.html
https://government-frontend-pr-871.herokuapp.com/component-guide

Bump components gem to 6.4.0

---

app/presenters/content_item/updatable.rb
app/presenters/news_article_presenter.rb
app/presenters/news_article_structured.rb
app/views/content_items/news_article.html.erb
test/presenters/news_article_presenter_test.rb

This implements a minimum of structured data for news articles.
As per Google:
> Structured data is a standardized format for providing information about a page and classifying the page content; for example, on a recipe page, what are the ingredients, the cooking time and temperature, the calories, and so on.
https://developers.google.com/search/docs/guides/intro-structured-data
We use the JSON-LD (JSON "Linked Data", https://json-ld.org) here. It's Google's recommended way of implementing this and avoids a lot of the hassle involved with Microdata, which interleaves the structured data with HTML.
Unfortunately, the "publisher" attribute needs a logo. I've chosen the Opengraph image for this because it's not likely to change and will probably stay around for a long time. If we're going to …

Add structured data for news articles

---

app/controllers/concerns/contextual_comms_ab_testable.rb
test/controllers/contextual_comms_ab_test_controller_test.rb

This campaign is linking to a site with a lapsed certificate, so users are seeing an SSL error.
Talked to Mark (PM) and decided to remove the campaign for now.
cc @emmabeynon 
Related to https://github.com/alphagov/government-frontend/pull/850.

Temporarily disable "Get in go far" campaign

---

Gemfile
Gemfile.lock
app/presenters/content_item_presenter.rb
app/presenters/travel_advice_presenter.rb
app/views/layouts/application.html.erb
test/integration/meta_tags_test.rb

This adds a number of new metatags for third parties to use.
It makes the most difference to pages that have images, like news articles and images.
[Linter output](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fgovernment-frontend-pr-878.herokuapp.com%2Fgovernment%2Fnews%2Fhalf-term-fishing-fun-in-cornwall)
Before:
After:
Before:
After:
Tested with https://cards-dev.twitter.com/validator.
Before:
After:
Before:
After:

Better meta tags for third parties

---

app/views/content_items/service_sign_in/_choose_sign_in.html.erb
app/views/content_items/specialist_document.html.erb
test/integration/service_sign_in/choose_sign_in_test.rb
test/integration/specialist_document_test.rb

Button component is now in the gem, not static. Updating to use the gem.
https://government-frontend-pr-883.surge.sh/gallery.html
https://government-frontend-pr-883.herokuapp.com/component-guide

Use button component from gem

---

app/controllers/content_items_controller.rb
app/presenters/service_sign_in/choose_sign_in_presenter.rb
test/controllers/service_sign_in_content_item_controller_test.rb

Errors were reported in Sentry for users on IE6. The value selected on the radio form did not match any of the available values in the radio button list.
Rather than throwing a 500 error, we should show the user an error message.
See: https://sentry.io/govuk/app-government-frontend/issues/540005743/

Show an error if a strange value is "selected"

---

app/presenters/content_item_presenter.rb
app/views/layouts/application.html.erb
test/presenters/content_item_presenter_test.rb

This adds a canonical URL `link` tag to all pages. For content items with parts, it makes sure that the part slug is included at the end of the URL.
[Trello Card](https://trello.com/c/J67JSy8r/148-investigate-how-to-implement-canonical-tags-for-government-frontend-to-help-remove-duplicate-urls-2-hour-timebox)
---
https://government-frontend-pr-898.surge.sh/gallery.html
https://government-frontend-pr-898.herokuapp.com/component-guide

Canonical meta tag

---

app/helpers/webchat_availability_helper.rb
app/views/shared/_webchat.html.erb
test/helpers/webchat_availability_helper_test.rb

https://govuk.zendesk.com/agent/tickets/2783996
eg. https://government-frontend-pr-901.herokuapp.com/government/organisations/hm-revenue-customs/contact/online-services-helpdesk
---

Add HMRC webchat unavailability message

---

app/views/content_items/_body_with_related_links.html.erb
test/integration/help_page_test.rb

To ensure we are GDPR compliant we need to follow the privacy notice template where we have to include an updated timestamp on the privacy page (https://www.gov.uk/help/privacy-policy), which uses the `help_page` document type.
The `last_updated` uses the `public_updated_at` content_item attribute and will affect all `help_page` pages.
---
Trello card: 
[Enable the 'last updated' timestamp on GOV.UK privacy page / 'help_page' format](https://trello.com/c/f55CKmXD/167-enable-the-last-updated-timestamp-on-govuk-privacy-page-helppage-format-1)
https://government-frontend-pr-907.herokuapp.com/help/privacy-policy
https://government-frontend-pr-907.surge.sh/gallery.html
https://government-frontend-pr-907.herokuapp.com/component-guide

Add last_updated timestamp on help_page format

---

app/presenters/contact_presenter.rb

Requested in Zendesk ticket 2819908

Remove Webchat from HMRC Trusts page

---

test/integration/fatality_notice_test.rb

- other builds are failing because this image cannot be loaded in CI. A separate PR exists to remove this image from govuk-content-schemas
Relates to https://github.com/alphagov/govuk-content-schemas/pull/766

Remove image expectation from fatality notice test

---

Gemfile
Gemfile.lock

Removes policy links from the taxonomy sidebar;
https://github.com/alphagov/govuk_publishing_components/pull/357
This will accomodate changes relating to this card;
https://trello.com/c/3xOhZgEJ/127-removing-policy-links-from-the-taxonomy-sidebar
---
https://government-frontend-pr-927.surge.sh/gallery.html
https://government-frontend-pr-927.herokuapp.com/component-guide

Updated version for `govuk_publishing_components` gem

---

Gemfile
Gemfile.lock
app/presenters/content_item/organisation_branding.rb
app/views/content_items/corporate_information_page.html.erb
app/views/content_items/html_publication.html.erb
test/integration/corporate_information_page_test.rb
test/integration/html_publication_test.rb
test/test_helper.rb

Uses the organisation logo component added to the gem (https://github.com/alphagov/govuk_publishing_components/pull/365), replacing it with the one from static.
Trello card: https://trello.com/c/jcRtJtvm/32-move-the-organisation-logo-component-to-the-gem
Trello card: https://trello.com/c/EKEwjJ7u/167-modify-component-organisation-logo
---
https://government-frontend-pr-931.surge.sh/gallery.html
https://government-frontend-pr-931.herokuapp.com/component-guide

Use organisation logo component from gem

---

app/presenters/content_item/body.rb
app/views/content_items/_body_with_related_links.html.erb
app/views/content_items/_document_collection_body.html.erb
app/views/content_items/_publication_inline_body.html.erb
app/views/content_items/case_study.html.erb
app/views/content_items/consultation.html.erb
app/views/content_items/corporate_information_page.html.erb
app/views/content_items/fatality_notice.html.erb
app/views/content_items/gone.html.erb
app/views/content_items/guide.html+print.erb
app/views/content_items/guide.html.erb
app/views/content_items/news_article.html.erb
app/views/content_items/service_sign_in/_choose_sign_in.html.erb
app/views/content_items/service_sign_in/_create_new_account.html.erb
app/views/content_items/speech.html.erb
app/views/content_items/statistical_data_set.html.erb
app/views/content_items/take_part.html.erb
app/views/content_items/topical_event_about_page.html.erb
app/views/content_items/travel_advice.html+print.erb
app/views/content_items/travel_advice.html.erb
app/views/content_items/unpublishing.html.erb
app/views/content_items/working_group.html.erb
app/views/content_items/world_location_news_article.html.erb
test/test_helper.rb

This makes sure that we only pass in safe HTML to the govspeak component, because in the future the component won't call `html_safe` on it for us (https://github.com/alphagov/govuk_publishing_components/pull/356).
In some cases I've used `raw` because the input may be nil.
https://trello.com/c/ZMVwIyj5

Only pass in safe HTML to govspeak component

---

app/views/content_items/html_publication.html.erb

Since moving the organisation logo to the gem we're seeing intermittent test failures. This happens in cases where the random content generator in `HtmlPublicationTest` generates an organisation item without a logo in the details. This makes [`OrganisationBranding#organisation_logo` return nil][1], which is passed into the component, which subsequently crashes with a nil-error.
This makes the page more robust by only displaying logos that exist.
[1]: https://github.com/alphagov/government-frontend/blob/fc0f75cd16f4e1f126690cf5f9aee005af504186/app/presenters/content_item/organisation_branding.rb#L4

Make HTML publication page more robust

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/views/shared/_travel_advice_summary.html.erb
test/integration/guide_print_test.rb
test/integration/service_sign_in/choose_sign_in_test.rb
test/integration/service_sign_in/create_new_account_test.rb
test/integration/specialist_document_test.rb
test/integration/travel_advice_print_test.rb
test/integration/travel_advice_test.rb
test/test_helper.rb

This make the app use the metadata component from the gem, and cleans up all other usage of Static-based components. See commits for details.
https://trello.com/c/pU7YINt1

Stop using components from Static

---

app/controllers/content_items_controller.rb
app/presenters/content_item_presenter.rb
app/presenters/travel_advice_presenter.rb
test/controllers/content_items_controller_test.rb

https://trello.com/c/5GRfTtMR/233-make-atom-feeds-more-resilient
---
https://government-frontend-pr-941.surge.sh/gallery.html
https://government-frontend-pr-941.herokuapp.com/component-guide

Cache travel advice atom feeds for 5 minutes.

---

app/views/content_items/service_sign_in/_choose_sign_in.html.erb
app/views/content_items/service_sign_in/_create_new_account.html.erb
app/views/layouts/application.html.erb

The service sign in pages currently have a back button and a breadcrumb.
https://www.gov.uk/check-income-tax-current-year/sign-in/prove-identity
This shouldn't be done according to the Design System:
https://design-system.service.gov.uk/components/back-link/#when-not-to-use-this-component

Avoid double breadcrumbs on service sign in pages

---

app/presenters/specialist_document_presenter.rb
app/views/content_items/specialist_document.html.erb
test/integration/specialist_document_test.rb

https://trello.com/c/tTKHE3Bx/280-add-a-link-from-statutory-instrument-content-pages-back-to-statutory-instrument-finder
Adds a link back to the EU Withdrawal Act 2018 statutory instruments finder.
This is currently placed at the end of the content body:
~Depends on https://github.com/alphagov/govuk-content-schemas/pull/794~
https://government-frontend-pr-955.herokuapp.com/eu-withdrawal-act-2018-statutory-instruments/eu-exit-guide
---
https://government-frontend-pr-955.surge.sh/gallery.html
https://government-frontend-pr-955.herokuapp.com/component-guide

Add a footer link back to Statutory Instruments finder

---

Gemfile
Gemfile.lock
test/integration/consultation_test.rb
test/integration/corporate_information_page_test.rb
test/integration/document_collection_test.rb
test/integration/fatality_notice_test.rb
test/integration/html_publication_test.rb
test/integration/meta_tags_test.rb
test/integration/phase_label_test.rb
test/integration/service_sign_in/choose_sign_in_test.rb
test/integration/speech_test.rb
test/integration/statistical_data_set_test.rb
test/integration/statistics_announcement_test.rb
test/integration/topical_event_about_page_test.rb
test/integration/travel_advice_atom_feed_test.rb
test/integration/travel_advice_print_test.rb
test/integration/travel_advice_test.rb
test/integration/working_group_test.rb
test/integration/world_location_news_article_test.rb
test/support/poltergeist.rb
test/test_helper.rb

PhantomJS development has now been abandoned and there are some outstanding bugs that will not be fixed.
Contains various fixes that ensure the test suite is compatible with the behaviour of Chrome.
https://trello.com/c/zrQWOwDl
---
https://government-frontend-pr-975.surge.sh/gallery.html
https://government-frontend-pr-975.herokuapp.com/component-guide

Switch from PhantomJS to Chrome

---

Dockerfile

The application has a specific `/healthcheck` endpoint so we should tell Docker to use it too.
---
https://government-frontend-pr-959.surge.sh/gallery.html
https://government-frontend-pr-959.herokuapp.com/component-guide

Use healthcheck route for Docker healthcheck

---

app/presenters/content_item/withdrawable.rb

The withdrawal notice explanation has been rendered to HTML from Govspeak.
Therefore we can mark the HTML as being safe. This addresses a warning in the notice component.
See https://github.com/alphagov/govuk_publishing_components/commit/106bf9c8b165b86959269108cb684091a945469f
---
https://government-frontend-pr-973.surge.sh/gallery.html
https://government-frontend-pr-973.herokuapp.com/component-guide

Mark withdrawal notice explanation HTML as safe

---

test/test_helper.rb

```
`require 'mocha/mini_test'` has been deprecated. Please use `require 'mocha/minitest' instead.
```
---

Fix deprecated Mocha MiniTest require

---

app/presenters/contact_presenter.rb
app/views/content_items/contact.html.erb
app/views/shared/_webchat.html.erb

This commit replaces the existing hardcoded webchat info for one page with the relevant content item field, to allow editors to specify this text using contacts-admin.
Depends on https://github.com/alphagov/govuk-content-schemas/pull/798 and https://github.com/alphagov/contacts-admin/pull/446.
Trello: https://trello.com/c/kcGo8LWv/331-webchats-changes-to-dynamic-text
---
https://government-frontend-pr-982.surge.sh/gallery.html
https://government-frontend-pr-982.herokuapp.com/component-guide

Get webchat info from content item

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/helpers/_taxonomy-navigation.scss
app/controllers/concerns/content_pages_nav_ab_testable.rb
app/controllers/content_items_controller.rb
app/lib/services.rb
app/presenters/content_item_presenter.rb
app/presenters/supergroups/services.rb
app/services/most_popular_content.rb
app/services/rummager_fields.rb
app/views/layouts/application.html.erb
app/views/shared/_taxonomy_navigation.html.erb
config/locales/en.yml
startup.sh
test/controllers/content_items_controller_test.rb
test/controllers/content_pages_nav_ab_testable_test.rb
test/controllers/step_navigation_controller_test.rb
test/integration/content_pages_navigation_test.rb
test/integration/specialist_document_test.rb
test/services/most_popular_content_test.rb
test/support/content_pages_nav_test_helper.rb
test/test_helper.rb

Trello: https://trello.com/c/X1RaZyOR/46-get-most-popular-services-content
This PR sets up the Content Pages AB test. The B variant will add taxonomy navigation to the bottom of content pages which are tagged to at least one live taxon (excluding HTML publications).
This PR also includes getting the data for the first supergroup section (Services) in that navigation section. Work done to tidy up the frontend rendering of this section will be done in a later commit.
**Note: we are currently rendering all results in highlight boxes rather than making use of the document list component. This will be addressed in a later commit.**
You will need to have an extension like [ModHeader](https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj?hl=en) installed in your …

Setup Content Pages Taxonomy Navigation AB Test (with services)

---

app/controllers/content_items_controller.rb
app/presenters/supergroups/services.rb
app/views/shared/_taxonomy_navigation.html.erb
test/integration/content_pages_navigation_test.rb
test/support/content_pages_nav_test_helper.rb

**Note: base branch is add-services-ab-2 for now, while that hasn't been merged in yet.**
Trello: https://trello.com/c/ac5YHBcd/54-use-live-data-in-services-section
Example pages:
- https://government-frontend-pr-988.herokuapp.com/government/publications/l-plate-size-rules
- https://government-frontend-pr-988.herokuapp.com/student-finance
- https://government-frontend-pr-988.herokuapp.com/help-with-childcare-costs
https://government-frontend-pr-988.herokuapp.com/component-guide

Add services frontend

---

app/controllers/content_items_controller.rb
app/presenters/supergroups/services.rb
app/services/most_popular_content.rb
test/services/most_popular_content_test.rb

We don't want to show the page that a user is on in any navigation.  It's
confusing and confers no benefit.
An example page with itself in the results is: https://www.gov.uk/government/publications/retiring-teachers-nomination-form-for-official-letter-of-thanks
https://trello.com/c/ljVuTZUL/80-exclude-current-page-from-navigation
You will need to have an extension like [ModHeader](https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj?hl=en) installed in your browser to see the B Variant. The values should be:
- [Tagged to one taxon](https://government-frontend-pr-997.herokuapp.com/apply-apprenticeship)
- [In its own results set](https://government-frontend-pr-997.herokuapp.com/governmen …

Exclude current page from most popular searches

---

app/controllers/content_items_controller.rb
app/presenters/supergroups/guidance_and_regulation.rb
app/presenters/supergroups/policy_and_engagement.rb
app/presenters/supergroups/supergroup.rb
app/services/most_recent_content.rb
app/views/shared/_taxonomy_navigation.html.erb
config/locales/en.yml
test/integration/content_pages_navigation_test.rb
test/presenters/supergroups/guidance_and_regulation_test.rb
test/presenters/supergroups/policy_and_engagement_test.rb
test/services/most_recent_content_test.rb
test/support/custom_assertions.rb
test/support/rummager_helpers.rb

Adds guidance and regulation, and policy and engagement sections to the nav section at the footer of content pages.
- Policy and engagement content:
- configured to get latest content
- shows public updated at date
- document type
- Guidance and regulation
- retrieved by popularity (as determined by rummager)
- shows document type (but not date)
They're both displayed as lists of items rather than highlight boxes.
The content page will show this navigation if they are tagged to a live taxonomy, be rendered by this application and not be an HTML publication (and have results to show)
This PR is to get things generally close to the desired outcome and then we'll polish after testing and a further design review.
You will need to have an extension like …

Add supergroup sections to taxonomy navigation

---

Gemfile
Gemfile.lock
test/integration/service_sign_in/choose_sign_in_test.rb
test/integration/specialist_document_test.rb

After a couple of components have been updated to use GOV.UK Frontend we need to updates the asserts selectors to match the new classes.
This helps [Dependabot passing](https://github.com/alphagov/government-frontend/pull/998).
---
https://government-frontend-pr-999.herokuapp.com/component-guide

Bump govuk_publishing_components from 9.6.0 to 9.7.0

---

app/controllers/content_items_controller.rb
app/presenters/supergroups/transparency.rb
app/views/shared/_taxonomy_navigation.html.erb
config/locales/en.yml
test/integration/content_pages_navigation_test.rb
test/presenters/supergroups/transparency_test.rb

Adds the transparency supergroup to the taxonomy navigation section.
As per the other PRs, this is currently behind an AB test and is not seen by general access.
Transparency docs are displayed as lists of items rather than highlight boxes.
The content page will show this navigation if they are tagged to a live taxonomy, be rendered by this application and not be an HTML publication (and  have results to show)
You will need to have an extension like [ModHeader](https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj?hl=en) installed in your browser to see the B Variant. The values should be:
- [Tagged to one taxon](https://government-frontend-pr-1000.herokuapp.com/apply-apprenticeship)
- …

Add transparency section

---

app/presenters/content_item/updatable.rb
test/presenters/content_item/updatable_test.rb

`details.first_public_at` is deprecated. They should be same, so no frontend changes are intended.
Depends on https://github.com/alphagov/govuk-content-schemas/pull/801.
https://trello.com/c/bMv5Tkgp

Use `first_published_at`

---

app/assets/stylesheets/helpers/_taxonomy-navigation.scss

- Adds a dividing line to the first section
- Increases the contrast of the dividing line
https://trello.com/c/JRfx5Kjj
---
https://government-frontend-pr-1003.surge.sh/gallery.html
https://government-frontend-pr-1003.herokuapp.com/component-guide

Differentiate taxonomy navigation sections more

---

app/controllers/content_items_controller.rb
app/presenters/supergroups/news_and_communications.rb
app/presenters/supergroups/services.rb
app/presenters/supergroups/supergroup.rb
app/views/shared/_taxonomy_navigation.html.erb
config/locales/en.yml
test/integration/content_pages_navigation_test.rb
test/presenters/supergroups/guidance_and_regulation_test.rb
test/presenters/supergroups/news_and_communications_test.rb
test/presenters/supergroups/policy_and_engagement_test.rb
test/presenters/supergroups/services_test.rb
test/presenters/supergroups/transparency_test.rb
test/support/content_pages_nav_test_helper.rb

News and communications are displayed differently from the other sections in that we show images from articles for the first three items.  We'll show a placeholder if there isn't an image.
This functionality will be updated in future to get content images from rummager which removes the need to call content store for each item.
We'll also update this to display results as one list rather than as separate items.  We have this as an item in [the backlog](https://trello.com/c/JK0lJvWp/104-adapt-image-card-components-to-work-in-a-list-of-links), but it'll need work on a couple of components to achieve
I've also added tests for the services supergroup presenter, as these were missing
You will need to have an extension like [ModHeader](https://chrome.google.com/webstore/detail/modheader/idgpnmon …

Add the news and communications section

---

app/assets/stylesheets/helpers/_taxonomy-navigation.scss
app/controllers/content_items_controller.rb
app/views/layouts/application.html.erb
app/views/shared/_sidebar_navigation.html.erb
app/views/shared/_taxonomy_navigation.html.erb
test/integration/content_pages_navigation_test.rb
test/integration/content_pages_related_navigation_test.rb

Moves related collections from the sidebar to the taxonomy navigation.
https://trello.com/c/zUWqJgX9
---
https://government-frontend-pr-1008.surge.sh/gallery.html
https://government-frontend-pr-1008.herokuapp.com/component-guide

Taxonomy navigation collections

---

app/views/shared/_sidebar_navigation.html.erb
test/integration/content_pages_navigation_test.rb

Removes explore the topic from the sidebar when the taxonomy navigation is shown.
This is achieved by stripping out the mainstream browse page and topic links that the component depends on:
https://github.com/alphagov/govuk_publishing_components/blob/5fed4505deef99ad447779029ffac46d62041a39/lib/govuk_publishing_components/presenters/related_navigation_helper.rb#L119-L128
https://trello.com/c/fFxBHBQm
---
https://government-frontend-pr-1010.surge.sh/gallery.html
https://government-frontend-pr-1010.herokuapp.com/component-guide

Remove explore the topic from the sidebar

---

app/controllers/concerns/content_pages_nav_ab_testable.rb
app/views/shared/_sidebar_navigation.html.erb
test/controllers/content_pages_nav_ab_testable_test.rb
test/integration/content_pages_navigation_test.rb
test/support/content_pages_nav_test_helper.rb

- Removes sidebar if publishing app is whitehall and in ab test variant B
You will need to have an extension like [ModHeader](https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj?hl=en) installed in your browser to see the B Variant. The values should be:
- [Tagged to one taxon](https://government-frontend-pr-1009.herokuapp.com/apply-apprenticeship)
- [Tagged to multiple taxons](https://government-frontend-pr-1009.herokuapp.com/government/publications/esfa-update-18-july-2018)
- [Tagged to a taxon without services](https://government-frontend-pr-1009.herokuapp.com/government/publications/working-together-to-safeguard-children--2)
- [Not tagged to any …

Remove contextual sidebar on variant B for whitehall

---

test/integration/content_pages_navigation_test.rb

The selector we were using wasn't always present

Fix inconsistent test for variant A on AB test

---

Gemfile
Gemfile.lock
app/views/layouts/application.html.erb
test/integration/content_pages_navigation_test.rb
test/integration/specialist_document_test.rb

Show taxon breadcrumbs if there are live taxons for a content item in variant B
https://government-frontend-pr-1013.surge.sh/gallery.html
https://government-frontend-pr-1013.herokuapp.com/component-guide
https://trello.com/c/yZfYuiJp/84-use-taxons-breadcrumb-in-b-sample

Show taxon breadcrumbs for b variant

---

app/assets/stylesheets/helpers/_taxonomy-navigation.scss
app/views/shared/_taxonomy_navigation.html.erb

Trello: https://trello.com/c/I9TueAJ5/95-font-size-of-topics-collections-on-mobile-is-small
This PR:
- Increases font size of Topic and Collection links on mobile from 14px to 16px.
- Tweaks spacing of links and headings
- Reorders CSS for taxonomy_navigation to make it easier to read/follow
- Remove CSS override for component
https://government-frontend-pr-1020.herokuapp.com/component-guide
Example:
https://government-frontend-pr-1020.herokuapp.com/government/publications/academies-finance-and-assurance-steering-group-terms-of-reference?ABTest-ContentPagesNav=B

Fix taxonomy navigation (AB) small link font & refactor CSS

---

Gemfile
Gemfile.lock
test/integration/document_collection_test.rb

This version removes headings from the document list component. This caused a couple of tests to fail which have also been fixed in this commit.
There should be no visible difference between how the document list renders.
---
https://government-frontend-pr-1025.herokuapp.com/component-guide

Bump govuk_publishing_components to 9.9.1

---

app/controllers/content_items_controller.rb

Trello: https://trello.com/c/AbYDeU6N/99-dont-show-current-item-in-taxonomy-navigation-continued
Extend the logic we added to exclude the current page from the taxonomy navigation, to also apply to multi-page formats like guides.
Examples:
- https://government-frontend-pr-1026.herokuapp.com/student-finance/new-fulltime-students
- https://government-frontend-pr-1026.herokuapp.com/change-address-driving-licence/apply-by-post

Use base path to exclude current page from tax nav

---

app/views/content_items/_body_with_related_links.html.erb
app/views/content_items/contact.html.erb
app/views/content_items/guide.html+print.erb
app/views/content_items/guide.html.erb

https://trello.com/c/BUij6N3Y/361-turn-on-bold-for-whitehall
Remove the restriction of bold text via `<strong>` tags in Govspeak.
- https://government-frontend-pr-1014.herokuapp.com/guidance/connect-to-govwifi-using-an-android-device
- https://government-frontend-pr-1014.herokuapp.com/government/news/new-common-sense-code-to-build-greener-homes
- https://government-frontend-pr-1014.herokuapp.com/government/speeches/baroness-warsi-delivers-speech-at-oic-conference
- https://government-frontend-pr-1014.herokuapp.com/guidance/using-nitrogen-fertilisers-in-nitrate-vulnerable-zones
- https://government-frontend-pr-1014.herokuapp.com/government/consultations/rabies-control-strategy
- https://government-frontend-pr-1014.herokuapp.com/government/news/common-clinical-language-for-nhs-will-help-impr …

Enable bold text in govspeak

---

app/services/world_location_base_path.rb
test/services/world_location_base_path_test.rb

This is the working URL [1], so change the special case to use the
working URL.
1: https://www.gov.uk/world/south-georgia-and-south-sandwich-islands/news
---
https://government-frontend-pr-1015.surge.sh/gallery.html
https://government-frontend-pr-1015.herokuapp.com/component-guide

Change the special case to not have the "the"

---

app/services/world_location_base_path.rb
test/services/world_location_base_path_test.rb

First, revert a ineffective change I made, then attempt to clean this WorldLocationBasePath class up.
As far as I can work out, this is never used. The only document type
that uses the metadata, which is I think where this is possibly used
is travel advice. I checked if any travel advice content is tagged to
world locations, and it isn't.
This is very confusing, as the exceptional cases aren't
exceptional. Looking at the code, the behaviour looks to be the same
with or without them.
I've also removed the comment, as the situation with the migration of
"world locations to a taxonomy based model" is pretty uncertian, as
the Topic Taxonomy doesn't have anything to do with country
classification (it's about subject, not geography), and this
"temporary solution" both as far as I can work out, …

Clean up the world location base path class

---

app/services/most_popular_content.rb
app/services/most_recent_content.rb
app/views/shared/_taxonomy_navigation.html.erb
test/integration/content_pages_navigation_test.rb
test/services/most_popular_content_test.rb
test/support/rummager_helpers.rb

**Previously default was 5, now changed to 3**
---
Examples:
You will need to have an extension like ModHeader installed in your browser to see the B Variant. The values should be:
- [Tagged to one taxon](https://government-frontend-pr-1043.herokuapp.com/apply-apprenticeship)
- [Tagged to multiple taxons](https://government-frontend-pr-1043.herokuapp.com/government/publications/esfa-update-18-july-2018)
- [Tagged to a taxon without services](https://government-frontend-pr-1043.herokuapp.com/government/publications/working-together-to-safeguard-children--2)
- [Not tagged to any taxons](https://government-frontend-pr-1043.herokuapp.com/government/case-studies/hard-lines)
- [HTML …

Reduce number of related links to 3 as default

---

app/presenters/supergroups/news_and_communications.rb
app/presenters/supergroups/services.rb
app/presenters/supergroups/supergroup.rb
app/services/most_recent_content.rb
app/services/rummager_fields.rb
app/views/shared/_taxonomy_navigation.html.erb
config/locales/en.yml
test/integration/content_pages_navigation_test.rb
test/presenters/supergroups/news_and_communications_test.rb
test/presenters/supergroups/services_test.rb
test/support/content_pages_nav_test_helper.rb
test/support/rummager_helpers.rb

This eliminates up to three calls to content store for each page's navigation.
To do this we need to add image_url to the fields that rummager returns.
We can remove the alt text for images that are links because the link text is more relevant (and is preferred by browsers anyway).
We then need a default image in case the content doesn't have an image (not all do).
After rebasing on top of https://github.com/alphagov/government-frontend/pull/1043 and https://github.com/alphagov/government-frontend/pull/1032 it became clear that we can remove some things from the `news_and_communications` and `services` as they don't need to have content split into `promoted` and `tagged` content any more as they only display it in one form now.
I've therefore removed the `promoted` sections from these …

Use rummager results for image_urls

---

app/assets/stylesheets/helpers/_taxonomy-navigation.scss
app/controllers/content_items_controller.rb
app/views/layouts/application.html.erb
test/integration/content_pages_navigation_test.rb
test/support/content_pages_nav_test_helper.rb

This adds a breadcrumb and a banner navigation element listing things a content item is part of.
If the content item is tagged to a single topic a full breadcrumb to it is shown. If it is tagged to multiple topics then a home breadcrumb is shown and the topics are listed in the banner.
https://trello.com/c/rznwkADc
---
https://government-frontend-pr-1041.surge.sh/gallery.html
https://government-frontend-pr-1041.herokuapp.com/component-guide

Add banner to the taxonomy navigation

---

app/assets/javascripts/modules/track-radio-group.js
spec/javascripts/track-radio-group.spec.js

https://govukverify.atlassian.net/browse/HUB-167 : Test - verify user behaviour on interstitial page GOV.UK
We'd like to see what choices existing Verify users make on the
service sign-in page. Therefore we're loading a JS snippet from Verify to make
an ajax call and based on the user cookie to decide whether it's a
Verify user and report accordingly. This is a baseline test to learn about the users' behaviour.
The js that is referenced is in verify-frontend -> https://github.com/alphagov/verify-frontend/blob/master/public/get_hint.js
It receives a boolean answer to if the user has the journey hint cookie present and triggers a Google Analytics event with the presence or absence of the hint together with the option the user selected.
The cookie that determines if a user has visited verify …

HUB-167: Recognise and report Verify users on GOV.UK

---

app/views/shared/_taxonomy_navigation.html.erb
test/integration/content_pages_navigation_test.rb

- Taxonomy Navigation language is set to English
- Rummager search result is mostly English

Set language within navigation sections

---

app/views/shared/_taxonomy_navigation.html.erb
test/support/content_pages_nav_test_helper.rb

Trello: https://trello.com/c/kstnTmJZ/131-render-news-items-in-a-list
We should be rendering the News and Communication items within a list, not a div. This is semantically correct and more accessible. This shouldn't change how the items render visually:
Examples:
You will need to have an extension like ModHeader installed in your browser to see the B Variant. The values should be:
- [Tagged to one taxon](https://government-frontend-pr-1048.herokuapp.com/apply-apprenticeship)
- [Tagged to multiple taxons](https://government-frontend-pr-1048.herokuapp.com/government/publications/esfa-update-18-july-2018)
- [Tagged to a taxon without services](https://government-frontend-pr-1048.herokuapp.com/government/publications/wo …

Render news items within a list

---

app/lib/services.rb
app/services/most_popular_content.rb
app/services/most_recent_content.rb
test/services/most_popular_content_test.rb
test/services/most_recent_content_test.rb

We reduce the timeout for rummager queries to 2 seconds.  If they go above 2 secs for all of the queries we risk timing out the whole page which is not good. (They are generally well below this 99th %ile is at 300ms, 50th %ile is at 21ms when running on staging at double our expected load)
In addition, we catch any errors returned from the api call and set the results to empty so that we can render what we need to.
We send metrics of these errors to Graphite so we can analyse them later.
https://trello.com/c/CNGGgjcB/129-add-logging-of-ab-test-variant

Catch rummager errors for navigation

---

config/initializers/logstasher.rb

This will enable us to determine which variant a log entry refers to.  This will help with allowing us to measure performance and track errors.
This is similar to [an equivalent thing in content store](https://github.com/alphagov/content-store/blob/master/config/initializers/logstasher.rb)
https://trello.com/c/CNGGgjcB/129-add-logging-of-ab-test-variant

Add logging of variant for navigation test

---

app/controllers/content_items_controller.rb
app/presenters/content_item/metadata.rb
app/presenters/content_item_presenter.rb
app/views/components/_publisher-metadata.html.erb
app/views/components/docs/publisher-metadata.yml
config/locales/en.yml
test/components/publisher_metadata_test.rb
test/integration/content_pages_related_navigation_test.rb

https://trello.com/c/kcZ8VQS7
---
https://government-frontend-pr-1049.surge.sh/gallery.html
https://government-frontend-pr-1049.herokuapp.com/component-guide

Add collections to publisher metadata if B variant

---

app/assets/javascripts/modules/track-radio-group.js

Fixed the undefined function error by extracting the function. Looks a bit ugly but allows
for better unit testing. Refactor suggestions are welcome.
Co-Authored-By: Rachel Smith <rachel.smith@digital.cabinet-office.gov.uk>
---
https://government-frontend-pr-1053.surge.sh/gallery.html
https://government-frontend-pr-1053.herokuapp.com/component-guide

HUB-167: Fix for a broken reference to the track function

---

app/controllers/content_items_controller.rb
app/views/layouts/application.html.erb
app/views/shared/_taxonomy_navigation.html.erb
test/integration/content_pages_navigation_test.rb
test/integration/content_pages_related_navigation_test.rb

Trello: https://trello.com/c/CALq4uG8/132-add-tracking-for-ab-test
Adds Google Analytics tracking to Topic, Collection, related taxon and step by step links.
Banner with taxon and step by step links:
Topic & Collection links:
You will need to have an extension like ModHeader installed in your browser to see the B Variant. The values should be:
To see Google Analytics events firing in the Dev Tools console, you need an extension like [Google Analytics Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en)
- [Tagged to one taxon](https://government-frontend-pr-1054.herokuapp.com/apply-apprenticeship)
- [Tagged to multiple …

Add tracking for our new taxonomy navigation

---

test/integration/links_out_config_test.rb

Fixes intermittently failing test. HTML dumps show the content was being rendered but the assertion was still failing. Making capybara wait slightly longer, only in this test, while making an assertion fixes the tests (locally at least). Additionally, fixes occasional error when the rails config isn't loaded
More information on why this occurs:
https://spin.atomicobject.com/2012/04/27/intermittent-test-failures/
In the section entitled "Not waiting long enough"
---
https://government-frontend-pr-1052.surge.sh/gallery.html
https://government-frontend-pr-1052.herokuapp.com/component-guide

Fix intermittent failing test

---

app/presenters/guide_presenter.rb
app/views/content_items/guide.html.erb
test/integration/guide_test.rb

- only happens if hide_chapter_navigation is true and the guide is in a step by step
- promotes guide part subtitle to be the page title
- hides guide contents list
- hides next/prev navigation and guide print link
**Before:**
**After:**
Follows on from [this spike](https://github.com/alphagov/government-frontend/pull/1007) done previously.
Depends on https://github.com/alphagov/govuk-content-schemas/pull/809
---
Trello card: https://trello.com/c/RNsA7E4Q/763-hide-chapter-navigation-on-mainstream-guides
https://government-frontend-pr-1039.surge.sh/gallery.html
https://government-frontend-pr-1039.herokuapp.com/component-guide

Use hide_chapter_navigation on guides

---

app/presenters/consultation_presenter.rb
app/views/content_items/consultation.html.erb

When we replaced this with the notice component in the gem, we removed the bottom margin in all cases. This meant that sometimes, the heading of a section could appear directly underneath a notice with no spacing.
This fix introduces spacing in those cases, but adds a bottom margin when the notice is immediately followed by a banner item (as per the original design)
Consultation pages:
- [Open Consultation](https://government-frontend-pr-1056.herokuapp.com/government/consultations/fire-safety-clarification-of-statutory-guidance-approved-document-b)
- [Closed Consultation](https://government-frontend-pr-1056.herokuapp.com/government/consultations/home-offices-immigration-statistics-arrivals-data)
- [Closed Consultation with banner](https://government-frontend-pr-1056.herokuapp.com/governmen …

Fix spacing for notices in consultations

---

config/application.rb
test/integration/links_out_config_test.rb
test/presenters/content_item/links_out_test.rb

Improves further on PR #1052. Moved custom configuration to a before_initialize block which seems to solve a problem with the config not being available in test environment. Based on the following stackoverflow post
https://stackoverflow.com/a/44770663
Trello: https://trello.com/c/toblYkmD/133-investigate-and-fix-failing-tests-on-government-frontend
---
https://government-frontend-pr-1057.surge.sh/gallery.html
https://government-frontend-pr-1057.herokuapp.com/component-guide

Fix intermittent failing tests

---

config/locales/ar.yml
config/locales/ru.yml

These got missed from #1055 somehow.
Examples:
- https://government-frontend-pr-1072.herokuapp.com/government/news/foreign-secretary-statement-israels-right-to-defend-itself.ar
- https://government-frontend-pr-1072.herokuapp.com/government/news/foreign-secretary-statement-israels-right-to-defend-itself.ru
---
[Trello card](https://trello.com/c/y8CzrRHI/400-add-the-language-translations-into-the-universal-layout-template)

Add missing taxonomy_navigation component ar and ru translations

---

app/controllers/content_items_controller.rb
app/presenters/content_item/links_out.rb
app/presenters/supergroups/supergroup.rb
test/presenters/content_item/links_out_test.rb

Previous calls to rummager were always being filtered by subgroups, regardless of the supergroup. This meant some supergroups were not displaying at all.
This commit changes the retrieval of subgroups to link them to the current supergroup for that search. Only subgroups relevant to that supergroup are returned. If there are no subgroup filters for that supergroup, all content is retrieved.
---
Examples:
https://government-frontend-pr-1068.herokuapp.com/student-finance?ABTest-ContentPagesNav=B
https://government-frontend-pr-1068.herokuapp.com/apply-uk-visa?ABTest-ContentPagesNav=B

Fix content out links for content pages AB

---

app/presenters/content_item/linkable.rb
test/presenters/content_item/linkable_test.rb
test/presenters/content_item/shareable_test.rb
test/presenters/publication_presenter_test.rb

Trello: https://trello.com/c/3GT17tkH/211-associate-content-with-ministers-l
This is marked as not to be merged due to requiring this: https://github.com/alphagov/govuk-content-schemas/pull/816
The ministers link type is now [deprecated](https://github.com/alphagov/govuk-content-schemas/blob/76fe9441a2b9ec6f030735f012347dbe8eb6e331/formats/news_article.jsonnet#L47) as it serves the same purpose as people links and these contain the same data. This allows widening up to link to people with other role appointments.
As people document_types don't require a base_path it also does a check that those actually have links (this is something that can affect pretty much all links so there should probably be more checks across this app - but I'm not opening up that rabbit hole just yet)

Link to people instead of ministers

---

Gemfile
Gemfile.lock
app/assets/javascripts/modules/track-radio-group.js
app/presenters/service_sign_in/choose_sign_in_presenter.rb
app/views/content_items/service_sign_in/_choose_sign_in.html.erb
test/integration/service_sign_in/choose_sign_in_test.rb

https://trello.com/c/CbTYssq1/478-enable-cross-domain-tracking-for-cysp-govuk-sign-in-pages
Depends on https://github.com/alphagov/govuk_publishing_components/pull/539 and https://github.com/alphagov/govuk-content-schemas/pull/817
We need to track radio button selection events across domains
so that other departments can monitor the efficacy of changes
and options on the service sign in pages. This commit modifies
the track radio group module to include cross domain tracking
via a tracking code and name. Support is being added for radio
buttons to pass the relevant url so that the hostname can be
identified as part of the tracking.
---
https://government-frontend-pr-1102.surge.sh/gallery.html …

Add cross domain tracking to service sign in form

---

app/assets/stylesheets/components/_published-dates.scss
app/assets/stylesheets/components/_publisher-metadata.scss
app/presenters/coming_soon_presenter.rb
app/presenters/content_item/updatable.rb
app/presenters/travel_advice_presenter.rb
app/views/components/_published-dates.html.erb
app/views/components/_publisher-metadata.html.erb
test/components/publisher_metadata_test.rb
test/integration/fatality_notice_test.rb
test/integration/travel_advice_atom_feed_test.rb
test/presenters/case_study_presenter_test.rb
test/presenters/specialist_document_presenter_test.rb

Trello: https://trello.com/c/LQKpXVSw/186-audit-components-that-use-a-toggle-and-update-to-hide-the-toggle-link-when-js-is-disabled
Previously, these components would auto-expand all contents when JS was disabled (which is good), but also continue to show the toggle link which would be confusing to users. This PR only shows the toggle link if JS is enabled.
Links:
https://government-frontend-pr-1110.herokuapp.com/component-guide/publisher-metadata
https://government-frontend-pr-1110.herokuapp.com/component-guide/published-dates

Fix toggle behaviour when JS disabled

---

test/test_helper.rb

[Master branch is failing on CI](https://ci.integration.publishing.service.gov.uk/job/government-frontend/job/master/931/console) because
```
[build] Error:
[build] ServiceSignIn::ChooseSignInTest#test_renders_errors_correctly:
[build] Net::ReadTimeout: Net::ReadTimeout
[build]     test/integration/service_sign_in/choose_sign_in_test.rb:116:in `setup_and_visit_choose_sign_in_page'
[build]     test/integration/service_sign_in/choose_sign_in_test.rb:53:in `block in <class:ChooseSignInTest>'
[build] 
[build] bin/rails test test/integration/service_sign_in/choose_sign_in_test.rb:52
```
Looking at previous fails it can be any test, but always the first to call `#visit`.
https://github.com/teamcapybara/capybara/issues/1305 implies the problem may be asset compilation.
I've increased the timeout …

Increase Capybara driver timeout

---

app/assets/javascripts/modules/track-radio-group.js

https://trello.com/c/CbTYssq1/478-enable-cross-domain-tracking-for-cysp-govuk-sign-in-pages
We modify the options object for cross domain tracking, this alters the default behaviour.
In any case we should be performing our own event tracking first.
---

Send cross domain events as final tracking step

---

app/assets/javascripts/modules/track-radio-group.js
spec/javascripts/track-radio-group.spec.js

https://trello.com/c/CbTYssq1/478-enable-cross-domain-tracking-for-cysp-govuk-sign-in-pages
Track events _and_ pageviews when tracking radio groups across domains.
The pageview data is also required when performing cross domain tracking,
also add some test coverage for radio group tracking.
Also makes a copy of event tracking options so that cross domain config doesn't change the original config object.
---

Track events and pageviews

---

app/assets/javascripts/modules/track-radio-group.js
app/presenters/service_sign_in/choose_sign_in_presenter.rb
spec/javascripts/track-radio-group.spec.js
test/presenters/service_sign_in/choose_sign_in_presenter_test.rb

See https://github.com/alphagov/publisher/pull/962 and https://github.com/alphagov/govuk-content-schemas/pull/823 for context.
- Uses the tracking domain data attribute to configure a cross domain tracker.
- Sends the page view as the tracking module loads, sends the event when the radio group form is submitted.
---

Send pageviews at module load time

---

Gemfile
Gemfile.lock

This is needed in order to use the correct styling for `govspeak-html-publication` components.
Trello: https://trello.com/c/wPyyRRfH/634-table-styling-on-2018-budget-query-from-hm-treasury
Related PRs:
- https://github.com/alphagov/govuk_publishing_components/pull/618
- https://github.com/alphagov/govuk_publishing_components/pull/622
---
https://government-frontend-pr-1156.surge.sh/gallery.html
https://government-frontend-pr-1156.herokuapp.com/component-guide

Update `govuk_publishing_components` to 12.8.0

---

app/presenters/news_article_presenter.rb
test/presenters/news_article_presenter_test.rb

For https://trello.com/c/UXUxzEv4/512-amend-government-frontend-logic-to-use-default-organisation-image
In cases where a news article doesn't have an image, we use its primary
publishing organisation's default image.

Use default news image on news article pages

---

app/presenters/content_item/news_image.rb
test/presenters/content_item/news_image_test.rb

It should return a hash instead of a string.

Fix placeholder image bug

---

Gemfile
Gemfile.lock
app/views/content_items/_body_with_related_links.html.erb
app/views/content_items/case_study.html.erb
app/views/content_items/consultation.html.erb
app/views/content_items/contact.html.erb
app/views/content_items/detailed_guide.html.erb
app/views/content_items/document_collection.html.erb
app/views/content_items/fatality_notice.html.erb
app/views/content_items/guide.html.erb
app/views/content_items/news_article.html.erb
app/views/content_items/publication.html.erb
app/views/content_items/specialist_document.html.erb
app/views/content_items/speech.html.erb
app/views/content_items/statistical_data_set.html.erb
app/views/content_items/statistics_announcement.html.erb
app/views/content_items/take_part.html.erb
app/views/content_items/topical_event_about_page.html.erb
app/views/content_items/travel_advice.html.erb
app/views/content_items/world_location_news_article.html.erb
app/views/shared/_footer_navigation.html.erb

This adds a contextual footer component which contains the following that have been moved from the contextual footer component:
- Mainstream browse pages
- Taxonomy topics
- Topical events
- World locations
- Statistical data sets
- Related external links
- Related contacts
The footer component is rendered in a new grid row so that:
- it sits below the contextual sidebar for narrow device widths
- it sits below the back to content link
See https://trello.com/c/y0AcHMPc
Example URLs:
- https://government-frontend-pr-1136.herokuapp.com/universal-credit
- https://government-frontend-pr-1136.herokuapp.com/pay-dartford-crossing-charge
- https://government-frontend-pr-1136.herokuapp.com/government/organisations/hm-revenue-customs/contact/income-tax-enquiries-for-individuals-pensioners-and-employ …

Contextual footer navigation

---

app/assets/stylesheets/components/_figure.scss
app/views/components/_figure.html.erb
app/views/content_items/case_study.html.erb
app/views/content_items/fatality_notice.html.erb
app/views/content_items/news_article.html.erb
app/views/content_items/speech.html.erb
app/views/content_items/take_part.html.erb
app/views/content_items/world_location_news_article.html.erb
config/locales/en.yml
test/components/figure_test.rb

Trello: https://trello.com/c/hGmJ5BfV 
Related to: 
* https://github.com/alphagov/govuk-content-schemas/pull/850
* https://github.com/alphagov/content-publisher/pull/627
Content Publisher allows publishers to add an image credit, but we are not displaying this data on the frontend
Paired with @DilwoarH

Display image credit for lead images

---

app/controllers/application_controller.rb
app/controllers/concerns/aa_testable.rb
app/views/development/index.html.erb
app/views/layouts/application.html.erb
test/controllers/development_controller_test.rb

This PR adds a new concern `AATestable`, which will be used to run an A/A test to determine
variance in our metrics and help guide metrics to use for upcoming A/B tests on related links.
Solo: @karlbaker02
---
https://government-frontend-pr-1211.surge.sh/gallery.html
https://government-frontend-pr-1211.herokuapp.com/component-guide

Add related links A/A test to all routes

---

Gemfile
Gemfile.lock
test/integration/service_sign_in/choose_sign_in_test.rb

This PR upgrades the govuk_publishing_components gem to version `13.6.1`.
---
https://government-frontend-pr-1223.surge.sh/gallery.html
https://government-frontend-pr-1223.herokuapp.com/component-guide

Upgrade govuk_publishing_components to 13.6.1

---

Gemfile
Gemfile.lock

This commit upgrades the govuk_publishing_components gem to version `13.8.1`.
---
https://government-frontend-pr-1234.surge.sh/gallery.html
https://government-frontend-pr-1234.herokuapp.com/component-guide

Upgrade govuk_publishing_components to 13.8.1

---

app/controllers/application_controller.rb
app/controllers/concerns/ab_testable.rb
app/controllers/content_items_controller.rb
test/controllers/content_items_controller_test.rb
test/controllers/development_controller_test.rb

This PR adds support for the Related Links A/B test, showing a different set of related links on the B variant from the content item's suggested_ordered_related_items, where it exists. It also updates the current RelatedLinksAATest to be RelatedLinksABTest.
Trello: https://trello.com/c/byNrHEMw
---
https://government-frontend-pr-1223.surge.sh/gallery.html
https://government-frontend-pr-1223.herokuapp.com/component-guide

Add related links A/B test

---

app/views/content_items/contact.html.erb

[Trello](https://trello.com/c/ZgUEa2nB/787-accessibility-issue-on-contact-pages)
This commit primarily removes a redundant and potentially confusing heading level. It also tidies up a couple of pieces of markup that aren't strictly needed for styling the page.
Copying the commit message from the first commit to remove a heading level:
We have some `h4` tags on the page that are unnecessary. Replace them with
`p` tags instead.
Contact pages on goverment-frontend can be represented by the following
pseudo code:
```
<h2>Phone</h2>
<h3>Phone group title</h3>
<p>Telephone number</p>
<h4>Opening times</h4>
<h4>Best time to call</h4>
<h3>Phone group title</h3>
<p>Telephone number</p>
<h4>Opening times</h4>
<h4>Best time to call</h4>
```
Some contact pages, however, do not have multiple "Phone …

Rationalise heading levels on contact pages

---

test/test_helper.rb

Master is failing with Net::ReadTimeout errors. We have
[previously](https://github.com/alphagov/government-frontend/pull/1121)
increased timeouts which seemed to solve the problem. Let's hope the
magic works again.
At the same time, we are getting a deprecation warning:
```
WARN Selenium [DEPRECATION] :timeout= is deprecated. Use #read_timeout= and #open_timeout= instead.
```
so I have changed `timeout` to `read_timeout` instead.
---
https://government-frontend-pr-1249.surge.sh/gallery.html
https://government-frontend-pr-1249.herokuapp.com/component-guide

Increase Capybara timeouts

---

config/initializers/csp.rb

This implements CSP headers for requests.
It's a continuation of https://github.com/alphagov/govuk-cdn-config/pull/101, and an experiment to see if we can implement CSP more easily app-by-app - if this is successful we'll update the RFC: https://github.com/alphagov/govuk-rfcs/pull/98.

Add CSP headers
