alphagov/government-frontend

app/assets/stylesheets/application.scss
app/assets/stylesheets/helpers/_available-languages.scss
app/helpers/available_languages_helper.rb
app/presenters/content_item_presenter.rb
app/views/content_items/case_study.html.erb
app/views/shared/_available_languages.html.erb
config/application.rb
config/locales/ar.yml
config/locales/en.yml
config/locales/es.yml
config/locales/ur.yml
test/helpers/available_languages_helper_test.rb
test/presenters/content_item_presenter_test.rb

This hasn't gone into a shared component because there is a bit too much logic for a simple standalone template.

Add the available languages block

---

Gemfile
Gemfile.lock
app/presenters/content_item_presenter.rb
app/views/content_items/case_study.html.erb
config/application.rb
config/locales/ar.yml
config/locales/en.yml
config/locales/es.yml
config/locales/uk.yml
config/locales/ur.yml
config/locales/zh.yml
test/controllers/content_items_controller_test.rb

Add in some missing bits of localisation:
* Localise dates and metadata where possible
* Add Chinese and Ukrainian locale files
* Fix translated page header

Missing pieces of localisation

---

app/views/layouts/application.html.erb

So that the correct analytics data is sent add the analytics meta tag
component.

Add analytics meta tags component

---

Gemfile
bin/rails
bin/rake
config/environments/production.rb

Set ruby version in Gemfile
Fix ruby versions for binstubs
Log to stdout
Enable debug logging
Serve static assets if set

Make app work on Heroku

---

app/presenters/service_manual_guide_presenter.rb
app/views/content_items/service_manual_guide.html.erb
test/presenters/service_manual_guide_presenter_test.rb

https://trello.com/c/ye82OWWF/179-topic-context-in-page-title-for-guide-pages-is-missing

Render main topic title in guide context

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/views/_working-group.scss
app/presenters/working_group_presenter.rb
app/views/content_items/working_group.html.erb
test/integration/working_group_test.rb
test/support/govuk_content_schema_examples.rb
test/test_helper.rb

Working groups

---

app/presenters/detailed_guide_presenter.rb
app/presenters/national_applicability.rb
app/presenters/publication_presenter.rb
app/views/content_items/publication.html.erb
test/integration/detailed_guide_test.rb
test/integration/publication_test.rb
test/presenters/detailed_guide_presenter_test.rb
test/presenters/publication_presenter_test.rb

* Move national applicability to module
* Make nation applicability work with any format
* Add national applicability to publications
cc @tvararu

Add national applicability to publications

---

app/assets/stylesheets/helpers/_back-to-content.scss
app/assets/stylesheets/views/_detailed-guide.scss

Fix back to content link focus issues

---

app/views/content_items/case_study.html.erb
app/views/content_items/detailed_guide.html.erb
app/views/content_items/document_collection.html.erb
app/views/content_items/html_publication.html.erb
app/views/content_items/publication.html.erb
app/views/content_items/statistics_announcement.html.erb
app/views/content_items/take_part.html.erb
app/views/content_items/topical_event_about_page.html.erb
app/views/content_items/working_group.html.erb

This reverts commit aad185c42e143112164fb2697371d0f1805fcca0 that was accidentally pushed to master.

Revert "Add meta descriptions to content items"

---

app/views/content_items/fatality_notice.html.erb

Fix MOD logo path on Fatality Notice

---

lib/generators/format/templates/format_presenter_test.rb.erb
test/presenter_test_helper.rb
test/presenters/case_study_presenter_test.rb
test/presenters/coming_soon_presenter_test.rb
test/presenters/detailed_guide_presenter_test.rb
test/presenters/document_collection_presenter_test.rb
test/presenters/fatality_notice_presenter_test.rb
test/presenters/html_publication_presenter_test.rb
test/presenters/publication_presenter_test.rb
test/presenters/statistics_announcement_presenter_test.rb
test/presenters/take_part_presenter_test.rb
test/presenters/topical_event_about_page_presenter_test.rb

Some legibility improvements:
- Clearer test cases
- One assertion per test

Refactor document collection presenter tests

---

README.md

The `DetailedGuide` is now rendered by government-frontend

Update README.md with DetailedGuide

---

README.md

* Add speeches, consultations and statistical data sets
* Add examples for now migrated formats

Update README formats table

---

README.md
test/wraith/config-examples.yaml

Not all formats are live, and live content changes. Sometimes it’s preferable to compare examples on a branch against master.
* Create wraith config for testing diffs of examples
* Include instructions on how to generate diffs in readme
Example output:
https://fofr.github.io/government-frontend-wraith-tests/shots/gallery.html
Examples generated using this gist:
https://gist.github.com/fofr/765604f8ae27164736ac4a8c8e96ddeb

Add config and instructions for comparing examples with wraith

---

app/presenters/updatable.rb
test/presenters/updatable_test.rb

Fixes https://errbit.publishing.service.gov.uk/apps/546493f90da1150e4e001cfc/problems/58905b8465786333bfd80000

Guard against missing change history

---

test/wraith/config-speeches.yaml

https://trello.com/c/As5Anuer/613-speech-migration-4-wraith-tests

Adds config to test the top 100 speeches

---

test/wraith/config.yaml

[Trello](https://trello.com/c/agLwuVNJ/552-wlna-migration-4-wraith-tests-1)

Add most visited WLNA to wraith tests

---

Gemfile
Gemfile.lock
config/application.rb
config/initializers/govuk_navigation_helpers.rb
lib/services.rb

Trello: https://trello.com/c/S72dddmO/488-configure-navigation-helpers-with-statsd

Configure nav helpers with statsd

---

app/views/shared/_breadcrumbs.html+new_navigation.erb

https://trello.com/c/rAUEFO28/367-add-beta-survey-banner-to-new-education-navigation-pages

Add survey link and copy changes to banner on new nav pages

---

app/views/shared/_breadcrumbs.html+new_navigation.erb

Trello: https://trello.com/c/fqPhgYA6/22-the-survey-link-doesn-t-open-in-a-new-window

Open the survey in a new window in new navigation

---

Gemfile
Gemfile.lock
app/controllers/randomly_generated_content_item_controller.rb
app/presenters/contact_presenter.rb
app/presenters/content_item_presenter.rb
app/presenters/updatable.rb
config/routes.rb
test/integration/contact_test.rb
test/integration/publication_test.rb
test/presenters/updatable_test.rb
test/test_helper.rb

* Use GovukSchemas gem to generate random content
* Request random content for any given format using `/random/:schema`, eg /random/publication
* Run integration tests against 10 random publications and contacts, fix errors found
cc @tijmenb @nickcolley @mcgoooo

Run integration tests against random but valid content items

---

app/models/benchmarking_ab_test_request.rb

The previous merge to master failed to build because of this.

Fix indentation of method parameters

---

app/views/shared/_back_to_content_link.html.erb
test/integration/detailed_guide_test.rb

Trello: https://trello.com/c/DpEK2IwV/518-track-clicks-on-floating-contents-link-on-detailed-guide-pages

Update contents link tracking label

---

app/assets/javascripts/webchat/README.md

we need some documentation to point people at, this is it

Create a readme for webchat

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/views/_answers.scss
app/presenters/answer_presenter.rb
app/presenters/content_item_presenter.rb
app/views/content_items/answer.html.erb
app/views/shared/_related_items.html+new_navigation.erb
app/views/shared/_related_items.html.erb
test/integration/answers_test.rb
test/presenters/answer_presenter_test.rb
test/wraith/config.yaml

this migrates answers to government frontend
there is not much going on here, this pull does not actually do anything until the publisher is changed, which will be done in a further pull. This code is safe to be on live.
| old  | new |
| ------------- | ------------- |
| ![screencapture-gov-uk-contact-student-finance-england-1490184836899](https://cloud.githubusercontent.com/assets/248888/24197332/1b7aed04-0ef9-11e7-8040-eb681449521a.png) | ![screencapture-localhost-3090-contact-student-finance-england-1490184850134](https://cloud.githubusercontent.com/assets/248888/24197331/1b7a58a8-0ef9-11e7-8e13-87d7c595efcd.png) |

Migrate answers from frontend

---

test/presenters/answer_presenter_test.rb

did not get picked up on build on the pull for some reason

Linting answers presenter

---

README.md

All 3 formats now rendered by government-frontend

Add answers, help and specialist docs to README

---

test/wraith/config.yaml

* Include popular guides in wraith config

Add most popular guides to wraith

---

app/views/ab_testing/_ukvi_overview_section.html.erb

Related to #361 
[Trello card](https://trello.com/c/OtqjOlKD/616-5-a-b-copy-test-ukvi)
This PR updates the content as follows:
CHANGE: ^If you’re visiting for 6 months or less, check if you need a Standard Visitor visa.^
TO: ^If you’re visiting for 6 months or less, check if you need a Standard Visitor visa.^
REASON: The action is 'check' and should be in the link.

Content update for UKVI AB Test

---

app/assets/stylesheets/views/_specialist-document.scss

* Removing code no longer needed
* Relates to https://github.com/alphagov/static/pull/1077, must be deployed together
https://trello.com/c/2pik3I0j/109-1-increase-font-size-in-metadata-component-in-static

Metadata font size increase

---

README.md

* Indicate where components live
* Indicate which component guides to use

Add guidance on using components

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/views/_consultation.scss
app/views/components/_banner.html.erb

- padding right was on grid container, should be inside grid
- removing unneeded section title CSS from previous rebase error

Fix banner styles

---

Gemfile
config/application.rb

Based on https://github.com/alphagov/static/pull/1137
Thanks to @whoojemaflip 👍

Remove require logic from Gemfile

---

config/locales/cy.yml

https://trello.com/c/tWvPKudB/162-welsh-template-change-capitalisation-of-one-word

Capitalise 'cyhoeddwyd' and 'diweddarwyd' 

---

app.json

We no longer need these, and it's preventing Review Apps from running.

Remove S3 env vars from app.json

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/helpers/_task-list-title.scss
app/controllers/application_controller.rb
app/controllers/concerns/tasklist_ab_testable.rb
app/controllers/content_items_controller.rb
app/lib/tasklist_content.rb
app/views/content_items/_body_with_related_links.html.erb
app/views/content_items/answer.html.erb
app/views/content_items/guide.html.erb
app/views/layouts/application.html.erb
app/views/shared/_sidebar_tasklist.html.erb
config/tasklists/learn-to-drive-a-car.json
test/controllers/task_list_ab_testing_content_items_controller_test.rb
test/test_helper.rb
test/unit/tasklist_content_test.rb

Trello: https://trello.com/c/QUBFYtcf/217-add-a-b-test-functionality-into-the-government-frontend-app-%F0%9F%9A%97

Add sidebar tasklist to answers and guide pages

---

config/tasklists/learn-to-drive-a-car.json

https://trello.com/c/cUEwJxUz/287-tweak-after-you-pass-content

Amend after you pass text

---

config/tasklists/learn-to-drive-a-car.json

It looks a little odd as one paragraph.

Split text into two paragraphs

---

app/views/shared/_tasklist_header.html.erb

This has been agreed with @andysellick

Use default text for "skip link"

---

app/assets/stylesheets/components/_navigation-sidebar.scss
app/helpers/navigation_sidebar_helper.rb
app/views/components/_navigation-sidebar.html.erb
app/views/components/docs/navigation-sidebar.yml
config/locales/en.yml
test/components/navigation_sidebar_test.rb

This PR only covers making the navigation sidebar component production-ready, it doesn't deal with any of the logic that's needed to get the data in the right format to be passed to the component within templates.
https://government-frontend-pr-542.herokuapp.com/component-guide/navigation-sidebar
https://government-frontend-pr-542.surge.sh/gallery.html

Create navigation sidebar component

---

test/components/fieldset_test.rb

I missed a test out for this component, this adds one in.
https://trello.com/c/RRbQOeUK/243-create-a-fieldset-component-1

Add test for fieldset component

---

app/controllers/concerns/tasklist_pages.rb

Trello: https://trello.com/b/yPUeB93k/govuk-modelling-services-doing

Remove tasklist sidebar from/view-driving-licence

---

app/views/components/_important-metadata.html.erb
app/views/components/_publisher-metadata.html.erb
app/views/components/_related-navigation.html.erb
test/components/important_metadata_test.rb
test/components/publisher_metadata_test.rb
test/components/related_navigation_test.rb

Enable link tracking for navigation sidebar

---

test/integration/service_sign_in/create_new_account_test.rb

This could be done with seeding but then we wouldnt get a random result each time.
As part of https://trello.com/c/EzyEJjTk/296-update-create-new-account-test-so-it-does-not-randomly-skip

Update test to ensure random example always runs

---

manifest.yml

A first pass at a PaaS CF manifest file so that we can "cf push" this app to the PaaS.

Add Paas manifest file.

---

test/test_helper.rb

Review markups - changed name of test helper method
Added some new useful test helpers that can be used all over.

Added new test helpers for publisher metadata and side bar nav

---

app/views/components/_published-dates.html.erb
app/views/content_items/specialist_document.html.erb
test/integration/specialist_document_test.rb

Reverts alphagov/government-frontend#677

Revert "Revert "Move specialist documents to universal layout""

---

app/views/content_items/corporate_information_page.html.erb

Reverts alphagov/government-frontend#697
I'd like to resolve a couple of inconsistencies before deploying this.

Revert "Move corporate information page to universal layout"

---

Gemfile.lock

This [removes two step by step navs](https://github.com/alphagov/govuk_navigation_helpers/pull/114/commits/17d09f0b11f0454beb18f607102fb204ab81cc45) which may help with the load issues.

Bump govuk_navigation_helpers

---

config/environments/production.rb

This is [already in govuk_app_config](https://github.com/alphagov/govuk_app_config/blob/5220b89da3be24429656e69f0c0f90bef11abdd4/lib/govuk_app_config/govuk_logging.rb#L15-L23)

Remove other logging setup

---

app/presenters/content_item/contents_list.rb
app/presenters/document_collection_presenter.rb
app/presenters/working_group_presenter.rb
test/integration/document_collection_test.rb
test/integration/working_group_test.rb
test/presenters/content_item/contents_list_test.rb

For https://trello.com/c/2UIR4Sen/210-investigate-how-to-deal-with-short-content-lists
After deploying https://github.com/alphagov/government-frontend/pull/719 we noticed some bugs for Document Collections and Working Groups, so this PR aims to fix thes

Fix contents list bugs

---

app/controllers/content_items_controller.rb
app/services/presenter_builder.rb

There are a lot of methods in the `ContentItemsController` that relate to the process of determining the correct presenter. This moves them into a single class.

Extract methods to build the presenter

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/views/layouts/application.html.erb
test/integration/service_sign_in/choose_sign_in_test.rb

This replaces the "Is there anything wrong?" link with the new feedback component. This component asks the user if the page is useful and reports the results to Google Analytics.
See https://github.com/alphagov/govuk_publishing_components/pull/163 for the component.
https://trello.com/c/eKtXGtBD

Use feedback component

---

config/locales/cy.yml

https://govuk.zendesk.com/agent/tickets/2583792
https://trello.com/c/aPpXYR8h/227-translation-of-related-navigation-component
Add translation for 'Details' heading in publications.
Live:
https://www.gov.uk/government/publications/testing-for-tb-in-your-herd.cy
PR:
https://government-frontend-pr-795.herokuapp.com/government/publications/testing-for-tb-in-your-herd.cy
---
https://government-frontend-pr-795.herokuapp.com/component-guide

Add welsh translation for 'Details' (Manylion)

---

app/presenters/contact_presenter.rb
test/presenters/contact_presenter_test.rb

As per the Zendesk request: https://govuk.zendesk.com/agent/tickets/2594882

Fully remove webchat for self assessment webpage

---

app/assets/stylesheets/print.scss

Among other things, this will hide the feedback component when printing.
cc @fofr

Include all component print styles

---

app/views/content_items/case_study.html.erb
app/views/content_items/corporate_information_page.html.erb
app/views/content_items/detailed_guide.html.erb
app/views/content_items/document_collection.html.erb
app/views/content_items/fatality_notice.html.erb
app/views/content_items/news_article.html.erb
app/views/content_items/publication.html.erb
app/views/content_items/specialist_document.html.erb
app/views/content_items/speech.html.erb
app/views/content_items/statistical_data_set.html.erb
app/views/content_items/statistics_announcement.html.erb
app/views/content_items/take_part.html.erb
app/views/content_items/topical_event_about_page.html.erb
app/views/content_items/working_group.html.erb
app/views/content_items/world_location_news_article.html.erb
test/integration/fatality_notice_test.rb

Use the Lead paragraph component from the gem

---

app/views/content_items/guide.html.erb
app/views/content_items/travel_advice.html.erb
test/integration/guide_test.rb
test/integration/travel_advice_test.rb

Use the Previous/Next component from the gem

---

app/helpers/phase_label_helper.rb
test/integration/content_pages_navigation_test.rb

https://trello.com/c/iuCepmLQ
---
https://government-frontend-pr-1027.surge.sh/gallery.html
https://government-frontend-pr-1027.herokuapp.com/component-guide

Show BETA phase message during AB test

---

app/assets/stylesheets/components/_publisher-metadata.scss
app/views/components/docs/publisher-metadata.yml
app/views/content_items/consultation.html.erb
app/views/content_items/news_article.html.erb
app/views/content_items/world_location_news_article.html.erb
config/locales/ar.yml
config/locales/en.yml
config/locales/ru.yml

Pending review from translator.
Examples:
* https://government-frontend-pr-1055.herokuapp.com/government/news/foreign-secretary-statement-israels-right-to-defend-itself
* https://government-frontend-pr-1055.herokuapp.com/government/news/foreign-secretary-statement-israels-right-to-defend-itself.ar
* https://government-frontend-pr-1055.herokuapp.com/government/news/foreign-secretary-statement-israels-right-to-defend-itself.ru
---
https://government-frontend-pr-1055.surge.sh/gallery.html
https://government-frontend-pr-1055.herokuapp.com/component-guide
---
[Trello card](https://trello.com/c/y8CzrRHI/400-add-the-language-translations-into-the-universal-layout-template)

Add Arabic and Russian translations for navigation headings

---

Gemfile
Gemfile.lock

https://government-frontend-pr-1119.herokuapp.com/component-guide

Bump govuk_publishing_components to 11.2.0

---

app/lib/services.rb

This is included but not used.
---

Remove unused rummager requirement

---

app/views/components/_important-metadata.html.erb

Metadata title and description outputting needed a small tweak and explicit cast to string.

Change metadata title outputting

---

config/locales/da.yml
config/locales/fi.yml
config/locales/gd.yml
config/locales/hr.yml
config/locales/is.yml
config/locales/mt.yml
config/locales/nl.yml
config/locales/no.yml
config/locales/sl.yml
config/locales/sv.yml

We have received some language names to apply to the new locales we've
added. Include these so the frontend will display the language names
nicely translated.

Add language names to new locales

---

Gemfile.lock

This is so I can double check CSP is working correctly with the changes.

Bump govuk_app_config

---

config/machine_readable/voting-in-the-uk.yml

This is already in the content, but needed to be added to this section of
the FAQ to make it entirely clear.
---
https://government-frontend-pr-1545.herokuapp.com/voting-in-the-uk

Add line to ID faq section

---

config/machine_readable/voting-in-the-uk.yml

Escaping the quotes was not a great idea for this.

Fix link in schema

---

config/machine_readable/voting-in-the-uk.yml

The postal voting deadline in Northern Ireland has passed.
This should match (some of) the changes in https://publisher.publishing.service.gov.uk/editions/5dd41e2340f0b60b8662c351/diff
(Not all of the content is included in the schema)

Update voting in the UK schema

---

config/machine_readable/voting-in-the-uk.yml

Updated to reflect the passing deadlines.  Should match the changes in [publisher](https://publisher.publishing.service.gov.uk/editions/5dd7ee7140f0b60b8662c3b7/diff)
(where appropriate).
To be deployed later today

Update voting schema

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_back-to-top.scss
app/assets/stylesheets/components/_download-link.scss
app/assets/stylesheets/mixins/_white-links.scss
app/helpers/gone_helper.rb
app/views/content_items/unpublishing.html.erb
test/helpers/gone_helper_test.rb

This PR fixes the following issues and then switches to the new colour palette.
https://www.gov.uk/government/consultations/open-government-partnership-uk-national-action-plan-2016
-----
Language link:
https://www.gov.uk/government/world-location-news/pre-entry-tuberculosis-screening-for-long-term-visa-applicants-in-belarus.be
-----
Contents link
https://www.gov.uk/government/topical-events/london-somalia-conference-2017/about
-----
PDF link
https://www.gov.uk/foreign-travel-advice/afghanistan
-----
Update colours:

Update focus colours

---

config/machine_readable/voting-in-the-uk.yml

This is an update to the content in the FAQPage schema for /voting-in-the-uk which should match the relevant bits from https://publisher.publishing.service.gov.uk/editions/5de4e65ce5274a079bc034ee/diff

Update to /voting-in-the-uk for proxy deadline

---

config/machine_readable/voting-in-the-uk.yml

This should match the live section in https://www.gov.uk/voting-in-the-uk#voting-by-proxy

Update emergency proxy details

---

lib/webchat.yaml

Added details for webchat on HMPO contact page.
---

Added HMPO webchat

---

app/views/content_items/travel_advice.html.erb

Updated wording on FCO travel callout:

Update travel advice from FCO on travel pages

---

app/views/content_items/html_publication.html.erb

Use FAQ Schema for html publications
---
https://government-frontend-pr-1726.surge.sh/gallery.html

Use FAQ Schema for html publications

---

app/views/content_items/travel_advice.html.erb

The FCO would like to change the content displayed on this page.

Update COVID-19 Exceptional Travel Advisory Notice

---

app/views/content_items/travel_advice.html.erb

Update global travel advice callout to reflect 4th July updates

---

app/views/content_items/travel_advice.html.erb

Do not merge or deploy until 2020-07-04. Relates to https://github.com/alphagov/frontend/pull/2414.

Longer update to travel advice COVID callout text

---

.github/pull_request_template.md

https://trello.com/c/vFPSSGb7/175-activate-continuous-deployment-for-5-more-apps

Add PR template in advance of Continous Deployment

---

app/views/content_items/travel_advice.html.erb

Updating department name

---

.gitignore
Gemfile
Gemfile.lock
test/test_helper.rb

https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review

Add SimpleCov to report code coverage

---

app/views/content_items/travel_advice.html.erb

Trello: https://trello.com/c/lYe5hSDx
Updates Global travel advice call out box with information about the new restrictions in England

Update Global travel advice call out box

---

app/views/content_items/service_sign_in/_create_new_account.html.erb
app/views/content_items/statistical_data_set.html.erb

Updating inputs to govspeak due to issues seen on live with broken tables.

Undo sanitization that is having detrimental effects

---

Gemfile.lock

Bump govuk-publishing-components

---

app/presenters/content_item/no_deal_notice.rb
app/views/components/_header-notice.html.erb

Update transition call out box as a result of a deal with the EU

---

app/views/content_items/travel_advice.html.erb

See trello card for requested content: https://trello.com/c/afsR0MpI

Update travel advice callout content

---

app/views/content_items/travel_advice.html.erb

[Trello](https://trello.com/c/xZua4oZ2/1039-update-to-travel-advice-callout-box)

Update travel advice callout box content

---

app/views/content_items/_ireland_covid_travel_guidance.html.erb
app/views/content_items/travel_advice.html.erb

Update travel advice callout

---

app/views/content_items/_ireland_covid_travel_guidance.html.erb
app/views/content_items/travel_advice.html.erb

Add back "the"

---

app/views/content_items/_ireland_covid_travel_guidance.html.erb
app/views/content_items/travel_advice.html.erb

This is in line with updates from FCDO

Update travel advice callout box

---

config/locales/pa-pk.yml

Add text direction rtl to pa-pk locale

Add text direction rtl to pa-pk locale

---

app/views/content_items/travel_advice.html.erb

This is in line with latest guidance from DfT

Remove text from travel advice callout box

---

app/presenters/detailed_guide_presenter.rb

These private methods aren't used anywhere.

Remove unused code

---

app/views/content_items/travel_advice.html.erb

Adds **(or in Wales, stay local)** to first line.

Travel Advice callout updates -  12 March 2021

---

config/locales/plurals.rb

https://trello.com/c/eEphXlio/2394-5-check-and-update-rules-for-plural-forms-across-frontend-apps#comment-604a00ad005aeb703e5a5a86

Amend plural rules for translations

---

config/machine_readable/how-to-vote.yml
test/integration/guide_test.rb

The [live content has changed](https://www.gov.uk/how-to-vote)

Update How to vote schema

---

app/views/content_items/travel_advice.html.erb

Travel advice call out box update

---

config/machine_readable/how-to-vote.yml

Amendments to the how to vote schema 🗳

Update how-to-vote metadata

---

config/machine_readable/how-to-vote.yml

Bring metadata in line with upcoming content changes on [how to vote](https://www.gov.uk/how-to-vote) guidance

Add deadlines on 'how to vote' guidance

---

config/machine_readable/how-to-vote.yml
test/integration/guide_test.rb

The content is already live on https://www.gov.uk/how-to-vote and this is an update to match.

Add new voting and COVID section to the schema

---

config/machine_readable/how-to-vote.yml
test/integration/guide_test.rb

Update how to vote section as per [doc](https://docs.google.com/document/d/17i_0rH67XgBn2dy0DIQbCC0PLxiZofTkohbw042qtV0/edit#) 

Update How to vote section

---

config/machine_readable/how-to-vote.yml

as per https://docs.google.com/document/d/17i_0rH67XgBn2dy0DIQbCC0PLxiZofTkohbw042qtV0/edit#

Update how to vote top actions

---

config/machine_readable/how-to-vote.yml

This update covers the passing of the deadline for applying for a proxy vote.
This should match: https://publisher.publishing.service.gov.uk/editions/607f4743d3bf7f331cd037f7/diff
and https://docs.google.com/document/d/17i_0rH67XgBn2dy0DIQbCC0PLxiZofTkohbw042qtV0/edit#heading=h.dps7tpi6q19r

Update the how-to-vote schema

---

Gemfile.lock

Bump govuk_publishing_components to 24.18.1

---

config/locales/en.yml

Trello: https://trello.com/c/P881xXrT

Travel advice callout update - 15 July 2021

---

config/locales/en.yml

Trello: https://trello.com/c/l7IyYZ5n

Travel advice callout changes - 19 July 2021

---

Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/controllers/ab_tests/sab_pages_testable.rb
app/controllers/content_items_controller.rb
app/views/content_items/_body_with_related_links.html.erb
app/views/content_items/document_collection.html.erb
app/views/content_items/guide.html.erb
app/views/layouts/application.html.erb
test/controllers/sab_ab_test.rb

Add intervention

---

docs/visual-regression-tests.md

Fixes https://github.com/alphagov/govuk-developer-docs/issues/3214

Fix URL to Wraith website

---

config/locales/ps.yml

`ps` (Pashto) is a RTL language.
Trello:
https://trello.com/c/Xz78vNR4/2757-import-newly-sourced-translations-into-locale-files-5

Define correct language direction

---

app/controllers/get_involved_controller.rb

Pass the correct value to the document list component to render the department
Resolving issue introduced during review

Fix document type

---

config/locales/fr.yml

Fix translations argument typo

---

app/controllers/content_items_controller.rb

Add 22 more pages to the single page notification trial list. 
All these pages are using templates that the single page notification button is already on, therefore no template updates are required.
------
https://trello.com/c/BYrhoXT9/1217-add-single-page-notifications-to-20-more-pages
----

Update single page notification allow list

---

app/lib/recruitment_helper.rb
app/presenters/content_item/recruitment_banner.rb
test/integration/recruitment_banner_test.rb

Update survey URL

---

Gemfile.lock

Upgrade to the newest version of govuk_publishing_components.

Bump to latest components gem

---

app/presenters/content_item/recruitment_banner.rb
test/integration/recruitment_banner_test.rb

For pages tagged to browse/tax and browse/business

Update survey URL in recruitment banner on pages tagged to browse topics of interest

---

config/locales/fi.yml

For details see: https://gds.slack.com/archives/C02TXEW309Z/p1649777611276149
---

Update the translation for Finnish

---

app/presenters/content_item/recruitment_banner.rb
test/integration/recruitment_banner_test.rb

For pages tagged to browse/tax and browse/business

Update survey URL in the recruitment banner

---

config/locales/uk.yml

Done in response to this zendesk ticket: https://govuk.zendesk.com/agent/tickets/4947475

Change to the translation for 'Guidance' in Ukrainian.

---

test/presenters/content_item/manual_section_test.rb

https://trello.com/c/F5LmEArQ/1212-add-spec-for-manual-sections-module

added spec file for manual section test 

---

.github/workflows/deploy.yaml

https://trello.com/c/tUyJa4cb/923-extend-gha-to-deploy-to-specific-environment

Update deploy.yaml for better rollbacks

---

app/presenters/content_item/recruitment_banner.rb
test/integration/recruitment_banner_test.rb

https://trello.com/c/ZKgObFIV/1148-launch-tree-test-of-menu-bar-variant-1-menu-with-govt-activity-below-l1-l

Update survey link

---

app/presenters/content_item/recruitment_banner.rb
test/integration/recruitment_banner_test.rb

Update Tree test survey link

---

app/presenters/content_item/recruitment_banner.rb
test/integration/recruitment_banner_test.rb

The recruitment for this research is finished

Remove Tree test survey recruitment banners

---

app/lib/services.rb
app/presenters/content_item/shareable.rb
app/presenters/content_item_presenter.rb
test/presenters/content_item/shareable_test.rb

It's going to be deprecated https://github.com/alphagov/plek/pull/94

Replace Plek.current with Plek.new

---

test/controllers/get_involved_controller_test.rb

Update remaining occurrences of deprecated Plek.current

---

startup.sh

See https://github.com/alphagov/gds-api-adapters/pull/1170.

Fix environment variable for Search API backend in startup.sh.

---

app/views/content_items/detailed_guide.html.erb
app/views/content_items/guide.html+print.erb
app/views/content_items/hmrc_manual.html.erb
app/views/content_items/hmrc_manual_section.html.erb
app/views/content_items/html_publication.html.erb
app/views/content_items/manual.html.erb
app/views/content_items/manual_section.html.erb
app/views/content_items/manuals/_updates.html.erb
app/views/content_items/travel_advice.html+print.erb
app/views/shared/_published_dates_with_notification_button.html.erb

Update the `index` parameter on print links in line with a change to the format of the `index` parameter.
Part of the GA4 migration work.
None.
Trello card: https://trello.com/c/8tNN5gGX/426-change-the-index-parameter

Update print link GA4 tracking

---

app/presenters/content_item/research_banner.rb
test/integration/research_banner_test.rb

Trello card: https://trello.com/c/JNFBhMMR/1807-replace-survey-link-on-user-research-banner-for-col-s

Update survey link for COL user research banner

---

yarn.lock

Bump hosted-git-info

---

config/locales/en.yml

https://govuk.zendesk.com/agent/tickets/5406038

Fix text for component

---

config/locales/bg.yml

Zendesk ticket: https://govuk.zendesk.com/agent/tickets/5422811
Before:
After:

Update Bulgarian language name

---

app/views/content_items/document_collection.html.erb

Re-add skip govuk-account on subscribe button

---

app/views/histories/lancaster_house.html.erb

In response to zendesk ticket, apparently redirects being flakey
https://govuk.zendesk.com/agent/tickets/5778735

Update Lancaster house FCDO links

---

.gitignore

Add byebug history to ignore

---

app/presenters/publication_presenter.rb

Potential fix for: https://govuk.zendesk.com/agent/tickets/5808327

Fix csv preview url

---

app/presenters/publication_presenter.rb

Follow on fix from the fix here: https://govuk.zendesk.com/agent/tickets/5808327

Only fix preview_url if it already exists

---

.github/workflows/deploy.yml
Dockerfile

This enables multi-arch builds for government- frontend.

Enable multi-arch for gov-frontend

---

README.md

Add in relevant set up commands to run the test suite locally

Add in missing steps to run test suite locally

---

yarn.lock

Upgrade express and its dependecies

---

app/views/content_items/answer.html.erb
app/views/content_items/guide.html.erb
lib/data/recruitment_banners.yml
test/integration/recruitment_banner_test.rb

Add recruitment banner to pages of interest as requested by AI team.
[Trello](https://trello.com/c/vnr9mW0w/3025-put-live-govuk-user-research-banner-requests-ai-govuk)
Review app links
**Guides**
- https://government-frontend-pr-3412.herokuapp.com/self-assessment-tax-returns 
- https://government-frontend-pr-3412.herokuapp.com/self-employed-records
- https://government-frontend-pr-3412.herokuapp.com/expenses-if-youre-self-employed
- https://government-frontend-pr-3412.herokuapp.com/first-company-accounts-and-return
- https://government-frontend-pr-3412.herokuapp.com/capital-allowances
- https://government-frontend-pr-3412.herokuapp.com/simpler-income-tax-cash-basis
- https://government-frontend-pr-3412.herokuapp.com/capital-gains-tax
- …

Add recruitment banner to guides and answers

---

app/helpers/govuk_chat_promo_helper.rb

We want to show the Chat promo banner on some more pages to help funnel more users in.
These URLs cover some new document types:
* detailed_guide
* document_collection
* form
* guidance
* policy_paper
Each of those document types renders with the `_sidebar_navigation.html.erb` partial which is where we render the promo, so no additional views need changing.
Below are screenshots of each of those new document types with mobile/deskop before/after the rendering of the promo.
e.g. https://www.gov.uk/guidance/track-a-dbs-application
| Before  | After |
| ------------- | ------------- |
| ![detailed_guide_mobile_before](https://github.com/user-attachments/assets/f6bec3da-92bc-4d6b-a495-2dceddf32448) | ![detailed_guide_mobile_after](https://github.com/user-attachments/assets/e0a58b25-3ff3-458a-9 …

Add some more URLs to render GOV.UK Chat promo on

---

app/helpers/govuk_chat_promo_helper.rb

We're adding the promotional banner to some more pages to drive more user traffic.

Render chat promotional banner on additional URLs

---

app/views/layouts/application.html.erb

We will add this back in on https://github.com/alphagov/government-frontend/pull/3474

Remove banner partial from application layout

---

app/presenters/html_publication_presenter.rb
app/presenters/publication_presenter.rb
app/views/content_items/html_publication.html.erb
test/integration/html_publication_test.rb
test/presenters/html_publication_presenter_test.rb
test/test_helper.rb

Adds noindex to mobile paths html attachments

---

app/views/content_items/webchat.html.erb
test/integration/specialist_document_test.rb
test/integration/webchat_integration_test.rb

Necessary to facilitate the change made in this [Specialist Publisher PR](https://github.com/alphagov/specialist-publisher/pull/3147)
[Trello](https://trello.com/c/UXXwOxKQ/3728-specialist-finder-edit-request-countryside-stewardship-grants)

Countryside stewardship grants request
